// Author: Sreeman, Nasreddine Bencherchali (Nextron Systems)
// Date: 2020/01/13
// Level: high
// Description: Adversaries can use curl to download payloads remotely and execute them. Curl is included by default in Windows 10 build 17063 and later.
// Tags: attack.execution, attack.t1218, attack.command_and_control, attack.t1105
DeviceProcessEvents
| where ProcessCommandLine contains " /c " and ProcessCommandLine contains "curl " and ProcessCommandLine contains "http" and ProcessCommandLine contains "-o" and ProcessCommandLine contains "&"