// Author: Daniil Yugoslavskiy, oscd.community
// Date: 2019/10/24
// Level: medium
// Description: Execution of well known tools for data exfiltration and tunneling
// Tags: attack.exfiltration, attack.command_and_control, attack.t1041, attack.t1572, attack.t1071.001
DeviceProcessEvents
| where FolderPath endswith "\\plink.exe" or FolderPath endswith "\\socat.exe" or FolderPath endswith "\\stunnel.exe" or FolderPath endswith "\\httptunnel.exe"