// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/06/10
// Level: high
// Description: Detects execution of the Notepad++ updater (gup) from a process other than Notepad++ to download files.
// Tags: attack.command_and_control, attack.t1105
DeviceProcessEvents
| where ((ProcessCommandLine contains " -unzipTo " and ProcessCommandLine contains "http") and (FolderPath endswith "\\GUP.exe" or ProcessVersionInfoOriginalFileName =~ "gup.exe")) and (not(InitiatingProcessFolderPath endswith "\\notepad++.exe"))