// Author: Nasreddine Bencherchali (Nextron Systems), Christopher Peacock @securepeacock
// Date: 2023/04/18
// Level: low
// Description: Detects potential RDP connection via Mstsc using a local ".rdp" file
// Tags: attack.command_and_control, attack.t1219
DeviceProcessEvents
| where ((ProcessCommandLine endswith ".rdp" or ProcessCommandLine endswith ".rdp\"") and (FolderPath endswith "\\mstsc.exe" or ProcessVersionInfoOriginalFileName =~ "mstsc.exe")) and (not((ProcessCommandLine contains "C:\\ProgramData\\Microsoft\\WSL\\wslg.rdp" and InitiatingProcessFolderPath =~ "C:\\Windows\\System32\\lxss\\wslhost.exe")))