// Author: Florian Roth (Nextron Systems), Markus Neis, Jonhnathan Ribeiro, Daniil Yugoslavskiy, oscd.community
// Date: 2018/03/23
// Level: critical
// Description: Detects OilRig registry persistence as reported by Nyotron in their March 2018 report
// Tags: attack.persistence, attack.g0049, attack.t1053.005, attack.s0111, attack.t1543.003, attack.defense_evasion, attack.t1112, attack.command_and_control, attack.t1071.004
DeviceRegistryEvents
| where RegistryKey endswith "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\UMe" or RegistryKey endswith "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\UT"