// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/09/28
// Level: medium
// Description: Detects piping the password to an anydesk instance via CMD and the '--set-password' flag.
// Tags: attack.command_and_control, attack.t1219
DeviceProcessEvents
| where ProcessCommandLine contains "/c " and ProcessCommandLine contains "echo " and ProcessCommandLine contains ".exe --set-password"