// Title: Onyx Sleet APT File Creation Indicators
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-10-24
// Level: high
// Description: Detects file creation activity that is related to Onyx Sleet APT activity
// MITRE Tactic: Execution
// Tags: attack.execution, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2023/TA/Onyx-Sleet/file_event_win_apt_onyx_sleet_indicators.yml
// False Positives:
//   - Unlikely

DeviceFileEvents
| where FolderPath endswith ":\\Windows\\ADFS\\bg\\inetmgr.exe"