// Title: Peach Sandstorm APT Process Activity Indicators
// Author: X__Junior (Nextron Systems)
// Date: 2024-01-15
// Level: high
// Description: Detects process creation activity related to Peach Sandstorm APT
// MITRE Tactic: Execution
// Tags: attack.execution, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2023/TA/Peach-Sandstorm/proc_creation_win_apt_peach_sandstorm_indicators.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains "QP's*(58vaP!tF4"