// Title: Startup Item File Created - MacOS
// Author: Alejandro Ortuno, oscd.community
// Date: 2020-10-14
// Level: low
// Description: Detects the creation of a startup item plist file, that automatically get executed at boot initialization to establish persistence.
// Adversaries may use startup items automatically executed at boot initialization to establish persistence.
// Startup items execute during the final phase of the boot process and contain shell scripts or other executable files along with configuration information used by the system to determine the execution order for all startup items.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.t1037.005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/file_event/file_event_macos_susp_startup_item_created.yml
// False Positives:
//   - Legitimate administration activities

DeviceFileEvents
| where FolderPath endswith ".plist" and (FolderPath startswith "/Library/StartupItems/" or FolderPath startswith "/System/Library/StartupItems")