// Title: MacOS Emond Launch Daemon
// Author: Alejandro Ortuno, oscd.community
// Date: 2020-10-23
// Level: medium
// Description: Detects additions to the Emond Launch Daemon that adversaries may use to gain persistence and elevate privileges.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.t1546.014
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/file_event/file_event_macos_emond_launch_daemon.yml
// False Positives:
//   - Legitimate administration activities

DeviceFileEvents
| where (FolderPath contains "/etc/emond.d/rules/" and FolderPath endswith ".plist") or FolderPath contains "/private/var/db/emondClients/"