// Title: Ps.exe Renamed SysInternals Tool
// Author: Florian Roth (Nextron Systems)
// Date: 2017-10-22
// Level: high
// Description: Detects renamed SysInternals tool execution with a binary named ps.exe as used by Dragonfly APT group and documented in TA17-293A report
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.g0035, attack.t1036.003, car.2013-05-009, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2017/TA/Dragonfly/proc_creation_win_apt_ta17_293a_ps.yml
// False Positives:
//   - Renamed SysInternals tool

DeviceProcessEvents
| where ProcessCommandLine contains "ps.exe -accepteula" and ProcessCommandLine contains "-s cmd /c netstat"