// Title: Potential APT10 Cloud Hopper Activity
// Author: Florian Roth (Nextron Systems)
// Date: 2017-04-07
// Level: high
// Description: Detects potential process and execution activity related to APT10 Cloud Hopper operation
// MITRE Tactic: Execution
// Tags: attack.execution, attack.g0045, attack.t1059.005, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2017/TA/APT10/proc_creation_win_apt_apt10_cloud_hopper.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (ProcessCommandLine contains ".vbs /shell " and FolderPath endswith "\\cscript.exe") or (ProcessCommandLine contains "csvde -f C:\\windows\\web\\" and ProcessCommandLine contains ".log")