// Title: Linux Setgid Capability Set on a Binary via Setcap Utility
// Author: Luc Génaux
// Date: 2026-01-24
// Level: low
// Description: Detects the use of the 'setcap' utility to set the 'setgid' capability (cap_setgid) on a binary file.
// This capability allows a non privileged process to make arbitrary manipulations of group IDs (GIDs), including setting its current GID to a value that would otherwise be restricted (i.e. GID 0, the root group).
// This behavior can be used by adversaries to backdoor a binary in order to escalate privileges again in the future if needed.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.defense-evasion, attack.persistence, attack.t1548, attack.t1554

DeviceProcessEvents
| where ProcessCommandLine contains "cap_setgid" and FolderPath endswith "/setcap"