// Title: Linux Setuid Capability Set on a Binary via Setcap Utility
// Author: Luc Génaux
// Date: 2026-01-24
// Level: low
// Description: Detects the use of the 'setcap' utility to set the 'setuid' capability (cap_setuid) on a binary file.
// This capability allows a non privileged process to make arbitrary manipulations of user IDs (UIDs), including setting its current UID to a value that would otherwise be restricted (i.e. UID 0, the root user).
// This behavior can be used by adversaries to backdoor a binary in order to escalate privileges again in the future if needed.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.defense-evasion, attack.persistence, attack.t1548, attack.t1554

DeviceProcessEvents
| where ProcessCommandLine contains "cap_setuid" and FolderPath endswith "/setcap"