// Title: Potentially Suspicious Named Pipe Created Via Mkfifo
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-16
// Level: medium
// Description: Detects the creation of a new named pipe using the "mkfifo" utility in a potentially suspicious location
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_mkfifo_named_pipe_creation_susp_location.yml

DeviceProcessEvents
| where ProcessCommandLine contains " /tmp/" and FolderPath endswith "/mkfifo"