// Title: Python WebServer Execution - Linux
// Author: Mohamed LAKRI
// Date: 2025-10-17
// Level: medium
// Description: Detects the execution of Python web servers via command line interface (CLI).
// After gaining access to target systems, adversaries may use Python's built-in HTTP server modules to quickly establish a web server without requiring additional software.
// This technique is commonly used in post-exploitation scenarios as it provides a simple method for transferring files between the compromised host and attacker-controlled systems.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.t1048.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_python_http_server_execution.yml
// False Positives:
//   - Testing or development activity

DeviceProcessEvents
| where ((FolderPath endswith "/python" or FolderPath endswith "/python2" or FolderPath endswith "/python3") or (FolderPath contains "/python2." or FolderPath contains "/python3.")) and (ProcessCommandLine contains "http.server" or ProcessCommandLine contains "SimpleHTTPServer")