// Title: Remove Scheduled Cron Task/Job
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-15
// Level: medium
// Description: Detects usage of the 'crontab' utility to remove the current crontab.
// This is a common occurrence where cryptocurrency miners compete against each other by removing traces of other miners to hijack the maximum amount of resources possible
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_crontab_removal.yml

DeviceProcessEvents
| where ProcessCommandLine contains " -r" and FolderPath endswith "crontab"