// Title: Chmod Suspicious Directory
// Author: Christopher Peacock @SecurePeacock, SCYTHE @scythe_io
// Date: 2022-06-03
// Level: medium
// Description: Detects chmod targeting files in abnormal directory paths.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1222.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_susp_chmod_directories.yml
// False Positives:
//   - Admin changing file permissions.

DeviceProcessEvents
| where (ProcessCommandLine contains "/tmp/" or ProcessCommandLine contains "/.Library/" or ProcessCommandLine contains "/etc/" or ProcessCommandLine contains "/opt/") and FolderPath endswith "/chmod"