// Title: Local Groups Discovery - Linux
// Author: Ömer Günal, Alejandro Ortuno, oscd.community
// Date: 2020-10-11
// Level: low
// Description: Detects enumeration of local system groups. Adversaries may attempt to find local system groups and permission settings
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1069.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_local_groups.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where FolderPath endswith "/groups" or (ProcessCommandLine contains "/etc/group" and (FolderPath endswith "/cat" or FolderPath endswith "/ed" or FolderPath endswith "/head" or FolderPath endswith "/less" or FolderPath endswith "/more" or FolderPath endswith "/nano" or FolderPath endswith "/tail" or FolderPath endswith "/vi" or FolderPath endswith "/vim"))