// Title: ESXi Network Configuration Discovery Via ESXCLI
// Author: Cedric Maurugeon
// Date: 2023-09-04
// Level: medium
// Description: Detects execution of the "esxcli" command with the "network" flag in order to retrieve information about the network configuration.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.execution, attack.t1033, attack.t1007, attack.t1059.012
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_esxcli_network_discovery.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where (ProcessCommandLine contains " get" or ProcessCommandLine contains " list") and (ProcessCommandLine contains "network" and FolderPath endswith "/esxcli")