// Title: Mask System Power Settings Via Systemctl
// Author: Milad Cheraghi, Nasreddine Bencherchali
// Date: 2025-10-17
// Level: high
// Description: Detects the use of systemctl mask to disable system power management targets such as suspend, hibernate, or hybrid sleep.
// Adversaries may mask these targets to prevent a system from entering sleep or shutdown states, ensuring their malicious processes remain active and uninterrupted.
// This behavior can be associated with persistence or defense evasion, as it impairs normal system power operations to maintain long-term access or avoid termination of malicious activity.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.impact, attack.t1653
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_systemctl_mask_power_settings.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (ProcessCommandLine contains "suspend.target" or ProcessCommandLine contains "hibernate.target" or ProcessCommandLine contains "hybrid-sleep.target") and (ProcessCommandLine contains " mask" and FolderPath endswith "/systemctl")