// Title: Interactive Bash Suspicious Children
// Author: Florian Roth (Nextron Systems)
// Date: 2022-03-14
// Level: medium
// Description: Detects suspicious interactive bash as a parent to rather uncommon child processes
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, attack.t1059.004, attack.t1036
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_susp_interactive_bash.yml
// False Positives:
//   - Legitimate software that uses these patterns

DeviceProcessEvents
| where InitiatingProcessCommandLine =~ "bash -i" and ((ProcessCommandLine contains "-c import " or ProcessCommandLine contains "base64" or ProcessCommandLine contains "pty.spawn") or (FolderPath endswith "whoami" or FolderPath endswith "iptables" or FolderPath endswith "/ncat" or FolderPath endswith "/nc" or FolderPath endswith "/netcat"))