// Title: Group Has Been Deleted Via Groupdel
// Author: Tuan Le (NCSGroup)
// Date: 2022-12-26
// Level: medium
// Description: Detects execution of the "groupdel" binary. Which is used to delete a group. This is sometimes abused by threat actors in order to cover their tracks
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1531
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_groupdel.yml
// False Positives:
//   - Legitimate administrator activities

DeviceProcessEvents
| where FolderPath endswith "/groupdel"