// Title: User Added To Root/Sudoers Group Using Usermod
// Author: TuanLe (GTSC)
// Date: 2022-12-21
// Level: medium
// Description: Detects usage of the "usermod" binary to add users add users to the root or suoders groups
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_usermod_susp_group.yml
// False Positives:
//   - Legitimate administrator activities

DeviceProcessEvents
| where (ProcessCommandLine contains "-aG root" or ProcessCommandLine contains "-aG sudoers") and FolderPath endswith "/usermod"