// Title: Touch Suspicious Service File
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-01-11
// Level: medium
// Description: Detects usage of the "touch" process in service file.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1070.006
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_touch_susp.yml
// False Positives:
//   - Admin changing date of files.

DeviceProcessEvents
| where ProcessCommandLine contains " -t " and ProcessCommandLine endswith ".service" and FolderPath endswith "/touch"