// Title: PUA - TruffleHog Execution - Linux
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-09-24
// Level: medium
// Description: Detects execution of TruffleHog, a tool used to search for secrets in different platforms like Git, Jira, Slack, SharePoint, etc. that could be used maliciously.
// While it is a legitimate tool, intended for use in CI pipelines and security assessments,
// It was observed in the Shai-Hulud malware campaign targeting npm packages to steal sensitive information.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.credential-access, attack.t1083, attack.t1552.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_pua_trufflehog.yml
// False Positives:
//   - Legitimate use of TruffleHog by security teams or developers.

DeviceProcessEvents
| where FolderPath endswith "/trufflehog" or ((ProcessCommandLine contains " docker --image " or ProcessCommandLine contains " Git " or ProcessCommandLine contains " GitHub " or ProcessCommandLine contains " Jira " or ProcessCommandLine contains " Slack " or ProcessCommandLine contains " Confluence " or ProcessCommandLine contains " SharePoint " or ProcessCommandLine contains " s3 " or ProcessCommandLine contains " gcs ") and ProcessCommandLine contains " --results=verified")