// Title: Download File To Potentially Suspicious Directory Via Wget
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-06-02
// Level: medium
// Description: Detects the use of wget to download content to a suspicious directory
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_wget_download_suspicious_directory.yml

DeviceProcessEvents
| where FolderPath endswith "/wget" and (ProcessCommandLine matches regex "\\s-O\\s" or ProcessCommandLine contains "--output-document") and ProcessCommandLine contains "/tmp/"