// Title: Capsh Shell Invocation - Linux
// Author: Li Ling, Andy Parkidomo, Robert Rakowski, Blake Hartstein (Bloomberg L.P.)
// Date: 2024-09-02
// Level: high
// Description: Detects the use of the "capsh" utility to invoke a shell.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_capsh_shell_invocation.yml

DeviceProcessEvents
| where ProcessCommandLine endswith " --" and FolderPath endswith "/capsh"