// Title: Linux Recon Indicators
// Author: Florian Roth (Nextron Systems)
// Date: 2022-06-20
// Level: high
// Description: Detects events with patterns found in commands used for reconnaissance on linux systems
// MITRE Tactic: Reconnaissance
// Tags: attack.reconnaissance, attack.t1592.004, attack.credential-access, attack.t1552.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_susp_recon_indicators.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where ProcessCommandLine contains " -name .htpasswd" or ProcessCommandLine contains " -perm -4000 "