// Title: Kaspersky Endpoint Security Stopped Via CommandLine - Linux
// Author: Milad Cheraghi
// Date: 2025-10-18
// Level: high
// Description: Detects execution of the Kaspersky init.d stop script on Linux systems either directly or via systemctl.
// This activity may indicate a manual interruption of the antivirus service by an administrator, or it could be a sign of potential tampering or evasion attempts by malicious actors.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_av_kaspersky_av_disabled.yml
// False Positives:
//   - System administrator manually stopping Kaspersky services

DeviceProcessEvents
| where (ProcessCommandLine contains "stop" and ProcessCommandLine contains "kesl") and (FolderPath endswith "/systemctl" or FolderPath endswith "/bash" or FolderPath endswith "/sh")