// Title: Connection Proxy
// Author: Ömer Günal
// Date: 2020-06-17
// Level: low
// Description: Detects setting proxy configuration
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.command-and-control, attack.t1090
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_proxy_connection.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where ProcessCommandLine contains "http_proxy=" or ProcessCommandLine contains "https_proxy="