// Title: Suspicious Java Children Processes
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-03
// Level: high
// Description: Detects java process spawning suspicious children
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_susp_java_children.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "/bin/sh" or ProcessCommandLine contains "bash" or ProcessCommandLine contains "dash" or ProcessCommandLine contains "ksh" or ProcessCommandLine contains "zsh" or ProcessCommandLine contains "csh" or ProcessCommandLine contains "fish" or ProcessCommandLine contains "curl" or ProcessCommandLine contains "wget" or ProcessCommandLine contains "python") and InitiatingProcessFolderPath endswith "/java"