// Title: Potentially Suspicious Execution From Tmp Folder
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-06-02
// Level: medium
// Description: Detects a potentially suspicious execution of a process located in the '/tmp/' folder
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_susp_execution_tmp_folder.yml

DeviceProcessEvents
| where FolderPath startswith "/tmp/" and (not(FolderPath endswith "/usr/bin/nextcloud"))