// Title: Audit Rules Deleted Via Auditctl
// Author: Mohamed LAKRI
// Date: 2025-10-17
// Level: high
// Description: Detects the execution of 'auditctl' with the '-D' command line parameter, which deletes all configured audit rules and watches on Linux systems.
// This technique is commonly used by attackers to disable audit logging and cover their tracks by removing monitoring capabilities.
// Removal of audit rules can significantly impair detection of malicious activities on the affected system.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.012
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_auditctl_clear_rules.yml
// False Positives:
//   - An administrator troubleshooting. Investigate all attempts.

DeviceProcessEvents
| where ProcessCommandLine matches regex "-D" and FolderPath endswith "/auditctl"