// Title: ESXi Account Creation Via ESXCLI
// Author: Cedric Maurugeon
// Date: 2023-08-22
// Level: medium
// Description: Detects user account creation on ESXi system via esxcli
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.execution, attack.t1136, attack.t1059.012
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_esxcli_user_account_creation.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where (ProcessCommandLine contains "system " and ProcessCommandLine contains "account " and ProcessCommandLine contains "add ") and FolderPath endswith "/esxcli"