// Title: Ufw Force Stop Using Ufw-Init
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-01-18
// Level: medium
// Description: Detects attempts to force stop the ufw using ufw-init
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_disable_ufw.yml
// False Positives:
//   - Network administrators

DeviceProcessEvents
| where (ProcessCommandLine contains "-ufw-init" and ProcessCommandLine contains "force-stop") or (ProcessCommandLine contains "ufw" and ProcessCommandLine contains "disable")