// Title: BPFtrace Unsafe Option Usage
// Author: Andreas Hunkeler (@Karneades)
// Date: 2022-02-11
// Level: medium
// Description: Detects the usage of the unsafe bpftrace option
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_bpftrace_unsafe_option_usage.yml
// False Positives:
//   - Legitimate usage of the unsafe option

DeviceProcessEvents
| where ProcessCommandLine contains "--unsafe" and FolderPath endswith "bpftrace"