// Title: Potential Xterm Reverse Shell
// Author: @d4ns4n_
// Date: 2023-04-24
// Level: medium
// Description: Detects usage of "xterm" as a potential reverse shell tunnel
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_xterm_reverse_shell.yml

DeviceProcessEvents
| where ProcessCommandLine contains "-display" and ProcessCommandLine endswith ":1" and FolderPath contains "xterm"