// Title: Linux Base64 Encoded Shebang In CLI
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-15
// Level: medium
// Description: Detects the presence of a base64 version of the shebang in the commandline, which could indicate a malicious payload about to be decoded
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1140
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_base64_shebang_cli.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where ProcessCommandLine contains "IyEvYmluL2Jhc2" or ProcessCommandLine contains "IyEvYmluL2Rhc2" or ProcessCommandLine contains "IyEvYmluL3pza" or ProcessCommandLine contains "IyEvYmluL2Zpc2" or ProcessCommandLine contains "IyEvYmluL3No"