// Title: Docker Container Discovery Via Dockerenv Listing
// Author: Seth Hanford
// Date: 2023-08-23
// Level: low
// Description: Detects listing or file reading of ".dockerenv" which can be a sing of potential container discovery
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1082
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_susp_dockerenv_recon.yml
// False Positives:
//   - Legitimate system administrator usage of these commands
//   - Some container tools or deployments may use these techniques natively to determine how they proceed with execution, and will need to be filtered

DeviceProcessEvents
| where ProcessCommandLine endswith ".dockerenv" and (FolderPath endswith "/cat" or FolderPath endswith "/dir" or FolderPath endswith "/find" or FolderPath endswith "/ls" or FolderPath endswith "/stat" or FolderPath endswith "/test" or FolderPath endswith "grep")