// Title: Pnscan Binary Data Transmission Activity
// Author: David Burkett (@signalblur)
// Date: 2024-04-16
// Level: medium
// Description: Detects command line patterns associated with the use of Pnscan for sending and receiving binary data across the network.
// This behavior has been identified in a Linux malware campaign targeting Docker, Apache Hadoop, Redis, and Confluence and was previously used by the threat actor known as TeamTNT
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1046
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_pnscan_binary_cli_pattern.yml

DeviceProcessEvents
| where ProcessCommandLine matches regex "-(W|R)\\s?(\\s|"|')([0-9a-fA-F]{2}\\s?){2,20}(\\s|"|')"