// Title: Suspicious Curl File Upload - Linux
// Author: Nasreddine Bencherchali (Nextron Systems), Cedric MAURUGEON (Update)
// Date: 2022-09-15
// Level: medium
// Description: Detects a suspicious curl process start the adds a file to a web request
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.command-and-control, attack.t1567, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_susp_curl_fileupload.yml
// False Positives:
//   - Scripts created by developers and admins

DeviceProcessEvents
| where (((ProcessCommandLine contains " --form" or ProcessCommandLine contains " --upload-file " or ProcessCommandLine contains " --data " or ProcessCommandLine contains " --data-") or ProcessCommandLine matches regex "\\s-[FTd]\\s") and FolderPath endswith "/curl") and (not((ProcessCommandLine contains "://localhost" or ProcessCommandLine contains "://127.0.0.1")))