// Title: Python Reverse Shell Execution Via PTY And Socket Modules
// Author: @d4ns4n_, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-04-24
// Level: high
// Description: Detects the execution of python with calls to the socket and pty module in order to connect and spawn a potential reverse shell.
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_python_reverse_shell.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " -c " and ProcessCommandLine contains "import" and ProcessCommandLine contains "pty" and ProcessCommandLine contains "socket" and ProcessCommandLine contains "spawn" and ProcessCommandLine contains ".connect") and FolderPath contains "python"