// Title: Scheduled Task/Job At
// Author: Ömer Günal, oscd.community
// Date: 2020-10-06
// Level: low
// Description: Detects the use of at/atd which are utilities that are used to schedule tasks.
// They are often abused by adversaries to maintain persistence or to perform task scheduling for initial or recurring execution of malicious code
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.execution, attack.persistence, attack.t1053.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_at_command.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where FolderPath endswith "/at" or FolderPath endswith "/atd"