// Title: Nohup Execution
// Author: Christopher Peacock @SecurePeacock, SCYTHE @scythe_io
// Date: 2022-06-06
// Level: medium
// Description: Detects usage of nohup which could be leveraged by an attacker to keep a process running or break out from restricted environments
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_nohup.yml
// False Positives:
//   - Administrators or installed processes that leverage nohup

DeviceProcessEvents
| where FolderPath endswith "/nohup"