// Title: System Information Discovery
// Author: Ömer Günal, oscd.community
// Date: 2020-10-08
// Level: informational
// Description: Detects system information discovery commands
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1082
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_system_info_discovery.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where FolderPath endswith "/uname" or FolderPath endswith "/hostname" or FolderPath endswith "/uptime" or FolderPath endswith "/lspci" or FolderPath endswith "/dmidecode" or FolderPath endswith "/lscpu" or FolderPath endswith "/lsmod"