// Title: ESXi Admin Permission Assigned To Account Via ESXCLI
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-09-04
// Level: high
// Description: Detects execution of the "esxcli" command with the "system" and "permission" flags in order to assign admin permissions to an account.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.execution, attack.privilege-escalation, attack.t1059.012, attack.t1098
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_esxcli_permission_change_admin.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where ProcessCommandLine contains "system" and (ProcessCommandLine contains " permission " and ProcessCommandLine contains " set" and ProcessCommandLine contains "Admin") and FolderPath endswith "/esxcli"