// Title: ESXi VM Kill Via ESXCLI
// Author: Nasreddine Bencherchali (Nextron Systems), Cedric Maurugeon
// Date: 2023-09-04
// Level: medium
// Description: Detects execution of the "esxcli" command with the "vm" and "kill" flag in order to kill/shutdown a specific VM.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.impact, attack.t1059.012, attack.t1529
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_esxcli_vm_kill.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where (ProcessCommandLine contains "vm process" and ProcessCommandLine contains "kill") and FolderPath endswith "/esxcli"