// Title: Print History File Contents
// Author: Florian Roth (Nextron Systems)
// Date: 2022-06-20
// Level: medium
// Description: Detects events in which someone prints the contents of history files to the commandline or redirects it to a file for reconnaissance
// MITRE Tactic: Reconnaissance
// Tags: attack.reconnaissance, attack.t1592.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_susp_history_recon.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where (FolderPath endswith "/cat" or FolderPath endswith "/head" or FolderPath endswith "/tail" or FolderPath endswith "/more") and ((ProcessCommandLine contains "/.bash_history" or ProcessCommandLine contains "/.zsh_history") or (ProcessCommandLine endswith "_history" or ProcessCommandLine endswith ".history" or ProcessCommandLine endswith "zhistory"))