// Title: Suspicious Git Clone - Linux
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-03
// Level: medium
// Description: Detects execution of "git" in order to clone a remote repository that contain suspicious keywords which might be suspicious
// MITRE Tactic: Reconnaissance
// Tags: attack.reconnaissance, attack.t1593.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_susp_git_clone.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " clone " and FolderPath endswith "/git") and (ProcessCommandLine contains "exploit" or ProcessCommandLine contains "Vulns" or ProcessCommandLine contains "vulnerability" or ProcessCommandLine contains "RCE" or ProcessCommandLine contains "RemoteCodeExecution" or ProcessCommandLine contains "Invoke-" or ProcessCommandLine contains "CVE-" or ProcessCommandLine contains "poc-" or ProcessCommandLine contains "ProofOfConcept" or ProcessCommandLine contains "proxyshell" or ProcessCommandLine contains "log4shell" or ProcessCommandLine contains "eternalblue" or ProcessCommandLine contains "eternal-blue" or ProcessCommandLine contains "MS17-")