// Title: Install Root Certificate
// Author: Ömer Günal, oscd.community
// Date: 2020-10-05
// Level: low
// Description: Detects installation of new certificate on the system which attackers may use to avoid warnings when connecting to controlled web servers or C2s
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1553.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_install_root_certificate.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where FolderPath endswith "/update-ca-certificates" or FolderPath endswith "/update-ca-trust"