// Title: Decode Base64 Encoded Text
// Author: Daniil Yugoslavskiy, oscd.community
// Date: 2020-10-19
// Level: low
// Description: Detects usage of base64 utility to decode arbitrary base64-encoded text
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_base64_decode.yml
// False Positives:
//   - Legitimate activities

DeviceProcessEvents
| where ProcessCommandLine contains "-d" and FolderPath endswith "/base64"