// Title: Remove Immutable File Attribute
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-15
// Level: medium
// Description: Detects usage of the 'chattr' utility to remove immutable file attribute.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1222.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_chattr_immutable_removal.yml
// False Positives:
//   - Administrator interacting with immutable files (e.g. for instance backups).

DeviceProcessEvents
| where ProcessCommandLine contains " -i " and FolderPath endswith "/chattr"