// Title: Shell Invocation via Apt - Linux
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-28
// Level: medium
// Description: Detects the use of the "apt" and "apt-get" commands to execute a shell or proxy commands.
// Such behavior may be associated with privilege escalation, unauthorized command execution, or to break out from restricted environments.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1083
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_apt_shell_execution.yml

DeviceProcessEvents
| where ProcessCommandLine contains "APT::Update::Pre-Invoke::=" and (FolderPath endswith "/apt" or FolderPath endswith "/apt-get")