// Title: Clear Linux Logs
// Author: Ömer Günal, oscd.community
// Date: 2020-10-07
// Level: medium
// Description: Detects attempts to clear logs on the system. Adversaries may clear system logs to hide evidence of an intrusion
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1070.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_clear_logs.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where (ProcessCommandLine contains "/var/log" or ProcessCommandLine contains "/var/spool/mail") and (FolderPath endswith "/rm" or FolderPath endswith "/shred" or FolderPath endswith "/unlink")