// Title: Linux Doas Tool Execution
// Author: Sittikorn S, Teoderick Contreras
// Date: 2022-01-20
// Level: low
// Description: Detects the doas tool execution in linux host platform. This utility tool allow standard users to perform tasks as root, the same way sudo does.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1548
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_doas_execution.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where FolderPath endswith "/doas"