// Title: Clipboard Collection with Xclip Tool
// Author: Pawel Mazur, Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research), MSTIC
// Date: 2021-10-15
// Level: low
// Description: Detects attempts to collect data stored in the clipboard from users with the usage of xclip tool. Xclip has to be installed.
// Highly recommended using rule on servers, due to high usage of clipboard utilities on user workstations.
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1115
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_clipboard_collection.yml
// False Positives:
//   - Legitimate usage of xclip tools.

DeviceProcessEvents
| where (ProcessCommandLine contains "-sel" and ProcessCommandLine contains "clip" and ProcessCommandLine contains "-o") and FolderPath contains "xclip"