// Title: Enable BPF Kprobes Tracing
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-25
// Level: medium
// Description: Detects common command used to enable bpf kprobes tracing
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_bpf_kprob_tracing_enabled.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "/myprobe/enable" or ProcessCommandLine contains "/myretprobe/enable") and (ProcessCommandLine contains "echo 1 >" and ProcessCommandLine contains "/sys/kernel/debug/tracing/events/kprobes/")