// Title: Linux Package Uninstall
// Author: Tuan Le (NCSGroup), Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-03-09
// Level: low
// Description: Detects linux package removal using builtin tools such as "yum", "apt", "apt-get" or "dpkg".
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1070
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_remove_package.yml
// False Positives:
//   - Administrator or administrator scripts might delete packages for several reasons (debugging, troubleshooting).

DeviceProcessEvents
| where ((ProcessCommandLine contains "remove" or ProcessCommandLine contains "purge") and (FolderPath endswith "/apt" or FolderPath endswith "/apt-get")) or ((ProcessCommandLine contains "--remove " or ProcessCommandLine contains " -r ") and FolderPath endswith "/dpkg") or (ProcessCommandLine contains " -e " and FolderPath endswith "/rpm") or ((ProcessCommandLine contains "erase" or ProcessCommandLine contains "remove") and FolderPath endswith "/yum")