// Title: Crontab Enumeration
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-06-02
// Level: low
// Description: Detects usage of crontab to list the tasks of the user
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1007
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_crontab_enumeration.yml
// False Positives:
//   - Legitimate use of crontab

DeviceProcessEvents
| where ProcessCommandLine contains " -l" and FolderPath endswith "/crontab"