// Title: Potential Container Discovery Via Inodes Listing
// Author: Seth Hanford
// Date: 2023-08-23
// Level: low
// Description: Detects listing of the inodes of the "/" directory to determine if the we are running inside of a container.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1082
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_susp_inod_listing.yml
// False Positives:
//   - Legitimate system administrator usage of these commands
//   - Some container tools or deployments may use these techniques natively to determine how they proceed with execution, and will need to be filtered

DeviceProcessEvents
| where (ProcessCommandLine endswith " /" or ProcessCommandLine contains " / ") and FolderPath endswith "/ls" and ProcessCommandLine matches regex "(?:\\s-[^-\\s]{0,20}d|\\s--directory\\s)" and ProcessCommandLine matches regex "(?:\\s-[^-\\s]{0,20}i|\\s--inode\\s)"