// Title: Suspicious Nohup Execution
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-06-02
// Level: high
// Description: Detects execution of binaries located in potentially suspicious locations via "nohup"
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_nohup_susp_execution.yml

DeviceProcessEvents
| where ProcessCommandLine contains "/tmp/" and FolderPath endswith "/nohup"