// Title: Mount Execution With Hidepid Parameter
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2023-01-12
// Level: medium
// Description: Detects execution of the "mount" command with "hidepid" parameter to make invisible processes to other users from the system
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.defense-evasion, attack.t1564
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_mount_hidepid.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "hidepid=2" and ProcessCommandLine contains " -o ") and FolderPath endswith "/mount"