// Title: Suspicious Package Installed - Linux
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-03
// Level: medium
// Description: Detects installation of suspicious packages using system installation utilities
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1553.004
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where ((ProcessCommandLine contains "install" and (FolderPath endswith "/apt" or FolderPath endswith "/apt-get")) or ((ProcessCommandLine contains "--install" or ProcessCommandLine contains "-i") and FolderPath endswith "/dpkg") or (ProcessCommandLine contains "-i" and FolderPath endswith "/rpm") or ((ProcessCommandLine contains "localinstall" or ProcessCommandLine contains "install") and FolderPath endswith "/yum")) and (ProcessCommandLine contains "nmap" or ProcessCommandLine contains " nc" or ProcessCommandLine contains "netcat" or ProcessCommandLine contains "wireshark" or ProcessCommandLine contains "tshark" or ProcessCommandLine contains "openconnect" or ProcessCommandLine contains "proxychains" or ProcessCommandLine contains "socat")