// Title: Potential APT FIN7 Reconnaissance/POWERTRASH Related Activity
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-04
// Level: high
// Description: Detects specific command line execution used by FIN7 as reported by WithSecureLabs for reconnaissance and POWERTRASH execution
// MITRE Tactic: Execution
// Tags: attack.execution, attack.g0046, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2023/TA/FIN7/proc_creation_win_apt_fin7_powertrash_lateral_movement.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (ProcessCommandLine contains "-noni -nop -exe bypass -f \\\\" and ProcessCommandLine contains "ADMIN$") or (ProcessCommandLine contains "-ex bypass -noprof -nolog -nonint -f" and ProcessCommandLine contains "C:\\Windows\\Temp\\")