// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2021/12/13
// Level: high
// Description: Detects the deletion of all backups or system state backups via "wbadmin.exe".
This technique is used by numerous ransomware families and actors.
This may only be successful on server platforms that have Windows Backup enabled.

// Tags: attack.impact, attack.t1490
DeviceProcessEvents
| where (ProcessCommandLine contains "keepVersions:0" and (ProcessCommandLine contains "delete" and ProcessCommandLine contains "backup")) and (FolderPath endswith "\\wbadmin.exe" or ProcessVersionInfoOriginalFileName =~ "WBADMIN.EXE")