// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/09/09
// Level: high
// Description: Detects the usage of schtasks with the delete flag and the asterisk symbole to delete all tasks from the schedule of the local computer, including tasks scheduled by other users.
// Tags: attack.impact, attack.t1489
DeviceProcessEvents
| where (ProcessCommandLine contains " /delete " and ProcessCommandLine contains "/tn \*" and ProcessCommandLine contains " /f") and FolderPath endswith "\\schtasks.exe"