// Author: Nasreddine Bencherchali (Nextron Systems), frack113
// Date: 2023/08/09
// Level: high
// Description: Detects the execution of a renamed "gpg.exe". Often used by ransomware and loaders to decrypt/encrypt data.
// Tags: attack.impact, attack.t1486
DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "gpg.exe" and (not((FolderPath endswith "\\gpg.exe" or FolderPath endswith "\\gpg2.exe")))