// Author: Max Altgelt (Nextron Systems), Tobias Michalski (Nextron Systems)
// Date: 2021/08/09
// Level: high
// Description: Detects a command that accesses password storing registry hives via volume shadow backups
// Tags: attack.impact, attack.t1490
DeviceProcessEvents
| where ProcessCommandLine contains "\\\\?\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy" and (ProcessCommandLine contains "\\NTDS.dit" or ProcessCommandLine contains "\\SYSTEM" or ProcessCommandLine contains "\\SECURITY" or ProcessCommandLine contains "C:\\tmp\\log")