// Author: Jakob Weinzettl, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/03/05
// Level: low
// Description: Detects the stopping of a Windows service via the PowerShell Cmdlet "Stop-Service"
// Tags: attack.impact, attack.t1489
DeviceProcessEvents
| where ProcessCommandLine contains "Stop-Service " and ((ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")) or (FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe"))