// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/10/17
// Level: high
// Description: Detects usage of the "Set-Service" powershell cmdlet to configure a new SecurityDescriptor that allows a service to be hidden from other utilities such as "sc.exe", "Get-Service"...etc. (Works only in powershell 7)
// Tags: attack.persistence, attack.defense_evasion, attack.privilege_escalation, attack.t1574.011
DeviceProcessEvents
| where (ProcessCommandLine contains "-SecurityDescriptorSddl " or ProcessCommandLine contains "-sd ") and (FolderPath endswith "\\pwsh.exe" or ProcessVersionInfoOriginalFileName =~ "pwsh.dll") and (ProcessCommandLine contains "Set-Service " and ProcessCommandLine contains "DCLCWPDTSD")