// Author: frack113
// Date: 2021/12/30
// Level: medium
// Description: Adversaries may use port monitors to run an attacker supplied DLL during system boot for persistence or privilege escalation.
A port monitor can be set through the AddMonitor API call to set a DLL to be loaded at startup.

// Tags: attack.persistence, attack.t1547.010
DeviceRegistryEvents
| where (RegistryValueData endswith ".dll" and RegistryKey contains "\\Control\\Print\\Monitors") and (not(((RegistryValueData =~ "cpwmon64_v40.dll" and InitiatingProcessFolderPath =~ "C:\\Windows\\System32\\spoolsv.exe" and RegistryKey contains "\\Control\\Print\\Monitors\\CutePDF Writer Monitor v4.0\\Driver" and (InitiatingProcessAccountName contains "AUTHORI" or InitiatingProcessAccountName contains "AUTORI")) or RegistryKey contains "\\Control\\Print\\Monitors\\MONVNC\\Driver" or (RegistryKey contains "Control\\Print\\Environments" and RegistryKey contains "\\Drivers" and RegistryKey contains "\\VNC Printer"))))