// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/07/21
// Level: high
// Description: Detects when an attacker adds a new "Debugger" value to the "Hangs" key in order to achieve persistence which will get invoked when an application crashes
// Tags: attack.persistence
DeviceRegistryEvents
| where ActionType =~ "RegistryValueSet" and RegistryKey contains "\\SOFTWARE\\Microsoft\\Windows\\Windows Error Reporting\\Hangs\\Debugger"