// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/06/28
// Level: high
// Description: Detects when a program changes the default file association of any extension to an executable.
When a file is opened, the default program used to open the file (also called the file association or handler) is checked. File association selections are stored in the Windows Registry and can be edited by users, administrators, or programs that have Registry access or by administrators using the built-in assoc utility. Applications can modify the file association for a given file extension to call an arbitrary program when a file with the given extension is opened.

// Tags: attack.persistence, attack.t1546.001
DeviceProcessEvents
| where ((ProcessCommandLine contains "assoc " and ProcessCommandLine contains "exefile") and (FolderPath endswith "\\cmd.exe" or ProcessVersionInfoOriginalFileName =~ "Cmd.Exe")) and (not(ProcessCommandLine contains ".exe=exefile"))