// Author: Aedan Russell, frack113, X__Junior (Nextron Systems)
// Date: 2022/06/19
// Level: medium
// Description: Detects a Chromium based browser process with the 'load-extension' flag to start a instance with a custom extension
// Tags: attack.persistence, attack.t1176
DeviceProcessEvents
| where ProcessCommandLine contains "--load-extension=" and (FolderPath endswith "\\brave.exe" or FolderPath endswith "\\chrome.exe" or FolderPath endswith "\\msedge.exe" or FolderPath endswith "\\opera.exe" or FolderPath endswith "\\vivaldi.exe")