// Author: frack113
// Date: 2022/08/28
// Level: medium
// Description: Detect modification of TreatAs key to enable "rundll32.exe -sta" command
// Tags: attack.persistence, attack.t1546.015
DeviceRegistryEvents
| where RegistryKey endswith "TreatAs\\(Default)" and (not(((InitiatingProcessFolderPath in~ ("C:\\Windows\\system32\\msiexec.exe", "C:\\Windows\\SysWOW64\\msiexec.exe")) or (InitiatingProcessFolderPath endswith "\\OfficeClickToRun.exe" and InitiatingProcessFolderPath startswith "C:\\Program Files\\Common Files\\Microsoft Shared\\ClickToRun\\") or InitiatingProcessFolderPath =~ "C:\\Program Files (x86)\\Microsoft Office\\root\\integration\\integrator.exe" or InitiatingProcessFolderPath =~ "C:\\Windows\\system32\\svchost.exe")))