// Author: frack113
// Date: 2022/05/09
// Level: high
// Description: Detects WerFault copoed to a suspicious folder, which could be a sign of WerFault DLL hijacking
// Tags: attack.persistence, attack.defense_evasion, attack.t1574.001
DeviceFileEvents
| where (FolderPath endswith "\\WerFault.exe" or FolderPath endswith "\\wer.dll") and (not((FolderPath contains "\\System32\\" or FolderPath contains "\\SysWOW64\\" or FolderPath contains "\\WinSxS\\")))