// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/05/23
// Level: low
// Description: Detects the registration of a new ODBC driver.
// Tags: attack.persistence
DeviceRegistryEvents
| where (ActionType =~ "RegistryValueSet" and RegistryKey contains "\\SOFTWARE\\ODBC\\ODBCINST.INI" and RegistryKey endswith "\\Driver") and (not((RegistryValueData =~ "%WINDIR%\\System32\\SQLSRV32.dll" and RegistryKey contains "\\SQL Server"))) and (not(((RegistryValueData endswith "\\ACEODBC.DLL" and RegistryValueData startswith "C:\\Progra" and RegistryKey contains "\\Microsoft Access ") or (RegistryValueData endswith "\\ACEODBC.DLL" and RegistryValueData startswith "C:\\Progra" and RegistryKey contains "\\Microsoft Excel Driver"))))