// Author: Teymur Kheirkhabarov
// Date: 2019/10/26
// Level: high
// Description: Detection of sc.exe utility spawning by user with Medium integrity level to change service ImagePath or FailureCommand
// Tags: attack.persistence, attack.defense_evasion, attack.privilege_escalation, attack.t1574.011
DeviceProcessEvents
| where (FolderPath endswith "\\sc.exe" and ProcessIntegrityLevel =~ "Medium") and ((ProcessCommandLine contains "config" and ProcessCommandLine contains "binPath") or (ProcessCommandLine contains "failure" and ProcessCommandLine contains "command"))