// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024/03/06
// Level: medium
// Description: Detects potentially suspicious changes to the SentinelOne context menu scan command by a process other than SentinelOne.
// Tags: attack.persistence
DeviceRegistryEvents
| where RegistryKey contains "\\shell\\SentinelOneScan\\command" and (not(((InitiatingProcessFolderPath endswith "C:\\Program Files\\SentinelOne\\" or InitiatingProcessFolderPath endswith "C:\\Program Files (x86)\\SentinelOne\\") or (RegistryValueData contains "\\SentinelScanFromContextMenu.exe" and (RegistryValueData startswith "C:\\Program Files\\SentinelOne\\Sentinel Agent" or RegistryValueData startswith "C:\\Program Files (x86)\\SentinelOne\\Sentinel Agent")))))