// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/07/21
// Level: high
// Description: Detects when an attacker modifies the registry key "HtmlHelp Author" to achieve persistence
// Tags: attack.persistence
DeviceRegistryEvents
| where RegistryKey contains "\\Software\\Microsoft\\HtmlHelp Author\\Location" or RegistryKey contains "\\Software\\WOW6432Node\\Microsoft\\HtmlHelp Author\\Location"