// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/07/21
// Level: high
// Description: Detects when an attacker registers a new AMSI provider in order to achieve persistence
// Tags: attack.persistence
DeviceRegistryEvents
| where (ActionType =~ "RegistryKeyCreated" and (RegistryKey contains "\\SOFTWARE\\Microsoft\\AMSI\\Providers" or RegistryKey contains "\\SOFTWARE\\WOW6432Node\\Microsoft\\AMSI\\Providers")) and (not((InitiatingProcessFolderPath startswith "C:\\Windows\\System32\\" or InitiatingProcessFolderPath startswith "C:\\Program Files\\" or InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\")))