// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/05/09
// Level: medium
// Description: Detects the creation of a new PowerShell module in the first folder of the module directory structure "\WindowsPowerShell\Modules\malware\malware.psm1". This is somewhat an uncommon practice as legitimate modules often includes a version folder.
// Tags: attack.persistence
DeviceFileEvents
| where match or match