// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2021/04/05
// Level: high
// Description: Detects the modification of Outlook setting "LoadMacroProviderOnBoot" which if enabled allows the automatic loading of any configured VBA project/module
// Tags: attack.persistence, attack.command_and_control, attack.t1137, attack.t1008, attack.t1546
DeviceRegistryEvents
| where RegistryValueData contains "0x00000001" and RegistryKey endswith "\\Outlook\\LoadMacroProviderOnBoot"