// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/08/01
// Level: high
// Description: Detects the installation of a new shim database where the file is located in a non-default location
// Tags: attack.persistence, attack.t1546.011
DeviceRegistryEvents
| where (RegistryKey contains "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\AppCompatFlags\\InstalledSDB" and RegistryKey contains "\\DatabasePath") and (not(RegistryValueData contains ":\\Windows\\AppPatch\\Custom"))