// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/05/05
// Level: medium
// Description: Detects creation of the Process Monitor driver by processes other than Process Monitor (procmon) itself.
// Tags: attack.persistence, attack.privilege_escalation, attack.t1068
DeviceFileEvents
| where (FolderPath contains "\\procmon" and FolderPath endswith ".sys") and (not((InitiatingProcessFolderPath endswith "\\procmon.exe" or InitiatingProcessFolderPath endswith "\\procmon64.exe")))