// Author: frack113
// Date: 2022/06/19
// Level: high
// Description: Detects processes setting a new DLL in DllName in under HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\W32Time\TimeProvider.
Adversaries may abuse time providers to execute DLLs when the system boots.
The Windows Time service (W32Time) enables time synchronization across and within domains.

// Tags: attack.persistence, attack.privilege_escalation, attack.t1547.003
DeviceRegistryEvents
| where (ActionType =~ "RegistryValueSet" and RegistryKey endswith "DllName" and RegistryKey startswith "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet001\\Services\\W32Time\\TimeProviders") and (not(RegistryValueData =~ "C:\\Windows\\SYSTEM32\\w32time.DLL"))