// Author: Florian Roth (Nextron Systems)
// Date: 2021/03/11
// Level: high
// Description: Detects the creation of scheduled tasks that involves a temporary folder and runs only once
// Tags: attack.execution, attack.persistence, attack.t1053.005
DeviceProcessEvents
| where (ProcessCommandLine contains " /create " and ProcessCommandLine contains " /sc once " and ProcessCommandLine contains "\\Temp\\") and FolderPath endswith "\\schtasks.exe"