// Author: Florian Roth (Nextron Systems), oscd.community, Jonhnathan Ribeiro
// Date: 2019/09/06
// Level: high
// Description: Detects the registration of a debugger for a program that is available in the logon screen (sticky key backdoor).
// Tags: attack.persistence, attack.privilege_escalation, attack.t1546.008
DeviceProcessEvents
| where ProcessCommandLine contains "\\CurrentVersion\\Image File Execution Options\\" and (ProcessCommandLine contains "sethc.exe" or ProcessCommandLine contains "utilman.exe" or ProcessCommandLine contains "osk.exe" or ProcessCommandLine contains "magnify.exe" or ProcessCommandLine contains "narrator.exe" or ProcessCommandLine contains "displayswitch.exe" or ProcessCommandLine contains "atbroker.exe" or ProcessCommandLine contains "HelpPane.exe")