// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/10
// Level: high
// Description: Detects when a file with a suspicious extension is created in the startup folder
// Tags: attack.persistence, attack.t1547.001
DeviceFileEvents
| where FolderPath contains "\\Windows\\Start Menu\\Programs\\Startup\\" and (FolderPath endswith ".vbs" or FolderPath endswith ".vbe" or FolderPath endswith ".bat" or FolderPath endswith ".ps1" or FolderPath endswith ".hta" or FolderPath endswith ".dll" or FolderPath endswith ".jar" or FolderPath endswith ".msi" or FolderPath endswith ".scr" or FolderPath endswith ".cmd")