// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/06/16
// Level: medium
// Description: Detects usage of Sysinternals PsService which can be abused for service reconnaissance and tampering
// Tags: attack.discovery, attack.persistence, attack.t1543.003
DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "psservice.exe" or (FolderPath endswith "\\PsService.exe" or FolderPath endswith "\\PsService64.exe")