// Author: Tom Ueltschi (@c_APT_ure), Tim Shelton
// Date: 2019/01/12
// Level: high
// Description: Detects uncommon "userinit.exe" child processes, which could be a sign of uncommon shells or login scripts used for persistence.
// Tags: attack.t1037.001, attack.persistence
DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\userinit.exe" and (not(FolderPath =~ "C:\\WINDOWS\\explorer.exe")) and (not((FolderPath endswith "\\Citrix\\System32\\icast.exe" or isnull(FolderPath) or (ProcessCommandLine contains "netlogon.bat" or ProcessCommandLine contains "UsrLogon.cmd") or (FolderPath in~ ("C:\\Windows\\System32\\proquota.exe", "C:\\Windows\\SysWOW64\\proquota.exe")) or ProcessCommandLine =~ "PowerShell.exe")))