// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/12
// Level: medium
// Description: Detects addition of users to the local administrator group via "Net" or "Add-LocalGroupMember".
// Tags: attack.persistence, attack.t1098
DeviceProcessEvents
| where (ProcessCommandLine contains " administrators " or ProcessCommandLine contains " administrateur") and ((ProcessCommandLine contains "localgroup " and ProcessCommandLine contains " /add") or (ProcessCommandLine contains "Add-LocalGroupMember " and ProcessCommandLine contains " -Group "))