// Author: Florian Roth (Nextron Systems)
// Date: 2021/12/06
// Level: high
// Description: Detects addition of users to the local Remote Desktop Users group via "Net" or "Add-LocalGroupMember".
// Tags: attack.persistence, attack.lateral_movement, attack.t1133, attack.t1136.001, attack.t1021.001
DeviceProcessEvents
| where (ProcessCommandLine contains "Remote Desktop Users" or ProcessCommandLine contains "Utilisateurs du Bureau à distance" or ProcessCommandLine contains "Usuarios de escritorio remoto") and ((ProcessCommandLine contains "localgroup " and ProcessCommandLine contains " /add") or (ProcessCommandLine contains "Add-LocalGroupMember " and ProcessCommandLine contains " -Group "))