// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/07/22
// Level: medium
// Description: Detects the creation or modification of the Windows Terminal Profile settings file "settings.json" by an uncommon process.
// Tags: attack.persistence, attack.t1547.015
DeviceFileEvents
| where (InitiatingProcessFolderPath endswith "\\cmd.exe" or InitiatingProcessFolderPath endswith "\\cscript.exe" or InitiatingProcessFolderPath endswith "\\mshta.exe" or InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe" or InitiatingProcessFolderPath endswith "\\wscript.exe") and FolderPath endswith "\\AppData\\Local\\Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\settings.json"