// Author: frack113
// Date: 2021/12/30
// Level: high
// Description: Adversaries may abuse features of Winlogon to execute DLLs and/or executables when a user logs in.
Winlogon.exe is a Windows component responsible for actions at logon/logoff as well as the secure attention sequence (SAS) triggered by Ctrl-Alt-Delete.

// Tags: attack.persistence, attack.t1547.004
DeviceRegistryEvents
| where RegistryValueData endswith ".dll" and ActionType =~ "RegistryValueSet" and RegistryKey endswith "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\Notify\\logon"