// Title: Tomcat WebServer Logs Deleted
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-16
// Level: medium
// Description: Detects the deletion of tomcat WebServer logs which may indicate an attempt to destroy forensic evidence
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1070
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_delete/file_delete_win_delete_tomcat_logs.yml
// False Positives:
//   - During uninstallation of the tomcat server
//   - During log rotation

DeviceFileEvents
| where (FolderPath contains "catalina." or FolderPath contains "_access_log." or FolderPath contains "localhost.") and (FolderPath contains "\\Tomcat" and FolderPath contains "\\logs\\")