// Title: Unusual File Deletion by Dns.exe
// Author: Tim Rauch (Nextron Systems), Elastic (idea)
// Date: 2022-09-27
// Level: high
// Description: Detects an unexpected file being deleted by dns.exe which my indicate activity related to remote code execution or other forms of exploitation as seen in CVE-2020-1350 (SigRed)
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.initial-access, attack.t1133
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_delete/file_delete_win_unusual_deletion_by_dns_exe.yml

DeviceFileEvents
| where InitiatingProcessFolderPath endswith "\\dns.exe" and (not(FolderPath endswith "\\dns.log"))