// Title: IIS WebServer Access Logs Deleted
// Author: Tim Rauch (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-16
// Level: medium
// Description: Detects the deletion of IIS WebServer access logs which may indicate an attempt to destroy forensic evidence
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1070
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_delete/file_delete_win_delete_iis_access_logs.yml
// False Positives:
//   - During uninstallation of the IIS service
//   - During log rotation

DeviceFileEvents
| where FolderPath contains "\\inetpub\\logs\\LogFiles\\" and FolderPath endswith ".log"