// Title: Prefetch File Deleted
// Author: Cedric MAURUGEON
// Date: 2021-09-29
// Level: high
// Description: Detects the deletion of a prefetch file which may indicate an attempt to destroy forensic evidence
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1070.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_delete/file_delete_win_delete_prefetch.yml

DeviceFileEvents
| where (FolderPath contains ":\\Windows\\Prefetch\\" and FolderPath endswith ".pf") and (not((InitiatingProcessFolderPath endswith ":\\windows\\system32\\svchost.exe" and (RequestAccountName contains "AUTHORI" or RequestAccountName contains "AUTORI"))))