// Title: Office Application Startup - Office Test
// Author: omkar72
// Date: 2020-10-25
// Level: medium
// Description: Detects the addition of office test registry that allows a user to specify an arbitrary DLL that will be executed every time an Office application is started
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1137.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_event/registry_event_office_test_regadd.yml
// False Positives:
//   - Unlikely

DeviceRegistryEvents
| where RegistryKey contains "\\Software\\Microsoft\\Office test\\Special\\Perf"