// Title: Registry Entries For Azorult Malware
// Author: Trent Liffick
// Date: 2020-05-08
// Level: critical
// Description: Detects the presence of a registry key created during Azorult execution
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.persistence, attack.execution, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_event/registry_event_mal_azorult.yml

DeviceRegistryEvents
| where RegistryKey endswith "SYSTEM*" and RegistryKey endswith "\\services\\localNETService"