// Title: Windows Registry Trust Record Modification
// Author: Antonlovesdnb, Trent Liffick (@tliffick)
// Date: 2020-02-19
// Level: medium
// Description: Alerts on trust record modification within the registry, indicating usage of macros
// MITRE Tactic: Initial Access
// Tags: attack.initial-access, attack.t1566.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_event/registry_event_office_trust_record_modification.yml
// False Positives:
//   - This will alert on legitimate macro usage as well, additional tuning is required

DeviceRegistryEvents
| where RegistryKey contains "\\Security\\Trusted Documents\\TrustRecords"