// Title: Wdigest CredGuard Registry Modification
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2019-08-25
// Level: high
// Description: Detects potential malicious modification of the property value of IsCredGuardEnabled from
// HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest to disable Cred Guard on a system.
// This is usually used with UseLogonCredential to manipulate the caching credentials.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_event/registry_event_disable_wdigest_credential_guard.yml

DeviceRegistryEvents
| where RegistryKey endswith "\\IsCredGuardEnabled"