// Title: Suspicious Camera and Microphone Access
// Author: Den Iuzvyk
// Date: 2020-06-07
// Level: high
// Description: Detects Processes accessing the camera and microphone from suspicious folder
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1125, attack.t1123
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_event/registry_event_susp_mic_cam_access.yml
// False Positives:
//   - Unlikely, there could be conferencing software running from a Temp folder accessing the devices

DeviceRegistryEvents
| where (RegistryKey endswith "\\Software\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore*" and RegistryKey contains "\\NonPackaged") and (RegistryKey contains "microphone" or RegistryKey contains "webcam") and (RegistryKey contains ":#Windows#Temp#" or RegistryKey contains ":#$Recycle.bin#" or RegistryKey contains ":#Temp#" or RegistryKey contains ":#Users#Public#" or RegistryKey contains ":#Users#Default#" or RegistryKey contains ":#Users#Desktop#")