// Title: Suspicious Run Key from Download
// Author: Florian Roth (Nextron Systems), Swachchhanda Shrawan Poude (Nextron Systems)
// Date: 2019-10-01
// Level: high
// Description: Detects the suspicious RUN keys created by software located in Download or temporary Outlook/Internet Explorer directories
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_event/registry_event_susp_download_run_key.yml
// False Positives:
//   - Software installers downloaded and used by users

DeviceRegistryEvents
| where (InitiatingProcessFolderPath contains "\\AppData\\Local\\Packages\\Microsoft.Outlook_" or InitiatingProcessFolderPath contains "\\AppData\\Local\\Microsoft\\Olk\\Attachments\\" or InitiatingProcessFolderPath contains "\\Downloads\\" or InitiatingProcessFolderPath contains "\\Temporary Internet Files\\Content.Outlook\\" or InitiatingProcessFolderPath contains "\\Local Settings\\Temporary Internet Files\\") and (RegistryKey contains "\\Software\\Microsoft\\Windows\\CurrentVersion\\Run" or RegistryKey contains "\\Software\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Run" or RegistryKey contains "\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\Run")