// Title: Potential Credential Dumping Via LSASS SilentProcessExit Technique
// Author: Florian Roth (Nextron Systems)
// Date: 2021-02-26
// Level: critical
// Description: Detects changes to the Registry in which a monitor program gets registered to dump the memory of the lsass.exe process
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_event/registry_event_silentprocessexit_lsass.yml
// False Positives:
//   - Unlikely

DeviceRegistryEvents
| where RegistryKey contains "Microsoft\\Windows NT\\CurrentVersion\\SilentProcessExit\\lsass.exe"