// Title: HybridConnectionManager Service Installation - Registry
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2021-04-12
// Level: high
// Description: Detects the installation of the Azure Hybrid Connection Manager service to allow remote code execution from Azure function.
// MITRE Tactic: Resource Development
// Tags: attack.resource-development, attack.t1608
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_event/registry_event_hybridconnectionmgr_svc_installation.yml

DeviceRegistryEvents
| where RegistryKey contains "\\Services\\HybridConnectionManager" or (RegistryValueData contains "Microsoft.HybridConnectionManager.Listener.exe" and ActionType =~ "RegistryValueSet")