// Title: Mint Sandstorm - Log4J Wstomcat Process Execution
// Author: Nasreddine Bencherchali (Nextron Systems), MSTIC (idea)
// Date: 2023-04-20
// Level: high
// Description: Detects Log4J Wstomcat process execution as seen in Mint Sandstorm activity
// MITRE Tactic: Execution
// Tags: attack.execution, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2023/TA/Mint-Sandstorm/proc_creation_win_apt_mint_sandstorm_log4j_wstomcat_execution.yml

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\ws_tomcatservice.exe" and (not(FolderPath endswith "\\repadmin.exe"))