// Title: Msiexec.EXE Initiated Network Connection Over HTTP
// Author: frack113
// Date: 2022-01-16
// Level: low
// Description: Detects a network connection initiated by an "Msiexec.exe" process over port 80 or 443.
// Adversaries might abuse "msiexec.exe" to install and execute remotely hosted packages.
// Use this rule to hunt for potentially anomalous or suspicious communications.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.007, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/network_connection/net_connection_win_msiexec_http.yml
// False Positives:
//   - Likely

DeviceNetworkEvents
| where (RemotePort in~ ("80", "443")) and InitiatingProcessFolderPath endswith "\\msiexec.exe"