// Title: Potentially Suspicious Azure Front Door Connection
// Author: Isaac Dunham
// Date: 2024-11-07
// Level: medium
// Description: Detects connections with Azure Front Door (known legitimate service that can be leveraged for C2)
// that fall outside of known benign behavioral baseline (not using common apps or common azurefd.net endpoints)
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1102.002, attack.t1090.004, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/network_connection/net_connection_win_susp_azurefd_connection.yml
// False Positives:
//   - Results are not inherently suspicious, but should be investigated during threat hunting for potential cloud C2.
//   - Organization-specific Azure Front Door endpoints

DeviceNetworkEvents
| where RemoteUrl contains "azurefd.net" and (not((InitiatingProcessFolderPath endswith "searchapp.exe" or (RemoteUrl contains "afdxtest.z01.azurefd.net" or RemoteUrl contains "fp-afd.azurefd.net" or RemoteUrl contains "fp-afdx-bpdee4gtg6frejfd.z01.azurefd.net" or RemoteUrl contains "roxy.azurefd.net" or RemoteUrl contains "powershellinfraartifacts-gkhedzdeaghdezhr.z01.azurefd.net" or RemoteUrl contains "storage-explorer-publishing-feapcgfgbzc2cjek.b01.azurefd.net" or RemoteUrl contains "graph.azurefd.net") or (InitiatingProcessFolderPath endswith "brave.exe" or InitiatingProcessFolderPath endswith "chrome.exe" or InitiatingProcessFolderPath endswith "chromium.exe" or InitiatingProcessFolderPath endswith "firefox.exe" or InitiatingProcessFolderPath endswith "msedge.exe" or InitiatingProcessFolderPath endswith "msedgewebview2.exe" or InitiatingProcessFolderPath endswith "opera.exe" or InitiatingProcessFolderPath endswith "vivaldi.exe"))))