// Title: HH.EXE Initiated HTTP Network Connection
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-05
// Level: medium
// Description: Detects a network connection initiated by the "hh.exe" process to HTTP destination ports, which could indicate the execution/download of remotely hosted .chm files.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.001, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/network_connection/net_connection_win_hh_http_connection.yml
// False Positives:
//   - False positive is expected from launching "hh.exe" for the first time on a machine in a while or simply from help files containing reference to external sources. Best correlate this with process creation and file events.

DeviceNetworkEvents
| where (RemotePort in~ ("80", "443")) and InitiatingProcessFolderPath endswith "\\hh.exe"