// Title: Network Connection Initiated From Users\Public Folder
// Author: Florian Roth (Nextron Systems)
// Date: 2024-05-31
// Level: medium
// Description: Detects a network connection initiated from a process located in the "C:\Users\Public" folder.
// Attacker are known to drop their malicious payloads and malware in this directory as its writable by everyone.
// Use this rule to hunt for potential suspicious or uncommon activity in your environement.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1105, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/network_connection/net_connection_win_susp_initaited_public_folder.yml
// False Positives:
//   - Likely from legitimate third party application that execute from the "Public" directory.

DeviceNetworkEvents
| where InitiatingProcessFolderPath contains ":\\Users\\Public\\" and (not(InitiatingProcessFolderPath contains ":\\Users\\Public\\IBM\\ClientSolutions\\Start_Programs\\"))