// Title: Mustang Panda Dropper
// Author: Florian Roth (Nextron Systems), oscd.community
// Date: 2019-10-30
// Level: high
// Description: Detects specific process parameters as used by Mustang Panda droppers
// MITRE Tactic: Resource Development
// Tags: attack.t1587.001, attack.resource-development, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2019/TA/MustangPanda/proc_creation_win_apt_mustangpanda.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ((ProcessCommandLine contains "Temp\\wtask.exe /create" or ProcessCommandLine contains "%windir:~-3,1%%PUBLIC:~-9,1%" or ProcessCommandLine contains "/tn \"Security Script " or ProcessCommandLine contains "%windir:~-1,1%") or (ProcessCommandLine contains "/E:vbscript" and ProcessCommandLine contains "C:\\Users\\" and ProcessCommandLine contains ".txt" and ProcessCommandLine contains "/F")) or FolderPath endswith "Temp\\winwsh.exe"