// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/03/14
// Level: medium
// Description: Detects the execution of "ldifde.exe" in order to export organizational Active Directory structure.
// Tags: attack.exfiltration
DeviceProcessEvents
| where (ProcessCommandLine contains "-f" and (FolderPath endswith "\\ldifde.exe" or ProcessVersionInfoOriginalFileName =~ "ldifde.exe")) and (not(ProcessCommandLine contains " -i"))