// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/12
// Level: medium
// Description: Detects suspicious command line that adds an account to the local administrators/administrateurs group
// Tags: attack.persistence, attack.t1098
DeviceProcessEvents
| where (ProcessCommandLine contains " administrators " or ProcessCommandLine contains " administrateur") and ((ProcessCommandLine contains "localgroup " and ProcessCommandLine contains " /add") or (ProcessCommandLine contains "Add-LocalGroupMember " and ProcessCommandLine contains " -Group "))