// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/07/21
// Level: medium
// Description: Detects when an attacker adds a new "Debugger" value to the "AeDebug" key in order to achieve persistence which will get invoked when an application crashes
// Tags: attack.persistence
DeviceRegistryEvents
| where (RegistryValueData endswith ".dll" and ActionType =~ "RegistryValueSet" and RegistryKey contains "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\AeDebug\\Debugger") and (not(RegistryValueData =~ "\"C:\\WINDOWS\\system32\\vsjitdebugger.exe\" -p %ld -e %ld -j 0x%p"))