// Author: Florian Roth (Nextron Systems)
// Date: 2022/01/11
// Level: medium
// Description: Detects a certain command line flag combination used by "devinit.exe", which can be abused as a LOLBIN to download arbitrary MSI packages on a Windows system
// Tags: attack.execution, attack.defense_evasion, attack.t1218
DeviceProcessEvents
| where ProcessCommandLine contains " -t msi-install " and ProcessCommandLine contains " -i http"