// Author: Oleg Kolesnikov @securonix invrep_de, oscd.community, Florian Roth (Nextron Systems), Christian Burkard (Nextron Systems)
// Date: 2020/10/23
// Level: high
// Description: Detects attackers using tooling with bad opsec defaults.
E.g. spawning a sacrificial process to inject a capability into the process without taking into account how the process is normally run.
One trivial example of this is using rundll32.exe without arguments as a sacrificial process (default in CS, now highlighted by c2lint), running WerFault without arguments (Kraken - credit am0nsec), and other examples.

// Tags: attack.defense_evasion, attack.t1218.011
DeviceProcessEvents
| where ((ProcessCommandLine endswith "WerFault.exe" and FolderPath endswith "\\WerFault.exe") or (ProcessCommandLine endswith "rundll32.exe" and FolderPath endswith "\\rundll32.exe") or (ProcessCommandLine endswith "regsvcs.exe" and FolderPath endswith "\\regsvcs.exe") or (ProcessCommandLine endswith "regasm.exe" and FolderPath endswith "\\regasm.exe") or (ProcessCommandLine endswith "regsvr32.exe" and FolderPath endswith "\\regsvr32.exe")) and (not((InitiatingProcessCommandLine contains "\\setup.exe\" --install-archive=\"C:\\Users\\" and InitiatingProcessFolderPath contains "\\AppData\\Local\\Microsoft\\EdgeUpdate\\Install\\{" and InitiatingProcessFolderPath endswith "\\setup.exe" and InitiatingProcessFolderPath startswith "C:\\Users\\")))