// Author: E.M. Anhaus (originally from Atomic Blue Detections, Tony Lambert), oscd.community
// Date: 2019/10/24
// Level: high
// Description: Identifies use of Fodhelper.exe to bypass User Account Control. Adversaries use this technique to execute privileged processes.
// Tags: attack.privilege_escalation, attack.t1548.002
DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\fodhelper.exe"