// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/05/18
// Level: medium
// Description: Detects calls to cmdlets that are used to export certificates from the local certificate store. Threat actors were seen abusing this to steal private keys from compromised machines.
// Tags: 
DeviceProcessEvents
| where ProcessCommandLine contains "Export-PfxCertificate " or ProcessCommandLine contains "Export-Certificate "