// Author: frack113
// Date: 2022/01/01
// Level: high
// Description: Remote desktop is a common feature in operating systems.
It allows a user to log into an interactive session with a system desktop graphical user interface on a remote system.
Microsoft refers to its implementation of the Remote Desktop Protocol (RDP) as Remote Desktop Services (RDS).

// Tags: attack.persistence, attack.t1547.010
DeviceRegistryEvents
| where (ActionType =~ "RegistryValueSet" and RegistryKey =~ "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet001\\Control\\Terminal Server\\WinStations\\RDP-Tcp\\PortNumber") and (not(RegistryValueData =~ "DWORD (0x00000d3d)"))