// Author: Julia Fomina, oscd.community
// Date: 2020/10/05
// Level: medium
// Description: Detects launch of executable by calling the LaunchApplication function from pcwutl.dll library.
// Tags: attack.defense_evasion, attack.t1218.011
DeviceProcessEvents
| where (ProcessCommandLine contains "pcwutl" and ProcessCommandLine contains "LaunchApplication") and (FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE")