// Author: frack113
// Date: 2021/07/27
// Level: medium
// Description: An adversary may compress or encrypt data that is collected prior to exfiltration using 3rd party utilities
// Tags: attack.collection, attack.t1560.001
DeviceProcessEvents
| where (ProcessCommandLine contains " a " or ProcessCommandLine contains " u ") and (ProcessVersionInfoFileDescription contains "7-Zip" or (FolderPath endswith "\\7z.exe" or FolderPath endswith "\\7zr.exe" or FolderPath endswith "\\7za.exe") or (ProcessVersionInfoOriginalFileName in~ ("7z.exe", "7za.exe"))) and ProcessCommandLine contains " -p"