// Author: frack113
// Date: 2021/07/27
// Level: medium
// Description: An adversary may compress or encrypt data that is collected prior to exfiltration using 3rd party utilities
// Tags: attack.collection, attack.t1560.001
DeviceProcessEvents
| where (ProcessCommandLine contains " -min " or ProcessCommandLine contains " -a ") and ProcessCommandLine contains "-s\"" and (ProcessCommandLine contains "winzip.exe" or ProcessCommandLine contains "winzip64.exe")