// Author: Max Altgelt (Nextron Systems), Tobias Michalski (Nextron Systems)
// Date: 2021/08/09
// Level: high
// Description: Detects the execution of the builtin "copy" command that targets a shadow copy (sometimes used to copy registry hives that are in use)
// Tags: attack.impact, attack.t1490
DeviceProcessEvents
| where ProcessCommandLine contains "copy " and ProcessCommandLine contains "\\\\?\\GLOBALROOT\\Device\\HarddiskVolumeShadowCopy"