// Author: Nasreddine Bencherchali (Nextron Systems), fornotes
// Date: 2022/12/01
// Level: medium
// Description: Detects the creation of system dlls that are not present on the system. Usually to achieve dll hijacking
// Tags: attack.defense_evasion, attack.persistence, attack.privilege_escalation, attack.t1574.001, attack.t1574.002
DeviceFileEvents
| where ((FolderPath in~ ("C:\\Windows\\System32\\WLBSCTRL.dll", "C:\\Windows\\System32\\TSMSISrv.dll", "C:\\Windows\\System32\\TSVIPSrv.dll", "C:\\Windows\\System32\\wow64log.dll", "C:\\Windows\\System32\\WptsExtensions.dll", "C:\\Windows\\System32\\wbem\\wbemcomn.dll")) or FolderPath endswith "\\SprintCSP.dll") and (not(InitiatingProcessFolderPath startswith "C:\\Windows\\System32\\"))