// Author: frack113
// Date: 2021/12/30
// Level: high
// Description: Adversaries may execute their own malicious payloads by hijacking vulnerable file path references.
Adversaries can take advantage of paths that lack surrounding quotations by placing an executable in a higher level directory within the path, so that Windows will choose the adversary's executable to launch.

// Tags: attack.persistence, attack.t1547.009
DeviceFileEvents
| where FolderPath =~ "C:\\program.exe"