// Author: frack113
// Date: 2021/06/08
// Level: high
// Description: Disable Microsoft Office Security Features by registry
// Tags: attack.defense_evasion, attack.t1562.001
DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000001)" and ActionType =~ "RegistryValueSet" and RegistryKey contains "\\SOFTWARE\\Microsoft\\Office" and (RegistryKey endswith "VBAWarnings" or RegistryKey endswith "DisableInternetFilesInPV" or RegistryKey endswith "DisableUnsafeLocationsInPV" or RegistryKey endswith "DisableAttachementsInPV")