// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/10/25
// Level: high
// Description: Detects tampering with the MacroRuntimeScanScope registry key to disable runtime scanning of enabled macros
// Tags: attack.defense_evasion
DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and ActionType =~ "RegistryValueSet" and (RegistryKey contains "\\SOFTWARE" and RegistryKey contains "\\Microsoft\\Office" and RegistryKey contains "\\Common\\Security") and RegistryKey endswith "\\MacroRuntimeScanScope"