// Author: frack113, Nasreddine Bencherchali
// Date: 2022/07/30
// Level: high
// Description: Detects when an attacker create a similar folder structure to windows system folders such as (Windows, Program Files...)
but with a space in order to trick DLL load search order and perform a "DLL Search Order Hijacking" attack

// Tags: attack.persistence, attack.privilege_escalation, attack.defense_evasion, attack.t1574.002
DeviceFileEvents
| where FolderPath endswith ".dll" and (FolderPath startswith "C:\\Windows \\" or FolderPath startswith "C:\\Program Files \\" or FolderPath startswith "C:\\Program Files (x86) \\")