// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/19
// Level: medium
// Description: Detects usage of "MSOHTMED" to download arbitrary files
// Tags: attack.defense_evasion, attack.execution, attack.t1218
DeviceProcessEvents
| where (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://" or ProcessCommandLine contains "ftp://") and (FolderPath endswith "\\MSOHTMED.exe" or ProcessVersionInfoOriginalFileName =~ "MsoHtmEd.exe")