// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/07/28
// Level: medium
// Description: Detects the creation of suspcious binary files inside the "\windows\system32\spool\drivers\color\" as seen in the blog referenced below
// Tags: attack.defense_evasion
DeviceFileEvents
| where (FolderPath endswith ".dll" or FolderPath endswith ".exe" or FolderPath endswith ".sys") and FolderPath startswith "C:\\Windows\\System32\\spool\\drivers\\color\\"