// Author: frack113
// Date: 2022/01/09
// Level: low
// Description: When C# is compiled dynamically, a .cmdline file will be created as a part of the process.
Certain processes are not typically observed compiling C# code, but can do so without touching disk.
This can be used to unpack a payload for execution

// Tags: attack.defense_evasion, attack.t1027.004
DeviceFileEvents
| where FolderPath endswith ".cmdline"