// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/12/09
// Level: low
// Description: Detects changes to the "ExtErrorInformation" key in order to disable ETW logging for rpcrt4.dll
// Tags: attack.defense_evasion, attack.t1112, attack.t1562
DeviceRegistryEvents
| where (RegistryValueData in~ ("DWORD (0x00000000)", "DWORD (0x00000002)")) and ActionType =~ "RegistryValueSet" and RegistryKey endswith "\\Microsoft\\Windows NT\\Rpc\\ExtErrorInformation"