// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/10/26
// Level: high
// Description: Detects the deletion of the Exchange PowerShell cmdlet History logs which may indicate an attempt to destroy forensic evidence
// Tags: attack.defense_evasion, attack.t1070
DeviceFileEvents
| where FolderPath contains "_Cmdlet_" and FolderPath startswith "\\Logging\\CmdletInfra\\LocalPowerShell\\Cmdlet\\"