// Author: frack113, Nasreddine Bencherchali
// Date: 2022/08/20
// Level: medium
// Description: Detects code execution via Pester.bat (Pester - Powershell Modulte for testing)
// Tags: attack.execution, attack.t1059.001, attack.defense_evasion, attack.t1216
DeviceProcessEvents
| where (InitiatingProcessCommandLine contains "{ Invoke-Pester -EnableExit ;" or InitiatingProcessCommandLine contains "{ Get-Help \"") and (InitiatingProcessCommandLine contains "\\WindowsPowerShell\\Modules\\Pester\\" and (InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe"))