// Author: Fatih Sirin
// Date: 2019/11/01
// Level: medium
// Description: Detects netsh commands that turns off the Windows firewall
// Tags: attack.defense_evasion, attack.t1562.004, attack.s0108
DeviceProcessEvents
| where (FolderPath endswith "\\netsh.exe" or ProcessVersionInfoOriginalFileName =~ "netsh.exe") and ((ProcessCommandLine contains "firewall" and ProcessCommandLine contains "set" and ProcessCommandLine contains "opmode" and ProcessCommandLine contains "disable") or (ProcessCommandLine contains "advfirewall" and ProcessCommandLine contains "set" and ProcessCommandLine contains "state" and ProcessCommandLine contains "off"))