// Author: Victor Sergeev, oscd.community
// Date: 2020/10/09
// Level: medium
// Description: Detects when GfxDownloadWrapper.exe downloads file from non standard URL
// Tags: attack.command_and_control, attack.t1105
DeviceProcessEvents
| where FolderPath endswith "\\GfxDownloadWrapper.exe" and (not((ProcessCommandLine contains "gameplayapi.intel.com" and (InitiatingProcessFolderPath endswith "\\GfxDownloadWrapper.exe" or InitiatingProcessFolderPath endswith "\\igfxEM.exe"))))