// Author: frack113
// Date: 2021/12/02
// Level: medium
// Description: Detects execution of the "del" builtin command to remove files using greedy/wildcard expression. This is often used by malware to delete content of folders that perhaps contains the initial malware infection or to delete evidence.
// Tags: attack.defense_evasion, attack.t1070.004
DeviceProcessEvents
| where (ProcessCommandLine contains "del " or ProcessCommandLine contains "erase ") and (ProcessCommandLine contains "\\\*.dll" or ProcessCommandLine contains "\\\*.exe") and (FolderPath endswith "\\cmd.exe" or ProcessVersionInfoOriginalFileName =~ "Cmd.Exe")