// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/09/05
// Level: high
// Description: Detects usage of the Quarks PwDump tool via commandline arguments
// Tags: attack.credential_access, attack.t1003.002
DeviceProcessEvents
| where (ProcessCommandLine in~ (" -dhl", " --dump-hash-local", " -dhdc", " --dump-hash-domain-cached", " --dump-bitlocker", " -dhd ", " --dump-hash-domain ", "--ntds-file")) or FolderPath endswith "\\QuarksPwDump.exe"