// Author: Florian Roth (Nextron Systems)
// Date: 2019/04/20
// Level: high
// Description: Detects suspicious powershell command line parameters used in Empire
// Tags: attack.execution, attack.t1059.001
DeviceProcessEvents
| where ProcessCommandLine contains " -NoP -sta -NonI -W Hidden -Enc " or ProcessCommandLine contains " -noP -sta -w 1 -enc " or ProcessCommandLine contains " -NoP -NonI -W Hidden -enc " or ProcessCommandLine contains " -noP -sta -w 1 -enc" or ProcessCommandLine contains " -enc  SQB" or ProcessCommandLine contains " -nop -exec bypass -EncodedCommand "