// Author: frack113
// Date: 2021/12/27
// Level: high
// Description: Execute Hashcat.exe with provided SAM file from registry of Windows and Password list to crack against
// Tags: attack.credential_access, attack.t1110.002
DeviceProcessEvents
| where (ProcessCommandLine contains "-a " and ProcessCommandLine contains "-m 1000 " and ProcessCommandLine contains "-r ") or FolderPath endswith "\\hashcat.exe"