// Author: Alexander Rausch
// Date: 2020/06/24
// Level: high
// Description: Detects actions caused by the RedMimicry Winnti playbook a automated breach emulations utility
// Tags: attack.execution, attack.defense_evasion, attack.t1106, attack.t1059.003, attack.t1218.011
DeviceProcessEvents
| where (ProcessCommandLine contains "gthread-3.6.dll" or ProcessCommandLine contains "\\Windows\\Temp\\tmp.bat" or ProcessCommandLine contains "sigcmm-2.4.dll") and (FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\cmd.exe")