// Author: Thomas Patzke
// Date: 2020/05/22
// Level: high
// Description: Detects various execution patterns of the CrackMapExec pentesting framework
// Tags: attack.execution, attack.t1047, attack.t1053, attack.t1059.003, attack.t1059.001, attack.s0106
DeviceProcessEvents
| where (ProcessCommandLine contains "powershell.exe -exec bypass -noni -nop -w 1 -C \"" or ProcessCommandLine contains "powershell.exe -noni -nop -w 1 -enc ") and (match or match or match)