// Author: Florian Roth (Nextron Systems)
// Date: 2021/06/18
// Level: critical
// Description: Detects the execution of the PurpleSharp adversary simulation tool
// Tags: attack.t1587, attack.resource_development
DeviceProcessEvents
| where (ProcessCommandLine contains "xyz123456.exe" or ProcessCommandLine contains "PurpleSharp") or (FolderPath contains "\\purplesharp" or ProcessVersionInfoOriginalFileName =~ "PurpleSharp.exe")