// Author: Florian Roth (Nextron Systems)
// Date: 2022/09/07
// Level: high
// Description: Detects the use of SharpEvtHook, a tool that tampers with the Windows event logs
// Tags: attack.defense_evasion, attack.t1562.002
DeviceProcessEvents
| where FolderPath endswith "\\SharpEvtMute.exe" or ProcessVersionInfoFileDescription =~ "SharpEvtMute" or (ProcessCommandLine contains "--Filter \"rule " or ProcessCommandLine contains "--Encoded --Filter \\\"")