// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/11/29
// Level: high
// Description: Detects the execution of the tool PowerTool which has the ability to kill a process, delete its process file, unload drivers, and delete the driver files
// Tags: attack.defense_evasion, attack.t1562.001
DeviceProcessEvents
| where (FolderPath endswith "\\PowerTool.exe" or FolderPath endswith "\\PowerTool64.exe") or ProcessVersionInfoOriginalFileName =~ "PowerTool.exe"