// Author: Oddvar Moe, Sander Wiebing, oscd.community
// Date: 2020/10/07
// Level: medium
// Description: Detects the import of the specified file to the registry with regedit.exe.
// Tags: attack.t1112, attack.defense_evasion
DeviceProcessEvents
| where ((ProcessCommandLine contains " /i " or ProcessCommandLine contains " /s " or ProcessCommandLine contains ".reg") and (FolderPath endswith "\\regedit.exe" or ProcessVersionInfoOriginalFileName =~ "REGEDIT.EXE")) and (not(((ProcessCommandLine contains " /e " or ProcessCommandLine contains " /a " or ProcessCommandLine contains " /c " or ProcessCommandLine contains " -e " or ProcessCommandLine contains " -a " or ProcessCommandLine contains " -c ") and ProcessCommandLine matches regex ":[^ \\\\]")))