// Author: Nikita Nazarov, oscd.community
// Date: 2020/10/08
// Level: high
// Description: Detects Obfuscated Powershell via use MSHTA in Scripts
// Tags: attack.defense_evasion, attack.t1027, attack.execution, attack.t1059.001
DeviceProcessEvents
| where ProcessCommandLine contains "set" and ProcessCommandLine contains "&&" and ProcessCommandLine contains "mshta" and ProcessCommandLine contains "vbscript:createobject" and ProcessCommandLine contains ".run" and ProcessCommandLine contains "(window.close)"