// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/05/16
// Level: high
// Description: Detects execution of LiveKD with the "-m" flag to potentially dump the kernel memory
// Tags: attack.defense_evasion
DeviceProcessEvents
| where (ProcessCommandLine contains " /m" and ProcessCommandLine contains " -m") and ((FolderPath endswith "\\livekd.exe" or FolderPath endswith "\\livekd64.exe") or ProcessVersionInfoOriginalFileName =~ "livekd.exe")