// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/19
// Level: medium
// Description: Detects the use of the 'Launch-VsDevShell.ps1' Microsoft signed script to execute commands.
// Tags: attack.defense_evasion, attack.t1216.001
DeviceProcessEvents
| where (ProcessCommandLine contains "VsWherePath " or ProcessCommandLine contains "VsInstallationPath ") and ProcessCommandLine contains "Launch-VsDevShell.ps1"