// Author: Florian Roth (Nextron Systems)
// Date: 2022/03/22
// Level: high
// Description: Detects the usage of the "reg.exe" utility to disable PPL protection on the LSA process
// Tags: attack.defense_evasion, attack.t1562.010
DeviceProcessEvents
| where (ProcessCommandLine contains "SYSTEM\\CurrentControlSet\\Control\\Lsa" and (ProcessCommandLine contains " add " and ProcessCommandLine contains " /d 0" and ProcessCommandLine contains " /v RunAsPPL ")) and (FolderPath endswith "\\reg.exe" or ProcessVersionInfoOriginalFileName =~ "reg.exe")