// Author: Agro (@agro_sev), Ensar Şamil (@sblmsrsn), oscd.community
// Date: 2020/10/14
// Level: medium
// Description: There is an option for a MS VS Just-In-Time Debugger "vsjitdebugger.exe" to launch specified executable and attach a debugger.
This option may be used adversaries to execute malicious code by signed verified binary.
The debugger is installed alongside with Microsoft Visual Studio package.

// Tags: attack.t1218, attack.defense_evasion
DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\vsjitdebugger.exe" and (not((match or FolderPath endswith "\\devenv.exe")))