// Author: Tim Rauch, Janantha Marasinghe
// Date: 2022/11/08
// Level: high
// Description: Detects the Internet Information Services (IIS) command-line tool, AppCmd, being used to list passwords
// Tags: attack.credential_access, attack.t1003
DeviceProcessEvents
| where (ProcessCommandLine contains "list " and (FolderPath endswith "\\appcmd.exe" or ProcessVersionInfoOriginalFileName =~ "appcmd.exe")) and ((ProcessCommandLine contains " /config" or ProcessCommandLine contains " /xml" or ProcessCommandLine contains " -config" or ProcessCommandLine contains " -xml") or ((ProcessCommandLine contains " /@t" or ProcessCommandLine contains " /text" or ProcessCommandLine contains " /show" or ProcessCommandLine contains " -@t" or ProcessCommandLine contains " -text" or ProcessCommandLine contains " -show") and (ProcessCommandLine contains ":\*" or ProcessCommandLine contains "password")))