// Author: frack113
// Date: 2022/11/18
// Level: high
// Description: Detects changes to the NGenAssemblyUsageLog registry key.
.NET Usage Log output location can be controlled by setting the NGenAssemblyUsageLog CLR configuration knob in the Registry or by configuring an environment variable (as described in the next section).
By simplify specifying an arbitrary value (e.g. fake output location or junk data) for the expected value, a Usage Log file for the .NET execution context will not be created.

// Tags: attack.defense_evasion, attack.t1112
DeviceRegistryEvents
| where ActionType =~ "RegistryValueSet" and RegistryKey endswith "SOFTWARE\\Microsoft\\.NETFramework\\NGenAssemblyUsageLog"