// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/02/03
// Level: medium
// Description: Detects usage of cmdkey to add generic credentials. As an example, this has to be used before connecting to an RDP session via command line interface.
// Tags: attack.credential_access, attack.t1003.005
DeviceProcessEvents
| where (ProcessCommandLine contains " /g" and ProcessCommandLine contains " /u" and ProcessCommandLine contains " /p") and (FolderPath endswith "\\cmdkey.exe" or ProcessVersionInfoOriginalFileName =~ "cmdkey.exe")