// Author: Timur Zinniatullin, Daniil Yugoslavskiy, oscd.community
// Date: 2023/02/20
// Level: low
// Description: Detects the creation of a new service using the "sc.exe" utility.
// Tags: attack.persistence, attack.privilege_escalation, attack.t1543.003
DeviceProcessEvents
| where (ProcessCommandLine contains "create" and ProcessCommandLine contains "binPath") and FolderPath endswith "\\sc.exe"