// Author: Florian Roth (Nextron Systems), Markus Neis, Sander Wiebing
// Date: 2018/08/25
// Level: high
// Description: Detects suspicious new RUN key element pointing to an executable in a suspicious folder
// Tags: attack.persistence, attack.t1547.001
DeviceRegistryEvents
| where ((RegistryValueData contains "C:\\Windows\\Temp\\" or RegistryValueData contains "C:\\$Recycle.bin\\" or RegistryValueData contains "C:\\Temp\\" or RegistryValueData contains "C:\\Users\\Public\\" or RegistryValueData contains "C:\\Users\\Default\\" or RegistryValueData contains "C:\\Users\\Desktop\\" or RegistryValueData contains "\\AppData\\Local\\Temp\\" or RegistryValueData contains "%temp%\\" or RegistryValueData contains "%tmp%\\") or (RegistryValueData startswith "%Public%\\" or RegistryValueData startswith "wscript" or RegistryValueData startswith "cscript")) and (ActionType =~ "RegistryValueSet" and (RegistryKey contains "\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run" or RegistryKey contains "\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnce"))