// Author: megan201296, Jonhnathan Ribeiro
// Date: 2019/04/14
// Level: critical
// Description: Detects registry keys created in OceanLotus (also known as APT32) attacks
// Tags: attack.defense_evasion, attack.t1112
DeviceRegistryEvents
| where ((RegistryKey contains "Classes\\AppXc52346ec40fb4061ad96be0e6cb7d16a" or RegistryKey contains "Classes\\AppX3bbba44c6cae4d9695755183472171e2" or RegistryKey contains "Classes\\CLSID\\{E3517E26-8E93-458D-A6DF-8030BC80528B}" or RegistryKey contains "Classes\\CLSID\\{E08A0F4B-1F65-4D4D-9A09-BD4625B9C5A1}\\Model") and RegistryKey startswith "HKCU") or RegistryKey =~ "HKCU\\SOFTWARE\\Classes\\CLSID\\{E08A0F4B-1F65-4D4D-9A09-BD4625B9C5A1}\\Model" or ((RegistryKey contains "AppXbf13d4ea2945444d8b13e2121cb6b663" or RegistryKey contains "AppX70162486c7554f7f80f481985d67586d" or RegistryKey contains "AppX37cc7fdccd644b4f85f4b22d5a3f105a") and (RegistryKey endswith "Application" or RegistryKey endswith "DefaultIcon") and (RegistryKey startswith "HKCU\\SOFTWARE\\App" or RegistryKey startswith "HKEY_LOCAL_MACHINE\\SOFTWARE\\App"))