// Author: _pete_0, TheDFIRReport
// Date: 2022/05/06
// Level: high
// Description: Detects Cobalt Strike module/commands accidentally entered in CMD shell
// Tags: attack.execution, attack.t1059.003
DeviceProcessEvents
| where (ProcessCommandLine contains "Invoke-UserHunter" or ProcessCommandLine contains "Invoke-ShareFinder" or ProcessCommandLine contains "Invoke-Kerberoast" or ProcessCommandLine contains "Invoke-SMBAutoBrute" or ProcessCommandLine contains "Invoke-Nightmare" or ProcessCommandLine contains "zerologon" or ProcessCommandLine contains "av_query") and (ProcessVersionInfoOriginalFileName =~ "Cmd.Exe" or FolderPath endswith "\\cmd.exe")