// Author: Markus Neis, Nasreddine Bencherchali (Nextron Systems)
// Date: 2018/12/27
// Level: high
// Description: Detects an attacker trying to enable the outlook security setting "EnableUnsafeClientMailRules" which allows outlook to run applications or execute macros
// Tags: attack.execution, attack.t1059, attack.t1202
DeviceProcessEvents
| where ProcessCommandLine contains "\\Outlook\\Security\\EnableUnsafeClientMailRules"