// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/02/08
// Level: high
// Description: Detects an attacker trying to enable the outlook security setting "EnableUnsafeClientMailRules" which allows outlook to run applications or execute macros
// Tags: attack.defense_evasion, attack.t1112
DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000001)" and ActionType =~ "RegistryValueSet" and RegistryKey endswith "\\Outlook\\Security\\EnableUnsafeClientMailRules"