// Author: Tim Shelton (HAWK.IO)
// Date: 2021/12/09
// Level: medium
// Description: Detects a when net.exe is called with a password in the command line
// Tags: 
DeviceProcessEvents
| where ((ProcessCommandLine contains " use " and match and match) and ((FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe") or (ProcessVersionInfoOriginalFileName in~ ("net.exe", "net1.exe")))) and (not(ProcessCommandLine endswith " "))