// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/01/02
// Level: medium
// Description: Detects execution of perl using the "-e"/"-E" flags. This is could be used as a way to launch a reverse shell or execute live perl code.
// Tags: attack.execution, attack.t1059
DeviceProcessEvents
| where ProcessCommandLine contains " -e" and (FolderPath endswith "\\perl.exe" or ProcessVersionInfoOriginalFileName =~ "perl.exe")