// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/22
// Level: medium
// Description: Detects modification addition to the 'TypedPaths' key in the user or admin registry via the commandline. Which might indicate persistence attempt
// Tags: attack.persistence
DeviceProcessEvents
| where ProcessCommandLine contains "\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\TypedPaths"