// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/01/02
// Level: medium
// Description: Detects execution of php using the "-r" flag. This is could be used as a way to launch a reverse shell or execute live php code.
// Tags: attack.execution, attack.t1059
DeviceProcessEvents
| where ProcessCommandLine contains " -r" and (FolderPath endswith "\\php.exe" or ProcessVersionInfoOriginalFileName =~ "php.exe")