// Author: Andreas Hunkeler (@Karneades)
// Date: 2021/06/22
// Level: medium
// Description: Detects the modification of PortProxy registry key which is used for port forwarding. For command execution see rule win_netsh_port_fwd.yml.
// Tags: attack.lateral_movement, attack.defense_evasion, attack.command_and_control, attack.t1090
DeviceRegistryEvents
| where RegistryKey =~ "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet001\\Services\\PortProxy\\v4tov4\\tcp"