// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/23
// Level: medium
// Description: Detects when an attacker tries to add a new network provider in order to dump clear text credentials, similar to how the NPPSpy tool does it
// Tags: attack.credential_access, attack.t1003
DeviceRegistryEvents
| where (ActionType =~ "RegistryValueSet" and (RegistryKey contains "\\System\\CurrentControlSet\\Services" and RegistryKey contains "\\NetworkProvider")) and (not(((RegistryKey contains "\\System\\CurrentControlSet\\Services\\WebClient\\NetworkProvider" or RegistryKey contains "\\System\\CurrentControlSet\\Services\\LanmanWorkstation\\NetworkProvider" or RegistryKey contains "\\System\\CurrentControlSet\\Services\\RDPNP\\NetworkProvider") or InitiatingProcessFolderPath =~ "C:\\Windows\\System32\\poqexec.exe")))