// Author: @gott_cyber
// Date: 2022/07/31
// Level: medium
// Description: Detects an attempt to leverage dnscmd.exe to enumerate the DNS zones of a domain. DNS zones used to host the DNS records for a particular domain.
// Tags: attack.discovery, attack.execution, attack.t1543.003
DeviceProcessEvents
| where (ProcessCommandLine contains "/enumrecords" or ProcessCommandLine contains "/enumzones" or ProcessCommandLine contains "/ZonePrint" or ProcessCommandLine contains "/info") and FolderPath endswith "\\dnscmd.exe"