// Author: Roberto Rodriguez @Cyb3rWard0g, Open Threat Research (OTR), wagga
// Date: 2020/10/12
// Level: critical
// Description: Detects potential DLL hijack of "iertutil.dll" found in the DCOM InternetExplorer.Application Class
// Tags: attack.lateral_movement, attack.t1021.002, attack.t1021.003
DeviceImageLoadEvents
| where FolderPath endswith "\\Internet Explorer\\iertutil.dll" and InitiatingProcessFolderPath endswith "\\Internet Explorer\\iexplore.exe"