// Author: Florian Roth (Nextron Systems), Samir Bousseaden
// Date: 2021/11/27
// Level: critical
// Description: Detects a suspicious LSASS process process clone that could be a sign of credential dumping activity
// Tags: attack.credential_access, attack.t1003, attack.t1003.001
DeviceProcessEvents
| where FolderPath endswith "\\Windows\\System32\\lsass.exe" and InitiatingProcessFolderPath endswith "\\Windows\\System32\\lsass.exe"