// Author: X__Junior (Nextron Systems)
// Date: 2023/06/09
// Level: medium
// Description: Detects loading of "RjvPlatform.dll" by the "SystemResetPlatform.exe" binary which can be abused as a method of DLL side loading since the "$SysReset" directory isn't created by default.
// Tags: attack.defense_evasion, attack.privilege_escalation, attack.t1574.001, attack.t1574.002
DeviceImageLoadEvents
| where InitiatingProcessFolderPath =~ "C:\\Windows\\System32\\SystemResetPlatform\\SystemResetPlatform.exe" and FolderPath =~ "C:\\$SysReset\\Framework\\Stack\\RjvPlatform.dll"