// Author: BlackBerry Threat Research and Intelligence Team - @Joseliyo_Jstnk
// Date: 2023/06/07
// Level: high
// Description: Detects changes to the PSFactory COM InProcServer32 registry. This technique was used by RomCom to create persistence storing a malicious DLL.
// Tags: attack.persistence, attack.t1546.015
DeviceRegistryEvents
| where (ActionType =~ "RegistryValueSet" and RegistryKey endswith "\\CLSID\\{c90250f3-4d7d-4991-9b69-a5c5bc1c2ae6}\\InProcServer32\\(Default)") and (not((RegistryValueData in~ ("%windir%\\System32\\ActXPrxy.dll", "C:\\Windows\\System32\\ActXPrxy.dll"))))