// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/05/22
// Level: high
// Description: Detects execution of "odbcconf" with the "REGSVR" action where the DLL in question doesn't contain a ".dll" extension. Which is often used as a method to evade defenses.
// Tags: attack.defense_evasion, attack.t1218.008
DeviceProcessEvents
| where (ProcessCommandLine contains "REGSVR " and (FolderPath endswith "\\odbcconf.exe" or ProcessVersionInfoOriginalFileName =~ "odbcconf.exe")) and (not(ProcessCommandLine contains ".dll"))