// Author: Harish Segar (rule)
// Date: 2020/03/20
// Level: medium
// Description: Detects PowerShell downgrade attack by comparing the host versions with the actually used engine version 2.0
// Tags: attack.defense_evasion, attack.execution, attack.t1059.001
DeviceProcessEvents
| where (ProcessCommandLine contains " -version 2 " or ProcessCommandLine contains " -versio 2 " or ProcessCommandLine contains " -versi 2 " or ProcessCommandLine contains " -vers 2 " or ProcessCommandLine contains " -ver 2 " or ProcessCommandLine contains " -ve 2 " or ProcessCommandLine contains " -v 2 ") and FolderPath endswith "\\powershell.exe"