// Author: Lednyov Alexey, oscd.community, Sreeman
// Date: 2020/10/16
// Level: high
// Description: Detects potential persistence behaviour using the windows telemetry registry key.
Windows telemetry makes use of the binary CompatTelRunner.exe to run a variety of commands and perform the actual telemetry collections.
This binary was created to be easily extensible, and to that end, it relies on the registry to instruct on which commands to run.
The problem is, it will run any arbitrary command without restriction of location or type.

// Tags: attack.persistence, attack.t1053.005
DeviceRegistryEvents
| where ((RegistryValueData contains ".sh" or RegistryValueData contains ".exe" or RegistryValueData contains ".dll" or RegistryValueData contains ".bin" or RegistryValueData contains ".bat" or RegistryValueData contains ".cmd" or RegistryValueData contains ".js" or RegistryValueData contains ".ps" or RegistryValueData contains ".vb" or RegistryValueData contains ".jar" or RegistryValueData contains ".hta" or RegistryValueData contains ".msi" or RegistryValueData contains ".vbs") and ActionType =~ "RegistryValueSet" and RegistryKey contains "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\AppCompatFlags\\TelemetryController" and RegistryKey endswith "\\Command") and (not((RegistryValueData contains "\\system32\\CompatTelRunner.exe" or RegistryValueData contains "\\system32\\DeviceCensus.exe")))