// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/05/17
// Level: medium
// Description: Detects execution of "rundll32" with potential obfuscated ordinal calls
// Tags: attack.defense_evasion
DeviceProcessEvents
| where (ProcessCommandLine contains "#+" or ProcessCommandLine contains "#-") and (FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE" or ProcessCommandLine contains "rundll32")