// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/02
// Level: high
// Description: Detects loading of a DLL by the VMware Xfer utility from the non-default directory which may be an attempt to sideload arbitrary DLL
// Tags: attack.defense_evasion, attack.t1574.002
DeviceImageLoadEvents
| where (FolderPath endswith "\\glib-2.0.dll" and InitiatingProcessFolderPath endswith "\\VMwareXferlogs.exe") and (not(FolderPath startswith "C:\\Program Files\\VMware\\"))