// Author: Markus Neis, Nasreddine Bencherchali
// Date: 2018/08/25
// Level: high
// Description: Detects potential PowerShell execution from a DLL instead of the usual PowerShell process as seen used in PowerShdll
// Tags: attack.defense_evasion, attack.t1218.011
DeviceProcessEvents
| where (ProcessCommandLine contains "Default.GetString" or ProcessCommandLine contains "FromBase64String" or ProcessCommandLine contains "Invoke-Expression" or ProcessCommandLine contains "IEX " or ProcessCommandLine contains "Invoke-Command" or ProcessCommandLine contains "ICM " or ProcessCommandLine contains "DownloadString") and ((FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\regsvcs.exe" or FolderPath endswith "\\InstallUtil.exe" or FolderPath endswith "\\regasm.exe") or (ProcessVersionInfoOriginalFileName in~ ("RUNDLL32.EXE", "RegSvcs.exe", "InstallUtil.exe", "RegAsm.exe")))