// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/05/17
// Level: medium
// Description: Detects potential arbitrary file download using a Microsoft Office application
// Tags: attack.defense_evasion, attack.t1202
DeviceProcessEvents
| where (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://") and ((FolderPath endswith "\\EXCEL.EXE" or FolderPath endswith "\\POWERPNT.EXE" or FolderPath endswith "\\WINWORD.exe") or (ProcessVersionInfoOriginalFileName in~ ("Excel.exe", "POWERPNT.EXE", "WinWord.exe")))