// Author: TropChaud
// Date: 2023/01/26
// Level: medium
// Description: Detects the use of the WMI command-line (WMIC) utility to identify and display various system information,
including OS, CPU, GPU, and disk drive names; memory capacity; display resolution; and baseboard, BIOS,
and GPU driver products/versions.
Some of these commands were used by Aurora Stealer in late 2022/early 2023.

// Tags: attack.discovery, attack.t1082
DeviceProcessEvents
| where (ProcessCommandLine contains "baseboard get product" or ProcessCommandLine contains "baseboard get version" or ProcessCommandLine contains "bios get SMBIOSBIOSVersion" or ProcessCommandLine contains "cpu get name" or ProcessCommandLine contains "DISKDRIVE get Caption" or ProcessCommandLine contains "LOGICALDISK get Name,Size,FreeSpace" or ProcessCommandLine contains "MEMPHYSICAL get MaxCapacity" or ProcessCommandLine contains "OS get Caption,OSArchitecture,Version" or ProcessCommandLine contains "path win32_VideoController get DriverVersion" or ProcessCommandLine contains "path win32_VideoController get name" or ProcessCommandLine contains "path win32_VideoController get VideoModeDescription") and (ProcessVersionInfoFileDescription =~ "WMI Commandline Utility" or ProcessVersionInfoOriginalFileName =~ "wmic.exe" or FolderPath endswith "\\WMIC.exe")