// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/01/12
// Level: high
// Description: Detects when the enablement of developer features such as "Developer Mode" or "Application Sideloading". Which allows the user to install untrusted packages.
// Tags: attack.defense_evasion
DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000001)" and ActionType =~ "RegistryValueSet" and (RegistryKey contains "\\Microsoft\\Windows\\CurrentVersion\\AppModelUnlock" or RegistryKey contains "\\Policies\\Microsoft\\Windows\\Appx") and (RegistryKey endswith "\\AllowAllTrustedApps" or RegistryKey endswith "\\AllowDevelopmentWithoutDevLicense")