// Author: Florian Roth (Nextron Systems)
// Date: 2021/06/28
// Level: medium
// Description: Detects suspicious command line reg.exe tool adding key to RUN key in Registry
// Tags: attack.persistence, attack.t1547.001
DeviceProcessEvents
| where ProcessCommandLine contains "reg" and ProcessCommandLine contains " ADD " and ProcessCommandLine contains "Software\\Microsoft\\Windows\\CurrentVersion\\Run"