// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/02/28
// Level: high
// Description: Detects potential psexec command that initiate execution on a remote systems via common commandline flags used by the utility
// Tags: attack.resource_development, attack.t1587.001
DeviceProcessEvents
| where ProcessCommandLine contains "accepteula" and ProcessCommandLine contains " -u " and ProcessCommandLine contains " -p " and ProcessCommandLine contains " \\\\"