// Author: Victor Sergeev, oscd.community
// Date: 2019/10/25
// Level: high
// Description: Detects the execution of netsh with "add helper" flag in order to add a custom helper DLL. This technique can be abused to add a malicious helper DLL that can be used as a persistence proxy that gets called when netsh.exe is executed.
// Tags: attack.privilege_escalation, attack.persistence, attack.t1546.007, attack.s0108
DeviceProcessEvents
| where (ProcessCommandLine contains "add" and ProcessCommandLine contains "helper") and FolderPath endswith "\\netsh.exe"