// Author: Florian Roth (Nextron Systems)
// Date: 2021/04/29
// Level: medium
// Description: Detects requests to exclude files, folders or processes from Antivirus scanning using PowerShell cmdlets
// Tags: attack.defense_evasion, attack.t1562.001
DeviceProcessEvents
| where (ProcessCommandLine contains "Add-MpPreference " or ProcessCommandLine contains "Set-MpPreference ") and (ProcessCommandLine contains " -ExclusionPath " or ProcessCommandLine contains " -ExclusionExtension " or ProcessCommandLine contains " -ExclusionProcess " or ProcessCommandLine contains " -ExclusionIpAddress ")