// Author: Florian Roth (Nextron Systems)
// Date: 2021/07/29
// Level: high
// Description: Detects suspicious PowerShell scripts accessing SAM hives
// Tags: attack.credential_access, attack.t1003.002
DeviceProcessEvents
| where (ProcessCommandLine contains "\\HarddiskVolumeShadowCopy" and ProcessCommandLine contains "System32\\config\\sam") and (ProcessCommandLine contains "Copy-Item" or ProcessCommandLine contains "cp $_." or ProcessCommandLine contains "cpi $_." or ProcessCommandLine contains "copy $_." or ProcessCommandLine contains ".File]::Copy(")