// Author: Florian Roth (Nextron Systems)
// Date: 2020/08/28
// Level: high
// Description: Detects the execution of powershell, a WebClient object creation and the invocation of DownloadFile in a single command line
// Tags: attack.execution, attack.t1059.001, attack.command_and_control, attack.t1104, attack.t1105
DeviceProcessEvents
| where ProcessCommandLine contains "powershell" and ProcessCommandLine contains ".DownloadFile" and ProcessCommandLine contains "System.Net.WebClient"