// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/05/09
// Level: low
// Description: Detects the creation of a new PowerShell module ".psm1", ".psd1", ".dll", ".ps1", etc.
// Tags: attack.persistence
DeviceFileEvents
| where (InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe") and (FolderPath contains "\\WindowsPowerShell\\Modules\\" or FolderPath contains "\\PowerShell\\7\\Modules\\")