// Author: frack113
// Date: 2022/08/20
// Level: medium
// Description: Detects the execution of WebBrowserPassView.exe. A password recovery tool that reveals the passwords stored by the following Web browsers, Internet Explorer (Version 4.0 - 11.0), Mozilla Firefox (All Versions), Google Chrome, Safari, and Opera
// Tags: attack.credential_access, attack.t1555.003
DeviceProcessEvents
| where ProcessVersionInfoFileDescription =~ "Web Browser Password Viewer" or FolderPath endswith "\\WebBrowserPassView.exe"