// Author: Florian Roth (Nextron Systems)
// Date: 2022/01/24
// Level: high
// Description: Detects the use of the RunXCmd tool to execute commands with System or TrustedInstaller accounts
// Tags: attack.execution, attack.t1569.002, attack.s0029
DeviceProcessEvents
| where (ProcessCommandLine contains " /account=system " or ProcessCommandLine contains " /account=ti ") and ProcessCommandLine contains "/exec="