// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/02/08
// Level: medium
// Description: Detects creation of files with the ".pub" extension in suspicious or uncommon locations. This could be a sign of attackers abusing Publisher documents
// Tags: attack.defense_evasion
DeviceFileEvents
| where (FolderPath contains "\\AppData\\Local\\Temp\\" or FolderPath contains "\\Users\\Public\\" or FolderPath contains "\\Windows\\Temp\\" or FolderPath contains "C:\\Temp\\") and FolderPath endswith ".pub"