// Author: Patrick St. John, OTR (Open Threat Research)
// Date: 2020/05/03
// Level: medium
// Description: Detects the image load of Python Core indicative of a Python script bundled with Py2Exe.
// Tags: attack.defense_evasion, attack.t1027.002
DeviceImageLoadEvents
| where InitiatingProcessVersionInfoFileDescription =~ "Python Core" and (not((isnull(InitiatingProcessFolderPath) or (InitiatingProcessFolderPath contains "Python" or (InitiatingProcessFolderPath startswith "C:\\Program Files\\" or InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\" or InitiatingProcessFolderPath startswith "C:\\ProgramData\\Anaconda3\\")))))