// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/01
// Level: medium
// Description: Detects usage of "query.exe" a system binary to exfil information such as "sessions" and "processes" for later use
// Tags: attack.execution
DeviceProcessEvents
| where (ProcessCommandLine contains "session >" or ProcessCommandLine contains "process >") and FolderPath endswith ":\\Windows\\System32\\query.exe"