// Author: frack113
// Date: 2021/07/30
// Level: medium
// Description: Once established within a system or network, an adversary may use automated techniques for collecting internal data.
// Tags: attack.collection, attack.t1119
DeviceProcessEvents
| where ((FolderPath endswith "\\tree.com" or FolderPath endswith "\\WMIC.exe" or FolderPath endswith "\\doskey.exe" or FolderPath endswith "\\sc.exe") or (ProcessVersionInfoOriginalFileName in~ ("wmic.exe", "DOSKEY.EXE", "sc.exe"))) and (InitiatingProcessCommandLine contains " > %TEMP%\\" or InitiatingProcessCommandLine contains " > %TMP%\\")