// Author: Florian Roth (Nextron Systems)
// Date: 2021/05/27
// Level: high
// Description: Detects a regedit started with TrustedInstaller privileges or by ProcessHacker.exe
// Tags: attack.privilege_escalation, attack.t1548
DeviceProcessEvents
| where FolderPath endswith "\\regedit.exe" and (InitiatingProcessFolderPath endswith "\\TrustedInstaller.exe" or InitiatingProcessFolderPath endswith "\\ProcessHacker.exe")