// Author: frack113
// Date: 2022/01/22
// Level: medium
// Description: Hides the file extension through modification of the registry
// Tags: attack.persistence, attack.t1137
DeviceRegistryEvents
| where (RegistryValueData =~ "DWORD (0x00000002)" and ActionType =~ "RegistryValueSet" and RegistryKey endswith "\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\\Hidden") or (RegistryValueData =~ "DWORD (0x00000001)" and ActionType =~ "RegistryValueSet" and RegistryKey endswith "\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\\HideFileExt")