// Author: Julia Fomina, oscd.community
// Date: 2020/10/07
// Level: medium
// Description: Detects an attempt to execute code or create service on remote host via winrm.vbs.
// Tags: attack.defense_evasion, attack.t1216
DeviceProcessEvents
| where (ProcessCommandLine contains "winrm" and ProcessCommandLine contains "invoke Create wmicimv2/Win32_" and ProcessCommandLine contains "-r:http") and (FolderPath endswith "\\cscript.exe" or ProcessVersionInfoOriginalFileName =~ "cscript.exe")