// Author: Florian Roth (Nextron Systems)
// Date: 2021/02/11
// Level: high
// Description: Detects ScreenConnect program starts that establish a remote access to that system (not meeting, not remote support)
// Tags: attack.initial_access, attack.t1133
DeviceProcessEvents
| where ProcessCommandLine contains "e=Access&" and ProcessCommandLine contains "y=Guest&" and ProcessCommandLine contains "&p=" and ProcessCommandLine contains "&c=" and ProcessCommandLine contains "&k="