// Author: Christopher Peacock @securepeacock, SCYTHE @scythe_io, TactiKoolSec
// Date: 2022/04/28
// Level: medium
// Description: An attacker may execute an application as a SCR File using rundll32.exe desk.cpl,InstallScreenSaver
// Tags: attack.t1218.011, attack.defense_evasion
DeviceProcessEvents
| where ProcessCommandLine contains "InstallScreenSaver" and (FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE")