// Author: Christian Burkard (Nextron Systems)
// Date: 2021/11/24
// Level: high
// Description: Detects shell32.dll executing a DLL in a suspicious directory
// Tags: attack.defense_evasion, attack.execution, attack.t1218.011
DeviceProcessEvents
| where ((ProcessCommandLine contains "%AppData%" or ProcessCommandLine contains "%LocalAppData%" or ProcessCommandLine contains "%Temp%" or ProcessCommandLine contains "%tmp%" or ProcessCommandLine contains "\\AppData\\" or ProcessCommandLine contains "\\Temp\\" or ProcessCommandLine contains "\\Users\\Public\\") and (ProcessCommandLine contains "shell32.dll" and ProcessCommandLine contains "Control_RunDLL")) and (FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE")