// Author: Florian Roth (Nextron Systems)
// Date: 2021/02/01
// Level: high
// Description: Detects actions that clear the local ShimCache and remove forensic evidence
// Tags: attack.defense_evasion, attack.t1112
DeviceProcessEvents
| where ((ProcessCommandLine contains "rundll32" and ProcessCommandLine contains "apphelp.dll") and (ProcessCommandLine contains "ShimFlushCache" or ProcessCommandLine contains "#250")) or ((ProcessCommandLine contains "rundll32" and ProcessCommandLine contains "kernel32.dll") and (ProcessCommandLine contains "BaseFlushAppcompatCache" or ProcessCommandLine contains "#46"))