// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/02/28
// Level: high
// Description: Detects the execution of "whoami.exe" with the "/all" flag or with redirection options to export the results to a file for later use.
// Tags: attack.discovery, attack.t1033, car.2016-03-001
DeviceProcessEvents
| where ((ProcessCommandLine contains " -all" or ProcessCommandLine contains " /all" or ProcessCommandLine contains " /FO CSV" or ProcessCommandLine contains " -FO CSV") and (FolderPath endswith "\\whoami.exe" or ProcessVersionInfoOriginalFileName =~ "whoami.exe")) or (ProcessCommandLine contains "whoami" and ProcessCommandLine contains ">")