// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/10/17
// Level: medium
// Description: Detects suspicious processes based on name and location that access the Windows Credential History File.
Which can be a sign of credential stealing. Example case would be usage of mimikatz "dpapi::credhist" function

// Tags: attack.credential_access, attack.t1555.004
DeviceFileEvents
| where FileName endswith "\\Microsoft\\Protect\\CREDHIST" and (not((InitiatingProcessFolderPath =~ "C:\\Windows\\explorer.exe" or (InitiatingProcessFolderPath startswith "C:\\Program Files\\" or InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\system32\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\SysWOW64\\"))))