// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/09/01
// Level: medium
// Description: Detects potential suspicious execution of a GUID like folder name located in a suspicious location such as %TEMP% as seen being used in IcedID attacks
// Tags: attack.defense_evasion, attack.t1027
DeviceProcessEvents
| where ((ProcessCommandLine contains "\\AppData\\Roaming\\" or ProcessCommandLine contains "\\AppData\\Local\\Temp\\") and (ProcessCommandLine contains "\\{" and ProcessCommandLine contains "}\\")) and (not(((FolderPath contains "\\{" and FolderPath contains "}\\") or FolderPath =~ "C:\\Windows\\System32\\drvinst.exe" or isnull(FolderPath))))