// Author: frack113
// Date: 2022/01/23
// Level: medium
// Description: Uses the .NET InstallUtil.exe application in order to execute image without log
// Tags: attack.defense_evasion
DeviceProcessEvents
| where (ProcessCommandLine contains "/logfile= " and ProcessCommandLine contains "/LogToConsole=false") and FolderPath contains "Microsoft.NET\\Framework" and FolderPath endswith "\\InstallUtil.exe"