// Author: Beyu Denis, oscd.community
// Date: 2019/10/26
// Level: high
// Description: Detects the usage of one of three Microsoft office applications (Word, Excel, PowerPoint) to download arbitrary files
// Tags: attack.command_and_control, attack.t1105
DeviceProcessEvents
| where ProcessCommandLine contains "http" and (FolderPath endswith "\\powerpnt.exe" or FolderPath endswith "\\winword.exe" or FolderPath endswith "\\excel.exe")