// Author: frack113
// Date: 2021/11/03
// Level: medium
// Description: lolbas Cmdl32 is use to download a payload to evade antivirus
// Tags: attack.execution, attack.defense_evasion, attack.t1218, attack.t1202
DeviceProcessEvents
| where (ProcessCommandLine contains "/vpn " and ProcessCommandLine contains "/lan ") and (FolderPath endswith "\\cmdl32.exe" or ProcessVersionInfoOriginalFileName =~ "CMDL32.EXE")