// Author: Florian Roth (Nextron Systems)
// Date: 2021/11/16
// Level: high
// Description: Detects the creation of tasks from processes executed from suspicious locations
// Tags: attack.persistence, attack.execution, attack.t1053
DeviceFileEvents
| where (InitiatingProcessFolderPath contains "\\AppData\\" or InitiatingProcessFolderPath contains "C:\\PerfLogs" or InitiatingProcessFolderPath contains "\\Windows\\System32\\config\\systemprofile") and FolderPath contains "\\Windows\\System32\\Tasks"