// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/19
// Level: medium
// Description: Detects the execution of CustomShellHost binary where the child isn't located in 'C:\Windows\explorer.exe'
// Tags: attack.defense_evasion, attack.t1216
DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\CustomShellHost.exe" and (not(FolderPath =~ "C:\\Windows\\explorer.exe"))