// Author: Austin Songer @austinsonger, Florian Roth
// Date: 2021/11/26
// Level: high
// Description: Detects when a user bypasses Defender by renaming a tool to dump64.exe and placing it in a Visual Studio folder
// Tags: attack.credential_access, attack.t1003.001
DeviceProcessEvents
| where (FolderPath endswith "\\dump64.exe" and (not(FolderPath contains "\\Installer\\Feedback\\dump64.exe"))) or (FolderPath endswith "\\dump64.exe" and (ProcessCommandLine contains " -ma " or ProcessCommandLine contains "accepteula"))