// Author: Florian Roth (Nextron Systems)
// Date: 2019/02/11
// Level: high
// Description: Detects a suspicious parent of csc.exe, which could by a sign of payload delivery
// Tags: attack.execution, attack.t1059.005, attack.t1059.007, attack.defense_evasion, attack.t1218.005, attack.t1027.004
DeviceProcessEvents
| where FolderPath endswith "\\csc.exe" and (InitiatingProcessFolderPath endswith "\\wscript.exe" or InitiatingProcessFolderPath endswith "\\cscript.exe" or InitiatingProcessFolderPath endswith "\\mshta.exe")