// Author: Florian Roth (Nextron Systems)
// Date: 2021/12/07
// Level: high
// Description: Detects the creation of files that indicator an interactive use of PowerShell in the SYSTEM user context
// Tags: 
DeviceFileEvents
| where FolderPath in~ ("C:\\Windows\\System32\\config\\systemprofile\\AppData\\Roaming\\Microsoft\\Windows\\PowerShell\\PSReadLine\\ConsoleHost_history.txt", "C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\Microsoft\\Windows\\PowerShell\\StartupProfileData-Interactive")