// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/10/31
// Level: medium
// Description: Detects creation of a scheduled task with a GUID like name
// Tags: attack.execution, attack.t1053.005
DeviceProcessEvents
| where (ProcessCommandLine contains "}\"" or ProcessCommandLine contains "}'" or ProcessCommandLine contains "} ") and (ProcessCommandLine contains "/Create " and FolderPath endswith "\\schtasks.exe") and (ProcessCommandLine contains "/TN \"{" or ProcessCommandLine contains "/TN '{" or ProcessCommandLine contains "/TN {")