// Author: Florian Roth (Nextron Systems)
// Date: 2022/10/14
// Level: high
// Description: Detects suspicious Windows Error Reporting manager (wermgr.exe) process patterns - suspicious parents / children, execution folders, command lines etc.
// Tags: 
DeviceProcessEvents
| where ((FolderPath endswith "\\nslookup.exe" or FolderPath endswith "\\ipconfig.exe" or FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe" or FolderPath endswith "\\whoami.exe" or FolderPath endswith "\\netstat.exe" or FolderPath endswith "\\systeminfo.exe" or FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\powershell.exe") and InitiatingProcessFolderPath endswith "\\wermgr.exe") or (FolderPath endswith "\\wermgr.exe" and (not((FolderPath startswith "C:\\Windows\\System32\\" or FolderPath startswith "C:\\Windows\\SysWOW64\\" or FolderPath startswith "C:\\Windows\\WinSxS\\"))))