// Author: Eli Salem, Sander Wiebing, oscd.community
// Date: 2020/10/12
// Level: high
// Description: Detects the import of an alternate data stream with regini.exe, regini.exe can be used to modify registry keys.
// Tags: attack.t1112, attack.defense_evasion
DeviceProcessEvents
| where (FolderPath endswith "\\regini.exe" or ProcessVersionInfoOriginalFileName =~ "REGINI.EXE") and ProcessCommandLine matches regex ":[^ \\\\]"