// Author: Hai Vaknin @LuxNoBulIshit, Avihay eldad  @aloneliassaf, Austin Songer @austinsonger
// Date: 2021/09/30
// Level: medium
// Description: Detects when a possible suspicious driver is being installed via pnputil.exe lolbin
// Tags: attack.persistence, attack.t1547
DeviceProcessEvents
| where (ProcessCommandLine contains "-i" or ProcessCommandLine contains "/install" or ProcessCommandLine contains "-a" or ProcessCommandLine contains "/add-driver" or ProcessCommandLine contains ".inf") and FolderPath endswith "\\pnputil.exe"