// Author: Florian Roth (Nextron Systems)
// Date: 2017/08/15
// Level: high
// Description: Detects a suspicious svchost process start
// Tags: attack.defense_evasion, attack.t1036.005
DeviceProcessEvents
| where FolderPath endswith "\\svchost.exe" and (not(((InitiatingProcessFolderPath endswith "\\services.exe" or InitiatingProcessFolderPath endswith "\\MsMpEng.exe" or InitiatingProcessFolderPath endswith "\\Mrt.exe" or InitiatingProcessFolderPath endswith "\\rpcnet.exe" or InitiatingProcessFolderPath endswith "\\ngen.exe" or InitiatingProcessFolderPath endswith "\\TiWorker.exe") or InitiatingProcessFolderPath =~ "-" or isnull(InitiatingProcessFolderPath) or InitiatingProcessFolderPath =~ "")))