// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/09/01
// Level: high
// Description: Detects suspicious usage of the ShellExec_RunDLL function to launch other commands as seen in the the raspberry-robin attack
// Tags: attack.defense_evasion
DeviceProcessEvents
| where ProcessCommandLine contains "ShellExec_RunDLL" and (ProcessCommandLine contains "regsvr32" or ProcessCommandLine contains "msiexec" or ProcessCommandLine contains "\\Users\\Public\\" or ProcessCommandLine contains "odbcconf" or ProcessCommandLine contains "\\Desktop\\" or ProcessCommandLine contains "\\Temp\\" or ProcessCommandLine contains "Invoke-" or ProcessCommandLine contains "iex" or ProcessCommandLine contains "comspec")