// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/10/25
// Level: medium
// Description: Detects possible search for office tokens via CLI by looking for the string "eyJ0eX". This string is used as an anchor to look for the start of the JWT token used by office and similar apps.
// Tags: attack.credential_access, attack.t1528
DeviceProcessEvents
| where ProcessCommandLine contains "eyJ0eXAiOi" or ProcessCommandLine contains " eyJ0eX" or ProcessCommandLine contains " \"eyJ0eX\"" or ProcessCommandLine contains " 'eyJ0eX'"