// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/31
// Level: medium
// Description: Detects scheduled task creations or modification to be run with high privileges on a suspicious schedule type
// Tags: attack.execution, attack.t1053.005
DeviceProcessEvents
| where (FolderPath endswith "\\schtasks.exe" or ProcessVersionInfoOriginalFileName =~ "schtasks.exe") and (ProcessCommandLine contains "NT AUT" or ProcessCommandLine contains " SYSTEM" or ProcessCommandLine contains "HIGHEST") and (ProcessCommandLine contains " ONLOGON " or ProcessCommandLine contains " ONSTART " or ProcessCommandLine contains " ONCE " or ProcessCommandLine contains " ONIDLE ")