// Author: David Burkett, @signalblur
// Date: 2019/12/28
// Level: high
// Description: It is extremely abnormal for svchost.exe to spawn without any CLI arguments and is normally observed when a malicious process spawns the process and injects code into the process memory space.
// Tags: attack.defense_evasion, attack.privilege_escalation, attack.t1055
DeviceProcessEvents
| where (ProcessCommandLine endswith "svchost.exe" and FolderPath endswith "\\svchost.exe") and (not(((InitiatingProcessFolderPath endswith "\\rpcnet.exe" or InitiatingProcessFolderPath endswith "\\rpcnetp.exe") or isnull(ProcessCommandLine))))