// Author: X__Junior (Nextron Systems), Florian Roth (Nextron Systems)
// Date: 2022/12/15
// Level: high
// Description: Detects RAR usage that creates an archive from a suspicious folder, either a system folder or one of the folders often used by attackers for staging purposes
// Tags: attack.execution, attack.t1059
DeviceProcessEvents
| where ((FolderPath endswith "\\rar.exe" or ProcessVersionInfoFileDescription =~ "Command line RAR") or (ProcessCommandLine contains ".exe a " or ProcessCommandLine contains " a -m")) and ((ProcessCommandLine contains " -hp" and ProcessCommandLine contains " -r ") and (ProcessCommandLine contains " C:\\\*." or ProcessCommandLine contains " C:\\\\\*." or ProcessCommandLine contains " C:\\Users\\Public\\" or ProcessCommandLine contains " %public%" or ProcessCommandLine contains " C:\\Windows\\" or ProcessCommandLine contains " C:\\PerfLogs\\" or ProcessCommandLine contains " C:\\Temp" or ProcessCommandLine contains " C:\\$Recycle.bin\\"))