// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/09/14
// Level: medium
// Description: Detects execution of ntdsutil.exe to perform different actions such as restoring snapshots...etc.
// Tags: attack.credential_access, attack.t1003.003
DeviceProcessEvents
| where ((ProcessCommandLine contains "snapshot" and ProcessCommandLine contains "mount ") or (ProcessCommandLine contains "ac" and ProcessCommandLine contains " i" and ProcessCommandLine contains " ntds")) and (FolderPath endswith "\\ntdsutil.exe" or ProcessVersionInfoOriginalFileName =~ "ntdsutil.exe")