// Author: Florian Roth (Nextron Systems)
// Date: 2022/02/26
// Level: high
// Description: Detects suspicious Windows Update Agent activity in which a wuauclt.exe process command line doesn't contain any command line flags
// Tags: 
DeviceProcessEvents
| where ProcessCommandLine endswith "\\Wuauclt.exe" and (FolderPath endswith "\\Wuauclt.exe" or ProcessVersionInfoOriginalFileName =~ "Wuauclt.exe")