// Author: frack113
// Date: 2022/09/05
// Level: high
// Description: Detect creation of suspicious executable file name. Some strings look for suspicious file extensions, others look for filenames that exploit unquoted service paths.
// Tags: attack.defense_evasion, attack.t1564
DeviceFileEvents
| where (FolderPath endswith ".bat.exe" or FolderPath endswith ".sys.exe") or (FolderPath in~ ("C:\\$Recycle.Bin.exe", "C:\\Documents and Settings.exe", "C:\\MSOCache.exe", "C:\\Recovery.exe", "C:\\PerfLogs.exe"))