// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/10/17
// Level: medium
// Description: Detects suspicious processes based on name and location that access the Windows Data Protection API Master keys.
Which can be a sign of credential stealing. Example case would be usage of mimikatz "dpapi::masterkey" function

// Tags: attack.credential_access, attack.t1555.004
DeviceFileEvents
| where (FileName contains "\\Microsoft\\Protect\\S-1-5-18\\" or FileName contains "\\Microsoft\\Protect\\S-1-5-21-") and (not((InitiatingProcessFolderPath startswith "C:\\Program Files\\" or InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\system32\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\SysWOW64\\")))