// Author: Florian Roth (Nextron Systems)
// Date: 2019/10/24
// Level: high
// Description: Detects suspicious Hangul Word Processor (Hanword) sub processes that could indicate an exploitation
// Tags: attack.initial_access, attack.t1566.001, attack.execution, attack.t1203, attack.t1059.003, attack.g0032
DeviceProcessEvents
| where FolderPath endswith "\\gbb.exe" and InitiatingProcessFolderPath endswith "\\Hwp.exe"