// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/03/23
// Level: medium
// Description: Detects usage of Sysinternals PsSuspend which can be abused to suspend critical processes
// Tags: attack.discovery, attack.persistence, attack.t1543.003
DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "pssuspend.exe" or (FolderPath endswith "\\pssuspend.exe" or FolderPath endswith "\\pssuspend64.exe")