// Author: Kirill Kiryanov, oscd.community
// Date: 2019/10/23
// Level: high
// Description: Detects possible Sysmon filter driver unloaded via fltmc.exe
// Tags: attack.defense_evasion, attack.t1070, attack.t1562, attack.t1562.002
DeviceProcessEvents
| where (ProcessCommandLine contains "unload" and ProcessCommandLine contains "sysmon") and (FolderPath endswith "\\fltMC.exe" or ProcessVersionInfoOriginalFileName =~ "fltMC.exe")