// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/05
// Level: high
// Description: Detects attempts to remove Windows Defender configurations using the 'MpPreference' cmdlet
// Tags: attack.defense_evasion, attack.t1562.001
DeviceProcessEvents
| where ProcessCommandLine contains "Remove-MpPreference" and (ProcessCommandLine contains "-ControlledFolderAccessProtectedFolders " or ProcessCommandLine contains "-AttackSurfaceReductionRules_Ids " or ProcessCommandLine contains "-AttackSurfaceReductionRules_Actions " or ProcessCommandLine contains "-CheckForSignaturesBeforeRunningScan ")