// Author: frack113
// Date: 2022/01/16
// Level: low
// Description: Detects the deletion of the TeamViewer log files which may indicate an attempt to destroy forensic evidence
// Tags: attack.defense_evasion, attack.t1070.004
DeviceFileEvents
| where (FolderPath contains "\\TeamViewer_" and FolderPath endswith ".log") and (not(InitiatingProcessFolderPath =~ "C:\\Windows\\system32\\svchost.exe"))