// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/02/16
// Level: medium
// Description: Detects the deletion of tomcat WebServer logs which may indicate an attempt to destroy forensic evidence
// Tags: attack.defense_evasion, attack.t1070
DeviceFileEvents
| where (FolderPath contains "catalina." or FolderPath contains "_access_log." or FolderPath contains "localhost.") and (FolderPath contains "\\Tomcat" and FolderPath contains "\\logs\\")