// Author: Christian Burkard (Nextron Systems)
// Date: 2021/08/30
// Level: high
// Description: Detects the pattern of UAC Bypass using a msconfig GUI hack (UACMe 55)
// Tags: attack.defense_evasion, attack.privilege_escalation, attack.t1548.002
DeviceProcessEvents
| where ProcessCommandLine =~ "\"C:\\Windows\\system32\\msconfig.exe\" -5" and (ProcessIntegrityLevel in~ ("High", "System")) and InitiatingProcessFolderPath endswith "\\AppData\\Local\\Temp\\pkgmgr.exe"