// Author: frack113, Nasreddine Bencherchali
// Date: 2022/08/07
// Level: medium
// Description: Detect use of the Windows 8.3 short name. Which could be used as a method to avoid command-line detection
// Tags: attack.defense_evasion, attack.t1564.004
DeviceProcessEvents
| where (ProcessCommandLine contains "~1\\" or ProcessCommandLine contains "~2\\") and (not(((InitiatingProcessFolderPath in~ ("C:\\Windows\\System32\\Dism.exe", "C:\\Windows\\System32\\cleanmgr.exe", "C:\\Program Files\\GPSoftware\\Directory Opus\\dopus.exe")) or (InitiatingProcessFolderPath endswith "\\WebEx\\WebexHost.exe" or InitiatingProcessFolderPath endswith "\\thor\\thor64.exe" or InitiatingProcessFolderPath endswith "\\veam.backup.shell.exe" or InitiatingProcessFolderPath endswith "\\winget.exe" or InitiatingProcessFolderPath endswith "\\Everything\\Everything.exe") or InitiatingProcessFolderPath contains "\\AppData\\Local\\Temp\\WinGet\\" or (ProcessCommandLine contains "\\appdata\\local\\webex\\webex64\\meetings\\wbxreport.exe" or ProcessCommandLine contains "C:\\Program Files\\Git\\post-install.bat" or ProcessCommandLine contains "C:\\Program Files\\Git\\cmd\\scalar.exe"))))