// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/06/14
// Level: medium
// Description: Execute commands and binaries from the context of "forfiles". This is used as a LOLBIN for example to bypass application whitelisting.
// Tags: attack.execution, attack.t1059
DeviceProcessEvents
| where (ProcessCommandLine contains " /c " or ProcessCommandLine contains " -c ") and (ProcessCommandLine contains " /m " or ProcessCommandLine contains " -m ") and (ProcessCommandLine contains " /p " or ProcessCommandLine contains " -p ") and (FolderPath endswith "\\forfiles.exe" or ProcessVersionInfoOriginalFileName =~ "forfiles.exe")