// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/06/09
// Level: medium
// Description: The "Trace log generation tool for Media Foundation Tools" (Mftrace.exe) can be used to execute arbitrary binaries
// Tags: attack.defense_evasion, attack.t1127
DeviceProcessEvents
| where ((ProcessCommandLine contains ".exe " and ProcessCommandLine endswith ".exe") and (FolderPath endswith "\\mftrace.exe" or ProcessVersionInfoOriginalFileName =~ "mftrace.exe")) or InitiatingProcessFolderPath endswith "\\mftrace.exe"