// Author: @gott_cyber
// Date: 2022/12/11
// Level: medium
// Description: Detects the use of Setres.exe to set the screen resolution and then potentially launch a file named "choice" (with any executable extension such as ".cmd" or ".exe") from the current execution path
// Tags: attack.defense_evasion, attack.t1218, attack.t1202
DeviceProcessEvents
| where FolderPath endswith "\\choice" and InitiatingProcessFolderPath endswith "\\setres.exe"