// Author: Anton Kutepov, oscd.community
// Date: 2020/02/05
// Level: high
// Description: Detects using SettingSyncHost.exe to run hijacked binary
// Tags: attack.execution, attack.defense_evasion, attack.t1574.008
DeviceProcessEvents
| where (not((FolderPath startswith "C:\\Windows\\System32\\" or FolderPath startswith "C:\\Windows\\SysWOW64\\"))) and (InitiatingProcessCommandLine contains "cmd.exe /c" and InitiatingProcessCommandLine contains "RoamDiag.cmd" and InitiatingProcessCommandLine contains "-outputpath")