// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/24
// Level: medium
// Description: Detects the creation or modification of a vscode related powershell profile which could indicate suspicious activity as the profile can be used as a mean of persistence
// Tags: attack.persistence, attack.privilege_escalation, attack.t1546.013
DeviceFileEvents
| where FolderPath endswith "\\Microsoft.VSCode_profile.ps1"