// Author: Florian Roth (Nextron Systems)
// Date: 2022/06/27
// Level: high
// Description: Detects WerFault creating a dump file with a name that indicates that the dump file could be an LSASS process memory, which contains user credentials
// Tags: attack.credential_access, attack.t1003.001
DeviceFileEvents
| where InitiatingProcessFolderPath =~ "C:\\WINDOWS\\system32\\WerFault.exe" and (FolderPath contains "\\lsass" or FolderPath contains "lsass.exe")