// Author: Beyu Denis, oscd.community, Tim Shelton
// Date: 2019/10/22
// Level: high
// Description: Possible webshell file creation on a static web site
// Tags: attack.persistence, attack.t1505.003
DeviceFileEvents
| where ((FolderPath contains "\\inetpub\\wwwroot\\" and (FolderPath contains ".asp" or FolderPath contains ".ashx" or FolderPath contains ".ph")) or ((FolderPath contains "\\www\\" or FolderPath contains "\\htdocs\\" or FolderPath contains "\\html\\") and FolderPath contains ".ph")) and (not(((FolderPath contains "\\AppData\\Local\\Temp\\" or FolderPath contains "\\Windows\\Temp\\") or FolderPath contains "\\xampp" or InitiatingProcessFolderPath =~ "System")))