// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/06/20
// Level: medium
// Description: Detects the execution of wmic with the "qfe" flag in order to obtain information about installed hotfix updates on the system. This is often used by pentester and attacker enumeration scripts
// Tags: attack.execution, attack.t1047
DeviceProcessEvents
| where ProcessCommandLine contains " qfe" and (ProcessVersionInfoOriginalFileName =~ "wmic.exe" or FolderPath endswith "\\WMIC.exe")