// Author: frack113
// Date: 2022/04/08
// Level: medium
// Description: List credentials currently stored in Windows Credential Manager via the native Windows utility vaultcmd.exe
// Tags: attack.credential_access, attack.t1555.004
DeviceProcessEvents
| where ProcessCommandLine contains "/listcreds:" and (FolderPath endswith "\\VaultCmd.exe" or ProcessVersionInfoOriginalFileName =~ "VAULTCMD.EXE")