// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/02/21
// Level: high
// Description: Detects when an internet hosted webdav share is mounted using the "net.exe" utility
// Tags: attack.lateral_movement, attack.t1021.002
DeviceProcessEvents
| where (ProcessCommandLine contains " use " or ProcessCommandLine contains " http") and ((FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe") or (ProcessVersionInfoOriginalFileName in~ ("net.exe", "net1.exe")))