// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/09/09
// Level: medium
// Description: Detects when the 'AllowMultipleTSSessions' value is enabled.
Which allows for multiple Remote Desktop connection sessions to be opened at once.
This is often used by attacker as a way to connect to an RDP session without disconnecting the other users

// Tags: attack.persistence, attack.defense_evasion, attack.t1112
DeviceRegistryEvents
| where RegistryValueData endswith "DWORD (0x00000001)" and ActionType =~ "RegistryValueSet" and RegistryKey endswith "\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\AllowMultipleTSSessions"