// Author: Florian Roth (Nextron Systems), Tigzy
// Date: 2021/11/17
// Level: high
// Description: Detects a suspicious winrar execution in a folder which is not the default installation folder
// Tags: attack.collection, attack.t1560.001
DeviceProcessEvents
| where ((FolderPath endswith "\\rar.exe" or FolderPath endswith "\\winrar.exe") or ProcessVersionInfoFileDescription =~ "Command line RAR") and (not((FolderPath contains "\\WinRAR" or FolderPath contains "C:\\Windows\\Temp" or FolderPath contains "\\UnRAR.exe")))