// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/05/11
// Level: medium
// Description: Detects the creation of binaries in the WinSxS folder by non-system processes
// Tags: attack.execution
DeviceFileEvents
| where (FolderPath endswith ".exe" and FolderPath startswith "C:\\Windows\\WinSxS\\") and (not((InitiatingProcessFolderPath startswith "C:\\Windows\\Systems32\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\SysWOW64\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\WinSxS\\")))