// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/02/14
// Level: medium
// Description: Detects the execution of WMIC to query information on a remote system
// Tags: attack.execution, attack.t1047
DeviceProcessEvents
| where (ProcessCommandLine contains "/node:" and (FolderPath endswith "\\WMIC.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")) and (not((ProcessCommandLine contains "/node:127.0.0.1 " or ProcessCommandLine contains "/node:localhost ")))