// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/06/02
// Level: critical
// Description: Detects the creation of the default output filename used by the wmiexec tool
// Tags: attack.lateral_movement, attack.t1047
DeviceFileEvents
| where FolderPath matches regex "\\\\Windows\\\\__1\\d{9}\\.\\d{1,7}$" or FolderPath matches regex "C:\\\\__1\\d{9}\\.\\d{1,7}$" or FolderPath matches regex "D:\\\\__1\\d{9}\\.\\d{1,7}$"