// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/05
// Level: high
// Description: Detects usage of the "wusa.exe" (Windows Update Standalone Installer) utility to extract cab using the "/extract" argument from suspicious paths
// Tags: attack.execution
DeviceProcessEvents
| where (ProcessCommandLine contains "C:\\Users\\Public\\" or ProcessCommandLine contains "\\Desktop\\" or ProcessCommandLine contains "\\Downloads\\" or ProcessCommandLine contains "\\Appdata\\Local\\Temp\\" or ProcessCommandLine contains "\\Windows\\Temp\\" or ProcessCommandLine contains "\\PerfLogs\\") and (ProcessCommandLine contains "/extract:" and FolderPath endswith "\\wusa.exe")