// Title: Lazarus System Binary Masquerading
// Author: Trent Liffick (@tliffick), Bartlomiej Czyz (@bczyz1)
// Date: 2020-06-03
// Level: high
// Description: Detects binaries used by the Lazarus group which use system names but are executed and launched from non-default location
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036.005, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2017/TA/Lazarus/proc_creation_win_apt_lazarus_binary_masquerading.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (FolderPath endswith "\\msdtc.exe" or FolderPath endswith "\\gpsvc.exe") and (not((FolderPath startswith "C:\\Windows\\System32\\" or FolderPath startswith "C:\\Windows\\SysWOW64\\")))