// Title: RegAsm.EXE Initiating Network Connection To Public IP
// Author: frack113
// Date: 2024-04-25
// Level: medium
// Description: Detects "RegAsm.exe" initiating a network connection to public IP adresses
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.009
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_regasm_network_activity.yml

DeviceNetworkEvents
| where InitiatingProcessFolderPath endswith "\\regasm.exe" and (not((ipv4_is_in_range(RemoteIP, "127.0.0.0/8") or ipv4_is_in_range(RemoteIP, "10.0.0.0/8") or ipv4_is_in_range(RemoteIP, "172.16.0.0/12") or ipv4_is_in_range(RemoteIP, "192.168.0.0/16") or ipv4_is_in_range(RemoteIP, "169.254.0.0/16") or ipv4_is_in_range(RemoteIP, "::1/128") or ipv4_is_in_range(RemoteIP, "fe80::/10") or ipv4_is_in_range(RemoteIP, "fc00::/7"))))