// Title: Network Connection Initiated By Regsvr32.EXE
// Author: Dmitriy Lifanov, oscd.community
// Date: 2019-10-25
// Level: medium
// Description: Detects a network connection initiated by "Regsvr32.exe"
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1559.001, attack.defense-evasion, attack.t1218.010
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_regsvr32_network_activity.yml

DeviceNetworkEvents
| where InitiatingProcessFolderPath endswith "\\regsvr32.exe"