// Title: Communication To Ngrok Tunneling Service Initiated
// Author: Florian Roth (Nextron Systems)
// Date: 2022-11-03
// Level: high
// Description: Detects an executable initiating a network connection to "ngrok" tunneling domains.
// Attackers were seen using this "ngrok" in order to store their second stage payloads and malware.
// While communication with such domains can be legitimate, often times is a sign of either data exfiltration by malicious actors or additional download.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.command-and-control, attack.t1567, attack.t1568.002, attack.t1572, attack.t1090, attack.t1102, attack.s0508
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_domain_ngrok_tunnel.yml
// False Positives:
//   - Legitimate use of the ngrok service.

DeviceNetworkEvents
| where RemoteUrl contains "tunnel.us.ngrok.com" or RemoteUrl contains "tunnel.eu.ngrok.com" or RemoteUrl contains "tunnel.ap.ngrok.com" or RemoteUrl contains "tunnel.au.ngrok.com" or RemoteUrl contains "tunnel.sa.ngrok.com" or RemoteUrl contains "tunnel.jp.ngrok.com" or RemoteUrl contains "tunnel.in.ngrok.com"