// Title: Network Connection Initiated To Cloudflared Tunnels Domains
// Author: Kamran Saifullah, Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-05-27
// Level: medium
// Description: Detects network connections to Cloudflared tunnels domains initiated by a process on the system.
// Attackers can abuse that feature to establish a reverse shell or persistence on a machine.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.command-and-control, attack.t1567, attack.t1572
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_domain_cloudflared_communication.yml
// False Positives:
//   - Legitimate use of cloudflare tunnels will also trigger this.

DeviceNetworkEvents
| where RemoteUrl endswith ".v2.argotunnel.com" or RemoteUrl endswith "protocol-v2.argotunnel.com" or RemoteUrl endswith "trycloudflare.com" or RemoteUrl endswith "update.argotunnel.com"