// Title: Network Connection Initiated via Finger.EXE
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-11-19
// Level: high
// Description: Detects network connections via finger.exe, which can be abused by threat actors to retrieve remote commands for execution on Windows devices.
// In one ClickFix malware campaign, adversaries leveraged the finger protocol to fetch commands from a remote server.
// Since the finger utility is not commonly used in modern Windows environments, its presence already raises suspicion.
// Investigating such network connections can also help identify potential malicious infrastructure used by threat actors
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1071.004, attack.execution, attack.t1059.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_finger.yml
// False Positives:
//   - Unlikely

DeviceNetworkEvents
| where InitiatingProcessFolderPath endswith "\\finger.exe"