// Title: Process Initiated Network Connection To Ngrok Domain
// Author: Florian Roth (Nextron Systems)
// Date: 2022-07-16
// Level: high
// Description: Detects an executable initiating a network connection to "ngrok" domains.
// Attackers were seen using this "ngrok" in order to store their second stage payloads and malware.
// While communication with such domains can be legitimate, often times is a sign of either data exfiltration by malicious actors or additional download.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.command-and-control, attack.t1567, attack.t1572, attack.t1102
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_domain_ngrok.yml
// False Positives:
//   - Legitimate use of the ngrok service.

DeviceNetworkEvents
| where RemoteUrl endswith ".ngrok-free.app" or RemoteUrl endswith ".ngrok-free.dev" or RemoteUrl endswith ".ngrok.app" or RemoteUrl endswith ".ngrok.dev" or RemoteUrl endswith ".ngrok.io"