// Title: RDP Over Reverse SSH Tunnel
// Author: Samir Bousseaden
// Date: 2019-02-16
// Level: high
// Description: Detects svchost hosting RDP termsvcs communicating with the loopback address and on TCP port 3389
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1572, attack.lateral-movement, attack.t1021.001, car.2013-07-002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_rdp_reverse_tunnel.yml

DeviceNetworkEvents
| where (ipv4_is_in_range(RemoteIP, "127.0.0.0/8") or ipv4_is_in_range(RemoteIP, "::1/128")) and (InitiatingProcessFolderPath endswith "\\svchost.exe" and LocalPort == 3389)