// Title: Remote Access Tool - AnyDesk Incoming Connection
// Author: @d4ns4n_ (Wuerth-Phoenix)
// Date: 2024-09-02
// Level: medium
// Description: Detects incoming connections to AnyDesk. This could indicate a potential remote attacker trying to connect to a listening instance of AnyDesk and use it as potential command and control channel.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.command-and-control, attack.t1219.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_remote_access_tools_anydesk_incoming_connection.yml
// False Positives:
//   - Legitimate incoming connections (e.g. sysadmin activity). Most of the time I would expect outgoing connections (initiated locally).

DeviceNetworkEvents
| where InitiatingProcessFolderPath endswith "\\AnyDesk.exe" or InitiatingProcessFolderPath endswith "\\AnyDeskMSI.exe"