// Title: Silenttrinity Stager Msbuild Activity
// Author: Kiran kumar s, oscd.community
// Date: 2020-10-11
// Level: high
// Description: Detects a possible remote connections to Silenttrinity c2
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, attack.t1127.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_silenttrinity_stager_msbuild_activity.yml

DeviceNetworkEvents
| where InitiatingProcessFolderPath endswith "\\msbuild.exe" and (RemotePort in~ ("80", "443"))