// Title: Network Connection Initiated To Mega.nz
// Author: Florian Roth (Nextron Systems)
// Date: 2021-12-06
// Level: low
// Description: Detects a network connection initiated by a binary to "api.mega.co.nz".
// Attackers were seen abusing file sharing websites similar to "mega.nz" in order to upload/download additional payloads.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.t1567.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_domain_mega_nz.yml
// False Positives:
//   - Legitimate MEGA installers and utilities are expected to communicate with this domain. Exclude hosts that are known to be allowed to use this tool.

DeviceNetworkEvents
| where RemoteUrl endswith "mega.co.nz" or RemoteUrl endswith "mega.nz"