// Title: Network Connection Initiated To BTunnels Domains
// Author: Kamran Saifullah
// Date: 2024-09-13
// Level: medium
// Description: Detects network connections to BTunnels domains initiated by a process on the system.
// Attackers can abuse that feature to establish a reverse shell or persistence on a machine.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.command-and-control, attack.t1567, attack.t1572
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_domain_btunnels.yml
// False Positives:
//   - Legitimate use of BTunnels will also trigger this.

DeviceNetworkEvents
| where RemoteUrl endswith ".btunnel.co.in"