// Title: Suspicious Wordpad Outbound Connections
// Author: X__Junior (Nextron Systems)
// Date: 2023-07-12
// Level: medium
// Description: Detects a network connection initiated by "wordpad.exe" over uncommon destination ports.
// This might indicate potential process injection activity from a beacon or similar mechanisms.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.command-and-control
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_wordpad_uncommon_ports.yml
// False Positives:
//   - Other ports can be used, apply additional filters accordingly

DeviceNetworkEvents
| where InitiatingProcessFolderPath endswith "\\wordpad.exe" and (not((RemotePort in~ ("80", "139", "443", "445", "465", "587", "993", "995"))))