// Title: Suspicious Dropbox API Usage
// Author: Florian Roth (Nextron Systems)
// Date: 2022-04-20
// Level: high
// Description: Detects an executable that isn't dropbox but communicates with the Dropbox API
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.exfiltration, attack.t1105, attack.t1567.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_domain_dropbox_api.yml
// False Positives:
//   - Legitimate use of the API with a tool that the author wasn't aware of

DeviceNetworkEvents
| where (RemoteUrl endswith "api.dropboxapi.com" or RemoteUrl endswith "content.dropboxapi.com") and (not(InitiatingProcessFolderPath contains "\\Dropbox"))