// Title: Network Connection Initiated By AddinUtil.EXE
// Author: Michael McKinley (@McKinleyMike), Tony Latteri (@TheLatteri)
// Date: 2023-09-18
// Level: high
// Description: Detects a network connection initiated by the Add-In deployment cache updating utility "AddInutil.exe".
// This could indicate a potential command and control communication as this tool doesn't usually initiate network activity.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_addinutil_initiated.yml

DeviceNetworkEvents
| where InitiatingProcessFolderPath endswith "\\addinutil.exe"