// Title: Network Connection Initiated Via Notepad.EXE
// Author: EagleEye Team
// Date: 2020-05-14
// Level: high
// Description: Detects a network connection that is initiated by the "notepad.exe" process.
// This might be a sign of process injection from a beacon process or something similar.
// Notepad rarely initiates a network communication except when printing documents for example.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.command-and-control, attack.execution, attack.defense-evasion, attack.t1055
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_notepad.yml
// False Positives:
//   - Printing documents via notepad might cause communication with the printer via port 9100 or similar.

DeviceNetworkEvents
| where InitiatingProcessFolderPath endswith "\\notepad.exe" and (not(RemotePort == 9100))