// Title: Suspicious Outbound SMTP Connections
// Author: frack113
// Date: 2022-01-07
// Level: medium
// Description: Adversaries may steal data by exfiltrating it over an un-encrypted network protocol other than that of the existing command and control channel.
// The data may also be sent to an alternate network location from the main command and control server.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.t1048.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_susp_outbound_smtp_connections.yml
// False Positives:
//   - Other SMTP tools

DeviceNetworkEvents
| where (RemotePort in~ ("25", "587", "465", "2525")) and (not(((InitiatingProcessFolderPath endswith "\\thunderbird.exe" or InitiatingProcessFolderPath endswith "\\outlook.exe") or InitiatingProcessFolderPath startswith "C:\\Program Files\\Microsoft\\Exchange Server\\" or (InitiatingProcessFolderPath endswith "\\HxTsr.exe" and InitiatingProcessFolderPath startswith "C:\\Program Files\\WindowsApps\\microsoft.windowscommunicationsapps_"))))