// Title: Network Connection Initiated To Visual Studio Code Tunnels Domain
// Author: Kamran Saifullah
// Date: 2023-11-20
// Level: medium
// Description: Detects network connections to Visual Studio Code tunnel domains initiated by a process on a system. Attackers can abuse that feature to establish a reverse shell or persistence on a machine.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.command-and-control, attack.t1567, attack.t1572
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/network_connection/net_connection_win_domain_vscode_tunnel_connection.yml
// False Positives:
//   - Legitimate use of Visual Studio Code tunnel will also trigger this.

DeviceNetworkEvents
| where RemoteUrl endswith ".tunnels.api.visualstudio.com"