// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/09/11
// Level: medium
// Description: Detects calls to the "terminate" function via wmic in order to kill an application
// Tags: attack.execution, attack.t1047
DeviceProcessEvents
| where (ProcessCommandLine contains "call" and ProcessCommandLine contains "terminate") and (FolderPath endswith "\\WMIC.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")