// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/06/10
// Level: medium
// Description: Detects execution of the Notepad++ updater (gup) to launch other commands or executables
// Tags: attack.execution
DeviceProcessEvents
| where (FolderPath endswith "\\explorer.exe" and InitiatingProcessFolderPath endswith "\\gup.exe") and (not(((ProcessCommandLine contains "\\Notepad++\\notepad++.exe" and FolderPath endswith "\\explorer.exe") or isnull(ProcessCommandLine) or InitiatingProcessFolderPath contains "\\Notepad++\\updater\\")))