// Author: Swachchhanda Shrawan Poudel
// Date: 2023/11/09
// Level: high
// Description: Detects usage of "IMEWDBLD.exe" to download arbitrary files
// Tags: attack.defense_evasion, attack.execution, attack.t1218
DeviceProcessEvents
| where (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://") and (FolderPath endswith "\\IMEWDBLD.exe" or ProcessVersionInfoOriginalFileName =~ "imewdbld.exe")