// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/04/06
// Level: medium
// Description: Detects password change for the computer's domain account or host principal via "ksetup.exe"
// Tags: attack.execution
DeviceProcessEvents
| where ProcessCommandLine contains " /setcomputerpassword " and (FolderPath endswith "\\ksetup.exe" or ProcessVersionInfoOriginalFileName =~ "ksetup.exe")