// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/09/08
// Level: medium
// Description: Detects execution of wmic utility with the "computersystem" flag in order to obtain information about the machine such as the domain, username, model, etc.
// Tags: attack.discovery, attack.execution, attack.t1047
DeviceProcessEvents
| where ProcessCommandLine contains "computersystem" and (FolderPath endswith "\\wmic.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")