// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/10/18
// Level: high
// Description: Detects when a user downloads a file from an IP based URL using CertOC.exe
// Tags: attack.command_and_control, attack.execution, attack.t1105
DeviceProcessEvents
| where ProcessCommandLine contains "-GetCACAPS" and (FolderPath endswith "\\certoc.exe" or ProcessVersionInfoOriginalFileName =~ "CertOC.exe") and ProcessCommandLine matches regex "://[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}"