// Author: Tim Rauch, Elastic, E.M. Anhaus (originally from Atomic Blue Detections, Endgame), oscd.community
// Date: 2022/06/14
// Level: medium
// Description: Detects the execution of "forfiles" with the "/c" flag.
While this is an expected behavior of the tool, it can be abused in order to proxy execution through it with any binary.
Can be used to bypass application whitelisting.

// Tags: attack.execution, attack.t1059
DeviceProcessEvents
| where (ProcessCommandLine contains " -c " or ProcessCommandLine contains " /c ") and (FolderPath endswith "\\forfiles.exe" or ProcessVersionInfoOriginalFileName =~ "forfiles.exe")