// Author: wagga, Jonhnathan Ribeiro, oscd.community
// Date: 2020/01/12
// Level: high
// Description: Detects command line parameters used by Koadic hack tool
// Tags: attack.execution, attack.t1059.003, attack.t1059.005, attack.t1059.007
DeviceProcessEvents
| where (ProcessCommandLine contains "/q" and ProcessCommandLine contains "/c" and ProcessCommandLine contains "chcp") and (FolderPath endswith "\\cmd.exe" or ProcessVersionInfoOriginalFileName =~ "Cmd.Exe")