// Author: Jonathan Cheong, oscd.community
// Date: 2020/10/13
// Level: high
// Description: Detects Obfuscated use of Clip.exe to execute PowerShell
// Tags: attack.defense_evasion, attack.t1027, attack.execution, attack.t1059.001
DeviceProcessEvents
| where (ProcessCommandLine contains "/c" or ProcessCommandLine contains "/r") and (ProcessCommandLine contains "cmd" and ProcessCommandLine contains "&&" and ProcessCommandLine contains "clipboard]::" and ProcessCommandLine contains "-f")