// Author: Jonathan Cheong, oscd.community
// Date: 2020/10/15
// Level: high
// Description: Detects Obfuscated use of Environment Variables to execute PowerShell
// Tags: attack.defense_evasion, attack.t1027, attack.execution, attack.t1059.001
DeviceProcessEvents
| where ProcessCommandLine matches regex "cmd.{0,5}(?:/c|/r)(?:\\s|)\\"set\\s[a-zA-Z]{3,6}.*(?:\\{\\d\\}){1,}\\\\\\"\\s+?\\-f(?:.*\\)){1,}.*\\""