// Author: @2xxeformyshirt (Security Risk Advisors) - rule; Teymur Kheirkhabarov (idea)
// Date: 2020/03/04
// Level: high
// Description: Detects MMC20.Application Lateral Movement; specifically looks for the spawning of the parent MMC.exe with a command line of "-Embedding" as a child of svchost.exe
// Tags: attack.execution, attack.t1021.003
DeviceProcessEvents
| where ProcessCommandLine contains "-Embedding" and FolderPath endswith "\\mmc.exe" and InitiatingProcessFolderPath endswith "\\svchost.exe"