// Author: EagleEye Team
// Date: 2020/05/14
// Level: high
// Description: Detects a network connection that is initiated by the "notepad.exe" process.
This might be a sign of process injection from a beacon process or something similar.
Notepad rarely initiates a network communication except when printing documents for example.

// Tags: attack.command_and_control, attack.execution, attack.defense_evasion, attack.t1055
DeviceNetworkEvents
| where InitiatingProcessFolderPath endswith "\\notepad.exe" and (not(RemotePort == 9100))