// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/07/27
// Level: medium
// Description: Detects execution of "curl.exe" with the "-c" flag in order to save cookie data.
// Tags: attack.execution
DeviceProcessEvents
| where (ProcessCommandLine matches regex "\\s-c\\s" or ProcessCommandLine contains "--cookie-jar") and (FolderPath endswith "\\curl.exe" or ProcessVersionInfoOriginalFileName =~ "curl.exe")