// Author: X__Junior (Nextron Systems)
// Date: 2023/06/30
// Level: medium
// Description: Detects execution of "WerFault.exe" with the "-pr" commandline flag that is used to run files stored in the ReflectDebugger key which could be used to store the path to the malware in order to masquerade the execution flow
// Tags: attack.execution, attack.defense_evasion, attack.t1036
DeviceProcessEvents
| where ProcessCommandLine contains " -pr " and (FolderPath endswith "\\WerFault.exe" or ProcessVersionInfoOriginalFileName =~ "WerFault.exe")