// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/06/20
// Level: medium
// Description: Detects known WMI recon method to look for unquoted service paths using wmic. Often used by pentester and attacker enumeration scripts
// Tags: attack.execution, attack.t1047
DeviceProcessEvents
| where (ProcessCommandLine contains " service get " and ProcessCommandLine contains "name,displayname,pathname,startmode") and (ProcessVersionInfoOriginalFileName =~ "wmic.exe" or FolderPath endswith "\\WMIC.exe")