// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/22
// Level: high
// Description: Detects when 'DllRegisterServer' is called in the commandline and the image is not rundll32. This could mean that the 'rundll32' utility has been renamed in order to avoid detection
// Tags: attack.execution
DeviceProcessEvents
| where ProcessCommandLine contains "DllRegisterServer" and (not(FolderPath endswith "\\rundll32.exe"))