// Author: X__Junior (Nextron Systems)
// Date: 2023/06/20
// Level: medium
// Description: Detects potential "ShellDispatch.dll" functionality abuse to execute arbitrary binaries via "ShellExecute"
// Tags: attack.execution, attack.defense_evasion
DeviceProcessEvents
| where ProcessCommandLine contains "RunDll_ShellExecuteW" and (FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE")