// Author: xknow @xknow_infosec, Tim Shelton
// Date: 2020/06/11
// Level: high
// Description: Detects potential path traversal attempt via cmd.exe. Could indicate possible command/argument confusion/hijacking
// Tags: attack.execution, attack.t1059.003
DeviceProcessEvents
| where (((InitiatingProcessCommandLine contains "/c" or InitiatingProcessCommandLine contains "/k" or InitiatingProcessCommandLine contains "/r") or (ProcessCommandLine contains "/c" or ProcessCommandLine contains "/k" or ProcessCommandLine contains "/r")) and (InitiatingProcessFolderPath endswith "\\cmd.exe" or FolderPath endswith "\\cmd.exe" or ProcessVersionInfoOriginalFileName =~ "cmd.exe") and (InitiatingProcessCommandLine =~ "/../../" or ProcessCommandLine contains "/../../")) and (not(ProcessCommandLine contains "\\Tasktop\\keycloak\\bin\\/../../jre\\bin\\java"))