// Author: Nasreddine Bencherchali (Nextron Systems), Thurein Oo
// Date: 2023/10/18
// Level: low
// Description: Detects the enabling of the PowerShell script execution policy. Once enabled, this policy allows scripts to be executed.
// Tags: attack.execution
DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000001)" and RegistryKey endswith "\\Policies\\Microsoft\\Windows\\PowerShell\\EnableScripts"