// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/06/15
// Level: medium
// Description: Detects the execution of "lodctr.exe" to rebuild the performance counter registry values. This can be abused by attackers by providing a malicious config file to overwrite performance counter configuration to confuse and evade monitoring and security solutions.
// Tags: attack.execution
DeviceProcessEvents
| where (ProcessCommandLine contains " -r" or ProcessCommandLine contains " /r") and (FolderPath endswith "\\lodctr.exe" and ProcessVersionInfoOriginalFileName =~ "LODCTR.EXE")