// Author: Ali Alwashali
// Date: 2023/10/10
// Level: low
// Description: Detects the execution of a system command via the ScreenConnect RMM service.
// Tags: attack.execution, attack.t1059.003
DeviceProcessEvents
| where ProcessCommandLine contains "\\TEMP\\ScreenConnect\\" and (FolderPath endswith "\\cmd.exe" or ProcessVersionInfoOriginalFileName =~ "Cmd.Exe") and InitiatingProcessFolderPath endswith "\\ScreenConnect.ClientService.exe"