// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/02/14
// Level: medium
// Description: An adversary might use WMI to check if a certain remote service is running on a remote device.
When the test completes, a service information will be displayed on the screen if it exists.
A common feedback message is that "No instance(s) Available" if the service queried is not running.
A common error message is "Node - (provided IP or default) ERROR Description =The RPC server is unavailable" if the provided remote host is unreachable

// Tags: attack.execution, attack.t1047
DeviceProcessEvents
| where ProcessCommandLine contains "service" and (FolderPath endswith "\\WMIC.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")