// Author: Timur Zinniatullin, Daniil Yugoslavskiy, oscd.community
// Date: 2019/10/21
// Level: low
// Description: Detects the usage of the "net.exe" command to start a service using the "start" flag
// Tags: attack.execution, attack.t1569.002
DeviceProcessEvents
| where ProcessCommandLine contains " start " and ((FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe") or (ProcessVersionInfoOriginalFileName in~ ("net.exe", "net1.exe")))