// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/09/09
// Level: high
// Description: Detects scheduled task creations or modification on a suspicious schedule type
// Tags: attack.execution, attack.t1053.005
DeviceProcessEvents
| where ((FolderPath endswith "\\schtasks.exe" or ProcessVersionInfoOriginalFileName =~ "schtasks.exe") and (ProcessCommandLine contains " ONLOGON " or ProcessCommandLine contains " ONSTART " or ProcessCommandLine contains " ONCE " or ProcessCommandLine contains " ONIDLE ")) and (not((ProcessCommandLine contains "NT AUT" or ProcessCommandLine contains " SYSTEM" or ProcessCommandLine contains "HIGHEST")))