// Author: pH-T (Nextron Systems), Nasreddine Bencherchali
// Date: 2022/03/15
// Level: high
// Description: Detects the creation of a schtask that executes a file from C:\Users\<USER>\AppData\Local
// Tags: attack.execution, attack.persistence, attack.t1053.005, attack.t1059.001
DeviceProcessEvents
| where ((ProcessCommandLine contains "NT AUT" or ProcessCommandLine contains " SYSTEM ") and (ProcessCommandLine contains "/Create" and ProcessCommandLine contains "/RU" and ProcessCommandLine contains "/TR" and ProcessCommandLine contains "C:\\Users\\" and ProcessCommandLine contains "\\AppData\\Local\\") and FolderPath endswith "\\schtasks.exe") and (not((ProcessCommandLine contains "/TN TVInstallRestore" and FolderPath endswith "\\schtasks.exe" and (InitiatingProcessFolderPath contains "\\AppData\\Local\\Temp\\" and InitiatingProcessFolderPath contains "TeamViewer_.exe"))))