// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/10/13
// Level: medium
// Description: Detects an svchost process spawning an instance of an office application. This happens when the initial word application creates an instance of one of the Office COM objects such as 'Word.Application', 'Excel.Application', etc.
This can be used by malicious actors to create malicious Office documents with macros on the fly. (See vba2clr project in the references)

// Tags: attack.execution, attack.defense_evasion
DeviceProcessEvents
| where (FolderPath endswith "\\winword.exe" or FolderPath endswith "\\excel.exe" or FolderPath endswith "\\powerpnt.exe" or FolderPath endswith "\\msaccess.exe" or FolderPath endswith "\\mspub.exe" or FolderPath endswith "\\eqnedt32.exe" or FolderPath endswith "\\visio.exe") and InitiatingProcessFolderPath endswith "\\svchost.exe"