// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/02/08
// Level: high
// Description: Detects execution of the built-in script located in "C:\Windows\System32\gatherNetworkInfo.vbs". Which can be used to gather information about the target machine
// Tags: attack.discovery, attack.execution, attack.t1615, attack.t1059.005
DeviceProcessEvents
| where ProcessCommandLine contains "gatherNetworkInfo.vbs" and (not((FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\wscript.exe")))