// Author: Stephen Lincoln `@slincoln-aiq`(AttackIQ)
// Date: 2024/02/02
// Level: medium
// Description: An adversary might use WMI to discover information about the system, such as the volume name, size,
free space, and other disk information. This can be done using the `wmic` command-line utility and has been
observed being used by threat actors such as Volt Typhoon.

// Tags: attack.execution, attack.discovery, attack.t1047, attack.t1082
DeviceProcessEvents
| where (ProcessCommandLine contains "volume" or ProcessCommandLine contains "path win32_logicaldisk") and (FolderPath endswith "\\WMIC.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")