// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/07/03
// Level: high
// Description: Detects the creation of a file by "dllhost.exe" in System32 directory part of "IDiagnosticProfileUAC" UAC bypass technique
// Tags: attack.execution, attack.defense_evasion, attack.privilege_escalation, attack.t1548.002
DeviceFileEvents
| where InitiatingProcessFolderPath endswith "\\DllHost.exe" and FolderPath endswith ".dll" and FolderPath startswith "C:\\Windows\\System32\\"