// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/07/01
// Level: medium
// Description: The "ScriptRunner.exe" binary can be abused to proxy execution through it and bypass possible whitelisting
// Tags: attack.defense_evasion, attack.execution, attack.t1218
DeviceProcessEvents
| where ProcessCommandLine contains " -appvscript " and (FolderPath endswith "\\ScriptRunner.exe" or ProcessVersionInfoOriginalFileName =~ "ScriptRunner.exe")