// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/06/16
// Level: medium
// Description: Detects usage of OpenConsole binary as a LOLBIN to launch other binaries to bypass application Whitelisting
// Tags: attack.execution, attack.t1059
DeviceProcessEvents
| where (ProcessVersionInfoOriginalFileName =~ "OpenConsole.exe" or FolderPath endswith "\\OpenConsole.exe") and (not(FolderPath startswith "C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal"))