// Author: Christopher Peacock @SecurePeacock, SCYTHE @scythe_io
// Date: 2022/06/02
// Level: medium
// Description: Detects the execution of FSharp Interpreters "FsiAnyCpu.exe" and "FSi.exe"
Both can be used for AWL bypass and to execute F# code via scripts or inline.

// Tags: attack.execution, attack.t1059
DeviceProcessEvents
| where (FolderPath endswith "\\fsi.exe" or FolderPath endswith "\\fsianycpu.exe") or (ProcessVersionInfoOriginalFileName in~ ("fsi.exe", "fsianycpu.exe"))