// Author: Christopher Peacock @SecurePeacock, SCYTHE @scythe_io
// Date: 2022/06/02
// Level: medium
// Description: The FSharp Interpreters, FsiAnyCpu.exe and FSi.exe, can be used for AWL bypass and is listed in Microsoft recommended block rules.
// Tags: attack.execution, attack.t1059
DeviceProcessEvents
| where FolderPath endswith "\\fsianycpu.exe" or ProcessVersionInfoOriginalFileName =~ "fsianycpu.exe" or FolderPath endswith "\\fsi.exe" or ProcessVersionInfoOriginalFileName =~ "fsi.exe"