// Author: behops, Bhabesh Raj
// Date: 2021/10/08
// Level: high
// Description: Detects suspicious child process creations of VMware Tools process which may indicate persistence setup
// Tags: attack.execution, attack.persistence, attack.t1059
DeviceProcessEvents
| where (((FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\regsvr32.exe" or FolderPath endswith "\\wscript.exe" or FolderPath endswith "\\cscript.exe") or (ProcessVersionInfoOriginalFileName in~ ("Cmd.Exe", "PowerShell.EXE", "pwsh.dll", "RUNDLL32.EXE", "REGSVR32.EXE", "wscript.exe", "cscript.exe"))) and InitiatingProcessFolderPath endswith "\\vmtoolsd.exe") and (not((ProcessCommandLine contains "\\VMware\\VMware Tools\\poweron-vm-default.bat" or ProcessCommandLine contains "\\VMware\\VMware Tools\\poweroff-vm-default.bat" or ProcessCommandLine contains "\\VMware\\VMware Tools\\resume-vm-default.bat" or ProcessCommandLine contains "\\VMware\\VMware Tools\\suspend-vm-default.bat")))