// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/09/14
// Level: medium
// Description: Detects weak passwords or often abused passwords (seen used by threat actors) via the CLI. An example would be a threat actor creating a new user via the net command and providing the password inline
// Tags: attack.defense_evasion, attack.execution
DeviceProcessEvents
| where ProcessCommandLine contains "Asd123.aaaa" or ProcessCommandLine contains "password123" or ProcessCommandLine contains "123456789" or ProcessCommandLine contains "P@ssw0rd!"