// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/31
// Level: medium
// Description: Detects the presence of the keywords "Wscript", "Shell" and "Run" in the command, which could indicate a suspicious activity
// Tags: attack.execution, attack.t1059
DeviceProcessEvents
| where ProcessCommandLine contains "Wscript." and ProcessCommandLine contains ".Shell" and ProcessCommandLine contains ".Run"