// Title: File Download Via Bitsadmin
// Author: Michael Haag, FPT.EagleEye
// Date: 2017-03-09
// Level: medium
// Description: Detects usage of bitsadmin downloading a file
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.persistence, attack.t1197, attack.s0190, attack.t1036.003, attack.command-and-control, attack.t1105
// False Positives:
//   - Some legitimate apps use this, but limited.

DeviceProcessEvents
| where (FolderPath endswith "\\bitsadmin.exe" or ProcessVersionInfoOriginalFileName =~ "bitsadmin.exe") and (ProcessCommandLine contains " /transfer " or ((ProcessCommandLine contains " /create " or ProcessCommandLine contains " /addfile ") and ProcessCommandLine contains "http"))