// Title: Execution via WorkFolders.exe
// Author: Maxime Thiebaut (@0xThiebaut)
// Date: 2021-10-21
// Level: high
// Description: Detects using WorkFolders.exe to execute an arbitrary control.exe
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_workfolders.yml
// False Positives:
//   - Legitimate usage of the uncommon Windows Work Folders feature.

DeviceProcessEvents
| where (FolderPath endswith "\\control.exe" and InitiatingProcessFolderPath endswith "\\WorkFolders.exe") and (not(FolderPath =~ "C:\\Windows\\System32\\control.exe"))