// Title: Remote Access Tool - Renamed MeshAgent Execution - Windows
// Author: Norbert Jaśniewicz (AlphaSOC)
// Date: 2025-05-19
// Level: high
// Description: Detects the execution of a renamed instance of the Remote Monitoring and Management (RMM) tool, MeshAgent.
// RMM tools such as MeshAgent are commonly utilized by IT administrators for legitimate remote support and system management.
// However, malicious actors may exploit these tools by renaming them to bypass detection mechanisms, enabling unauthorized access and control over compromised systems.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.defense-evasion, attack.t1219.002, attack.t1036.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_remote_access_tools_renamed_meshagent_execution.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "--meshServiceName" or ProcessVersionInfoOriginalFileName contains "meshagent") and (not(FolderPath endswith "\\meshagent.exe"))