// Title: HackTool - PurpleSharp Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2021-06-18
// Level: critical
// Description: Detects the execution of the PurpleSharp adversary simulation tool
// MITRE Tactic: Resource Development
// Tags: attack.t1587, attack.resource-development
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_purplesharp_indicators.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (ProcessCommandLine contains "xyz123456.exe" or ProcessCommandLine contains "PurpleSharp") or (FolderPath contains "\\purplesharp" or ProcessVersionInfoOriginalFileName =~ "PurpleSharp.exe")