// Title: Visual Studio Code Tunnel Service Installation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-10-25
// Level: medium
// Description: Detects the installation of VsCode tunnel (code-tunnel) as a service.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1071.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_vscode_tunnel_service_install.yml
// False Positives:
//   - Legitimate installation of code-tunnel as a service

DeviceProcessEvents
| where ProcessCommandLine contains "tunnel " and ProcessCommandLine contains "service" and ProcessCommandLine contains "internal-run" and ProcessCommandLine contains "tunnel-service.log"