// Title: ConvertTo-SecureString Cmdlet Usage Via CommandLine
// Author: Teymur Kheirkhabarov (idea), Vasiliy Burov (rule), oscd.community, Tim Shelton
// Date: 2020-10-11
// Level: medium
// Description: Detects usage of the "ConvertTo-SecureString" cmdlet via the commandline. Which is fairly uncommon and could indicate potential suspicious activity
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_cmdline_convertto_securestring.yml
// False Positives:
//   - Legitimate use to pass password to different powershell commands

DeviceProcessEvents
| where ProcessCommandLine contains "ConvertTo-SecureString" and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")))