// Title: User Discovery And Export Via Get-ADUser Cmdlet
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-09
// Level: medium
// Description: Detects usage of the Get-ADUser cmdlet to collect user information and output it to a file
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1033
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_user_discovery_get_aduser.yml
// False Positives:
//   - Legitimate admin scripts may use the same technique, it's better to exclude specific computers or users who execute these commands or scripts often

DeviceProcessEvents
| where ((ProcessCommandLine contains " > " or ProcessCommandLine contains " | Select " or ProcessCommandLine contains "Out-File" or ProcessCommandLine contains "Set-Content" or ProcessCommandLine contains "Add-Content") and (ProcessCommandLine contains "Get-ADUser " and ProcessCommandLine contains " -Filter *")) and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")))