// Title: Gpresult Display Group Policy Information
// Author: frack113
// Date: 2022-05-01
// Level: medium
// Description: Detects cases in which a user uses the built-in Windows utility gpresult to display the Resultant Set of Policy (RSoP) information
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1615
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_gpresult_execution.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "/z" or ProcessCommandLine contains "/v") and FolderPath endswith "\\gpresult.exe"