// Title: Suspicious Driver Install by pnputil.exe
// Author: Hai Vaknin @LuxNoBulIshit, Avihay eldad  @aloneliassaf, Austin Songer @austinsonger
// Date: 2021-09-30
// Level: medium
// Description: Detects when a possible suspicious driver is being installed via pnputil.exe lolbin
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_susp_driver_installed_by_pnputil.yml
// False Positives:
//   - Pnputil.exe being used may be performed by a system administrator.
//   - Verify whether the user identity, user agent, and/or hostname should be making changes in your environment.
//   - Pnputil.exe being executed from unfamiliar users should be investigated. If known behavior is causing false positives, it can be exempted from the rule.

DeviceProcessEvents
| where (ProcessCommandLine contains "-i" or ProcessCommandLine contains "/install" or ProcessCommandLine contains "-a" or ProcessCommandLine contains "/add-driver" or ProcessCommandLine contains ".inf") and FolderPath endswith "\\pnputil.exe"