// Title: Potential RDP Tunneling Via SSH
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-12
// Level: high
// Description: Execution of ssh.exe to perform data exfiltration and tunneling through RDP
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1572
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_ssh_rdp_tunneling.yml

DeviceProcessEvents
| where ProcessCommandLine contains ":3389" and FolderPath endswith "\\ssh.exe"