// Title: Suspicious Download from Office Domain
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2021-12-27
// Level: high
// Description: Detects suspicious ways to download files from Microsoft domains that are used to store attachments in Emails or OneNote documents
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.resource-development, attack.t1105, attack.t1608
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_download_office_domain.yml
// False Positives:
//   - Scripts or tools that download attachments from these domains (OneNote, Outlook 365)

DeviceProcessEvents
| where (ProcessCommandLine contains "https://attachment.outlook.live.net/owa/" or ProcessCommandLine contains "https://onenoteonlinesync.onenote.com/onenoteonlinesync/") and ((FolderPath endswith "\\curl.exe" or FolderPath endswith "\\wget.exe") or (ProcessCommandLine contains "Invoke-WebRequest" or ProcessCommandLine contains "iwr " or ProcessCommandLine contains "curl " or ProcessCommandLine contains "wget " or ProcessCommandLine contains "Start-BitsTransfer" or ProcessCommandLine contains ".DownloadFile(" or ProcessCommandLine contains ".DownloadString("))