// Title: IIS Native-Code Module Command Line Installation
// Author: Florian Roth (Nextron Systems)
// Date: 2019-12-11
// Level: medium
// Description: Detects suspicious IIS native-code module installations via command line
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1505.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_iis_appcmd_susp_module_install.yml
// False Positives:
//   - Unknown as it may vary from organisation to organisation how admins use to install IIS modules

DeviceProcessEvents
| where (((ProcessCommandLine contains "install" and ProcessCommandLine contains "module") and (ProcessCommandLine contains "-name:" or ProcessCommandLine contains "/name:" or ProcessCommandLine contains "–name:" or ProcessCommandLine contains "—name:" or ProcessCommandLine contains "―name:")) and (FolderPath endswith "\\appcmd.exe" or ProcessVersionInfoOriginalFileName =~ "appcmd.exe")) and (not(InitiatingProcessFolderPath =~ "C:\\Windows\\System32\\inetsrv\\iissetup.exe"))