// Title: Rar Usage with Password and Compression Level
// Author: @ROxPinTeddy
// Date: 2020-05-12
// Level: high
// Description: Detects the use of rar.exe, on the command line, to create an archive with password protection or with a specific compression level. This is pretty indicative of malicious actions.
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1560.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_rar_compression_with_password.yml
// False Positives:
//   - Legitimate use of Winrar command line version
//   - Other command line tools, that use these flags

DeviceProcessEvents
| where ProcessCommandLine contains " -hp" and (ProcessCommandLine contains " -m" or ProcessCommandLine contains " a ")