// Title: Installation of WSL Kali-Linux
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-10-10
// Level: high
// Description: Detects installation of Kali Linux distribution through Windows Subsystem for Linux (WSL).
// Attackers may use Kali Linux WSL to leverage its penetration testing tools and capabilities for malicious purposes.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wsl_kali_linux_installation.yml
// False Positives:
//   - Legitimate installation or usage of Kali Linux WSL by administrators or security teams

DeviceProcessEvents
| where (FolderPath endswith "\\wsl.exe" or ProcessVersionInfoOriginalFileName =~ "wsl") and (ProcessCommandLine contains " --install " or ProcessCommandLine contains " -i ") and ProcessCommandLine contains "kali"