// Title: Execute Code with Pester.bat as Parent
// Author: frack113, Nasreddine Bencherchali
// Date: 2022-08-20
// Level: medium
// Description: Detects code execution via Pester.bat (Pester - Powershell Modulte for testing)
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.001, attack.defense-evasion, attack.t1216
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_pester.yml
// False Positives:
//   - Legitimate use of Pester for writing tests for Powershell scripts and modules

DeviceProcessEvents
| where (InitiatingProcessCommandLine contains "{ Invoke-Pester -EnableExit ;" or InitiatingProcessCommandLine contains "{ Get-Help \"") and (InitiatingProcessCommandLine contains "\\WindowsPowerShell\\Modules\\Pester\\" and (InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe"))