// Title: Start Windows Service Via Net.EXE
// Author: Timur Zinniatullin, Daniil Yugoslavskiy, oscd.community
// Date: 2019-10-21
// Level: low
// Description: Detects the usage of the "net.exe" command to start a service using the "start" flag
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1569.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_net_start_service.yml
// False Positives:
//   - Legitimate administrator or user executes a service for legitimate reasons.

DeviceProcessEvents
| where ProcessCommandLine contains " start " and ((FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe") or (ProcessVersionInfoOriginalFileName in~ ("net.exe", "net1.exe")))