// Title: Potential Network Sniffing Activity Using Network Tools
// Author: Timur Zinniatullin, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2019-10-21
// Level: medium
// Description: Detects potential network sniffing via use of network tools such as "tshark", "windump".
// Network sniffing refers to using the network interface on a system to monitor or capture information sent over a wired or wireless connection.
// An adversary may place a network interface into promiscuous mode to passively access data in transit over the network, or use span ports to capture a larger amount of data.
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.discovery, attack.t1040
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_network_sniffing.yml
// False Positives:
//   - Legitimate administration activity to troubleshoot network issues

DeviceProcessEvents
| where (ProcessCommandLine contains "-i" and FolderPath endswith "\\tshark.exe") or FolderPath endswith "\\windump.exe"