// Title: Potential Script Proxy Execution Via CL_Mutexverifiers.ps1
// Author: Nasreddine Bencherchali (Nextron Systems), oscd.community, Natalia Shornikova, frack113
// Date: 2022-05-21
// Level: medium
// Description: Detects the use of the Microsoft signed script "CL_mutexverifiers" to proxy the execution of additional PowerShell script commands
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1216
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_cl_mutexverifiers.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " -nologo -windowstyle minimized -file " and FolderPath endswith "\\powershell.exe" and (InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe")) and (ProcessCommandLine contains "\\AppData\\Local\\Temp\\" or ProcessCommandLine contains "\\Windows\\Temp\\")