// Title: PUA - Suspicious ActiveDirectory Enumeration Via AdFind.EXE
// Author: frack113
// Date: 2021-12-13
// Level: high
// Description: Detects active directory enumeration activity using known AdFind CLI flags
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1087.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_adfind_enumeration.yml
// False Positives:
//   - Authorized administrative activity

DeviceProcessEvents
| where ProcessCommandLine contains "-sc admincountdmp" or ProcessCommandLine contains "-sc exchaddresses" or (ProcessCommandLine contains "lockoutduration" or ProcessCommandLine contains "lockoutthreshold" or ProcessCommandLine contains "lockoutobservationwindow" or ProcessCommandLine contains "maxpwdage" or ProcessCommandLine contains "minpwdage" or ProcessCommandLine contains "minpwdlength" or ProcessCommandLine contains "pwdhistorylength" or ProcessCommandLine contains "pwdproperties")