// Title: Uncommon Child Process Of Defaultpack.EXE
// Author: frack113
// Date: 2022-12-31
// Level: medium
// Description: Detects uncommon child processes of "DefaultPack.EXE" binary as a proxy to launch other programs
// MITRE Tactic: Defense Evasion
// Tags: attack.t1218, attack.defense-evasion, attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_defaultpack_uncommon_child_process.yml

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\DefaultPack.exe"