// Title: Execute Pcwrun.EXE To Leverage Follina
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-13
// Level: high
// Description: Detects indirect command execution via Program Compatibility Assistant "pcwrun.exe" leveraging the follina (CVE-2022-30190) vulnerability
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218, attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_pcwrun_follina.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains "../" and FolderPath endswith "\\pcwrun.exe"