// Title: Proxy Execution via Vshadow
// Author: David Faiss
// Date: 2025-05-26
// Level: medium
// Description: Detects the invocation of vshadow.exe with the -exec parameter that executes a specified script or command after the shadow copies are created but before the VShadow tool exits.
// VShadow is a command-line tool that you can use to create and manage volume shadow copies. While legitimate backup or administrative scripts may use this flag,
// attackers can leverage this parameter to proxy the execution of malware.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1202
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_vshadow_exec.yml
// False Positives:
//   - System backup or administrator tools
//   - Legitimate administrative scripts

DeviceProcessEvents
| where ProcessCommandLine contains "-exec" and (FolderPath endswith "\\vshadow.exe" or ProcessVersionInfoOriginalFileName =~ "vshadow.exe")