// Title: Potential Meterpreter/CobaltStrike Activity
// Author: Teymur Kheirkhabarov, Ecco, Florian Roth
// Date: 2019-10-26
// Level: high
// Description: Detects the use of getsystem Meterpreter/Cobalt Strike command by detecting a specific service starting
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1134.001, attack.t1134.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_meterpreter_getsystem.yml
// False Positives:
//   - Commandlines containing components like cmd accidentally
//   - Jobs and services started with cmd

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\services.exe" and (((ProcessCommandLine contains "cmd" or ProcessCommandLine contains "%COMSPEC%") and (ProcessCommandLine contains "/c" and ProcessCommandLine contains "echo" and ProcessCommandLine contains "\\pipe\\")) or (ProcessCommandLine contains "rundll32" and ProcessCommandLine contains ".dll,a" and ProcessCommandLine contains "/p:")) and (not(ProcessCommandLine contains "MpCmdRun"))