// Title: Suspicious Execution of Shutdown to Log Out
// Author: frack113
// Date: 2022-10-01
// Level: medium
// Description: Detects the rare use of the command line tool shutdown to logoff a user
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1529
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_shutdown_logoff.yml

DeviceProcessEvents
| where ProcessCommandLine contains "/l" and FolderPath endswith "\\shutdown.exe"