// Title: PowerShell Get-Clipboard Cmdlet Via CLI
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2020-05-02
// Level: medium
// Description: Detects usage of the 'Get-Clipboard' cmdlet via CLI
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1115
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_get_clipboard.yml

DeviceProcessEvents
| where ProcessCommandLine contains "Get-Clipboard"