// Title: PUA - DIT Snapshot Viewer
// Author: Furkan Caliskan (@caliskanfurkan_)
// Date: 2020-07-04
// Level: high
// Description: Detects the use of Ditsnap tool, an inspection tool for Active Directory database, ntds.dit.
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_ditsnap.yml
// False Positives:
//   - Legitimate admin usage

DeviceProcessEvents
| where FolderPath endswith "\\ditsnap.exe" or ProcessCommandLine contains "ditsnap.exe"