// Title: Suspicious Diantz Download and Compress Into a CAB File
// Author: frack113
// Date: 2021-11-26
// Level: medium
// Description: Download and compress a remote file and store it in a cab file on local machine.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_diantz_remote_cab.yml

DeviceProcessEvents
| where ProcessCommandLine contains "diantz.exe" and ProcessCommandLine contains " \\\\" and ProcessCommandLine contains ".cab"