// Title: OpenWith.exe Executes Specified Binary
// Author: Beyu Denis, oscd.community (rule), @harr0ey (idea)
// Date: 2019-10-12
// Level: high
// Description: The OpenWith.exe executes other binary
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_openwith.yml

DeviceProcessEvents
| where ProcessCommandLine contains "/c" and FolderPath endswith "\\OpenWith.exe"