// Title: Suspicious Execution From Outlook Temporary Folder
// Author: Florian Roth (Nextron Systems)
// Date: 2019-10-01
// Level: high
// Description: Detects a suspicious program execution in Outlook temp folder
// MITRE Tactic: Initial Access
// Tags: attack.initial-access, attack.t1566.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_office_outlook_execution_from_temp.yml

DeviceProcessEvents
| where FolderPath contains "\\Temporary Internet Files\\Content.Outlook\\"