// Title: Potential DLL Injection Via AccCheckConsole
// Author: Florian Roth (Nextron Systems)
// Date: 2022-01-06
// Level: medium
// Description: Detects the execution "AccCheckConsole" a command-line tool for verifying the accessibility implementation of an application's UI.
// One of the tests that this checker can run are called "verification routine", which tests for things like Consistency, Navigation, etc.
// The tool allows a user to provide a DLL that can contain a custom "verification routine". An attacker can build such DLLs and pass it via the CLI, which would then be loaded in the context of the "AccCheckConsole" utility.
// MITRE Tactic: Execution
// Tags: attack.execution, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_acccheckconsole_execution.yml
// False Positives:
//   - Legitimate use of the UI Accessibility Checker

DeviceProcessEvents
| where (ProcessCommandLine contains " -hwnd" or ProcessCommandLine contains " -process " or ProcessCommandLine contains " -window ") and (FolderPath endswith "\\AccCheckConsole.exe" or ProcessVersionInfoOriginalFileName =~ "AccCheckConsole.exe")