// Title: Cloudflared Tunnel Connections Cleanup
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-17
// Level: medium
// Description: Detects execution of the "cloudflared" tool with the tunnel "cleanup" flag in order to cleanup tunnel connections.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1102, attack.t1090, attack.t1572
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_cloudflared_tunnel_cleanup.yml
// False Positives:
//   - Legitimate usage of Cloudflared.

DeviceProcessEvents
| where (ProcessCommandLine contains "-config " or ProcessCommandLine contains "-connector-id ") and (ProcessCommandLine contains " tunnel " and ProcessCommandLine contains "cleanup ")