// Title: Suspicious Usage of For Loop with Recursive Directory Search in CMD
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2025-11-12
// Level: medium
// Description: Detects suspicious usage of the cmd.exe 'for /f' loop combined with the 'tokens=' parameter and a recursive directory listing.
// This pattern may indicate an attempt to discover and execute system binaries dynamically, for example powershell, a technique sometimes used by attackers to evade detection.
// This behavior has been observed in various malicious lnk files.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.003, attack.defense-evasion, attack.t1027.010
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_cmd_for_loop_execution_with_recursive_directory_search.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "for /f" and ProcessCommandLine contains "tokens=" and ProcessCommandLine contains "in (" and ProcessCommandLine contains "dir") or (InitiatingProcessCommandLine contains "for /f" and InitiatingProcessCommandLine contains "tokens=" and InitiatingProcessCommandLine contains "in (" and InitiatingProcessCommandLine contains "dir")