// Title: Potential Hidden Directory Creation Via NTFS INDEX_ALLOCATION Stream - CLI
// Author: Nasreddine Bencherchali (Nextron Systems), Scoubi (@ScoubiMtl)
// Date: 2023-10-09
// Level: medium
// Description: Detects command line containing reference to the "::$index_allocation" stream, which can be used as a technique to prevent access to folders or files from tooling such as "explorer.exe" or "powershell.exe"
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1564.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_hidden_dir_index_allocation.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains "::$index_allocation"