// Title: Suspicious Remote Child Process From Outlook
// Author: Markus Neis, Nasreddine Bencherchali (Nextron Systems)
// Date: 2018-12-27
// Level: high
// Description: Detects a suspicious child process spawning from Outlook where the image is located in a remote location (SMB/WebDav shares).
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, attack.t1059, attack.t1202
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_office_outlook_susp_child_processes_remote.yml

DeviceProcessEvents
| where FolderPath startswith "\\\\" and InitiatingProcessFolderPath endswith "\\outlook.exe"