// Title: Suspicious Debugger Registration Cmdline
// Author: Florian Roth (Nextron Systems), oscd.community, Jonhnathan Ribeiro
// Date: 2019-09-06
// Level: high
// Description: Detects the registration of a debugger for a program that is available in the logon screen (sticky key backdoor).
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.t1546.008
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_registry_install_reg_debugger_backdoor.yml

DeviceProcessEvents
| where ProcessCommandLine contains "\\CurrentVersion\\Image File Execution Options\\" and (ProcessCommandLine contains "sethc.exe" or ProcessCommandLine contains "utilman.exe" or ProcessCommandLine contains "osk.exe" or ProcessCommandLine contains "magnify.exe" or ProcessCommandLine contains "narrator.exe" or ProcessCommandLine contains "displayswitch.exe" or ProcessCommandLine contains "atbroker.exe" or ProcessCommandLine contains "HelpPane.exe")