// Title: Service Started/Stopped Via Wmic.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-20
// Level: medium
// Description: Detects usage of wmic to start or stop a service
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1047
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wmic_service_manipulation.yml

DeviceProcessEvents
| where ((ProcessCommandLine contains "stopservice" or ProcessCommandLine contains "startservice") and (ProcessCommandLine contains " service " and ProcessCommandLine contains " call ")) and (ProcessVersionInfoOriginalFileName =~ "wmic.exe" or FolderPath endswith "\\WMIC.exe")