// Title: New Process Created Via Taskmgr.EXE
// Author: Florian Roth (Nextron Systems)
// Date: 2018-03-13
// Level: low
// Description: Detects the creation of a process via the Windows task manager. This might be an attempt to bypass UAC
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_taskmgr_susp_child_process.yml
// False Positives:
//   - Administrative activity

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\taskmgr.exe" and (not((FolderPath endswith ":\\Windows\\System32\\mmc.exe" or FolderPath endswith ":\\Windows\\System32\\resmon.exe" or FolderPath endswith ":\\Windows\\System32\\Taskmgr.exe")))