// Title: 7Zip Compressing Dump Files
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-27
// Level: medium
// Description: Detects execution of 7z in order to compress a file with a ".dmp"/".dump" extension, which could be a step in a process of dump file exfiltration.
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1560.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_7zip_exfil_dmp_files.yml
// False Positives:
//   - Legitimate use of 7z with a command line in which ".dmp" or ".dump" appears accidentally
//   - Legitimate use of 7z to compress WER ".dmp" files for troubleshooting

DeviceProcessEvents
| where (ProcessCommandLine contains ".dmp" or ProcessCommandLine contains ".dump" or ProcessCommandLine contains ".hdmp") and (ProcessVersionInfoFileDescription contains "7-Zip" or (FolderPath endswith "\\7z.exe" or FolderPath endswith "\\7zr.exe" or FolderPath endswith "\\7za.exe") or (ProcessVersionInfoOriginalFileName in~ ("7z.exe", "7za.exe")))