// Title: Psexec Execution
// Author: omkar72
// Date: 2020-10-30
// Level: medium
// Description: Detects user accept agreement execution in psexec commandline
// MITRE Tactic: Execution
// Tags: attack.execution, attack.lateral-movement, attack.t1569, attack.t1021
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sysinternals_psexec_execution.yml
// False Positives:
//   - Administrative scripts.

DeviceProcessEvents
| where FolderPath endswith "\\psexec.exe" or ProcessVersionInfoOriginalFileName =~ "psexec.c"