// Title: Tor Client/Browser Execution
// Author: frack113
// Date: 2022-02-20
// Level: high
// Description: Detects the use of Tor or Tor-Browser to connect to onion routing networks
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1090.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_browsers_tor_execution.yml

DeviceProcessEvents
| where ProcessVersionInfoFileDescription =~ "Tor Browser" or ProcessVersionInfoProductName =~ "Tor Browser" or (FolderPath endswith "\\tor.exe" or FolderPath endswith "\\Tor Browser\\Browser\\firefox.exe")