// Title: Rundll32 InstallScreenSaver Execution
// Author: Christopher Peacock @securepeacock, SCYTHE @scythe_io, TactiKoolSec
// Date: 2022-04-28
// Level: medium
// Description: An attacker may execute an application as a SCR File using rundll32.exe desk.cpl,InstallScreenSaver
// MITRE Tactic: Defense Evasion
// Tags: attack.t1218.011, attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_rundll32_installscreensaver.yml
// False Positives:
//   - Legitimate installation of a new screensaver

DeviceProcessEvents
| where ProcessCommandLine contains "InstallScreenSaver" and (FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE")