// Title: New Root Certificate Installed Via CertMgr.EXE
// Author: oscd.community, @redcanary, Zach Stanford @svch0st
// Date: 2023-03-05
// Level: medium
// Description: Detects execution of "certmgr" with the "add" flag in order to install a new certificate on the system.
// Adversaries may install a root certificate on a compromised system to avoid warnings when connecting to adversary controlled web servers.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1553.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_certmgr_certificate_installation.yml
// False Positives:
//   - Help Desk or IT may need to manually add a corporate Root CA on occasion. Need to test if GPO push doesn't trigger FP

DeviceProcessEvents
| where (ProcessCommandLine contains "/add" and ProcessCommandLine contains "root") and (FolderPath endswith "\\CertMgr.exe" or ProcessVersionInfoOriginalFileName =~ "CERTMGT.EXE")