// Title: Disable Windows IIS HTTP Logging
// Author: frack113
// Date: 2022-01-09
// Level: high
// Description: Disables HTTP logging on a Windows IIS web server as seen by Threat Group 3390 (Bronze Union)
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_iis_appcmd_http_logging.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "set" and ProcessCommandLine contains "config" and ProcessCommandLine contains "section:httplogging" and ProcessCommandLine contains "dontLog:true") and (FolderPath endswith "\\appcmd.exe" or ProcessVersionInfoOriginalFileName =~ "appcmd.exe")