// Title: Sensitive File Dump Via Wbadmin.EXE
// Author: Nasreddine Bencherchali (Nextron Systems), frack113
// Date: 2024-05-10
// Level: high
// Description: Detects the dump of highly sensitive files such as "NTDS.DIT" and "SECURITY" hive.
// Attackers can leverage the "wbadmin" utility in order to dump sensitive files that might contain credential or sensitive information.
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wbadmin_dump_sensitive_files.yml
// False Positives:
//   - Legitimate backup operation by authorized administrators. Matches must be investigated and allowed on a case by case basis.

DeviceProcessEvents
| where (ProcessCommandLine contains "start" or ProcessCommandLine contains "backup") and (FolderPath endswith "\\wbadmin.exe" or ProcessVersionInfoOriginalFileName =~ "WBADMIN.EXE") and (ProcessCommandLine contains "\\config\\SAM" or ProcessCommandLine contains "\\config\\SECURITY" or ProcessCommandLine contains "\\config\\SYSTEM" or ProcessCommandLine contains "\\Windows\\NTDS\\NTDS.dit")