// Title: Security Event Logging Disabled via MiniNt Registry Key - Process
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-04-09
// Level: high
// Description: Detects attempts to disable security event logging by adding the `MiniNt` registry key.
// This key is used to disable the Windows Event Log service, which collects and stores event logs from the operating system and applications.
// Adversaries may want to disable this service to prevent logging of security events that could be used to detect their activities.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1562.002, attack.t1112, car.2022-03-001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_event_logging_disable_via_key_minint.yml
// False Positives:
//   - Highly Unlikely

DeviceProcessEvents
| where ((ProcessCommandLine contains " add " and ProcessCommandLine contains "\\SYSTEM\\CurrentControlSet\\Control\\MiniNt") and (FolderPath endswith "\\reg.exe" or ProcessVersionInfoOriginalFileName =~ "reg.exe")) or ((ProcessCommandLine contains "New-Item " or ProcessCommandLine contains "ni ") and ProcessCommandLine contains "\\SYSTEM\\CurrentControlSet\\Control\\MiniNt" and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\powershell_ise.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll"))))