// Title: InfDefaultInstall.exe .inf Execution
// Author: frack113
// Date: 2021-07-13
// Level: medium
// Description: Executes SCT script using scrobj.dll from a command in entered into a specially prepared INF file.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_infdefaultinstall_execute_sct_scripts.yml

DeviceProcessEvents
| where ProcessCommandLine contains "InfDefaultInstall.exe " and ProcessCommandLine contains ".inf"