// Title: PUA - System Informer Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2023-05-08
// Level: medium
// Description: Detects the execution of System Informer, a task manager tool to view and manipulate processes, kernel options and other low level operations
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.discovery, attack.defense-evasion, attack.t1082, attack.t1564, attack.t1543
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_system_informer.yml
// False Positives:
//   - System Informer is regularly used legitimately by system administrators or developers. Apply additional filters accordingly

DeviceProcessEvents
| where FolderPath endswith "\\SystemInformer.exe" or ProcessVersionInfoOriginalFileName =~ "SystemInformer.exe" or ProcessVersionInfoFileDescription =~ "System Informer" or ProcessVersionInfoProductName =~ "System Informer" or (MD5 startswith "19426363A37C03C3ED6FEDF57B6696EC" or SHA1 startswith "8B12C6DA8FAC0D5E8AB999C31E5EA04AF32D53DC" or SHA256 startswith "8EE9D84DE50803545937A63C686822388A3338497CDDB660D5D69CF68B68F287")