// Title: Registry Modification Via Regini.EXE
// Author: Eli Salem, Sander Wiebing, oscd.community
// Date: 2020-10-08
// Level: low
// Description: Detects the execution of regini.exe which can be used to modify registry keys, the changes are imported from one or more text files.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1112, attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_regini_execution.yml
// False Positives:
//   - Legitimate modification of keys

DeviceProcessEvents
| where (FolderPath endswith "\\regini.exe" or ProcessVersionInfoOriginalFileName =~ "REGINI.EXE") and (not(ProcessCommandLine matches regex ":[^ \\\\]"))