// Title: PUA - Fast Reverse Proxy (FRP) Execution
// Author: frack113, Florian Roth
// Date: 2022-09-02
// Level: high
// Description: Detects the use of Fast Reverse Proxy. frp is a fast reverse proxy to help you expose a local server behind a NAT or firewall to the Internet.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1090
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_frp.yml
// False Positives:
//   - Legitimate use

DeviceProcessEvents
| where ProcessCommandLine contains "\\frpc.ini" or (MD5 startswith "7D9C233B8C9E3F0EA290D2B84593C842" or SHA1 startswith "06DDC9280E1F1810677935A2477012960905942F" or SHA256 startswith "57B0936B8D336D8E981C169466A15A5FD21A7D5A2C7DAF62D5E142EE860E387C") or (FolderPath endswith "\\frpc.exe" or FolderPath endswith "\\frps.exe")