// Title: PUA - Adidnsdump Execution
// Author: frack113
// Date: 2022-01-01
// Level: low
// Description: This tool enables enumeration and exporting of all DNS records in the zone for recon purposes of internal networks Python 3 and python.exe must be installed,
// Usee to Query/modify DNS records for Active Directory integrated DNS via LDAP
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1018
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_python_adidnsdump.yml

DeviceProcessEvents
| where ProcessCommandLine contains "adidnsdump" and FolderPath endswith "\\python.exe"