// Title: Remote Access Tool - Potential MeshAgent Execution - Windows
// Author: Norbert Jaśniewicz (AlphaSOC)
// Date: 2025-05-19
// Level: medium
// Description: Detects potential execution of MeshAgent which is a tool used for remote access.
// Historical data shows that threat actors rename MeshAgent binary to evade detection.
// Matching command lines with the '--meshServiceName' argument can indicate that the MeshAgent is being used for remote access.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1219.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_remote_access_tools_meshagent_arguments.yml
// False Positives:
//   - Environments that legitimately use MeshAgent

DeviceProcessEvents
| where ProcessCommandLine contains "--meshServiceName"