// Title: HackTool - WinRM Access Via Evil-WinRM
// Author: frack113
// Date: 2022-01-07
// Level: medium
// Description: Adversaries may use Valid Accounts to log into a computer using the Remote Desktop Protocol (RDP). The adversary may then perform actions as the logged-on user.
// MITRE Tactic: Lateral Movement
// Tags: attack.lateral-movement, attack.t1021.006
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_evil_winrm.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "-i " and ProcessCommandLine contains "-u " and ProcessCommandLine contains "-p ") and FolderPath endswith "\\ruby.exe"