// Title: Computer System Reconnaissance Via Wmic.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-08
// Level: medium
// Description: Detects execution of wmic utility with the "computersystem" flag in order to obtain information about the machine such as the domain, username, model, etc.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.execution, attack.t1047
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wmic_recon_computersystem.yml

DeviceProcessEvents
| where ProcessCommandLine contains "computersystem" and (FolderPath endswith "\\wmic.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")