// Title: Uninstall Crowdstrike Falcon Sensor
// Author: frack113
// Date: 2021-07-12
// Level: high
// Description: Adversaries may disable security tools to avoid possible detection of their tools and activities by uninstalling Crowdstrike Falcon
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_uninstall_crowdstrike_falcon.yml
// False Positives:
//   - Administrator might leverage the same command line for debugging or other purposes. However this action must be always investigated

DeviceProcessEvents
| where ProcessCommandLine contains "\\WindowsSensor.exe" and ProcessCommandLine contains " /uninstall" and ProcessCommandLine contains " /quiet"