// Title: Remote Access Tool - AnyDesk Silent Installation
// Author: Ján Trenčanský
// Date: 2021-08-06
// Level: high
// Description: Detects AnyDesk Remote Desktop silent installation. Which can be used by attackers to gain remote access.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1219.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_remote_access_tools_anydesk_silent_install.yml
// False Positives:
//   - Legitimate deployment of AnyDesk

DeviceProcessEvents
| where ProcessCommandLine contains "--install" and ProcessCommandLine contains "--start-with-win" and ProcessCommandLine contains "--silent"