// Title: Potential Product Class Reconnaissance Via Wmic.EXE
// Author: Michael Haag, Florian Roth (Nextron Systems), juju4, oscd.community, Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2023-02-14
// Level: medium
// Description: Detects the execution of WMIC in order to get a list of firewall, antivirus and antispywware products.
// Adversaries often enumerate security products installed on a system to identify security controls and potential ways to evade detection or disable protection mechanisms.
// This information helps them plan their next attack steps and choose appropriate techniques to bypass security measures.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1047, attack.discovery, attack.t1082
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wmic_recon_product_class.yml
// False Positives:
//   - Legitimate use of wmic.exe for reconnaissance of firewall, antivirus and antispywware products.

DeviceProcessEvents
| where (ProcessCommandLine contains "AntiVirusProduct" or ProcessCommandLine contains "AntiSpywareProduct" or ProcessCommandLine contains "FirewallProduct") and (FolderPath endswith "\\wmic.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")