// Title: Arbitrary File Download Via IMEWDBLD.EXE
// Author: Swachchhanda Shrawan Poudel
// Date: 2023-11-09
// Level: high
// Description: Detects usage of "IMEWDBLD.exe" to download arbitrary files
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_imewbdld_download.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://") and (FolderPath endswith "\\IMEWDBLD.exe" or ProcessVersionInfoOriginalFileName =~ "imewdbld.exe")