// Title: Use of Wfc.exe
// Author: Christopher Peacock @SecurePeacock, SCYTHE @scythe_io
// Date: 2022-06-01
// Level: medium
// Description: The Workflow Command-line Compiler can be used for AWL bypass and is listed in Microsoft's recommended block rules.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1127
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_wfc.yml
// False Positives:
//   - Legitimate use by a software developer

DeviceProcessEvents
| where FolderPath endswith "\\wfc.exe" or ProcessVersionInfoOriginalFileName =~ "wfc.exe"