// Title: Fsutil Suspicious Invocation
// Author: Ecco, E.M. Anhaus, oscd.community
// Date: 2019-09-26
// Level: high
// Description: Detects suspicious parameters of fsutil (deleting USN journal, configuring it with small size, etc).
// Might be used by ransomwares during the attack (seen by NotPetya and others).
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.impact, attack.t1070, attack.t1485
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_fsutil_usage.yml
// False Positives:
//   - Admin activity
//   - Scripts and administrative tools used in the monitored environment

DeviceProcessEvents
| where (ProcessCommandLine contains "deletejournal" or ProcessCommandLine contains "createjournal" or ProcessCommandLine contains "setZeroData") and (FolderPath endswith "\\fsutil.exe" or ProcessVersionInfoOriginalFileName =~ "fsutil.exe")