// Title: Suspicious CustomShellHost Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-19
// Level: high
// Description: Detects the execution of CustomShellHost.exe where the child isn't located in 'C:\Windows\explorer.exe'. CustomShellHost is a known LOLBin that can be abused by attackers for defense evasion techniques.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1216
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_customshellhost_susp_exec.yml
// False Positives:
//   - False positives are unlikely, investigate matches carefully.

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\CustomShellHost.exe" and (not(FolderPath =~ "C:\\Windows\\explorer.exe"))