// Title: Base64 Encoded PowerShell Command Detected
// Author: Florian Roth (Nextron Systems)
// Date: 2020-01-29
// Level: high
// Description: Detects usage of the "FromBase64String" function in the commandline which is used to decode a base64 encoded string
// MITRE Tactic: Defense Evasion
// Tags: attack.t1027, attack.defense-evasion, attack.execution, attack.t1140, attack.t1059.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_frombase64string.yml
// False Positives:
//   - Administrative script libraries

DeviceProcessEvents
| where ProcessCommandLine contains "::FromBase64String("