// Title: Windows Internet Hosted WebDav Share Mount Via Net.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-21
// Level: high
// Description: Detects when an internet hosted webdav share is mounted using the "net.exe" utility
// MITRE Tactic: Lateral Movement
// Tags: attack.lateral-movement, attack.t1021.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_net_use_mount_internet_share.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " use " and ProcessCommandLine contains " http") and ((FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe") or (ProcessVersionInfoOriginalFileName in~ ("net.exe", "net1.exe")))