// Title: HackTool - SharpChisel Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-05
// Level: high
// Description: Detects usage of the Sharp Chisel via the commandline arguments
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1090.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_sharp_chisel.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where FolderPath endswith "\\SharpChisel.exe" or ProcessVersionInfoProductName =~ "SharpChisel"