// Title: VeeamBackup Database Credentials Dump Via Sqlcmd.EXE
// Author: frack113
// Date: 2021-12-20
// Level: high
// Description: Detects dump of credentials in VeeamBackup dbo
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sqlcmd_veeam_dump.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "SELECT" and ProcessCommandLine contains "TOP" and ProcessCommandLine contains "[VeeamBackup].[dbo].[Credentials]") and FolderPath endswith "\\sqlcmd.exe"