// Title: Taskkill Symantec Endpoint Protection
// Author: Ilya Krestinichev, Florian Roth (Nextron Systems)
// Date: 2022-09-13
// Level: high
// Description: Detects one of the possible scenarios for disabling Symantec Endpoint Protection.
// Symantec Endpoint Protection antivirus software services incorrectly implement the protected service mechanism.
// As a result, the NT AUTHORITY/SYSTEM user can execute the taskkill /im command several times ccSvcHst.exe /f, thereby killing the process belonging to the service, and thus shutting down the service.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_taskkill_sep.yml

DeviceProcessEvents
| where ProcessCommandLine contains "taskkill" and ProcessCommandLine contains " /F " and ProcessCommandLine contains " /IM " and ProcessCommandLine contains "ccSvcHst.exe"