// Title: Suspicious Rundll32 Invoking Inline VBScript
// Author: Florian Roth (Nextron Systems)
// Date: 2021-03-05
// Level: high
// Description: Detects suspicious process related to rundll32 based on command line that invokes inline VBScript as seen being used by UNC2452
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.defense-evasion, attack.t1055
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_rundll32_inline_vbs.yml

DeviceProcessEvents
| where ProcessCommandLine contains "rundll32.exe" and ProcessCommandLine contains "Execute" and ProcessCommandLine contains "RegRead" and ProcessCommandLine contains "window.close"