// Title: Stop Windows Service Via Net.EXE
// Author: Jakob Weinzettl, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-03-05
// Level: low
// Description: Detects the stopping of a Windows service via the "net" utility.
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1489
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_net_stop_service.yml
// False Positives:
//   - There are many legitimate reasons to stop a service. This rule isn't looking for any suspicious behaviour in particular. Filter legitimate activity accordingly

DeviceProcessEvents
| where ProcessCommandLine contains " stop " and ((ProcessVersionInfoOriginalFileName in~ ("net.exe", "net1.exe")) or (FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe"))