// Title: Harvesting Of Wifi Credentials Via Netsh.EXE
// Author: Andreas Hunkeler (@Karneades), oscd.community
// Date: 2020-04-20
// Level: medium
// Description: Detect the harvesting of wifi credentials using netsh.exe
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.credential-access, attack.t1040
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_netsh_wifi_credential_harvesting.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "wlan" and ProcessCommandLine contains " s" and ProcessCommandLine contains " p" and ProcessCommandLine contains " k" and ProcessCommandLine contains "=clear") and (FolderPath endswith "\\netsh.exe" or ProcessVersionInfoOriginalFileName =~ "netsh.exe")