// Title: UAC Bypass Tools Using ComputerDefaults
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-31
// Level: high
// Description: Detects tools such as UACMe used to bypass UAC with computerdefaults.exe (UACMe 59)
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1548.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_uac_bypass_computerdefaults.yml

DeviceProcessEvents
| where (FolderPath =~ "C:\\Windows\\System32\\ComputerDefaults.exe" and (ProcessIntegrityLevel in~ ("High", "System", "S-1-16-16384", "S-1-16-12288"))) and (not((InitiatingProcessFolderPath contains ":\\Windows\\System32" or InitiatingProcessFolderPath contains ":\\Program Files")))