// Title: Potential Process Execution Proxy Via CL_Invocation.ps1
// Author: Nasreddine Bencherchali (Nextron Systems), oscd.community, Natalia Shornikova
// Date: 2020-10-14
// Level: medium
// Description: Detects calls to "SyncInvoke" that is part of the "CL_Invocation.ps1" script to proxy execution using "System.Diagnostics.Process"
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1216
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_cl_invocation.yml

DeviceProcessEvents
| where ProcessCommandLine contains "SyncInvoke "