// Title: Hiding Files with Attrib.exe
// Author: Sami Ruohonen
// Date: 2019-01-16
// Level: medium
// Description: Detects usage of attrib.exe to hide files from users.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1564.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_attrib_hiding_files.yml
// False Positives:
//   - IgfxCUIService.exe hiding *.cui files via .bat script (attrib.exe a child of cmd.exe and igfxCUIService.exe is the parent of the cmd.exe)
//   - Msiexec.exe hiding desktop.ini

DeviceProcessEvents
| where (ProcessCommandLine contains " +h " and (FolderPath endswith "\\attrib.exe" or ProcessVersionInfoOriginalFileName =~ "ATTRIB.EXE")) and (not(ProcessCommandLine contains "\\desktop.ini ")) and (not((ProcessCommandLine =~ "+R +H +S +A \\*.cui" and InitiatingProcessCommandLine =~ "C:\\WINDOWS\\system32\\*.bat" and InitiatingProcessFolderPath endswith "\\cmd.exe")))