// Title: Uncommon Link.EXE Parent Process
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-22
// Level: medium
// Description: Detects an uncommon parent process of "LINK.EXE".
// Link.EXE in Microsoft incremental linker. Its a utility usually bundled with Visual Studio installation.
// Multiple utilities often found in the same folder (editbin.exe, dumpbin.exe, lib.exe, etc) have a hardcode call to the "LINK.EXE" binary without checking its validity.
// This would allow an attacker to sideload any binary with the name "link.exe" if one of the aforementioned tools get executed from a different location.
// By filtering the known locations of such utilities we can spot uncommon parent process of LINK.EXE that might be suspicious or malicious.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_link_uncommon_parent_process.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "LINK /" and FolderPath endswith "\\link.exe") and (not(((InitiatingProcessFolderPath contains "\\VC\\bin\\" or InitiatingProcessFolderPath contains "\\VC\\Tools\\") and (InitiatingProcessFolderPath startswith "C:\\Program Files\\Microsoft Visual Studio\\" or InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\Microsoft Visual Studio\\"))))