// Title: Potential Suspicious Registry File Imported Via Reg.EXE
// Author: frack113, Nasreddine Bencherchali
// Date: 2022-08-01
// Level: medium
// Description: Detects the import of '.reg' files from suspicious paths using the 'reg.exe' utility
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1112, attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_reg_import_from_suspicious_paths.yml
// False Positives:
//   - Legitimate import of keys

DeviceProcessEvents
| where ProcessCommandLine contains " import " and (FolderPath endswith "\\reg.exe" or ProcessVersionInfoOriginalFileName =~ "reg.exe") and (ProcessCommandLine contains "C:\\Users\\" or ProcessCommandLine contains "%temp%" or ProcessCommandLine contains "%tmp%" or ProcessCommandLine contains "%appdata%" or ProcessCommandLine contains "\\AppData\\Local\\Temp\\" or ProcessCommandLine contains "C:\\Windows\\Temp\\" or ProcessCommandLine contains "C:\\ProgramData\\")