// Title: Renamed BrowserCore.EXE Execution
// Author: Max Altgelt (Nextron Systems)
// Date: 2022-06-02
// Level: high
// Description: Detects process creation with a renamed BrowserCore.exe (used to extract Azure tokens)
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.defense-evasion, attack.t1528, attack.t1036.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_renamed_browsercore.yml

DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "BrowserCore.exe" and (not(FolderPath endswith "\\BrowserCore.exe"))