// Title: IE ZoneMap Setting Downgraded To MyComputer Zone For HTTP Protocols Via CLI
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-09-05
// Level: high
// Description: Detects changes to Internet Explorer's (IE / Windows Internet properties) ZoneMap configuration of the "HTTP" and "HTTPS" protocols to point to the "My Computer" zone. This allows downloaded files from the Internet to be granted the same level of trust as files stored locally.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_registry_ie_security_zone_protocol_defaults_downgrade.yml

DeviceProcessEvents
| where ProcessCommandLine contains "\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ZoneMap\\ProtocolDefaults" and ProcessCommandLine contains "http" and ProcessCommandLine contains " 0"