// Title: Add New Download Source To Winget
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-04-17
// Level: medium
// Description: Detects usage of winget to add new additional download sources
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1059
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_winget_add_custom_source.yml
// False Positives:
//   - False positive are expected with legitimate sources

DeviceProcessEvents
| where (ProcessCommandLine contains "source " and ProcessCommandLine contains "add ") and (FolderPath endswith "\\winget.exe" or ProcessVersionInfoOriginalFileName =~ "winget.exe")