// Title: Weak or Abused Passwords In CLI
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-14
// Level: medium
// Description: Detects weak passwords or often abused passwords (seen used by threat actors) via the CLI.
// An example would be a threat actor creating a new user via the net command and providing the password inline
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_weak_or_abused_passwords.yml
// False Positives:
//   - Legitimate usage of the passwords by users via commandline (should be discouraged)
//   - Other currently unknown false positives

DeviceProcessEvents
| where ProcessCommandLine contains "123456789" or ProcessCommandLine contains "123123qwE" or ProcessCommandLine contains "Asd123.aaaa" or ProcessCommandLine contains "Decryptme" or ProcessCommandLine contains "P@ssw0rd!" or ProcessCommandLine contains "Pass8080" or ProcessCommandLine contains "password123" or ProcessCommandLine contains "test@202"