// Title: Potential DLL File Download Via PowerShell Invoke-WebRequest
// Author: Florian Roth (Nextron Systems), Hieu Tran
// Date: 2023-03-13
// Level: medium
// Description: Detects potential DLL files being downloaded using the PowerShell Invoke-WebRequest or Invoke-RestMethod cmdlets.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.execution, attack.t1059.001, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_download_dll.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "Invoke-RestMethod " or ProcessCommandLine contains "Invoke-WebRequest " or ProcessCommandLine contains "IRM " or ProcessCommandLine contains "IWR ") and (ProcessCommandLine contains "http" and ProcessCommandLine contains "OutFile" and ProcessCommandLine contains ".dll")