// Title: Add Insecure Download Source To Winget
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-04-17
// Level: high
// Description: Detects usage of winget to add a new insecure (http) download source.
// Winget will not allow the addition of insecure sources, hence this could indicate potential suspicious activity (or typos)
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1059
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_winget_add_insecure_custom_source.yml
// False Positives:
//   - False positives might occur if the users are unaware of such control checks

DeviceProcessEvents
| where (ProcessCommandLine contains "source " and ProcessCommandLine contains "add " and ProcessCommandLine contains "http://") and (FolderPath endswith "\\winget.exe" or ProcessVersionInfoOriginalFileName =~ "winget.exe")