// Title: HackTool - GMER Rootkit Detector and Remover Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-05
// Level: high
// Description: Detects the execution GMER tool based on image and hash fields.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_gmer.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where FolderPath endswith "\\gmer.exe" or (MD5 startswith "E9DC058440D321AA17D0600B3CA0AB04" or SHA1 startswith "539C228B6B332F5AA523E5CE358C16647D8BBE57" or SHA256 startswith "E8A3E804A96C716A3E9B69195DB6FFB0D33E2433AF871E4D4E1EAB3097237173")