// Title: Use of VisualUiaVerifyNative.exe
// Author: Christopher Peacock @SecurePeacock, SCYTHE @scythe_io
// Date: 2022-06-01
// Level: medium
// Description: VisualUiaVerifyNative.exe is a Windows SDK that can be used for AWL bypass and is listed in Microsoft's recommended block rules.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_visualuiaverifynative.yml
// False Positives:
//   - Legitimate testing of Microsoft UI parts.

DeviceProcessEvents
| where FolderPath endswith "\\VisualUiaVerifyNative.exe" or ProcessVersionInfoOriginalFileName =~ "VisualUiaVerifyNative.exe"