// Title: Renamed Remote Utilities RAT (RURAT) Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-19
// Level: medium
// Description: Detects execution of renamed Remote Utilities (RURAT) via Product PE header field
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.collection, attack.command-and-control, attack.discovery, attack.s0592
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_renamed_rurat.yml

DeviceProcessEvents
| where ProcessVersionInfoProductName =~ "Remote Utilities" and (not((FolderPath endswith "\\rutserv.exe" or FolderPath endswith "\\rfusclient.exe")))