// Title: Windows Backup Deleted Via Wbadmin.EXE
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2021-12-13
// Level: medium
// Description: Detects the deletion of backups or system state backups via "wbadmin.exe".
// This technique is used by numerous ransomware families and actors.
// This may only be successful on server platforms that have Windows Backup enabled.
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1490
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wbadmin_delete_backups.yml
// False Positives:
//   - Legitimate backup activity from administration scripts and software.

DeviceProcessEvents
| where ((ProcessCommandLine contains "delete " and ProcessCommandLine contains "backup") and (FolderPath endswith "\\wbadmin.exe" or ProcessVersionInfoOriginalFileName =~ "WBADMIN.EXE")) and (not(ProcessCommandLine contains "keepVersions:0"))