// Title: Suspicious RDP Redirect Using TSCON
// Author: Florian Roth (Nextron Systems)
// Date: 2018-03-17
// Level: high
// Description: Detects a suspicious RDP session redirect using tscon.exe
// MITRE Tactic: Lateral Movement
// Tags: attack.lateral-movement, attack.t1563.002, attack.t1021.001, car.2013-07-002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_tscon_rdp_redirect.yml

DeviceProcessEvents
| where ProcessCommandLine contains " /dest:rdp-tcp#"