// Title: Taskmgr as LOCAL_SYSTEM
// Author: Florian Roth (Nextron Systems)
// Date: 2018-03-18
// Level: high
// Description: Detects the creation of taskmgr.exe process in context of LOCAL_SYSTEM
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_taskmgr_localsystem.yml

DeviceProcessEvents
| where FolderPath endswith "\\taskmgr.exe" and (AccountName contains "AUTHORI" or AccountName contains "AUTORI")