// Title: Suspicious Schtasks Schedule Types
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-09
// Level: high
// Description: Detects scheduled task creations or modification on a suspicious schedule type
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.execution, attack.t1053.005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_schtasks_schedule_type.yml
// False Positives:
//   - Legitimate processes that run at logon. Filter according to your environment

DeviceProcessEvents
| where ((FolderPath endswith "\\schtasks.exe" or ProcessVersionInfoOriginalFileName =~ "schtasks.exe") and (ProcessCommandLine contains " ONLOGON " or ProcessCommandLine contains " ONSTART " or ProcessCommandLine contains " ONCE " or ProcessCommandLine contains " ONIDLE ")) and (not((ProcessCommandLine contains "NT AUT" or ProcessCommandLine contains " SYSTEM" or ProcessCommandLine contains "HIGHEST")))