// Title: Obfuscated PowerShell OneLiner Execution
// Author: @Kostastsale, TheDFIRReport
// Date: 2022-05-09
// Level: high
// Description: Detects the execution of a specific OneLiner to download and execute powershell modules in memory.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1059.001, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_download_cradle_obfuscated.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "http://127.0.0.1" and ProcessCommandLine contains "%{(IRM $_)}" and ProcessCommandLine contains "Invoke") and FolderPath endswith "\\powershell.exe"