// Title: Potential Active Directory Enumeration Using AD Module - ProcCreation
// Author: frack113
// Date: 2023-01-22
// Level: medium
// Description: Detects usage of the "Import-Module" cmdlet to load the "Microsoft.ActiveDirectory.Management.dl" DLL. Which is often used by attackers to perform AD enumeration.
// MITRE Tactic: Reconnaissance
// Tags: attack.reconnaissance, attack.discovery, attack.impact
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_active_directory_module_dll_import.yml
// False Positives:
//   - Legitimate use of the library for administrative activity

DeviceProcessEvents
| where (ProcessCommandLine contains "Import-Module " or ProcessCommandLine contains "ipmo ") and ProcessCommandLine contains "Microsoft.ActiveDirectory.Management.dll" and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")))