// Title: Potential Binary Proxy Execution Via VSDiagnostics.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-03
// Level: medium
// Description: Detects execution of "VSDiagnostics.exe" with the "start" command in order to launch and proxy arbitrary binaries.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_vsdiagnostics_execution_proxy.yml
// False Positives:
//   - Legitimate usage for tracing and diagnostics purposes

DeviceProcessEvents
| where (ProcessCommandLine contains " /launch:" or ProcessCommandLine contains " -launch:") and ProcessCommandLine contains "start" and (FolderPath endswith "\\VSDiagnostics.exe" or ProcessVersionInfoOriginalFileName =~ "VSDiagnostics.exe")