// Title: RDP Port Forwarding Rule Added Via Netsh.EXE
// Author: Florian Roth (Nextron Systems), oscd.community
// Date: 2019-01-29
// Level: high
// Description: Detects the execution of netsh to configure a port forwarding of port 3389 (RDP) rule
// MITRE Tactic: Lateral Movement
// Tags: attack.lateral-movement, attack.defense-evasion, attack.command-and-control, attack.t1090
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_netsh_port_forwarding_3389.yml
// False Positives:
//   - Legitimate administration activity

DeviceProcessEvents
| where (ProcessCommandLine contains " i" and ProcessCommandLine contains " p" and ProcessCommandLine contains "=3389" and ProcessCommandLine contains " c") and (FolderPath endswith "\\netsh.exe" or ProcessVersionInfoOriginalFileName =~ "netsh.exe")