// Title: Reg Add Suspicious Paths
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-19
// Level: high
// Description: Detects when an adversary uses the reg.exe utility to add or modify new keys or subkeys
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_reg_susp_paths.yml
// False Positives:
//   - Rare legitimate add to registry via cli (to these locations)

DeviceProcessEvents
| where (ProcessCommandLine contains "\\AppDataLow\\Software\\Microsoft\\" or ProcessCommandLine contains "\\Policies\\Microsoft\\Windows\\OOBE" or ProcessCommandLine contains "\\Policies\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon" or ProcessCommandLine contains "\\SOFTWARE\\Microsoft\\Windows NT\\Currentversion\\Winlogon" or ProcessCommandLine contains "\\CurrentControlSet\\Control\\SecurityProviders\\WDigest" or ProcessCommandLine contains "\\Microsoft\\Windows Defender\\") and (FolderPath endswith "\\reg.exe" or ProcessVersionInfoOriginalFileName =~ "reg.exe")