// Title: HackTool - Htran/NATBypass Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-12-27
// Level: high
// Description: Detects executable names or flags used by Htran or Htran-like tools (e.g. NATBypass)
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1090, attack.s0040
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_htran_or_natbypass.yml

DeviceProcessEvents
| where (ProcessCommandLine contains ".exe -tran " or ProcessCommandLine contains ".exe -slave ") or (FolderPath endswith "\\htran.exe" or FolderPath endswith "\\lcx.exe")