// Title: PUA - Process Hacker Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-10-10
// Level: medium
// Description: Detects the execution of Process Hacker based on binary metadata information (Image, Hash, Imphash, etc).
// Process Hacker is a tool to view and manipulate processes, kernel options and other low level options.
// Threat actors abused older vulnerable versions to manipulate system processes.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.discovery, attack.persistence, attack.privilege-escalation, attack.t1622, attack.t1564, attack.t1543
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_process_hacker.yml
// False Positives:
//   - While sometimes 'Process Hacker is used by legitimate administrators, the execution of Process Hacker must be investigated and allowed on a case by case basis

DeviceProcessEvents
| where FolderPath contains "\\ProcessHacker_" or FolderPath endswith "\\ProcessHacker.exe" or (ProcessVersionInfoOriginalFileName in~ ("ProcessHacker.exe", "Process Hacker")) or ProcessVersionInfoFileDescription =~ "Process Hacker" or ProcessVersionInfoProductName =~ "Process Hacker" or ((MD5 startswith "68F9B52895F4D34E74112F3129B3B00D" or MD5 startswith "B365AF317AE730A67C936F21432B9C71") or (SHA1 startswith "A0BDFAC3CE1880B32FF9B696458327CE352E3B1D" or SHA1 startswith "C5E2018BF7C0F314FED4FD7FE7E69FA2E648359E") or (SHA256 startswith "D4A0FE56316A2C45B9BA9AC1005363309A3EDC7ACF9E4DF64D326A0FF273E80F" or SHA256 startswith "BD2C2CF0631D881ED382817AFCCE2B093F4E412FFB170A719E2762F250ABFEA4"))