// Title: Deleted Data Overwritten Via Cipher.EXE
// Author: frack113
// Date: 2021-12-26
// Level: medium
// Description: Detects usage of the "cipher" built-in utility in order to overwrite deleted data from disk.
// Adversaries may destroy data and files on specific systems or in large numbers on a network to interrupt availability to systems, services, and network resources.
// Data destruction is likely to render stored data irrecoverable by forensic techniques through overwriting files or data on local and remote drives
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1485
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_cipher_overwrite_deleted_data.yml

DeviceProcessEvents
| where ProcessCommandLine contains " /w:" and (ProcessVersionInfoOriginalFileName =~ "CIPHER.EXE" or FolderPath endswith "\\cipher.exe")