// Title: Response File Execution Via Odbcconf.EXE
// Author: Kirill Kiryanov, Beyu Denis, Daniil Yugoslavskiy, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-22
// Level: medium
// Description: Detects execution of "odbcconf" with the "-f" flag in order to load a response file which might contain a malicious action.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.008
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_odbcconf_response_file.yml
// False Positives:
//   - The rule is looking for any usage of response file, which might generate false positive when this function is used legitimately. Investigate the contents of the ".rsp" file to determine if it is malicious and apply additional filters if necessary.

DeviceProcessEvents
| where (ProcessCommandLine contains " -f " or ProcessCommandLine contains " /f " or ProcessCommandLine contains " –f " or ProcessCommandLine contains " —f " or ProcessCommandLine contains " ―f ") and (FolderPath endswith "\\odbcconf.exe" or ProcessVersionInfoOriginalFileName =~ "odbcconf.exe") and ProcessCommandLine contains ".rsp"