// Title: New Kernel Driver Via SC.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-14
// Level: medium
// Description: Detects creation of a new service (kernel driver) with the type "kernel"
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.t1543.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sc_new_kernel_driver.yml
// False Positives:
//   - Rare legitimate installation of kernel drivers via sc.exe

DeviceProcessEvents
| where ((ProcessCommandLine contains "create" or ProcessCommandLine contains "config") and (ProcessCommandLine contains "binPath" and ProcessCommandLine contains "type" and ProcessCommandLine contains "kernel") and FolderPath endswith "\\sc.exe") and (not(((ProcessCommandLine contains "create netprotection_network_filter" and ProcessCommandLine contains "type= kernel start= " and ProcessCommandLine contains "binPath= System32\\drivers\\netprotection_network_filter" and ProcessCommandLine contains "DisplayName= netprotection_network_filter" and ProcessCommandLine contains "group= PNP_TDI tag= yes") or (ProcessCommandLine contains "create avelam binpath=C:\\Windows\\system32\\drivers\\avelam.sys" and ProcessCommandLine contains "type=kernel start=boot error=critical group=Early-Launch"))))