// Title: WinRAR Execution in Non-Standard Folder
// Author: Florian Roth (Nextron Systems), Tigzy
// Date: 2021-11-17
// Level: medium
// Description: Detects a suspicious WinRAR execution in a folder which is not the default installation folder
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1560.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_winrar_uncommon_folder_execution.yml
// False Positives:
//   - Legitimate use of WinRAR in a folder of a software that bundles WinRAR

DeviceProcessEvents
| where ((FolderPath endswith "\\rar.exe" or FolderPath endswith "\\winrar.exe") or (ProcessVersionInfoFileDescription in~ ("Command line RAR", "WinRAR"))) and (not(((FolderPath contains ":\\Program Files (x86)\\WinRAR\\" or FolderPath contains ":\\Program Files\\WinRAR\\") or FolderPath endswith "\\UnRAR.exe"))) and (not(FolderPath contains ":\\Windows\\Temp\\"))