// Title: Cloudflared Tunnel Execution
// Author: Janantha Marasinghe, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-17
// Level: medium
// Description: Detects execution of the "cloudflared" tool to connect back to a tunnel. This was seen used by threat actors to maintain persistence and remote access to compromised networks.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1102, attack.t1090, attack.t1572
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_cloudflared_tunnel_run.yml
// False Positives:
//   - Legitimate usage of Cloudflared tunnel.

DeviceProcessEvents
| where (ProcessCommandLine contains "-config " or ProcessCommandLine contains "-credentials-contents " or ProcessCommandLine contains "-credentials-file " or ProcessCommandLine contains "-token ") and (ProcessCommandLine contains " tunnel " and ProcessCommandLine contains " run ")