// Title: Network Reconnaissance Activity
// Author: Florian Roth (Nextron Systems)
// Date: 2022-02-07
// Level: high
// Description: Detects a set of suspicious network related commands often used in recon stages
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1087, attack.t1082, car.2016-03-001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_nslookup_domain_discovery.yml
// False Positives:
//   - False positives depend on scripts and administrative tools used in the monitored environment

DeviceProcessEvents
| where ProcessCommandLine contains "nslookup" and ProcessCommandLine contains "_ldap._tcp.dc._msdcs."