// Title: Potential Persistence Attempt Via Run Keys Using Reg.EXE
// Author: Florian Roth (Nextron Systems), Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2021-06-28
// Level: medium
// Description: Detects suspicious command line reg.exe tool adding key to RUN key in Registry
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_reg_add_run_key.yml
// False Positives:
//   - Legitimate software automatically (mostly, during installation) sets up autorun keys for legitimate reasons.
//   - Legitimate administrator sets up autorun keys for legitimate reasons.
//   - Discord

DeviceProcessEvents
| where (ProcessCommandLine contains "Software\\Microsoft\\Windows\\CurrentVersion\\Run" or ProcessCommandLine contains "\\Software\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Run" or ProcessCommandLine contains "\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\Run") and (ProcessCommandLine contains "reg" and ProcessCommandLine contains " add ") and FolderPath endswith "\\reg.exe"