// Title: HackTool - SharpLdapWhoami Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-08-29
// Level: high
// Description: Detects SharpLdapWhoami, a whoami alternative that queries the LDAP service on a domain controller
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1033, car.2016-03-001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_sharpldapwhoami.yml
// False Positives:
//   - Programs that use the same command line flags

DeviceProcessEvents
| where (ProcessCommandLine endswith " /method:ntlm" or ProcessCommandLine endswith " /method:kerb" or ProcessCommandLine endswith " /method:nego" or ProcessCommandLine endswith " /m:nego" or ProcessCommandLine endswith " /m:ntlm" or ProcessCommandLine endswith " /m:kerb") or FolderPath endswith "\\SharpLdapWhoami.exe" or (ProcessVersionInfoOriginalFileName contains "SharpLdapWhoami" or ProcessVersionInfoProductName =~ "SharpLdapWhoami")