// Title: Suspicious TSCON Start as SYSTEM
// Author: Florian Roth (Nextron Systems)
// Date: 2018-03-17
// Level: high
// Description: Detects a tscon.exe start as LOCAL SYSTEM
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1219.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_tscon_localsystem.yml

DeviceProcessEvents
| where FolderPath endswith "\\tscon.exe" and (AccountName contains "AUTHORI" or AccountName contains "AUTORI")