// Title: Potential Adplus.EXE Abuse
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-09
// Level: high
// Description: Detects execution of "AdPlus.exe", a binary that is part of the Windows SDK that can be used as a LOLBIN in order to dump process memory and execute arbitrary commands.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.credential-access, attack.t1003.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_adplus_memory_dump.yml
// False Positives:
//   - Legitimate usage of Adplus for debugging purposes

DeviceProcessEvents
| where (ProcessCommandLine contains " -hang " or ProcessCommandLine contains " -pn " or ProcessCommandLine contains " -pmn " or ProcessCommandLine contains " -p " or ProcessCommandLine contains " -po " or ProcessCommandLine contains " -c " or ProcessCommandLine contains " -sc ") and (FolderPath endswith "\\adplus.exe" or ProcessVersionInfoOriginalFileName =~ "Adplus.exe")