// Title: Arbitrary Shell Command Execution Via Settingcontent-Ms
// Author: Sreeman
// Date: 2020-03-13
// Level: medium
// Description: The .SettingContent-ms file type was introduced in Windows 10 and allows a user to create "shortcuts" to various Windows 10 setting pages. These files are simply XML and contain paths to various Windows 10 settings binaries.
// MITRE Tactic: Execution
// Tags: attack.t1204, attack.t1566.001, attack.execution, attack.initial-access
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_arbitrary_shell_execution_via_settingcontent.yml

DeviceProcessEvents
| where ProcessCommandLine contains ".SettingContent-ms" and (not(ProcessCommandLine contains "immersivecontrolpanel"))