// Title: Interactive AT Job
// Author: E.M. Anhaus (originally from Atomic Blue Detections, Endgame), oscd.community
// Date: 2019-10-24
// Level: high
// Description: Detects an interactive AT job, which may be used as a form of privilege escalation.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.execution, attack.privilege-escalation, attack.t1053.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_at_interactive_execution.yml
// False Positives:
//   - Unlikely (at.exe deprecated as of Windows 8)

DeviceProcessEvents
| where ProcessCommandLine contains "interactive" and FolderPath endswith "\\at.exe"