// Title: New User Created Via Net.EXE With Never Expire Option
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-12
// Level: high
// Description: Detects creation of local users via the net.exe command with the option "never expire"
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1136.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_net_user_add_never_expire.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (ProcessCommandLine contains "user" and ProcessCommandLine contains "add" and ProcessCommandLine contains "expires:never") and ((FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe") or (ProcessVersionInfoOriginalFileName in~ ("net.exe", "net1.exe")))