// Title: Suspicious Speech Runtime Binary Child Process
// Author: andrewdanis
// Date: 2025-10-23
// Level: high
// Description: Detects suspicious Speech Runtime Binary Execution by monitoring its child processes.
// Child processes spawned by SpeechRuntime.exe could indicate an attempt for lateral movement via COM & DCOM hijacking.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.lateral-movement, attack.t1021.003, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_speechruntime_child_process.yml
// False Positives:
//   - Unlikely.

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\SpeechRuntime.exe"