// Title: Uncommon System Information Discovery Via Wmic.EXE
// Author: TropChaud
// Date: 2023-01-26
// Level: medium
// Description: Detects the use of the WMI command-line (WMIC) utility to identify and display various system information,
// including OS, CPU, GPU, and disk drive names; memory capacity; display resolution; and baseboard, BIOS,
// and GPU driver products/versions.
// Some of these commands were used by Aurora Stealer in late 2022/early 2023.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1082
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wmic_recon_system_info_uncommon.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "LOGICALDISK get Name,Size,FreeSpace" or ProcessCommandLine contains "os get Caption,OSArchitecture,Version") and (ProcessVersionInfoFileDescription =~ "WMI Commandline Utility" or ProcessVersionInfoOriginalFileName =~ "wmic.exe" or FolderPath endswith "\\WMIC.exe")