// Title: Potentially Suspicious DLL Registered Via Odbcconf.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-22
// Level: high
// Description: Detects execution of "odbcconf" with the "REGSVR" action where the DLL in question doesn't contain a ".dll" extension. Which is often used as a method to evade defenses.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.008
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_odbcconf_register_dll_regsvr_susp.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (ProcessCommandLine contains "REGSVR " and (FolderPath endswith "\\odbcconf.exe" or ProcessVersionInfoOriginalFileName =~ "odbcconf.exe")) and (not(ProcessCommandLine contains ".dll"))