// Title: Compress Data and Lock With Password for Exfiltration With WINZIP
// Author: frack113
// Date: 2021-07-27
// Level: medium
// Description: An adversary may compress or encrypt data that is collected prior to exfiltration using 3rd party utilities
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1560.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_winzip_password_compression.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " -min " or ProcessCommandLine contains " -a ") and ProcessCommandLine contains "-s\"" and (ProcessCommandLine contains "winzip.exe" or ProcessCommandLine contains "winzip64.exe")