// Title: HackTool - Koadic Execution
// Author: wagga, Jonhnathan Ribeiro, oscd.community
// Date: 2020-01-12
// Level: high
// Description: Detects command line parameters used by Koadic hack tool
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.003, attack.t1059.005, attack.t1059.007
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_koadic.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "/q" and ProcessCommandLine contains "/c" and ProcessCommandLine contains "chcp") and (FolderPath endswith "\\cmd.exe" or ProcessVersionInfoOriginalFileName =~ "Cmd.Exe")