// Title: Rundll32 Execution Without Parameters
// Author: Bartlomiej Czyz, Relativity
// Date: 2021-01-31
// Level: high
// Description: Detects rundll32 execution without parameters as observed when running Metasploit windows/smb/psexec exploit module
// MITRE Tactic: Lateral Movement
// Tags: attack.lateral-movement, attack.t1021.002, attack.t1570, attack.execution, attack.t1569.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_rundll32_without_parameters.yml
// False Positives:
//   - False positives may occur if a user called rundll32 from CLI with no options

DeviceProcessEvents
| where ProcessCommandLine in~ ("rundll32.exe", "rundll32")