// Title: Nltest.EXE Execution
// Author: Arun Chauhan
// Date: 2023-02-03
// Level: low
// Description: Detects nltest commands that can be used for information discovery
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1016, attack.t1018, attack.t1482
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_nltest_execution.yml
// False Positives:
//   - Legitimate administration activity

DeviceProcessEvents
| where FolderPath endswith "\\nltest.exe" or ProcessVersionInfoOriginalFileName =~ "nltestrk.exe"