// Title: System Language Discovery via Reg.Exe
// Author: Marco Pedrinazzi (@pedrinazziM) (InTheCyber)
// Date: 2026-01-09
// Level: medium
// Description: Detects the usage of Reg.Exe to query system language settings.
// Attackers may discover the system language to determine the geographic location of victims, customize payloads for specific regions,
// or avoid targeting certain locales to evade detection.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1614.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_reg_system_language_discovery.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "query" and ProcessCommandLine contains "Control\\Nls\\Language") and (FolderPath endswith "\\reg.exe" or ProcessVersionInfoOriginalFileName =~ "reg.exe")