// Title: Kavremover Dropped Binary LOLBIN Usage
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-11-01
// Level: high
// Description: Detects the execution of a signed binary dropped by Kaspersky Lab Products Remover (kavremover) which can be abused as a LOLBIN to execute arbitrary commands and binaries.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1127
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_kavremover_uncommon_execution.yml

DeviceProcessEvents
| where ProcessCommandLine contains " run run-cmd " and (not((InitiatingProcessFolderPath endswith "\\cleanapi.exe" or InitiatingProcessFolderPath endswith "\\kavremover.exe")))