// Title: Invoke-Obfuscation CLIP+ Launcher
// Author: Jonathan Cheong, oscd.community
// Date: 2020-10-13
// Level: high
// Description: Detects Obfuscated use of Clip.exe to execute PowerShell
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_invoke_obfuscation_clip.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "/c" or ProcessCommandLine contains "/r") and (ProcessCommandLine contains "cmd" and ProcessCommandLine contains "&&" and ProcessCommandLine contains "clipboard]::" and ProcessCommandLine contains "-f")