// Title: CodePage Modification Via MODE.COM To Russian Language
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2024-01-17
// Level: medium
// Description: Detects a CodePage modification using the "mode.com" utility to Russian language.
// This behavior has been used by threat actors behind Dharma ransomware.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_mode_codepage_russian.yml
// False Positives:
//   - Russian speaking people changing the CodePage

DeviceProcessEvents
| where ((ProcessCommandLine contains " con " and ProcessCommandLine contains " cp " and ProcessCommandLine contains " select=") and (ProcessCommandLine endswith "=1251" or ProcessCommandLine endswith "=866")) and (FolderPath endswith "\\mode.com" or ProcessVersionInfoOriginalFileName =~ "MODE.COM")