// Title: Service StartupType Change Via PowerShell Set-Service
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-03-04
// Level: medium
// Description: Detects the use of the PowerShell "Set-Service" cmdlet to change the startup type of a service to "disabled" or "manual"
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_set_service_disabled.yml
// False Positives:
//   - False positives may occur with troubleshooting scripts

DeviceProcessEvents
| where ((ProcessCommandLine contains "Disabled" or ProcessCommandLine contains "Manual") and (ProcessCommandLine contains "Set-Service" and ProcessCommandLine contains "-StartupType")) and (FolderPath endswith "\\powershell.exe" or ProcessVersionInfoOriginalFileName =~ "PowerShell.EXE")