// Title: Remote Access Tool - Simple Help Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-02-23
// Level: medium
// Description: An adversary may use legitimate desktop support and remote access software, such as Team Viewer, Go2Assist, LogMein, AmmyyAdmin, etc, to establish an interactive command and control channel to target systems within networks.
// These services are commonly used as legitimate technical support software, and may be allowed by application control within a target environment.
// Remote access tools like VNC, Ammyy, and Teamviewer are used frequently when compared with other legitimate software commonly used by adversaries. (Citation: Symantec Living off the Land)
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1219.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_remote_access_tools_simple_help.yml
// False Positives:
//   - Legitimate usage of the tool

DeviceProcessEvents
| where (FolderPath contains "\\JWrapper-Remote Access\\" or FolderPath contains "\\JWrapper-Remote Support\\") and FolderPath endswith "\\SimpleService.exe"