// Title: Potential Arbitrary File Download Using Office Application
// Author: Nasreddine Bencherchali (Nextron Systems), Beyu Denis, oscd.community
// Date: 2022-05-17
// Level: high
// Description: Detects potential arbitrary file download using a Microsoft Office application
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1202
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_office_arbitrary_cli_download.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://") and ((FolderPath endswith "\\EXCEL.EXE" or FolderPath endswith "\\POWERPNT.EXE" or FolderPath endswith "\\WINWORD.exe") or (ProcessVersionInfoOriginalFileName in~ ("Excel.exe", "POWERPNT.EXE", "WinWord.exe")))