// Title: Port Forwarding Activity Via SSH.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-12
// Level: medium
// Description: Detects port forwarding activity via SSH.exe
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.lateral-movement, attack.t1572, attack.t1021.001, attack.t1021.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_ssh_port_forward.yml
// False Positives:
//   - Administrative activity using a remote port forwarding to a local port

DeviceProcessEvents
| where (ProcessCommandLine contains " -R " or ProcessCommandLine contains " /R " or ProcessCommandLine contains " –R " or ProcessCommandLine contains " —R " or ProcessCommandLine contains " ―R ") and FolderPath endswith "\\ssh.exe"