// Title: New Service Creation Using Sc.EXE
// Author: Timur Zinniatullin, Daniil Yugoslavskiy, oscd.community
// Date: 2023-02-20
// Level: low
// Description: Detects the creation of a new service using the "sc.exe" utility.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.t1543.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sc_create_service.yml
// False Positives:
//   - Legitimate administrator or user creates a service for legitimate reasons.
//   - Software installation

DeviceProcessEvents
| where ((ProcessCommandLine contains "create" and ProcessCommandLine contains "binPath") and FolderPath endswith "\\sc.exe") and (not((InitiatingProcessFolderPath endswith "\\Dropbox.exe" and (InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\Dropbox\\Client\\" or InitiatingProcessFolderPath startswith "C:\\Program Files\\Dropbox\\Client\\"))))