// Title: Disabled IE Security Features
// Author: Florian Roth (Nextron Systems)
// Date: 2020-06-19
// Level: high
// Description: Detects command lines that indicate unwanted modifications to registry keys that disable important Internet Explorer security features
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_disable_ie_features.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " -name IEHarden " and ProcessCommandLine contains " -value 0 ") or (ProcessCommandLine contains " -name DEPOff " and ProcessCommandLine contains " -value 1 ") or (ProcessCommandLine contains " -name DisableFirstRunCustomize " and ProcessCommandLine contains " -value 2 ")