// Title: Hidden Powershell in Link File Pattern
// Author: frack113
// Date: 2022-02-06
// Level: medium
// Description: Detects events that appear when a user click on a link file with a powershell command in it
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_embed_exe_lnk.yml
// False Positives:
//   - Legitimate commands in .lnk files

DeviceProcessEvents
| where (ProcessCommandLine contains "powershell" and ProcessCommandLine contains ".lnk") and FolderPath =~ "C:\\Windows\\System32\\cmd.exe" and InitiatingProcessFolderPath =~ "C:\\Windows\\explorer.exe"