// Title: Data Copied To Clipboard Via Clip.EXE
// Author: frack113
// Date: 2021-07-27
// Level: low
// Description: Detects the execution of clip.exe in order to copy data to the clipboard. Adversaries may collect data stored in the clipboard from users copying information within or between applications.
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1115
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_clip_execution.yml

DeviceProcessEvents
| where FolderPath endswith "\\clip.exe" or ProcessVersionInfoOriginalFileName =~ "clip.exe"