// Title: Sysprep on AppData Folder
// Author: Florian Roth (Nextron Systems)
// Date: 2018-06-22
// Level: medium
// Description: Detects suspicious sysprep process start with AppData folder as target (as used by Trojan Syndicasec in Thrip report by Symantec)
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sysprep_appdata.yml
// False Positives:
//   - False positives depend on scripts and administrative tools used in the monitored environment

DeviceProcessEvents
| where ProcessCommandLine contains "\\AppData\\" and FolderPath endswith "\\sysprep.exe"