// Title: File Download And Execution Via IEExec.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-05-16
// Level: high
// Description: Detects execution of the IEExec utility to download and execute files
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_ieexec_download.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://") and (FolderPath endswith "\\IEExec.exe" or ProcessVersionInfoOriginalFileName =~ "IEExec.exe")