// Title: PUA - Advanced Port Scanner Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2021-12-18
// Level: medium
// Description: Detects the use of Advanced Port Scanner.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1046, attack.t1135
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_advanced_port_scanner.yml
// False Positives:
//   - Legitimate administrative use
//   - Tools with similar commandline (very rare)

DeviceProcessEvents
| where (ProcessCommandLine contains "/portable" and ProcessCommandLine contains "/lng") or (FolderPath contains "\\advanced_port_scanner" or ProcessVersionInfoOriginalFileName contains "advanced_port_scanner" or ProcessVersionInfoFileDescription contains "Advanced Port Scanner")