// Title: Potential Defense Evasion Via Right-to-Left Override
// Author: Micah Babinski, @micahbabinski, Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2023-02-15
// Level: high
// Description: Detects the presence of the "u202+E" character, which causes a terminal, browser, or operating system to render text in a right-to-left sequence.
// This is used as an obfuscation and masquerading techniques.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_right_to_left_override.yml
// False Positives:
//   - Commandlines that contains scriptures such as arabic or hebrew might make use of this character

DeviceProcessEvents
| where ProcessCommandLine contains "\\u202e" or ProcessCommandLine contains "[U+202E]"