// Title: Mavinject Inject DLL Into Running Process
// Author: frack113, Florian Roth
// Date: 2021-07-12
// Level: high
// Description: Detects process injection using the signed Windows tool "Mavinject" via the "INJECTRUNNING" flag
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1055.001, attack.t1218.013
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_mavinject_process_injection.yml

DeviceProcessEvents
| where ProcessCommandLine contains " /INJECTRUNNING " and (not(InitiatingProcessFolderPath =~ "C:\\Windows\\System32\\AppVClient.exe"))