// Title: Potential Arbitrary DLL Load Using Winword
// Author: Victor Sergeev, oscd.community
// Date: 2020-10-09
// Level: medium
// Description: Detects potential DLL sideloading using the Microsoft Office winword process via the '/l' flag.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1202
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_office_winword_dll_load.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "/l " and ProcessCommandLine contains ".dll") and (FolderPath endswith "\\WINWORD.exe" or ProcessVersionInfoOriginalFileName =~ "WinWord.exe")