// Title: Potential Recon Activity Using DriverQuery.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-19
// Level: high
// Description: Detect usage of the "driverquery" utility to perform reconnaissance on installed drivers
// MITRE Tactic: Discovery
// Tags: attack.discovery
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_driverquery_recon.yml
// False Positives:
//   - Legitimate usage by some scripts might trigger this as well

DeviceProcessEvents
| where (FolderPath endswith "driverquery.exe" or ProcessVersionInfoOriginalFileName =~ "drvqry.exe") and ((InitiatingProcessFolderPath endswith "\\cscript.exe" or InitiatingProcessFolderPath endswith "\\mshta.exe" or InitiatingProcessFolderPath endswith "\\regsvr32.exe" or InitiatingProcessFolderPath endswith "\\rundll32.exe" or InitiatingProcessFolderPath endswith "\\wscript.exe") or (InitiatingProcessFolderPath contains "\\AppData\\Local\\" or InitiatingProcessFolderPath contains "\\Users\\Public\\" or InitiatingProcessFolderPath contains "\\Windows\\Temp\\"))