// Title: Suspicious Mstsc.EXE Execution With Local RDP File
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-04-18
// Level: high
// Description: Detects potential RDP connection via Mstsc using a local ".rdp" file located in suspicious locations.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1219.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_mstsc_run_local_rdp_file_susp_location.yml
// False Positives:
//   - Likelihood is related to how often the paths are used in the environment

DeviceProcessEvents
| where (ProcessCommandLine endswith ".rdp" or ProcessCommandLine endswith ".rdp\"") and (FolderPath endswith "\\mstsc.exe" or ProcessVersionInfoOriginalFileName =~ "mstsc.exe") and (ProcessCommandLine contains ":\\Users\\Public\\" or ProcessCommandLine contains ":\\Windows\\System32\\spool\\drivers\\color" or ProcessCommandLine contains ":\\Windows\\System32\\Tasks_Migrated " or ProcessCommandLine contains ":\\Windows\\Tasks\\" or ProcessCommandLine contains ":\\Windows\\Temp\\" or ProcessCommandLine contains ":\\Windows\\Tracing\\" or ProcessCommandLine contains "\\AppData\\Local\\Temp\\" or ProcessCommandLine contains "\\Downloads\\")