// Title: Group Membership Reconnaissance Via Whoami.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-28
// Level: medium
// Description: Detects the execution of whoami.exe with the /group command line flag to show group membership for the current user, account type, security identifiers (SID), and attributes.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1033
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_whoami_groups_discovery.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " /groups" or ProcessCommandLine contains " -groups") and (FolderPath endswith "\\whoami.exe" or ProcessVersionInfoOriginalFileName =~ "whoami.exe")