// Title: Attempts of Kerberos Coercion Via DNS SPN Spoofing
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-06-20
// Level: high
// Description: Detects the presence of "UWhRC....AAYBAAAA" pattern in command line.
// The pattern "1UWhRCAAAAA..BAAAA" is a base64-encoded signature that corresponds to a marshaled CREDENTIAL_TARGET_INFORMATION structure.
// Attackers can use this technique to coerce authentication from victim systems to attacker-controlled hosts.
// It is one of the strong indicators of a Kerberos coercion attack, where adversaries manipulate DNS records
// to spoof Service Principal Names (SPNs) and redirect authentication requests like in CVE-2025-33073.
// If you see this pattern in the command line, it is likely an attempt to add spoofed Service Principal Names (SPNs) to DNS records,
// or checking for the presence of such records through the `nslookup` command.
// MITRE Tactic: Collection
// Tags: attack.collection, attack.credential-access, attack.persistence, attack.privilege-escalation, attack.t1557.001, attack.t1187
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_kerberos_coercion_via_dns_spn_spoofing.yml

DeviceProcessEvents
| where ProcessCommandLine contains "UWhRCA" and ProcessCommandLine contains "BAAAA"