// Title: Regedit as Trusted Installer
// Author: Florian Roth (Nextron Systems)
// Date: 2021-05-27
// Level: high
// Description: Detects a regedit started with TrustedInstaller privileges or by ProcessHacker.exe
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1548
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_regedit_trustedinstaller.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where FolderPath endswith "\\regedit.exe" and (InitiatingProcessFolderPath endswith "\\TrustedInstaller.exe" or InitiatingProcessFolderPath endswith "\\ProcessHacker.exe")