// Title: HackTool - Pypykatz Credentials Dumping Activity
// Author: frack113
// Date: 2022-01-05
// Level: high
// Description: Detects the usage of "pypykatz" to obtain stored credentials. Adversaries may attempt to extract credential material from the Security Account Manager (SAM) database through Windows registry where the SAM database is stored
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_pypykatz.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "live" and ProcessCommandLine contains "registry") and (FolderPath endswith "\\pypykatz.exe" or FolderPath endswith "\\python.exe")