// Title: Suspicious Windows Trace ETW Session Tamper Via Logman.EXE
// Author: Florian Roth (Nextron Systems)
// Date: 2021-02-11
// Level: high
// Description: Detects the execution of "logman" utility in order to disable or delete Windows trace sessions
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001, attack.t1070.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_logman_disable_eventlog.yml
// False Positives:
//   - Legitimate deactivation by administrative staff
//   - Installer tools that disable services, e.g. before log collection agent installation

DeviceProcessEvents
| where (ProcessCommandLine contains "stop " or ProcessCommandLine contains "delete ") and (FolderPath endswith "\\logman.exe" or ProcessVersionInfoOriginalFileName =~ "Logman.exe") and (ProcessCommandLine contains "Circular Kernel Context Logger" or ProcessCommandLine contains "EventLog-" or ProcessCommandLine contains "SYSMON TRACE" or ProcessCommandLine contains "SysmonDnsEtwSession")