// Title: New Network Trace Capture Started Via Netsh.EXE
// Author: Kutepov Anton, oscd.community
// Date: 2019-10-24
// Level: medium
// Description: Detects the execution of netsh with the "trace" flag in order to start a network capture
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.credential-access, attack.t1040
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_netsh_packet_capture.yml
// False Positives:
//   - Legitimate administration activity

DeviceProcessEvents
| where (ProcessCommandLine contains "trace" and ProcessCommandLine contains "start") and (FolderPath endswith "\\netsh.exe" or ProcessVersionInfoOriginalFileName =~ "netsh.exe")