// Title: MMC Spawning Windows Shell
// Author: Karneades, Swisscom CSIRT
// Date: 2019-08-05
// Level: high
// Description: Detects a Windows command line executable started from MMC
// MITRE Tactic: Lateral Movement
// Tags: attack.lateral-movement, attack.t1021.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_mmc_susp_child_process.yml

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\mmc.exe" and ((FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\wscript.exe" or FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\sh.exe" or FolderPath endswith "\\bash.exe" or FolderPath endswith "\\reg.exe" or FolderPath endswith "\\regsvr32.exe") or FolderPath contains "\\BITSADMIN")