// Title: NodeJS Execution of JavaScript File
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-04-21
// Level: low
// Description: Detects execution of JavaScript or JSC files using NodeJs binary node.exe, that could be potentially suspicious.
// Node.js is a popular open-source JavaScript runtime that runs code outside browsers and is widely used for both frontend and backend development.
// Adversaries have been observed abusing Node.js to disguise malware as legitimate processes, evade security defenses, and maintain persistence within target systems.
// Because Node.js is commonly used, this rule may generate false positives in some environments. However, if such activity is unusual in your environment, it is highly suspicious and warrants immediate investigation.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.007
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_security_susp_node_js_execution.yml
// False Positives:
//   - Legitimate use of node.exe to execute JavaScript or JSC files on your environment

DeviceProcessEvents
| where ProcessCommandLine contains ".js" and (FolderPath endswith "\\node.exe" or ProcessVersionInfoOriginalFileName =~ "node.exe" or ProcessVersionInfoProductName =~ "Node.js")