// Title: Suspicious Cabinet File Execution Via Msdt.EXE
// Author: Nasreddine Bencherchali (Nextron Systems), GossiTheDog, frack113
// Date: 2022-06-21
// Level: medium
// Description: Detects execution of msdt.exe using the "cab" flag which could indicates suspicious diagcab files with embedded answer files leveraging CVE-2022-30190
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1202
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_msdt_susp_cab_options.yml
// False Positives:
//   - Legitimate usage of ".diagcab" files

DeviceProcessEvents
| where (ProcessCommandLine contains " -cab " or ProcessCommandLine contains " /cab " or ProcessCommandLine contains " –cab " or ProcessCommandLine contains " —cab " or ProcessCommandLine contains " ―cab ") and (FolderPath endswith "\\msdt.exe" or ProcessVersionInfoOriginalFileName =~ "msdt.exe")