// Title: New ActiveScriptEventConsumer Created Via Wmic.EXE
// Author: Florian Roth (Nextron Systems)
// Date: 2021-06-25
// Level: high
// Description: Detects WMIC executions in which an event consumer gets created. This could be used to establish persistence
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1546.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wmic_eventconsumer_creation.yml
// False Positives:
//   - Legitimate software creating script event consumers

DeviceProcessEvents
| where ProcessCommandLine contains "ActiveScriptEventConsumer" and ProcessCommandLine contains " CREATE "