// Title: New Firewall Rule Added Via Netsh.EXE
// Author: Markus Neis, Sander Wiebing
// Date: 2019-01-29
// Level: medium
// Description: Detects the addition of a new rule to the Windows firewall via netsh
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.004, attack.s0246
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_netsh_fw_add_rule.yml
// False Positives:
//   - Legitimate administration activity
//   - Software installations

DeviceProcessEvents
| where ((ProcessCommandLine contains " firewall " and ProcessCommandLine contains " add ") and (FolderPath endswith "\\netsh.exe" or ProcessVersionInfoOriginalFileName =~ "netsh.exe")) and (not(((ProcessCommandLine contains "advfirewall firewall add rule name=Dropbox dir=in action=allow \"program=" and ProcessCommandLine contains ":\\Program Files (x86)\\Dropbox\\Client\\Dropbox.exe\" enable=yes profile=Any") or (ProcessCommandLine contains "advfirewall firewall add rule name=Dropbox dir=in action=allow \"program=" and ProcessCommandLine contains ":\\Program Files\\Dropbox\\Client\\Dropbox.exe\" enable=yes profile=Any"))))