// Title: Suspicious FromBase64String Usage On Gzip Archive - Process Creation
// Author: frack113
// Date: 2022-12-23
// Level: medium
// Description: Detects attempts of decoding a base64 Gzip archive via PowerShell. This technique is often used as a method to load malicious content into memory afterward.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1132.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_frombase64string_archive.yml
// False Positives:
//   - Legitimate administrative script

DeviceProcessEvents
| where ProcessCommandLine contains "FromBase64String" and ProcessCommandLine contains "MemoryStream" and ProcessCommandLine contains "H4sI"