// Title: PDQ Deploy Remote Adminstartion Tool Execution
// Author: frack113
// Date: 2022-10-01
// Level: medium
// Description: Detect use of PDQ Deploy remote admin tool
// MITRE Tactic: Execution
// Tags: attack.execution, attack.lateral-movement, attack.t1072
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pdqdeploy_execution.yml
// False Positives:
//   - Legitimate use

DeviceProcessEvents
| where ProcessVersionInfoFileDescription =~ "PDQ Deploy Console" or ProcessVersionInfoProductName =~ "PDQ Deploy" or ProcessVersionInfoCompanyName =~ "PDQ.com" or ProcessVersionInfoOriginalFileName =~ "PDQDeployConsole.exe"