// Title: Windows Share Mount Via Net.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-02
// Level: low
// Description: Detects when a share is mounted using the "net.exe" utility
// MITRE Tactic: Lateral Movement
// Tags: attack.lateral-movement, attack.t1021.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_net_use_mount_share.yml
// False Positives:
//   - Legitimate activity by administrators and scripts

DeviceProcessEvents
| where (ProcessCommandLine contains " use " or ProcessCommandLine contains " \\\\") and ((FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe") or (ProcessVersionInfoOriginalFileName in~ ("net.exe", "net1.exe")))