// Title: Import LDAP Data Interchange Format File Via Ldifde.EXE
// Author: @gott_cyber
// Date: 2022-09-02
// Level: medium
// Description: Detects the execution of "Ldifde.exe" with the import flag "-i". The can be abused to include HTTP-based arguments which will allow the arbitrary download of files from a remote server.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.defense-evasion, attack.t1218, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_ldifde_file_load.yml
// False Positives:
//   - Since the content of the files are unknown, false positives are expected

DeviceProcessEvents
| where (ProcessCommandLine contains "-i" and ProcessCommandLine contains "-f") and (FolderPath endswith "\\ldifde.exe" or ProcessVersionInfoOriginalFileName =~ "ldifde.exe")