// Title: Use of UltraVNC Remote Access Software
// Author: frack113
// Date: 2022-10-02
// Level: medium
// Description: An adversary may use legitimate desktop support and remote access software,to establish an interactive command and control channel to target systems within networks
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1219.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_ultravnc.yml
// False Positives:
//   - Legitimate use

DeviceProcessEvents
| where ProcessVersionInfoFileDescription =~ "VNCViewer" or ProcessVersionInfoProductName =~ "UltraVNC VNCViewer" or ProcessVersionInfoCompanyName =~ "UltraVNC" or ProcessVersionInfoOriginalFileName =~ "VNCViewer.exe"