// Title: PUA - Nmap/Zenmap Execution
// Author: frack113
// Date: 2021-12-10
// Level: medium
// Description: Detects usage of namp/zenmap. Adversaries may attempt to get a listing of services running on remote hosts, including those that may be vulnerable to remote software exploitation
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1046
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_nmap_zenmap.yml
// False Positives:
//   - Legitimate administrator activity

DeviceProcessEvents
| where (FolderPath endswith "\\nmap.exe" or FolderPath endswith "\\zennmap.exe") or (ProcessVersionInfoOriginalFileName in~ ("nmap.exe", "zennmap.exe"))