// Title: C# IL Code Compilation Via Ilasm.EXE
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-05-07
// Level: medium
// Description: Detects the use of "Ilasm.EXE" in order to compile C# intermediate (IL) code to EXE or DLL.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1127
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_ilasm_il_code_compilation.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " /dll" or ProcessCommandLine contains " /exe") and (FolderPath endswith "\\ilasm.exe" or ProcessVersionInfoOriginalFileName =~ "ilasm.exe")