// Title: New User Created Via Net.EXE
// Author: Endgame, JHasenbusch (adapted to Sigma for oscd.community)
// Date: 2018-10-30
// Level: medium
// Description: Identifies the creation of local users via the net.exe command.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1136.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_net_user_add.yml
// False Positives:
//   - Legitimate user creation.
//   - Better use event IDs for user creation rather than command line rules.

DeviceProcessEvents
| where (ProcessCommandLine contains "user" and ProcessCommandLine contains "add") and ((FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe") or (ProcessVersionInfoOriginalFileName in~ ("net.exe", "net1.exe")))