// Title: Node Process Executions
// Author: Max Altgelt (Nextron Systems)
// Date: 2022-04-06
// Level: medium
// Description: Detects the execution of other scripts using the Node executable packaged with Adobe Creative Cloud
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1127, attack.t1059.007
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_node_adobe_creative_cloud_abuse.yml

DeviceProcessEvents
| where FolderPath endswith "\\Adobe Creative Cloud Experience\\libs\\node.exe" and (not(ProcessCommandLine contains "Adobe Creative Cloud Experience\\js"))