// Title: Suspicious File Characteristics Due to Missing Fields
// Author: Markus Neis, Sander Wiebing
// Date: 2018-11-22
// Level: medium
// Description: Detects Executables in the Downloads folder without FileVersion,Description,Product,Company likely created with py2exe
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.006
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_file_characteristics.yml

DeviceProcessEvents
| where ((ProcessVersionInfoFileDescription =~ "?" and ProcessVersionInfoProductVersion =~ "?") or (ProcessVersionInfoFileDescription =~ "?" and ProcessVersionInfoProductName =~ "?") or (ProcessVersionInfoCompanyName =~ "?" and ProcessVersionInfoFileDescription =~ "?")) and FolderPath contains "\\Downloads\\"