// Title: HackTool - SharpEvtMute Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-09-07
// Level: high
// Description: Detects the use of SharpEvtHook, a tool that tampers with the Windows event logs
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_sharpevtmute.yml

DeviceProcessEvents
| where FolderPath endswith "\\SharpEvtMute.exe" or ProcessVersionInfoFileDescription =~ "SharpEvtMute" or (ProcessCommandLine contains "--Filter \"rule " or ProcessCommandLine contains "--Encoded --Filter \\\"")