// Title: RegAsm.EXE Execution Without CommandLine Flags or Files
// Author: frack113
// Date: 2025-06-04
// Level: low
// Description: Detects the execution of "RegAsm.exe" without a commandline flag or file, which might indicate potential process injection activity.
// Usually "RegAsm.exe" should point to a dedicated DLL file or call the help with the "/?" flag.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.009
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_regasm_no_flag_or_dll_execution.yml
// False Positives:
//   - Legitimate use of Regasm by developers.

DeviceProcessEvents
| where (ProcessCommandLine endswith "RegAsm" or ProcessCommandLine endswith "RegAsm.exe" or ProcessCommandLine endswith "RegAsm.exe\"" or ProcessCommandLine endswith "RegAsm.exe'") and (FolderPath endswith "\\RegAsm.exe" or ProcessVersionInfoOriginalFileName =~ "RegAsm.exe")