// Title: File Download From IP Based URL Via CertOC.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-10-18
// Level: high
// Description: Detects when a user downloads a file from an IP based URL using CertOC.exe
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.execution, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_certoc_download_direct_ip.yml

DeviceProcessEvents
| where ProcessCommandLine contains "-GetCACAPS" and (FolderPath endswith "\\certoc.exe" or ProcessVersionInfoOriginalFileName =~ "CertOC.exe") and ProcessCommandLine matches regex "://[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}"