// Title: Suspicious Network Command
// Author: frack113, Christopher Peacock '@securepeacock', SCYTHE '@scythe_io'
// Date: 2021-12-07
// Level: low
// Description: Adversaries may look for details about the network configuration and settings of systems they access or through information discovery of remote systems
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1016
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_network_command.yml
// False Positives:
//   - Administrator, hotline ask to user

DeviceProcessEvents
| where ProcessCommandLine matches regex "ipconfig\\s+/all" or ProcessCommandLine matches regex "netsh\\s+interface show interface" or ProcessCommandLine matches regex "arp\\s+-a" or ProcessCommandLine matches regex "nbtstat\\s+-n" or ProcessCommandLine matches regex "net\\s+config" or ProcessCommandLine matches regex "route\\s+print"