// Title: Potential Renamed Rundll32 Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-22
// Level: high
// Description: Detects when 'DllRegisterServer' is called in the commandline and the image is not rundll32. This could mean that the 'rundll32' utility has been renamed in order to avoid detection
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_renamed_rundll32_dllregisterserver.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains "DllRegisterServer" and (not(FolderPath endswith "\\rundll32.exe"))