// Title: Potential Powershell ReverseShell Connection
// Author: FPT.EagleEye, wagga, Nasreddine Bencherchali (Nextron Systems)
// Date: 2021-03-03
// Level: high
// Description: Detects usage of the "TcpClient" class. Which can be abused to establish remote connections and reverse-shells. As seen used by the Nishang "Invoke-PowerShellTcpOneLine" reverse shell and other.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_reverse_shell_connection.yml
// False Positives:
//   - In rare administrative cases, this function might be used to check network connectivity

DeviceProcessEvents
| where (ProcessCommandLine contains " Net.Sockets.TCPClient" and ProcessCommandLine contains ".GetStream(" and ProcessCommandLine contains ".Write(") and ((ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")) or (FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe"))