// Title: Potential Cookies Session Hijacking
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-07-27
// Level: medium
// Description: Detects execution of "curl.exe" with the "-c" flag in order to save cookie data.
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_curl_cookie_hijacking.yml

DeviceProcessEvents
| where (ProcessCommandLine matches regex "\\s-c\\s" or ProcessCommandLine contains "--cookie-jar") and (FolderPath endswith "\\curl.exe" or ProcessVersionInfoOriginalFileName =~ "curl.exe")