// Title: RunDLL32 Spawning Explorer
// Author: elhoim, CD_ROM_
// Date: 2022-04-27
// Level: high
// Description: Detects RunDLL32.exe spawning explorer.exe as child, which is very uncommon, often observes Gamarue spawning the explorer.exe process in an unusual way
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.011
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_rundll32_spawn_explorer.yml

DeviceProcessEvents
| where (FolderPath endswith "\\explorer.exe" and InitiatingProcessFolderPath endswith "\\rundll32.exe") and (not(InitiatingProcessCommandLine contains "\\shell32.dll,Control_RunDLL"))