// Title: Suspicious SYSVOL Domain Group Policy Access
// Author: Markus Neis, Jonhnathan Ribeiro, oscd.community
// Date: 2018-04-09
// Level: medium
// Description: Detects Access to Domain Group Policies stored in SYSVOL
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1552.006
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_sysvol_access.yml
// False Positives:
//   - Administrative activity

DeviceProcessEvents
| where ProcessCommandLine contains "\\SYSVOL\\" and ProcessCommandLine contains "\\policies\\"