// Title: Visual Studio NodejsTools PressAnyKey Arbitrary Binary Execution
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-01-11
// Level: medium
// Description: Detects child processes of Microsoft.NodejsTools.PressAnyKey.exe that can be used to execute any other binary
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pressanykey_lolbin_execution.yml
// False Positives:
//   - Legitimate use by developers as part of NodeJS development with Visual Studio Tools

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\Microsoft.NodejsTools.PressAnyKey.exe"