// Title: DirLister Execution
// Author: frack113
// Date: 2022-08-20
// Level: low
// Description: Detect the usage of "DirLister.exe" a utility for quickly listing folder or drive contents. It was seen used by BlackCat ransomware to create a list of accessible directories and files.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1083
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_dirlister_execution.yml
// False Positives:
//   - Legitimate use by users

DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "DirLister.exe" or FolderPath endswith "\\DirLister.exe"