// Title: Scheduled Task Creation with Curl and PowerShell Execution Combo
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-02-05
// Level: medium
// Description: Detects the creation of a scheduled task using schtasks.exe, potentially in combination with curl for downloading payloads and PowerShell for executing them.
// This facilitates executing malicious payloads or connecting with C&C server persistently without dropping the malware sample on the host.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.execution, attack.persistence, attack.t1053.005, attack.defense-evasion, attack.t1218, attack.command-and-control, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_schtasks_curl_and_powershell_combo.yml
// False Positives:
//   - Legitimate use of schtasks for administrative purposes.
//   - Automation scripts combining curl and PowerShell in controlled environments.

DeviceProcessEvents
| where (ProcessCommandLine contains "curl " and ProcessCommandLine contains "http" and ProcessCommandLine contains "-o") and ((ProcessCommandLine contains " -create " or ProcessCommandLine contains " /create " or ProcessCommandLine contains " –create " or ProcessCommandLine contains " —create " or ProcessCommandLine contains " ―create ") and FolderPath endswith "\\schtasks.exe") and ProcessCommandLine contains "powershell"