// Title: Renamed Whoami Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2021-08-12
// Level: critical
// Description: Detects the execution of whoami that has been renamed to a different name to avoid detection
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1033, car.2016-03-001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_renamed_whoami.yml

DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "whoami.exe" and (not(FolderPath endswith "\\whoami.exe"))