// Title: Potential ReflectDebugger Content Execution Via WerFault.EXE
// Author: X__Junior (Nextron Systems)
// Date: 2023-06-30
// Level: medium
// Description: Detects execution of "WerFault.exe" with the "-pr" commandline flag that is used to run files stored in the ReflectDebugger key which could be used to store the path to the malware in order to masquerade the execution flow
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, attack.t1036
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_werfault_reflect_debugger_exec.yml

DeviceProcessEvents
| where ProcessCommandLine contains " -pr " and (FolderPath endswith "\\WerFault.exe" or ProcessVersionInfoOriginalFileName =~ "WerFault.exe")