// Title: HackTool - SafetyKatz Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-20
// Level: critical
// Description: Detects the execution of the hacktool SafetyKatz via PE information and default Image name
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_safetykatz.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where FolderPath endswith "\\SafetyKatz.exe" or ProcessVersionInfoOriginalFileName =~ "SafetyKatz.exe" or ProcessVersionInfoFileDescription =~ "SafetyKatz"