// Title: Cscript/Wscript Uncommon Script Extension Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-15
// Level: high
// Description: Detects Wscript/Cscript executing a file with an uncommon (i.e. non-script) extension
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.005, attack.t1059.007
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wscript_cscript_uncommon_extension_exec.yml

DeviceProcessEvents
| where (ProcessCommandLine contains ".csv" or ProcessCommandLine contains ".dat" or ProcessCommandLine contains ".doc" or ProcessCommandLine contains ".gif" or ProcessCommandLine contains ".jpeg" or ProcessCommandLine contains ".jpg" or ProcessCommandLine contains ".png" or ProcessCommandLine contains ".ppt" or ProcessCommandLine contains ".txt" or ProcessCommandLine contains ".xls" or ProcessCommandLine contains ".xml") and ((ProcessVersionInfoOriginalFileName in~ ("wscript.exe", "cscript.exe")) or (FolderPath endswith "\\wscript.exe" or FolderPath endswith "\\cscript.exe"))