// Title: File Recovery From Backup Via Wbadmin.EXE
// Author: Nasreddine Bencherchali (Nextron Systems), frack113
// Date: 2024-05-10
// Level: medium
// Description: Detects the recovery of files from backups via "wbadmin.exe".
// Attackers can restore sensitive files such as NTDS.DIT or Registry Hives from backups in order to potentially extract credentials.
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1490
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wbadmin_restore_file.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " recovery" and ProcessCommandLine contains "recoveryTarget" and ProcessCommandLine contains "itemtype:File") and (FolderPath endswith "\\wbadmin.exe" or ProcessVersionInfoOriginalFileName =~ "WBADMIN.EXE")