// Title: MSDT Execution Via Answer File
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-13
// Level: high
// Description: Detects execution of "msdt.exe" using an answer file which is simulating the legitimate way of calling msdt via "pcwrun.exe" (For example from the compatibility tab).
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218, attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_msdt_answer_file_exec.yml
// False Positives:
//   - Possible undocumented parents of "msdt" other than "pcwrun".

DeviceProcessEvents
| where (ProcessCommandLine contains "\\WINDOWS\\diagnostics\\index\\PCWDiagnostic.xml" and (ProcessCommandLine contains " -af " or ProcessCommandLine contains " /af " or ProcessCommandLine contains " –af " or ProcessCommandLine contains " —af " or ProcessCommandLine contains " ―af ") and FolderPath endswith "\\msdt.exe") and (not(InitiatingProcessFolderPath endswith "\\pcwrun.exe"))