// Title: RunMRU Registry Key Deletion
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-09-25
// Level: high
// Description: Detects deletion of the RunMRU registry key, which stores the history of commands executed via the Run dialog.
// In the clickfix techniques, the phishing lures instruct users to open a run dialog through (Win + R) and execute malicious commands.
// Adversaries may delete this key to cover their tracks after executing commands.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1070.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_reg_delete_runmru.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " del" and ProcessCommandLine contains "\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RunMRU") and (FolderPath endswith "\\reg.exe" or ProcessVersionInfoOriginalFileName =~ "reg.exe")