// Title: New Root Certificate Installed Via Certutil.EXE
// Author: oscd.community, @redcanary, Zach Stanford @svch0st
// Date: 2023-03-05
// Level: medium
// Description: Detects execution of "certutil" with the "addstore" flag in order to install a new certificate on the system.
// Adversaries may install a root certificate on a compromised system to avoid warnings when connecting to adversary controlled web servers.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1553.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_certutil_certificate_installation.yml
// False Positives:
//   - Help Desk or IT may need to manually add a corporate Root CA on occasion. Need to test if GPO push doesn't trigger FP

DeviceProcessEvents
| where (ProcessCommandLine contains "-addstore" or ProcessCommandLine contains "/addstore" or ProcessCommandLine contains "–addstore" or ProcessCommandLine contains "—addstore" or ProcessCommandLine contains "―addstore") and ProcessCommandLine contains "root" and (FolderPath endswith "\\certutil.exe" or ProcessVersionInfoOriginalFileName =~ "CertUtil.exe")