// Title: Phishing Pattern ISO in Archive
// Author: Florian Roth (Nextron Systems)
// Date: 2022-06-07
// Level: high
// Description: Detects cases in which an ISO files is opend within an archiver like 7Zip or Winrar, which is a sign of phishing as threat actors put small ISO files in archives as email attachments to bypass certain filters and protective measures (mark of web)
// MITRE Tactic: Initial Access
// Tags: attack.initial-access, attack.t1566
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_archiver_iso_phishing.yml
// False Positives:
//   - Legitimate cases in which archives contain ISO or IMG files and the user opens the archive and the image via clicking and not extraction

DeviceProcessEvents
| where (FolderPath endswith "\\isoburn.exe" or FolderPath endswith "\\PowerISO.exe" or FolderPath endswith "\\ImgBurn.exe") and (InitiatingProcessFolderPath endswith "\\Winrar.exe" or InitiatingProcessFolderPath endswith "\\7zFM.exe" or InitiatingProcessFolderPath endswith "\\peazip.exe")