// Title: Unsigned AppX Installation Attempt Using Add-AppxPackage
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-31
// Level: medium
// Description: Detects usage of the "Add-AppxPackage" or it's alias "Add-AppPackage" to install unsigned AppX packages
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_install_unsigned_appx_packages.yml
// False Positives:
//   - Installation of unsigned packages for testing purposes

DeviceProcessEvents
| where (ProcessCommandLine contains "Add-AppPackage " or ProcessCommandLine contains "Add-AppxPackage ") and ProcessCommandLine contains " -AllowUnsigned" and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")))