// Title: Potential Persistence Via VMwareToolBoxCmd.EXE VM State Change Script
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-14
// Level: medium
// Description: Detects execution of the "VMwareToolBoxCmd.exe" with the "script" and "set" flag to setup a specific script to run for a specific VM state
// MITRE Tactic: Execution
// Tags: attack.execution, attack.persistence, attack.t1059
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_vmware_toolbox_cmd_persistence.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " script " and ProcessCommandLine contains " set ") and (FolderPath endswith "\\VMwareToolBoxCmd.exe" or ProcessVersionInfoOriginalFileName =~ "toolbox-cmd.exe")