// Title: New Remote Desktop Connection Initiated Via Mstsc.EXE
// Author: frack113
// Date: 2022-01-07
// Level: medium
// Description: Detects the usage of "mstsc.exe" with the "/v" flag to initiate a connection to a remote server.
// Adversaries may use valid accounts to log into a computer using the Remote Desktop Protocol (RDP). The adversary may then perform actions as the logged-on user.
// MITRE Tactic: Lateral Movement
// Tags: attack.lateral-movement, attack.t1021.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_mstsc_remote_connection.yml
// False Positives:
//   - WSL (Windows Sub System For Linux)

DeviceProcessEvents
| where ((ProcessCommandLine contains " -v:" or ProcessCommandLine contains " /v:" or ProcessCommandLine contains " –v:" or ProcessCommandLine contains " —v:" or ProcessCommandLine contains " ―v:") and (FolderPath endswith "\\mstsc.exe" or ProcessVersionInfoOriginalFileName =~ "mstsc.exe")) and (not((ProcessCommandLine contains "C:\\ProgramData\\Microsoft\\WSL\\wslg.rdp" and InitiatingProcessFolderPath =~ "C:\\Windows\\System32\\lxss\\wslhost.exe")))