// Title: Potentially Suspicious Regsvr32 HTTP/FTP Pattern
// Author: Florian Roth (Nextron Systems)
// Date: 2023-05-24
// Level: medium
// Description: Detects regsvr32 execution to download/install/register new DLLs that are hosted on Web or FTP servers.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.010
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_regsvr32_network_pattern.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " /i" or ProcessCommandLine contains " -i") and (FolderPath endswith "\\regsvr32.exe" or ProcessVersionInfoOriginalFileName =~ "REGSVR32.EXE") and (ProcessCommandLine contains "ftp" or ProcessCommandLine contains "http")