// Title: PUA - Radmin Viewer Utility Execution
// Author: frack113
// Date: 2022-01-22
// Level: medium
// Description: Detects the execution of Radmin which can be abused by an adversary to remotely control Windows machines
// MITRE Tactic: Execution
// Tags: attack.execution, attack.lateral-movement, attack.t1072
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_radmin.yml

DeviceProcessEvents
| where ProcessVersionInfoFileDescription =~ "Radmin Viewer" or ProcessVersionInfoProductName =~ "Radmin Viewer" or ProcessVersionInfoOriginalFileName =~ "Radmin.exe"