// Title: File Download Using Notepad++ GUP Utility
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-10
// Level: high
// Description: Detects execution of the Notepad++ updater (gup) from a process other than Notepad++ to download files.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_gup_download.yml
// False Positives:
//   - Other parent processes other than notepad++ using GUP that are not currently identified

DeviceProcessEvents
| where ((ProcessCommandLine contains " -unzipTo " and ProcessCommandLine contains "http") and (FolderPath endswith "\\GUP.exe" or ProcessVersionInfoOriginalFileName =~ "gup.exe")) and (not(InitiatingProcessFolderPath endswith "\\notepad++.exe"))