// Title: Sysinternals PsSuspend Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-03-23
// Level: medium
// Description: Detects usage of Sysinternals PsSuspend which can be abused to suspend critical processes
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.discovery, attack.persistence, attack.t1543.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sysinternals_pssuspend_execution.yml

DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "pssuspend.exe" or (FolderPath endswith "\\pssuspend.exe" or FolderPath endswith "\\pssuspend64.exe")