// Title: MSExchange Transport Agent Installation
// Author: Tobias Michalski (Nextron Systems)
// Date: 2021-06-08
// Level: medium
// Description: Detects the Installation of a Exchange Transport Agent
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1505.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_msexchange_transport_agent.yml
// False Positives:
//   - Legitimate installations of exchange TransportAgents. AssemblyPath is a good indicator for this.

DeviceProcessEvents
| where ProcessCommandLine contains "Install-TransportAgent"