// Title: Suspicious Processes Spawned by WinRM
// Author: Andreas Hunkeler (@Karneades), Markus Neis
// Date: 2021-05-20
// Level: high
// Description: Detects suspicious processes including shells spawnd from WinRM host process
// MITRE Tactic: Initial Access
// Tags: attack.t1190, attack.initial-access, attack.persistence, attack.privilege-escalation
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_winrm_susp_child_process.yml
// False Positives:
//   - Legitimate WinRM usage

DeviceProcessEvents
| where (FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\sh.exe" or FolderPath endswith "\\bash.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\wsl.exe" or FolderPath endswith "\\schtasks.exe" or FolderPath endswith "\\certutil.exe" or FolderPath endswith "\\whoami.exe" or FolderPath endswith "\\bitsadmin.exe") and InitiatingProcessFolderPath endswith "\\wsmprovhost.exe"