// Title: Potential Ransomware or Unauthorized MBR Tampering Via Bcdedit.EXE
// Author: @neu5ron
// Date: 2019-02-07
// Level: medium
// Description: Detects potential malicious and unauthorized usage of bcdedit.exe
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1070, attack.persistence, attack.t1542.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_bcdedit_susp_execution.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "delete" or ProcessCommandLine contains "deletevalue" or ProcessCommandLine contains "import" or ProcessCommandLine contains "safeboot" or ProcessCommandLine contains "network") and (FolderPath endswith "\\bcdedit.exe" or ProcessVersionInfoOriginalFileName =~ "bcdedit.exe")