// Title: Conhost.exe CommandLine Path Traversal
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-14
// Level: high
// Description: detects the usage of path traversal in conhost.exe indicating possible command/argument confusion/hijacking
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_conhost_path_traversal.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains "/../../" and InitiatingProcessCommandLine contains "conhost"