// Title: Enumerate All Information With Whoami.EXE
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-12-04
// Level: medium
// Description: Detects the execution of "whoami.exe" with the "/all" flag
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1033, car.2016-03-001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_whoami_all_execution.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " -all" or ProcessCommandLine contains " /all" or ProcessCommandLine contains " –all" or ProcessCommandLine contains " —all" or ProcessCommandLine contains " ―all") and (FolderPath endswith "\\whoami.exe" or ProcessVersionInfoOriginalFileName =~ "whoami.exe")