// Title: Potential Memory Dumping Activity Via LiveKD
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-15
// Level: medium
// Description: Detects execution of LiveKD based on PE metadata or image name
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sysinternals_livekd_execution.yml
// False Positives:
//   - Administration and debugging activity (must be investigated)

DeviceProcessEvents
| where (FolderPath endswith "\\livekd.exe" or FolderPath endswith "\\livekd64.exe") or ProcessVersionInfoOriginalFileName =~ "livekd.exe"