// Title: PUA - CsExec Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-08-22
// Level: high
// Description: Detects the use of the lesser known remote execution tool named CsExec a PsExec alternative
// MITRE Tactic: Resource Development
// Tags: attack.resource-development, attack.t1587.001, attack.execution, attack.t1569.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_csexec.yml

DeviceProcessEvents
| where FolderPath endswith "\\csexec.exe" or ProcessVersionInfoFileDescription =~ "csexec"