// Title: QuickAssist Execution
// Author: Muhammad Faisal (@faisalusuf)
// Date: 2024-12-19
// Level: low
// Description: Detects the execution of Microsoft Quick Assist tool "QuickAssist.exe". This utility can be used by attackers to gain remote access.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1219.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_quickassist_execution.yml
// False Positives:
//   - Legitimate use of Quick Assist in the environment.

DeviceProcessEvents
| where FolderPath endswith "\\QuickAssist.exe"