// Title: Kernel Memory Dump Via LiveKD
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-16
// Level: high
// Description: Detects execution of LiveKD with the "-m" flag to potentially dump the kernel memory
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sysinternals_livekd_kernel_memory_dump.yml
// False Positives:
//   - Unlikely in production environment

DeviceProcessEvents
| where (ProcessCommandLine contains " -m" or ProcessCommandLine contains " /m" or ProcessCommandLine contains " –m" or ProcessCommandLine contains " —m" or ProcessCommandLine contains " ―m") and ((FolderPath endswith "\\livekd.exe" or FolderPath endswith "\\livekd64.exe") or ProcessVersionInfoOriginalFileName =~ "livekd.exe")