// Title: Service StartupType Change Via Sc.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-01
// Level: medium
// Description: Detect the use of "sc.exe" to change the startup type of a service to "disabled" or "demand"
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sc_disable_service.yml
// False Positives:
//   - False positives may occur with troubleshooting scripts

DeviceProcessEvents
| where ((ProcessCommandLine contains "disabled" or ProcessCommandLine contains "demand") and (ProcessCommandLine contains " config " and ProcessCommandLine contains "start")) and (FolderPath endswith "\\sc.exe" or ProcessVersionInfoOriginalFileName =~ "sc.exe")