// Title: Hiding User Account Via SpecialAccounts Registry Key - CommandLine
// Author: @Kostastsale, TheDFIRReport
// Date: 2022-05-14
// Level: medium
// Description: Detects changes to the registry key "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\SpecialAccounts\Userlist" where the value is set to "0" in order to hide user account from being listed on the logon screen.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1564.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_registry_special_accounts_hide_user.yml
// False Positives:
//   - System administrator activities

DeviceProcessEvents
| where (ProcessCommandLine contains "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\SpecialAccounts\\UserList" and ProcessCommandLine contains "add" and ProcessCommandLine contains "/v" and ProcessCommandLine contains "/d 0") and FolderPath endswith "\\reg.exe"