// Title: Start of NT Virtual DOS Machine
// Author: frack113
// Date: 2022-07-16
// Level: medium
// Description: Ntvdm.exe allows the execution of 16-bit Windows applications on 32-bit Windows operating systems, as well as the execution of both 16-bit and 32-bit DOS applications
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_16bit_application.yml
// False Positives:
//   - Legitimate use

DeviceProcessEvents
| where FolderPath endswith "\\ntvdm.exe" or FolderPath endswith "\\csrstub.exe"