// Title: PowerShell MSI Install via WindowsInstaller COM From Remote Location
// Author: Meroujan Antonyan (vx3r)
// Date: 2025-06-05
// Level: medium
// Description: Detects the execution of PowerShell commands that attempt to install MSI packages via the
// Windows Installer COM object (`WindowsInstaller.Installer`) hosted remotely.
// This could be indication of malicious software deployment or lateral movement attempts using Windows Installer functionality.
// And the usage of WindowsInstaller COM object rather than msiexec could be an attempt to bypass the detection.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.001, attack.defense-evasion, attack.t1218, attack.command-and-control, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_comobject_msi_remote.yml

DeviceProcessEvents
| where ((ProcessCommandLine contains "-ComObject" and ProcessCommandLine contains "InstallProduct(") and ((FolderPath endswith "\\powershell_ise.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell_ISE.EXE", "PowerShell.EXE", "pwsh.dll"))) and (ProcessCommandLine contains "http" or ProcessCommandLine contains "\\\\")) and (not((ProcessCommandLine contains "://127.0.0.1" or ProcessCommandLine contains "://localhost")))