// Title: Uncommon Sigverif.EXE Child Process
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-19
// Level: medium
// Description: Detects uncommon child processes spawning from "sigverif.exe", which could indicate potential abuse of the latter as a living of the land binary in order to proxy execution.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1216
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sigverif_uncommon_child_process.yml

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\sigverif.exe" and (not((FolderPath in~ ("C:\\Windows\\System32\\WerFault.exe", "C:\\Windows\\SysWOW64\\WerFault.exe"))))