// Title: HackTool - Quarks PwDump Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-05
// Level: high
// Description: Detects usage of the Quarks PwDump tool via commandline arguments
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_quarks_pwdump.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (ProcessCommandLine in~ (" -dhl", " --dump-hash-local", " -dhdc", " --dump-hash-domain-cached", " --dump-bitlocker", " -dhd ", " --dump-hash-domain ", "--ntds-file")) or FolderPath endswith "\\QuarksPwDump.exe"