// Title: Renamed CURL.EXE Execution
// Author: X__Junior (Nextron Systems)
// Date: 2023-09-11
// Level: medium
// Description: Detects the execution of a renamed "CURL.exe" binary based on the PE metadata fields
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059, attack.defense-evasion, attack.t1202
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_renamed_curl.yml

DeviceProcessEvents
| where (ProcessVersionInfoOriginalFileName =~ "curl.exe" or ProcessVersionInfoFileDescription =~ "The curl executable") and (not(FolderPath contains "\\curl"))