// Title: Gpscript Execution
// Author: frack113
// Date: 2022-05-16
// Level: medium
// Description: Detects the execution of the LOLBIN gpscript, which executes logon or startup scripts configured in Group Policy
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_gpscript.yml
// False Positives:
//   - Legitimate uses of logon scripts distributed via group policy

DeviceProcessEvents
| where ((ProcessCommandLine contains " /logon" or ProcessCommandLine contains " /startup") and (FolderPath endswith "\\gpscript.exe" or ProcessVersionInfoOriginalFileName =~ "GPSCRIPT.EXE")) and (not(InitiatingProcessCommandLine =~ "C:\\windows\\system32\\svchost.exe -k netsvcs -p -s gpsvc"))