// Title: HackTool - SharpLDAPmonitor Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-30
// Level: medium
// Description: Detects execution of the SharpLDAPmonitor. Which can monitor the creation, deletion and changes to LDAP objects.
// MITRE Tactic: Discovery
// Tags: attack.discovery
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_sharp_ldap_monitor.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "/user:" and ProcessCommandLine contains "/pass:" and ProcessCommandLine contains "/dcip:") or (FolderPath endswith "\\SharpLDAPmonitor.exe" or ProcessVersionInfoOriginalFileName =~ "SharpLDAPmonitor.exe")