// Title: SyncAppvPublishingServer VBS Execute Arbitrary PowerShell Code
// Author: frack113
// Date: 2021-07-16
// Level: medium
// Description: Executes arbitrary PowerShell code using SyncAppvPublishingServer.vbs
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218, attack.t1216
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_syncappvpublishingserver_vbs_execute_psh.yml

DeviceProcessEvents
| where ProcessCommandLine contains "\\SyncAppvPublishingServer.vbs" and ProcessCommandLine contains ";"