// Title: Certificate Exported Via PowerShell
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-18
// Level: medium
// Description: Detects calls to cmdlets that are used to export certificates from the local certificate store. Threat actors were seen abusing this to steal private keys from compromised machines.
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.execution, attack.t1552.004, attack.t1059.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_export_certificate.yml
// False Positives:
//   - Legitimate certificate exports by administrators. Additional filters might be required.

DeviceProcessEvents
| where ProcessCommandLine contains "Export-PfxCertificate " or ProcessCommandLine contains "Export-Certificate "