// Title: Remote CHM File Download/Execution Via HH.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-29
// Level: high
// Description: Detects the usage of "hh.exe" to execute/download remotely hosted ".chm" files.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hh_chm_remote_download_or_execution.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://" or ProcessCommandLine contains "\\\\") and (ProcessVersionInfoOriginalFileName =~ "HH.exe" or FolderPath endswith "\\hh.exe")