// Title: Fsutil Drive Enumeration
// Author: Christopher Peacock '@securepeacock', SCYTHE '@scythe_io'
// Date: 2022-03-29
// Level: low
// Description: Attackers may leverage fsutil to enumerated connected drives.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1120
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_fsutil_drive_enumeration.yml
// False Positives:
//   - Certain software or administrative tasks may trigger false positives.

DeviceProcessEvents
| where ProcessCommandLine contains "drives" and (FolderPath endswith "\\fsutil.exe" or ProcessVersionInfoOriginalFileName =~ "fsutil.exe")