// Title: Compressed File Creation Via Tar.EXE
// Author: Nasreddine Bencherchali (Nextron Systems), AdmU3
// Date: 2023-12-19
// Level: low
// Description: Detects execution of "tar.exe" in order to create a compressed file.
// Adversaries may abuse various utilities to compress or encrypt data before exfiltration.
// MITRE Tactic: Collection
// Tags: attack.collection, attack.exfiltration, attack.t1560, attack.t1560.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_tar_compression.yml
// False Positives:
//   - Likely

DeviceProcessEvents
| where (ProcessCommandLine contains "-c" or ProcessCommandLine contains "-r" or ProcessCommandLine contains "-u") and (FolderPath endswith "\\tar.exe" or ProcessVersionInfoOriginalFileName =~ "bsdtar")