// Title: Suspicious Usage Of ShellExec_RunDLL
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-01
// Level: high
// Description: Detects suspicious usage of the ShellExec_RunDLL function to launch other commands as seen in the the raspberry-robin attack
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_rundll32_susp_shellexec_execution.yml

DeviceProcessEvents
| where ProcessCommandLine contains "ShellExec_RunDLL" and (ProcessCommandLine contains "\\Desktop\\" or ProcessCommandLine contains "\\Temp\\" or ProcessCommandLine contains "\\Users\\Public\\" or ProcessCommandLine contains "comspec" or ProcessCommandLine contains "iex" or ProcessCommandLine contains "Invoke-" or ProcessCommandLine contains "msiexec" or ProcessCommandLine contains "odbcconf" or ProcessCommandLine contains "regsvr32")