// Title: HackTool - SILENTTRINITY Stager Execution
// Author: Aleksey Potapov, oscd.community
// Date: 2019-10-22
// Level: high
// Description: Detects SILENTTRINITY stager use via PE metadata
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1071
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_silenttrinity_stager.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessVersionInfoFileDescription contains "st2stager"