// Title: File Decryption Using Gpg4win
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-09
// Level: medium
// Description: Detects usage of Gpg4win to decrypt files
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_gpg4win_decryption.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " -d " and ProcessCommandLine contains "passphrase") and ((FolderPath endswith "\\gpg.exe" or FolderPath endswith "\\gpg2.exe") or ProcessVersionInfoFileDescription =~ "GnuPG’s OpenPGP tool")