// Title: Time Travel Debugging Utility Usage
// Author: Ensar Şamil, @sblmsrsn, @oscd_initiative
// Date: 2020-10-06
// Level: high
// Description: Detects usage of Time Travel Debugging Utility. Adversaries can execute malicious processes and dump processes, such as lsass.exe, via tttracer.exe.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.credential-access, attack.t1218, attack.t1003.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_tttracer_mod_load.yml
// False Positives:
//   - Legitimate usage by software developers/testers

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\tttracer.exe"