// Title: Use of OpenConsole
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-16
// Level: medium
// Description: Detects usage of OpenConsole binary as a LOLBIN to launch other binaries to bypass application Whitelisting
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_openconsole.yml
// False Positives:
//   - Legitimate use by an administrator

DeviceProcessEvents
| where (ProcessVersionInfoOriginalFileName =~ "OpenConsole.exe" or FolderPath endswith "\\OpenConsole.exe") and (not(FolderPath startswith "C:\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal"))