// Title: Renamed Gpg.EXE Execution
// Author: Nasreddine Bencherchali (Nextron Systems), frack113
// Date: 2023-08-09
// Level: high
// Description: Detects the execution of a renamed "gpg.exe". Often used by ransomware and loaders to decrypt/encrypt data.
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1486
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_renamed_gpg4win.yml

DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "gpg.exe" and (not((FolderPath endswith "\\gpg.exe" or FolderPath endswith "\\gpg2.exe")))