// Title: Suspicious Process Masquerading As SvcHost.EXE
// Author: Swachchhanda Shrawan Poudel
// Date: 2024-08-07
// Level: high
// Description: Detects a suspicious process that is masquerading as the legitimate "svchost.exe" by naming its binary "svchost.exe" and executing from an uncommon location.
// Adversaries often disguise their malicious binaries by naming them after legitimate system processes like "svchost.exe" to evade detection.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036.005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_svchost_masqueraded_execution.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where FolderPath endswith "\\svchost.exe" and (not(((FolderPath in~ ("C:\\Windows\\System32\\svchost.exe", "C:\\Windows\\SysWOW64\\svchost.exe")) or ProcessVersionInfoOriginalFileName =~ "svchost.exe")))