// Title: Renamed BOINC Client Execution
// Author: Matt Anderson (Huntress)
// Date: 2024-07-23
// Level: medium
// Description: Detects the execution of a renamed BOINC binary.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1553
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_renamed_boinc.yml

DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "BOINC.exe" and (not(FolderPath endswith "\\BOINC.exe"))