// Title: Email Exifiltration Via Powershell
// Author: Nasreddine Bencherchali (Nextron Systems),  Azure-Sentinel (idea)
// Date: 2022-09-09
// Level: high
// Description: Detects email exfiltration via powershell cmdlets
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_email_exfil.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "Add-PSSnapin" and ProcessCommandLine contains "Get-Recipient" and ProcessCommandLine contains "-ExpandProperty" and ProcessCommandLine contains "EmailAddresses" and ProcessCommandLine contains "SmtpAddress" and ProcessCommandLine contains "-hidetableheaders") and (FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")