// Title: Potential NTLM Coercion Via Certutil.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-01
// Level: high
// Description: Detects possible NTLM coercion via certutil using the 'syncwithWU' flag
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_certutil_ntlm_coercion.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " -syncwithWU " and ProcessCommandLine contains " \\\\") and (FolderPath endswith "\\certutil.exe" or ProcessVersionInfoOriginalFileName =~ "CertUtil.exe")