// Title: Privilege Escalation via Named Pipe Impersonation
// Author: Tim Rauch, Elastic (idea)
// Date: 2022-09-27
// Level: high
// Description: Detects a remote file copy attempt to a hidden network share. This may indicate lateral movement or data staging activity.
// MITRE Tactic: Lateral Movement
// Tags: attack.lateral-movement, attack.t1021
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_priv_escalation_via_named_pipe.yml
// False Positives:
//   - Other programs that cause these patterns (please report)

DeviceProcessEvents
| where (ProcessCommandLine contains "echo" and ProcessCommandLine contains ">" and ProcessCommandLine contains "\\\\.\\pipe\\") and ((FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\powershell.exe") or (ProcessVersionInfoOriginalFileName in~ ("Cmd.Exe", "PowerShell.EXE")))