// Title: Suspicious Control Panel DLL Load
// Author: Florian Roth (Nextron Systems)
// Date: 2017-04-15
// Level: high
// Description: Detects suspicious Rundll32 execution from control.exe as used by Equation Group and Exploit Kits
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.011
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_rundll32_susp_control_dll_load.yml

DeviceProcessEvents
| where ((FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE") and InitiatingProcessFolderPath endswith "\\System32\\control.exe") and (not(ProcessCommandLine contains "Shell32.dll"))