// Title: Change Default File Association Via Assoc
// Author: Timur Zinniatullin, oscd.community
// Date: 2019-10-21
// Level: low
// Description: Detects file association changes using the builtin "assoc" command.
// When a file is opened, the default program used to open the file (also called the file association or handler) is checked. File association selections are stored in the Windows Registry and can be edited by users, administrators, or programs that have Registry access or by administrators using the built-in assoc utility. Applications can modify the file association for a given file extension to call an arbitrary program when a file with the given extension is opened.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1546.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_cmd_assoc_execution.yml
// False Positives:
//   - Admin activity

DeviceProcessEvents
| where ProcessCommandLine contains "assoc" and (FolderPath endswith "\\cmd.exe" or ProcessVersionInfoOriginalFileName =~ "Cmd.Exe")