// Title: Potentially Over Permissive Permissions Granted Using Dsacls.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-20
// Level: medium
// Description: Detects usage of Dsacls to grant over permissive permissions
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_dsacls_abuse_permissions.yml
// False Positives:
//   - Legitimate administrators granting over permissive permissions to users

DeviceProcessEvents
| where ProcessCommandLine contains " /G " and (FolderPath endswith "\\dsacls.exe" or ProcessVersionInfoOriginalFileName =~ "DSACLS.EXE") and (ProcessCommandLine contains "GR" or ProcessCommandLine contains "GE" or ProcessCommandLine contains "GW" or ProcessCommandLine contains "GA" or ProcessCommandLine contains "WP" or ProcessCommandLine contains "WD")