// Title: Windows Firewall Disabled via PowerShell
// Author: Tim Rauch, Elastic (idea)
// Date: 2022-09-14
// Level: medium
// Description: Detects attempts to disable the Windows Firewall using PowerShell
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_disable_firewall.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "Set-NetFirewallProfile " and ProcessCommandLine contains " -Enabled " and ProcessCommandLine contains " False") and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\powershell_ise.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll"))) and (ProcessCommandLine contains " -All " or ProcessCommandLine contains "Public" or ProcessCommandLine contains "Domain" or ProcessCommandLine contains "Private")