// Title: Potential Fake Instance Of Hxtsr.EXE Executed
// Author: Sreeman
// Date: 2020-04-17
// Level: medium
// Description: HxTsr.exe is a Microsoft compressed executable file called Microsoft Outlook Communications.
// HxTsr.exe is part of Outlook apps, because it resides in a hidden "WindowsApps" subfolder of "C:\Program Files".
// Any instances of hxtsr.exe not in this folder may be malware camouflaging itself as HxTsr.exe
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hxtsr_masquerading.yml

DeviceProcessEvents
| where FolderPath endswith "\\hxtsr.exe" and (not((FolderPath contains ":\\program files\\windowsapps\\microsoft.windowscommunicationsapps_" and FolderPath endswith "\\hxtsr.exe")))