// Title: PowerShell Get-Process LSASS
// Author: Florian Roth (Nextron Systems)
// Date: 2021-04-23
// Level: high
// Description: Detects a "Get-Process" cmdlet and it's aliases on lsass process, which is in almost all cases a sign of malicious activity
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1552.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_getprocess_lsass.yml

DeviceProcessEvents
| where ProcessCommandLine contains "Get-Process lsas" or ProcessCommandLine contains "ps lsas" or ProcessCommandLine contains "gps lsas"