// Title: HackTool - XORDump Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-01-28
// Level: high
// Description: Detects suspicious use of XORDump process memory dumping utility
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036, attack.t1003.001, attack.credential-access
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_xordump.yml
// False Positives:
//   - Another tool that uses the command line switches of XORdump

DeviceProcessEvents
| where FolderPath endswith "\\xordump.exe" or (ProcessCommandLine contains " -process lsass.exe " or ProcessCommandLine contains " -m comsvcs " or ProcessCommandLine contains " -m dbghelp " or ProcessCommandLine contains " -m dbgcore ")