// Title: Diskshadow Script Mode - Uncommon Script Extension Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-09-15
// Level: medium
// Description: Detects execution of "Diskshadow.exe" in script mode to execute an script with a potentially uncommon extension.
// Initial baselining of the allowed extension list is required.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_diskshadow_script_mode_susp_ext.yml
// False Positives:
//   - False postitve might occur with legitimate or uncommon extensions used internally. Initial baseline is required.

DeviceProcessEvents
| where ((ProcessCommandLine contains "-s " or ProcessCommandLine contains "/s " or ProcessCommandLine contains "–s " or ProcessCommandLine contains "—s " or ProcessCommandLine contains "―s ") and (ProcessVersionInfoOriginalFileName =~ "diskshadow.exe" or FolderPath endswith "\\diskshadow.exe")) and (not(ProcessCommandLine contains ".txt"))