// Title: Malicious Windows Script Components File Execution by TAEF Detection
// Author: Agro (@agro_sev) oscd.community
// Date: 2020-10-13
// Level: low
// Description: Windows Test Authoring and Execution Framework (TAEF) framework allows you to run automation by executing tests files written on different languages (C, C#, Microsoft COM Scripting interfaces
// Adversaries may execute malicious code (such as WSC file with VBScript, dll and so on) directly by running te.exe
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_use_of_te_bin.yml
// False Positives:
//   - It's not an uncommon to use te.exe directly to execute legal TAEF tests

DeviceProcessEvents
| where FolderPath endswith "\\te.exe" or InitiatingProcessFolderPath endswith "\\te.exe" or ProcessVersionInfoOriginalFileName =~ "\\te.exe"