// Title: Firewall Disabled via Netsh.EXE
// Author: Fatih Sirin
// Date: 2019-11-01
// Level: medium
// Description: Detects netsh commands that turns off the Windows firewall
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.004, attack.s0108
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_netsh_fw_disable.yml
// False Positives:
//   - Legitimate administration activity

DeviceProcessEvents
| where (FolderPath endswith "\\netsh.exe" or ProcessVersionInfoOriginalFileName =~ "netsh.exe") and ((ProcessCommandLine contains "firewall" and ProcessCommandLine contains "set" and ProcessCommandLine contains "opmode" and ProcessCommandLine contains "disable") or (ProcessCommandLine contains "advfirewall" and ProcessCommandLine contains "set" and ProcessCommandLine contains "state" and ProcessCommandLine contains "off"))