// Title: Suspicious Msbuild Execution By Uncommon Parent Process
// Author: frack113
// Date: 2022-11-17
// Level: medium
// Description: Detects suspicious execution of 'Msbuild.exe' by a uncommon parent process
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_msbuild_susp_parent_process.yml

DeviceProcessEvents
| where (FolderPath endswith "\\MSBuild.exe" or ProcessVersionInfoOriginalFileName =~ "MSBuild.exe") and (not((InitiatingProcessFolderPath endswith "\\devenv.exe" or InitiatingProcessFolderPath endswith "\\cmd.exe" or InitiatingProcessFolderPath endswith "\\msbuild.exe" or InitiatingProcessFolderPath endswith "\\python.exe" or InitiatingProcessFolderPath endswith "\\explorer.exe" or InitiatingProcessFolderPath endswith "\\nuget.exe")))