// Title: Use of TTDInject.exe
// Author: frack113
// Date: 2022-05-16
// Level: medium
// Description: Detects the executiob of TTDInject.exe, which is used by Windows 10 v1809 and newer to debug time travel (underlying call of tttracer.exe)
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1127
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_ttdinject.yml
// False Positives:
//   - Legitimate use

DeviceProcessEvents
| where FolderPath endswith "ttdinject.exe" or ProcessVersionInfoOriginalFileName =~ "TTDInject.EXE"