// Title: Use of FSharp Interpreters
// Author: Christopher Peacock @SecurePeacock, SCYTHE @scythe_io
// Date: 2022-06-02
// Level: medium
// Description: Detects the execution of FSharp Interpreters "FsiAnyCpu.exe" and "FSi.exe"
// Both can be used for AWL bypass and to execute F# code via scripts or inline.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_fsi_fsharp_code_execution.yml
// False Positives:
//   - Legitimate use by a software developer.

DeviceProcessEvents
| where (FolderPath endswith "\\fsi.exe" or FolderPath endswith "\\fsianycpu.exe") or (ProcessVersionInfoOriginalFileName in~ ("fsi.exe", "fsianycpu.exe"))