// Title: Browser Execution In Headless Mode
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-09-12
// Level: low
// Description: Detects execution of Chromium based browser in headless mode
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.command-and-control, attack.t1105, attack.t1564.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_browsers_chromium_headless_exec.yml

DeviceProcessEvents
| where ProcessCommandLine contains "--headless" and (FolderPath endswith "\\brave.exe" or FolderPath endswith "\\chrome.exe" or FolderPath endswith "\\msedge.exe" or FolderPath endswith "\\opera.exe" or FolderPath endswith "\\vivaldi.exe")