// Title: HackTool - Hashcat Password Cracker Execution
// Author: frack113
// Date: 2021-12-27
// Level: high
// Description: Execute Hashcat.exe with provided SAM file from registry of Windows and Password list to crack against
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1110.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_hashcat.yml
// False Positives:
//   - Tools that use similar command line flags and values

DeviceProcessEvents
| where (ProcessCommandLine contains "-a " and ProcessCommandLine contains "-m 1000 " and ProcessCommandLine contains "-r ") or FolderPath endswith "\\hashcat.exe"