// Title: Discovery of a System Time
// Author: E.M. Anhaus (originally from Atomic Blue Detections, Endgame), oscd.community
// Date: 2019-10-24
// Level: low
// Description: Identifies use of various commands to query a systems time. This technique may be used before executing a scheduled task or to discover the time zone of a target system.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1124
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_remote_time_discovery.yml
// False Positives:
//   - Legitimate use of the system utilities to discover system time for legitimate reason

DeviceProcessEvents
| where (ProcessCommandLine contains "time" and (FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe")) or (ProcessCommandLine contains "tz" and FolderPath endswith "\\w32tm.exe")