// Title: Compressed File Extraction Via Tar.EXE
// Author: AdmU3
// Date: 2023-12-19
// Level: low
// Description: Detects execution of "tar.exe" in order to extract compressed file.
// Adversaries may abuse various utilities in order to decompress data to avoid detection.
// MITRE Tactic: Collection
// Tags: attack.collection, attack.exfiltration, attack.t1560, attack.t1560.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_tar_extraction.yml
// False Positives:
//   - Likely

DeviceProcessEvents
| where ProcessCommandLine contains "-x" and (FolderPath endswith "\\tar.exe" or ProcessVersionInfoOriginalFileName =~ "bsdtar")