// Title: Suspicious Execution of Hostname
// Author: frack113
// Date: 2022-01-01
// Level: low
// Description: Use of hostname to get information
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1082
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hostname_execution.yml

DeviceProcessEvents
| where FolderPath endswith "\\HOSTNAME.EXE"