// Title: Computer Password Change Via Ksetup.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-04-06
// Level: medium
// Description: Detects password change for the computer's domain account or host principal via "ksetup.exe"
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_ksetup_password_change_computer.yml

DeviceProcessEvents
| where ProcessCommandLine contains " /setcomputerpassword " and (FolderPath endswith "\\ksetup.exe" or ProcessVersionInfoOriginalFileName =~ "ksetup.exe")