// Title: Regsvr32 DLL Execution With Uncommon Extension
// Author: Florian Roth (Nextron Systems)
// Date: 2019-07-17
// Level: medium
// Description: Detects a "regsvr32" execution where the DLL doesn't contain a common file extension.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.defense-evasion, attack.t1574, attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_regsvr32_uncommon_extension.yml
// False Positives:
//   - Other legitimate extensions currently not in the list either from third party or specific Windows components.

DeviceProcessEvents
| where (FolderPath endswith "\\regsvr32.exe" or ProcessVersionInfoOriginalFileName =~ "REGSVR32.EXE") and (not((ProcessCommandLine =~ "" or (ProcessCommandLine contains ".ax" or ProcessCommandLine contains ".cpl" or ProcessCommandLine contains ".dll" or ProcessCommandLine contains ".ocx") or isnull(ProcessCommandLine)))) and (not((ProcessCommandLine contains ".bav" or ProcessCommandLine contains ".ppl")))