// Title: Powershell Defender Exclusion
// Author: Florian Roth (Nextron Systems)
// Date: 2021-04-29
// Level: medium
// Description: Detects requests to exclude files, folders or processes from Antivirus scanning using PowerShell cmdlets
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_defender_exclusion.yml
// False Positives:
//   - Possible Admin Activity
//   - Other Cmdlets that may use the same parameters

DeviceProcessEvents
| where (ProcessCommandLine contains "Add-MpPreference " or ProcessCommandLine contains "Set-MpPreference ") and (ProcessCommandLine contains " -ExclusionPath " or ProcessCommandLine contains " -ExclusionExtension " or ProcessCommandLine contains " -ExclusionProcess " or ProcessCommandLine contains " -ExclusionIpAddress ")