// Title: UAC Bypass Using Event Viewer RecentViews
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-11-22
// Level: high
// Description: Detects the pattern of UAC Bypass using Event Viewer RecentViews
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_uac_bypass_eventvwr_recentviews.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "\\Event Viewer\\RecentViews" or ProcessCommandLine contains "\\EventV~1\\RecentViews") and ProcessCommandLine contains ">"