// Title: Add Potential Suspicious New Download Source To Winget
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-04-17
// Level: medium
// Description: Detects usage of winget to add new potentially suspicious download sources
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1059
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_winget_add_susp_custom_source.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "source " and ProcessCommandLine contains "add ") and (FolderPath endswith "\\winget.exe" or ProcessVersionInfoOriginalFileName =~ "winget.exe") and ProcessCommandLine matches regex "://\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}"