// Title: Directory Removal Via Rmdir
// Author: frack113
// Date: 2022-01-15
// Level: low
// Description: Detects execution of the builtin "rmdir" command in order to delete directories.
// Adversaries may delete files left behind by the actions of their intrusion activity.
// Malware, tools, or other non-native files dropped or created on a system by an adversary may leave traces to indicate to what was done within a network and how.
// Removal of these files can occur during an intrusion, or as part of a post-intrusion process to minimize the adversary's footprint.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1070.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_cmd_rmdir_execution.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "/s" or ProcessCommandLine contains "/q") and (FolderPath endswith "\\cmd.exe" or ProcessVersionInfoOriginalFileName =~ "Cmd.Exe") and ProcessCommandLine contains "rmdir"