// Title: PUA - CleanWipe Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2021-12-18
// Level: high
// Description: Detects the use of CleanWipe a tool usually used to delete Symantec antivirus.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_cleanwipe.yml
// False Positives:
//   - Legitimate administrative use (Should be investigated either way)

DeviceProcessEvents
| where FolderPath endswith "\\SepRemovalToolNative_x64.exe" or (ProcessCommandLine contains "--uninstall" and FolderPath endswith "\\CATClean.exe") or (ProcessCommandLine contains "-r" and FolderPath endswith "\\NetInstaller.exe") or ((ProcessCommandLine contains "/uninstall" and ProcessCommandLine contains "/enterprise") and FolderPath endswith "\\WFPUnins.exe")