// Title: HackTool - RedMimicry Winnti Playbook Execution
// Author: Alexander Rausch
// Date: 2020-06-24
// Level: high
// Description: Detects actions caused by the RedMimicry Winnti playbook a automated breach emulations utility
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, attack.t1106, attack.t1059.003, attack.t1218.011
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_redmimicry_winnti_playbook.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "gthread-3.6.dll" or ProcessCommandLine contains "\\Windows\\Temp\\tmp.bat" or ProcessCommandLine contains "sigcmm-2.4.dll") and (FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\cmd.exe")