// Title: Security Privileges Enumeration Via Whoami.EXE
// Author: Florian Roth (Nextron Systems)
// Date: 2021-05-05
// Level: high
// Description: Detects a whoami.exe executed with the /priv command line flag instructing the tool to show all current user privileges. This is often used after a privilege escalation attempt.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.discovery, attack.t1033
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_whoami_priv_discovery.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " /priv" or ProcessCommandLine contains " -priv") and (FolderPath endswith "\\whoami.exe" or ProcessVersionInfoOriginalFileName =~ "whoami.exe")