// Title: UAC Bypass Using Consent and Comctl32 - Process
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-23
// Level: high
// Description: Detects the pattern of UAC Bypass using consent.exe and comctl32.dll (UACMe 22)
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1548.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_uac_bypass_consent_comctl32.yml

DeviceProcessEvents
| where FolderPath endswith "\\werfault.exe" and (ProcessIntegrityLevel in~ ("High", "System", "S-1-16-16384", "S-1-16-12288")) and InitiatingProcessFolderPath endswith "\\consent.exe"