// Title: Potential Amazon SSM Agent Hijacking
// Author: Muhammad Faisal
// Date: 2023-08-02
// Level: medium
// Description: Detects potential Amazon SSM agent hijack attempts as outlined in the Mitiga research report.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.persistence, attack.t1219.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_ssm_agent_abuse.yml
// False Positives:
//   - Legitimate activity of system administrators

DeviceProcessEvents
| where (ProcessCommandLine contains "-register " and ProcessCommandLine contains "-code " and ProcessCommandLine contains "-id " and ProcessCommandLine contains "-region ") and FolderPath endswith "\\amazon-ssm-agent.exe"