// Title: Visual Studio Code Tunnel Shell Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-10-25
// Level: medium
// Description: Detects the execution of a shell (powershell, bash, wsl...) via Visual Studio Code tunnel. Attackers can abuse this functionality to establish a C2 channel and execute arbitrary commands on the system.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1071.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_vscode_tunnel_remote_shell_.yml
// False Positives:
//   - Legitimate use of Visual Studio Code tunnel and running code from there

DeviceProcessEvents
| where (InitiatingProcessCommandLine contains ".vscode-server" and InitiatingProcessFolderPath contains "\\servers\\Stable-" and InitiatingProcessFolderPath endswith "\\server\\node.exe") and ((ProcessCommandLine contains "\\terminal\\browser\\media\\shellIntegration.ps1" and (FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) or (FolderPath endswith "\\wsl.exe" or FolderPath endswith "\\bash.exe"))