// Title: Suspicious Registry Modification From ADS Via Regini.EXE
// Author: Eli Salem, Sander Wiebing, oscd.community
// Date: 2020-10-12
// Level: high
// Description: Detects the import of an alternate data stream with regini.exe, regini.exe can be used to modify registry keys.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1112, attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_regini_ads.yml

DeviceProcessEvents
| where (FolderPath endswith "\\regini.exe" or ProcessVersionInfoOriginalFileName =~ "REGINI.EXE") and ProcessCommandLine matches regex ":[^ \\\\]"