// Title: Data Export From MSSQL Table Via BCP.EXE
// Author: Omar Khaled (@beacon_exe), MahirAli Khan (in/mahiralikhan), Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-08-20
// Level: medium
// Description: Detects the execution of the BCP utility in order to export data from the database.
// Attackers were seen saving their malware to a database column or table and then later extracting it via "bcp.exe" into a file.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.exfiltration, attack.t1048
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_bcp_export_data.yml
// False Positives:
//   - Legitimate data export operations.

DeviceProcessEvents
| where (ProcessCommandLine contains " out " or ProcessCommandLine contains " queryout ") and (FolderPath endswith "\\bcp.exe" or ProcessVersionInfoOriginalFileName =~ "BCP.exe")