// Title: New Service Creation Using PowerShell
// Author: Timur Zinniatullin, Daniil Yugoslavskiy, oscd.community
// Date: 2023-02-20
// Level: low
// Description: Detects the creation of a new service using powershell.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.t1543.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_create_service.yml
// False Positives:
//   - Legitimate administrator or user creates a service for legitimate reasons.
//   - Software installation

DeviceProcessEvents
| where ProcessCommandLine contains "New-Service" and ProcessCommandLine contains "-BinaryPathName"