// Title: Possible Privilege Escalation via Weak Service Permissions
// Author: Teymur Kheirkhabarov
// Date: 2019-10-26
// Level: high
// Description: Detection of sc.exe utility spawning by user with Medium integrity level to change service ImagePath or FailureCommand
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.privilege-escalation, attack.t1574.011
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sc_change_sevice_image_path_by_non_admin.yml

DeviceProcessEvents
| where (FolderPath endswith "\\sc.exe" and (ProcessIntegrityLevel in~ ("Medium", "S-1-16-8192"))) and ((ProcessCommandLine contains "config" and ProcessCommandLine contains "binPath") or (ProcessCommandLine contains "failure" and ProcessCommandLine contains "command"))