// Title: Invoke-Obfuscation VAR++ LAUNCHER OBFUSCATION
// Author: Timur Zinniatullin, oscd.community
// Date: 2020-10-13
// Level: high
// Description: Detects Obfuscated Powershell via VAR++ LAUNCHER
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_invoke_obfuscation_via_var.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "{0}" or ProcessCommandLine contains "{1}" or ProcessCommandLine contains "{2}" or ProcessCommandLine contains "{3}" or ProcessCommandLine contains "{4}" or ProcessCommandLine contains "{5}") and (ProcessCommandLine contains "&&set" and ProcessCommandLine contains "cmd" and ProcessCommandLine contains "/c" and ProcessCommandLine contains "-f")