// Title: Disabling Windows Defender WMI Autologger Session via Reg.exe
// Author: Matt Anderson (Huntress)
// Date: 2025-07-09
// Level: high
// Description: Detects the use of reg.exe to disable the Event Tracing for Windows (ETW) Autologger session for Windows Defender API and Audit events.
// By setting the 'Start' value to '0' for the 'DefenderApiLogger' or 'DefenderAuditLogger' session, an attacker can prevent these critical security events
// from being logged, effectively blinding monitoring tools that rely on this data. This is a powerful defense evasion technique.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_reg_disable_defender_wmi_autologger.yml
// False Positives:
//   - Highly unlikely

DeviceProcessEvents
| where ((FolderPath endswith "\\reg.exe" or ProcessVersionInfoOriginalFileName =~ "reg.exe") and (ProcessCommandLine contains "add" and ProcessCommandLine contains "0") and (ProcessCommandLine contains "\\Control\\WMI\\Autologger\\DefenderApiLogger\\Start" or ProcessCommandLine contains "\\Control\\WMI\\Autologger\\DefenderAuditLogger\\Start")) and (not(ProcessCommandLine contains "0x00000001"))