// Title: PUA - NPS Tunneling Tool Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-10-08
// Level: high
// Description: Detects the use of NPS, a port forwarding and intranet penetration proxy server
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1090
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_nps.yml
// False Positives:
//   - Legitimate use

DeviceProcessEvents
| where (ProcessCommandLine contains " -server=" and ProcessCommandLine contains " -vkey=" and ProcessCommandLine contains " -password=") or ProcessCommandLine contains " -config=npc" or (MD5 startswith "AE8ACF66BFE3A44148964048B826D005" or SHA1 startswith "CEA49E9B9B67F3A13AD0BE1C2655293EA3C18181" or SHA256 startswith "5A456283392FFCEEEACA3D3426C306EB470304637520D72FED1CC1FEBBBD6856") or FolderPath endswith "\\npc.exe"