// Title: Stop Windows Service Via Sc.EXE
// Author: Jakob Weinzettl, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-03-05
// Level: low
// Description: Detects the stopping of a Windows service via the "sc.exe" utility
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1489
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sc_stop_service.yml
// False Positives:
//   - There are many legitimate reasons to stop a service. This rule isn't looking for any suspicious behavior in particular. Filter legitimate activity accordingly

DeviceProcessEvents
| where ProcessCommandLine contains " stop " and (ProcessVersionInfoOriginalFileName =~ "sc.exe" or FolderPath endswith "\\sc.exe")