// Title: Permission Misconfiguration Reconnaissance Via Findstr.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-12
// Level: medium
// Description: Detects usage of findstr with the "EVERYONE" or "BUILTIN" keywords.
// This was seen being used in combination with "icacls" and other utilities to spot misconfigured files or folders permissions.
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1552.006
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_findstr_recon_everyone.yml

DeviceProcessEvents
| where ((ProcessCommandLine contains "\"Everyone\"" or ProcessCommandLine contains "'Everyone'" or ProcessCommandLine contains "\"BUILTIN\\\"" or ProcessCommandLine contains "'BUILTIN\\'") and ((FolderPath endswith "\\find.exe" or FolderPath endswith "\\findstr.exe") or (ProcessVersionInfoOriginalFileName in~ ("FIND.EXE", "FINDSTR.EXE")))) or (ProcessCommandLine contains "icacls " and ProcessCommandLine contains "findstr " and ProcessCommandLine contains "Everyone")