// Title: Winrar Compressing Dump Files
// Author: Florian Roth (Nextron Systems)
// Date: 2022-01-04
// Level: medium
// Description: Detects execution of WinRAR in order to compress a file with a ".dmp"/".dump" extension, which could be a step in a process of dump file exfiltration.
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1560.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_winrar_exfil_dmp_files.yml
// False Positives:
//   - Legitimate use of WinRAR with a command line in which ".dmp" or ".dump" appears accidentally
//   - Legitimate use of WinRAR to compress WER ".dmp" files for troubleshooting

DeviceProcessEvents
| where (ProcessCommandLine contains ".dmp" or ProcessCommandLine contains ".dump" or ProcessCommandLine contains ".hdmp") and ((FolderPath endswith "\\rar.exe" or FolderPath endswith "\\winrar.exe") or ProcessVersionInfoFileDescription =~ "Command line RAR")