// Title: Potentially Suspicious Usage Of Qemu
// Author: Muhammad Faisal (@faisalusuf), Hunter Juhan (@threatHNTR)
// Date: 2024-06-03
// Level: medium
// Description: Detects potentially suspicious execution of the Qemu utility in a Windows environment.
// Threat actors have leveraged this utility and this technique for achieving network access as reported by Kaspersky.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1090, attack.t1572
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_qemu_suspicious_execution.yml

DeviceProcessEvents
| where ((ProcessCommandLine contains "-m 1M" or ProcessCommandLine contains "-m 2M" or ProcessCommandLine contains "-m 3M") and (ProcessCommandLine contains "restrict=off" and ProcessCommandLine contains "-netdev " and ProcessCommandLine contains "connect=" and ProcessCommandLine contains "-nographic")) and (not((ProcessCommandLine contains " -cdrom " or ProcessCommandLine contains " type=virt " or ProcessCommandLine contains " -blockdev ")))