// Title: Suspicious Recursive Takeown
// Author: frack113
// Date: 2022-01-30
// Level: medium
// Description: Adversaries can interact with the DACLs using built-in Windows commands takeown which can grant adversaries higher permissions on specific files and folders
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1222.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_takeown_recursive_own.yml
// False Positives:
//   - Scripts created by developers and admins
//   - Administrative activity

DeviceProcessEvents
| where (ProcessCommandLine contains "/f " and ProcessCommandLine contains "/r") and FolderPath endswith "\\takeown.exe"