// Title: Raccine Uninstall
// Author: Florian Roth (Nextron Systems)
// Date: 2021-01-21
// Level: high
// Description: Detects commands that indicate a Raccine removal from an end system. Raccine is a free ransomware protection tool.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_disable_raccine.yml
// False Positives:
//   - Legitimate deinstallation by administrative staff

DeviceProcessEvents
| where (ProcessCommandLine contains "taskkill " and ProcessCommandLine contains "RaccineSettings.exe") or (ProcessCommandLine contains "reg.exe" and ProcessCommandLine contains "delete" and ProcessCommandLine contains "Raccine Tray") or (ProcessCommandLine contains "schtasks" and ProcessCommandLine contains "/DELETE" and ProcessCommandLine contains "Raccine Rules Updater")