// Title: Use of W32tm as Timer
// Author: frack113
// Date: 2022-09-25
// Level: high
// Description: When configured with suitable command line arguments, w32tm can act as a delay mechanism
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1124
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_w32tm.yml
// False Positives:
//   - Legitimate use

DeviceProcessEvents
| where (ProcessCommandLine contains "/stripchart" and ProcessCommandLine contains "/computer:" and ProcessCommandLine contains "/period:" and ProcessCommandLine contains "/dataonly" and ProcessCommandLine contains "/samples:") and (FolderPath endswith "\\w32tm.exe" or ProcessVersionInfoOriginalFileName =~ "w32time.dll")