// Title: Monitoring For Persistence Via BITS
// Author: Sreeman
// Date: 2020-10-29
// Level: medium
// Description: BITS will allow you to schedule a command to execute after a successful download to notify you that the job is finished.
// When the job runs on the system the command specified in the BITS job will be executed.
// This can be abused by actors to create a backdoor within the system and for persistence.
// It will be chained in a BITS job to schedule the download of malware/additional binaries and execute the program after being downloaded.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1197
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_bitsadmin_potential_persistence.yml

DeviceProcessEvents
| where (FolderPath endswith "\\bitsadmin.exe" or ProcessVersionInfoOriginalFileName =~ "bitsadmin.exe") and ((ProcessCommandLine contains "/SetNotifyCmdLine" and (ProcessCommandLine contains "%COMSPEC%" or ProcessCommandLine contains "cmd.exe" or ProcessCommandLine contains "regsvr32.exe")) or (ProcessCommandLine contains "/Addfile" and (ProcessCommandLine contains "http:" or ProcessCommandLine contains "https:" or ProcessCommandLine contains "ftp:" or ProcessCommandLine contains "ftps:")))