// Title: Suspicious Reconnaissance Activity Using Get-LocalGroupMember Cmdlet
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-10
// Level: medium
// Description: Detects suspicious reconnaissance command line activity on Windows systems using the PowerShell Get-LocalGroupMember Cmdlet
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1087.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_get_localgroup_member_recon.yml
// False Positives:
//   - Administrative activity

DeviceProcessEvents
| where ProcessCommandLine contains "Get-LocalGroupMember " and (ProcessCommandLine contains "domain admins" or ProcessCommandLine contains " administrator" or ProcessCommandLine contains " administrateur" or ProcessCommandLine contains "enterprise admins" or ProcessCommandLine contains "Exchange Trusted Subsystem" or ProcessCommandLine contains "Remote Desktop Users" or ProcessCommandLine contains "Utilisateurs du Bureau à distance" or ProcessCommandLine contains "Usuarios de escritorio remoto")