// Title: Potentially Suspicious Execution Of Regasm/Regsvcs From Uncommon Location
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-25
// Level: medium
// Description: Detects potentially suspicious execution of the Regasm/Regsvcs utilities from a potentially suspicious location
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.009
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_regasm_regsvcs_uncommon_location_execution.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "\\AppData\\Local\\Temp\\" or ProcessCommandLine contains "\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\" or ProcessCommandLine contains "\\PerfLogs\\" or ProcessCommandLine contains "\\Users\\Public\\" or ProcessCommandLine contains "\\Windows\\Temp\\") and ((FolderPath endswith "\\Regsvcs.exe" or FolderPath endswith "\\Regasm.exe") or (ProcessVersionInfoOriginalFileName in~ ("RegSvcs.exe", "RegAsm.exe")))