// Title: COM Object Execution via Xwizard.EXE
// Author: Ensar Şamil, @sblmsrsn, @oscd_initiative, Nasreddine Bencherchali (Nextron Systems)
// Date: 2020-10-07
// Level: medium
// Description: Detects the execution of Xwizard tool with the "RunWizard" flag and a GUID like argument.
// This utility can be abused in order to run custom COM object created in the registry.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_xwizard_runwizard_com_object_exec.yml

DeviceProcessEvents
| where ProcessCommandLine =~ "RunWizard" and ProcessCommandLine matches regex "\\{[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}\\}"