// Title: Suspicious IIS Module Registration
// Author: Florian Roth (Nextron Systems), Microsoft (idea)
// Date: 2022-08-04
// Level: high
// Description: Detects a suspicious IIS module registration as described in Microsoft threat report on IIS backdoors
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1505.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_iis_susp_module_registration.yml
// False Positives:
//   - Administrative activity

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\w3wp.exe" and (ProcessCommandLine contains "appcmd.exe add module" or (ProcessCommandLine contains " system.enterpriseservices.internal.publish" and FolderPath endswith "\\powershell.exe") or (ProcessCommandLine contains "gacutil" and ProcessCommandLine contains " /I"))