// Title: Suspicious Regsvr32 Execution From Remote Share
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-31
// Level: high
// Description: Detects REGSVR32.exe to execute DLL hosted on remote shares
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.010
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_regsvr32_remote_share.yml

DeviceProcessEvents
| where ProcessCommandLine contains " \\\\" and (FolderPath endswith "\\regsvr32.exe" or ProcessVersionInfoOriginalFileName =~ "\\REGSVR32.EXE")