// Title: Potential File Overwrite Via Sysinternals SDelete
// Author: frack113
// Date: 2021-06-03
// Level: high
// Description: Detects the use of SDelete to erase a file not the free space
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1485
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sysinternals_sdelete.yml

DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "sdelete.exe" and (not((ProcessCommandLine contains " -h" or ProcessCommandLine contains " -c" or ProcessCommandLine contains " -z" or ProcessCommandLine contains " /?")))