// Title: PUA - DefenderCheck Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-08-30
// Level: high
// Description: Detects the use of DefenderCheck, a tool to evaluate the signatures used in Microsoft Defender. It can be used to figure out the strings / byte chains used in Microsoft Defender to detect a tool and thus used for AV evasion.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027.005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_defendercheck.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where FolderPath endswith "\\DefenderCheck.exe" or ProcessVersionInfoFileDescription =~ "DefenderCheck"