// Title: Potential Discovery Activity Via Dnscmd.EXE
// Author: @gott_cyber
// Date: 2022-07-31
// Level: medium
// Description: Detects an attempt to leverage dnscmd.exe to enumerate the DNS zones of a domain. DNS zones used to host the DNS records for a particular domain.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_dnscmd_discovery.yml
// False Positives:
//   - Legitimate administration use

DeviceProcessEvents
| where (ProcessCommandLine contains "/enumrecords" or ProcessCommandLine contains "/enumzones" or ProcessCommandLine contains "/ZonePrint" or ProcessCommandLine contains "/info") and FolderPath endswith "\\dnscmd.exe"