// Title: Potential MsiExec Masquerading
// Author: Florian Roth (Nextron Systems)
// Date: 2019-11-14
// Level: high
// Description: Detects the execution of msiexec.exe from an uncommon directory
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036.005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_msiexec_masquerading.yml

DeviceProcessEvents
| where (FolderPath endswith "\\msiexec.exe" or ProcessVersionInfoOriginalFileName =~ "\\msiexec.exe") and (not((FolderPath startswith "C:\\Windows\\System32\\" or FolderPath startswith "C:\\Windows\\SysWOW64\\" or FolderPath startswith "C:\\Windows\\WinSxS\\")))