// Title: Potential Command Line Path Traversal Evasion Attempt
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-10-26
// Level: medium
// Description: Detects potential evasion or obfuscation attempts using bogus path traversal via the commandline
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_commandline_path_traversal_evasion.yml
// False Positives:
//   - Google Drive
//   - Citrix

DeviceProcessEvents
| where (((ProcessCommandLine contains "\\..\\Windows\\" or ProcessCommandLine contains "\\..\\System32\\" or ProcessCommandLine contains "\\..\\..\\") and FolderPath contains "\\Windows\\") or ProcessCommandLine contains ".exe\\..\\") and (not((ProcessCommandLine contains "\\Citrix\\Virtual Smart Card\\Citrix.Authentication.VirtualSmartcard.Launcher.exe\\..\\" or ProcessCommandLine contains "\\Google\\Drive\\googledrivesync.exe\\..\\")))