// Title: Browser Started with Remote Debugging
// Author: pH-T (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-27
// Level: medium
// Description: Detects browsers starting with the remote debugging flags. Which is a technique often used to perform browser injection attacks
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.collection, attack.t1185
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_browsers_remote_debugging.yml

DeviceProcessEvents
| where ProcessCommandLine contains " --remote-debugging-" or (ProcessCommandLine contains " -start-debugger-server" and FolderPath endswith "\\firefox.exe")