// Title: HackTool - Dumpert Process Dumper Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2020-02-04
// Level: critical
// Description: Detects the use of Dumpert process dumper, which dumps the lsass.exe process memory
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_dumpert.yml
// False Positives:
//   - Very unlikely

DeviceProcessEvents
| where MD5 startswith "09D278F9DE118EF09163C6140255C690" or ProcessCommandLine contains "Dumpert.dll"