// Title: Suspicious Execution of InstallUtil Without Log
// Author: frack113
// Date: 2022-01-23
// Level: medium
// Description: Uses the .NET InstallUtil.exe application in order to execute image without log
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_instalutil_no_log_execution.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "/logfile= " and ProcessCommandLine contains "/LogToConsole=false") and FolderPath contains "Microsoft.NET\\Framework" and FolderPath endswith "\\InstallUtil.exe"