// Title: PUA - 3Proxy Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-09-13
// Level: high
// Description: Detects the use of 3proxy, a tiny free proxy server
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1572
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_3proxy_execution.yml
// False Positives:
//   - Administrative activity

DeviceProcessEvents
| where FolderPath endswith "\\3proxy.exe" or ProcessCommandLine contains ".exe -i127.0.0.1 -p" or ProcessVersionInfoFileDescription =~ "3proxy - tiny proxy server"