// Title: Arbitrary MSI Download Via Devinit.EXE
// Author: Florian Roth (Nextron Systems)
// Date: 2022-01-11
// Level: medium
// Description: Detects a certain command line flag combination used by "devinit.exe", which can be abused as a LOLBIN to download arbitrary MSI packages on a Windows system
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_devinit_lolbin_usage.yml

DeviceProcessEvents
| where ProcessCommandLine contains " -t msi-install " and ProcessCommandLine contains " -i http"