// Title: New Capture Session Launched Via DXCap.EXE
// Author: Beyu Denis, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2019-10-26
// Level: medium
// Description: Detects the execution of "DXCap.EXE" with the "-c" flag, which allows a user to launch any arbitrary binary or windows package through DXCap itself. This can be abused to potentially bypass application whitelisting.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_dxcap_arbitrary_binary_execution.yml
// False Positives:
//   - Legitimate execution of dxcap.exe by legitimate user

DeviceProcessEvents
| where ProcessCommandLine contains " -c " and (FolderPath endswith "\\DXCap.exe" or ProcessVersionInfoOriginalFileName =~ "DXCap.exe")