// Title: Loaded Module Enumeration Via Tasklist.EXE
// Author: Swachchhanda Shrawan Poudel
// Date: 2024-02-12
// Level: medium
// Description: Detects the enumeration of a specific DLL or EXE being used by a binary via "tasklist.exe".
// This is often used by attackers in order to find the specific process identifier (PID) that is using the DLL in question.
// In order to dump the process memory or perform other nefarious actions.
// MITRE Tactic: Credential Access
// Tags: attack.t1003, attack.credential-access
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_tasklist_module_enumeration.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "-m" or ProcessCommandLine contains "/m" or ProcessCommandLine contains "–m" or ProcessCommandLine contains "—m" or ProcessCommandLine contains "―m") and (FolderPath endswith "\\tasklist.exe" or ProcessVersionInfoOriginalFileName =~ "tasklist.exe") and ProcessCommandLine contains "rdpcorets.dll"