// Title: Potential Binary Proxy Execution Via Cdb.EXE
// Author: Beyu Denis, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2019-10-26
// Level: medium
// Description: Detects usage of "cdb.exe" to launch arbitrary processes or commands from a debugger script file
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1106, attack.defense-evasion, attack.t1218, attack.t1127
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_cdb_arbitrary_command_execution.yml
// False Positives:
//   - Legitimate use of debugging tools

DeviceProcessEvents
| where (ProcessCommandLine contains " -c " or ProcessCommandLine contains " -cf ") and (FolderPath endswith "\\cdb.exe" or ProcessVersionInfoOriginalFileName =~ "CDB.Exe")