// Title: JScript Compiler Execution
// Author: frack113
// Date: 2022-05-02
// Level: low
// Description: Detects the execution of the "jsc.exe" (JScript Compiler).
// Attacker might abuse this in order to compile JScript files on the fly and bypassing application whitelisting.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1127
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_jsc_execution.yml
// False Positives:
//   - Legitimate use to compile JScript by developers.

DeviceProcessEvents
| where FolderPath endswith "\\jsc.exe" or ProcessVersionInfoOriginalFileName =~ "jsc.exe"