// Title: Service Security Descriptor Tampering Via Sc.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-28
// Level: medium
// Description: Detection of sc.exe utility adding a new service with special permission which hides that service.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.privilege-escalation, attack.t1574.011
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sc_sdset_modification.yml

DeviceProcessEvents
| where ProcessCommandLine contains "sdset" and (FolderPath endswith "\\sc.exe" or ProcessVersionInfoOriginalFileName =~ "sc.exe")