// Title: Enumeration for Credentials in Registry
// Author: frack113
// Date: 2021-12-20
// Level: medium
// Description: Adversaries may search the Registry on compromised systems for insecurely stored credentials.
// The Windows Registry stores configuration information that can be used by the system or other programs.
// Adversaries may query the Registry looking for credentials and passwords that have been stored for use by other programs or services
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1552.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_reg_enumeration_for_credentials_in_registry.yml

DeviceProcessEvents
| where ((ProcessCommandLine contains " query " and ProcessCommandLine contains "/t " and ProcessCommandLine contains "REG_SZ" and ProcessCommandLine contains "/s") and FolderPath endswith "\\reg.exe") and ((ProcessCommandLine contains "/f " and ProcessCommandLine contains "HKLM") or (ProcessCommandLine contains "/f " and ProcessCommandLine contains "HKCU") or ProcessCommandLine contains "HKCU\\Software\\SimonTatham\\PuTTY\\Sessions")