// Title: Indirect Command Execution By Program Compatibility Wizard
// Author: A. Sungurov , oscd.community
// Date: 2020-10-12
// Level: low
// Description: Detect indirect command execution via Program Compatibility Assistant pcwrun.exe
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218, attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_pcwrun.yml
// False Positives:
//   - Need to use extra processing with 'unique_count' / 'filter' to focus on outliers as opposed to commonly seen artifacts
//   - Legit usage of scripts

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\pcwrun.exe"