// Title: Netsh Allow Group Policy on Microsoft Defender Firewall
// Author: frack113
// Date: 2022-01-09
// Level: medium
// Description: Adversaries may modify system firewalls in order to bypass controls limiting network usage
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_netsh_fw_enable_group_rule.yml
// False Positives:
//   - Legitimate administration activity

DeviceProcessEvents
| where (ProcessCommandLine contains "advfirewall" and ProcessCommandLine contains "firewall" and ProcessCommandLine contains "set" and ProcessCommandLine contains "rule" and ProcessCommandLine contains "group=" and ProcessCommandLine contains "new" and ProcessCommandLine contains "enable=Yes") and (FolderPath endswith "\\netsh.exe" or ProcessVersionInfoOriginalFileName =~ "netsh.exe")