// Title: Potential SysInternals ProcDump Evasion
// Author: Florian Roth (Nextron Systems)
// Date: 2022-01-11
// Level: high
// Description: Detects uses of the SysInternals ProcDump utility in which ProcDump or its output get renamed, or a dump file is moved or copied to a different name
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036, attack.t1003.001, attack.credential-access
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sysinternals_procdump_evasion.yml
// False Positives:
//   - False positives are expected in cases in which ProcDump just gets copied to a different directory without any renaming

DeviceProcessEvents
| where (ProcessCommandLine contains "copy procdump" or ProcessCommandLine contains "move procdump") or ((ProcessCommandLine contains "2.dmp" or ProcessCommandLine contains "lsass" or ProcessCommandLine contains "out.dmp") and (ProcessCommandLine contains "copy " and ProcessCommandLine contains ".dmp ")) or (ProcessCommandLine contains "copy lsass.exe_" or ProcessCommandLine contains "move lsass.exe_")