// Title: Suspicious Execution Location Of Wermgr.EXE
// Author: Florian Roth (Nextron Systems)
// Date: 2022-10-14
// Level: high
// Description: Detects suspicious Windows Error Reporting manager (wermgr.exe) execution location.
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wermgr_susp_exec_location.yml

DeviceProcessEvents
| where FolderPath endswith "\\wermgr.exe" and (not((FolderPath startswith "C:\\Windows\\System32\\" or FolderPath startswith "C:\\Windows\\SysWOW64\\" or FolderPath startswith "C:\\Windows\\WinSxS\\")))