// Title: File Deletion Via Del
// Author: frack113
// Date: 2022-01-15
// Level: low
// Description: Detects execution of the builtin "del"/"erase" commands in order to delete files.
// Adversaries may delete files left behind by the actions of their intrusion activity.
// Malware, tools, or other non-native files dropped or created on a system by an adversary may leave traces to indicate to what was done within a network and how.
// Removal of these files can occur during an intrusion, or as part of a post-intrusion process to minimize the adversary's footprint.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1070.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_cmd_del_execution.yml
// False Positives:
//   - False positives levels will differ Depending on the environment. You can use a combination of ParentImage and other keywords from the CommandLine field to filter legitimate activity

DeviceProcessEvents
| where (ProcessCommandLine contains "del " or ProcessCommandLine contains "erase ") and (ProcessCommandLine contains " -f" or ProcessCommandLine contains " /f" or ProcessCommandLine contains " –f" or ProcessCommandLine contains " —f" or ProcessCommandLine contains " ―f" or ProcessCommandLine contains " -s" or ProcessCommandLine contains " /s" or ProcessCommandLine contains " –s" or ProcessCommandLine contains " —s" or ProcessCommandLine contains " ―s" or ProcessCommandLine contains " -q" or ProcessCommandLine contains " /q" or ProcessCommandLine contains " –q" or ProcessCommandLine contains " —q" or ProcessCommandLine contains " ―q") and (FolderPath endswith "\\cmd.exe" or ProcessVersionInfoOriginalFileName =~ "Cmd.Exe")