// Title: New Generic Credentials Added Via Cmdkey.EXE
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-03
// Level: medium
// Description: Detects usage of "cmdkey.exe" to add generic credentials.
// As an example, this can be used before connecting to an RDP session via command line interface.
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_cmdkey_adding_generic_creds.yml
// False Positives:
//   - Legitimate usage for administration purposes

DeviceProcessEvents
| where (ProcessCommandLine contains " -g" or ProcessCommandLine contains " /g" or ProcessCommandLine contains " –g" or ProcessCommandLine contains " —g" or ProcessCommandLine contains " ―g") and (ProcessCommandLine contains " -p" or ProcessCommandLine contains " /p" or ProcessCommandLine contains " –p" or ProcessCommandLine contains " —p" or ProcessCommandLine contains " ―p") and (ProcessCommandLine contains " -u" or ProcessCommandLine contains " /u" or ProcessCommandLine contains " –u" or ProcessCommandLine contains " —u" or ProcessCommandLine contains " ―u") and (FolderPath endswith "\\cmdkey.exe" or ProcessVersionInfoOriginalFileName =~ "cmdkey.exe")