// Title: Rundll32 Execution Without CommandLine Parameters
// Author: Florian Roth (Nextron Systems)
// Date: 2021-05-27
// Level: high
// Description: Detects suspicious start of rundll32.exe without any parameters as found in CobaltStrike beacon activity
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1202
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_rundll32_no_params.yml
// False Positives:
//   - Possible but rare

DeviceProcessEvents
| where (ProcessCommandLine endswith "\\rundll32.exe" or ProcessCommandLine endswith "\\rundll32.exe\"" or ProcessCommandLine endswith "\\rundll32") and (not((InitiatingProcessFolderPath contains "\\AppData\\Local\\" or InitiatingProcessFolderPath contains "\\Microsoft\\Edge\\")))