// Title: Msxsl.EXE Execution
// Author: Timur Zinniatullin, oscd.community
// Date: 2019-10-21
// Level: medium
// Description: Detects the execution of the MSXSL utility. This can be used to execute Extensible Stylesheet Language (XSL) files. These files are commonly used to describe the processing and rendering of data within XML files.
// Adversaries can abuse this functionality to execute arbitrary files while potentially bypassing application whitelisting defenses.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1220
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_msxsl_execution.yml
// False Positives:
//   - Msxsl is not installed by default and is deprecated, so unlikely on most systems.

DeviceProcessEvents
| where FolderPath endswith "\\msxsl.exe"