// Title: Ping Hex IP
// Author: Florian Roth (Nextron Systems)
// Date: 2018-03-23
// Level: high
// Description: Detects a ping command that uses a hex encoded IP address
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1140, attack.t1027
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_ping_hex_ip.yml
// False Positives:
//   - Unlikely, because no sane admin pings IP addresses in a hexadecimal form

DeviceProcessEvents
| where ProcessCommandLine matches regex "0x[a-fA-F0-9]{8}" and FolderPath endswith "\\ping.exe"