// Title: Active Directory Structure Export Via Csvde.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-03-14
// Level: medium
// Description: Detects the execution of "csvde.exe" in order to export organizational Active Directory structure.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.discovery, attack.t1087.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_csvde_export.yml

DeviceProcessEvents
| where ((FolderPath endswith "\\csvde.exe" or ProcessVersionInfoOriginalFileName =~ "csvde.exe") and ProcessCommandLine contains " -f") and (not(ProcessCommandLine contains " -i"))