// Title: Unmount Share Via Net.EXE
// Author: oscd.community, @redcanary, Zach Stanford @svch0st
// Date: 2020-10-08
// Level: low
// Description: Detects when when a mounted share is removed. Adversaries may remove share connections that are no longer useful in order to clean up traces of their operation
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1070.005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_net_share_unmount.yml
// False Positives:
//   - Administrators or Power users may remove their shares via cmd line

DeviceProcessEvents
| where (ProcessCommandLine contains "share" and ProcessCommandLine contains "/delete") and ((FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe") or (ProcessVersionInfoOriginalFileName in~ ("net.exe", "net1.exe")))