// Title: Windows Recovery Environment Disabled Via Reagentc
// Author: Daniel Koifman (KoifSec), Michael Vilshin
// Date: 2025-07-31
// Level: medium
// Description: Detects attempts to disable windows recovery environment using Reagentc.
// ReAgentc.exe is a command-line tool in Windows used to manage the Windows Recovery Environment (WinRE).
// It allows users to enable, disable, and configure WinRE, which is used for troubleshooting and repairing common boot issues.
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1490
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_reagentc_disable_windows_recovery_environment.yml
// False Positives:
//   - Legitimate administrative activity

DeviceProcessEvents
| where (ProcessCommandLine contains "-disable" or ProcessCommandLine contains "/disable" or ProcessCommandLine contains "–disable" or ProcessCommandLine contains "—disable" or ProcessCommandLine contains "―disable") and (FolderPath endswith "\\reagentc.exe" or ProcessVersionInfoOriginalFileName =~ "reagentc.exe")