// Title: Execute Code with Pester.bat
// Author: Julia Fomina, oscd.community
// Date: 2020-10-08
// Level: medium
// Description: Detects code execution via Pester.bat (Pester - Powershell Modulte for testing)
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.001, attack.defense-evasion, attack.t1216
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_pester_1.yml
// False Positives:
//   - Legitimate use of Pester for writing tests for Powershell scripts and modules

DeviceProcessEvents
| where ((ProcessCommandLine contains "Pester" and ProcessCommandLine contains "Get-Help") and (FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) or (((ProcessCommandLine contains "pester" and ProcessCommandLine contains ";") and FolderPath endswith "\\cmd.exe") and (ProcessCommandLine contains "help" or ProcessCommandLine contains "?"))