// Title: REGISTER_APP.VBS Proxy Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-19
// Level: medium
// Description: Detects the use of a Microsoft signed script 'REGISTER_APP.VBS' to register a VSS/VDS Provider as a COM+ application.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_register_app.yml
// False Positives:
//   - Legitimate usage of the script. Always investigate what's being registered to confirm if it's benign

DeviceProcessEvents
| where ProcessCommandLine contains "\\register_app.vbs" and ProcessCommandLine contains "-register"