// Title: Indirect Command Execution From Script File Via Bash.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-15
// Level: medium
// Description: Detects execution of Microsoft bash launcher without any flags to execute the content of a bash script directly.
// This can be used to potentially bypass defenses and execute Linux or Windows-based binaries directly via bash.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1202
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_bash_file_execution.yml

DeviceProcessEvents
| where ((FolderPath endswith ":\\Windows\\System32\\bash.exe" or FolderPath endswith ":\\Windows\\SysWOW64\\bash.exe") or ProcessVersionInfoOriginalFileName =~ "Bash.exe") and (not(((ProcessCommandLine contains "bash.exe -" or ProcessCommandLine contains "bash -") or ProcessCommandLine =~ "" or isnull(ProcessCommandLine) or (ProcessCommandLine in~ ("bash.exe", "bash")))))