// Title: Command Line Execution with Suspicious URL and AppData Strings
// Author: Florian Roth (Nextron Systems), Jonhnathan Ribeiro, oscd.community
// Date: 2019-01-16
// Level: medium
// Description: Detects a suspicious command line execution that includes an URL and AppData string in the command line parameters as used by several droppers (js/vbs > powershell)
// MITRE Tactic: Execution
// Tags: attack.execution, attack.command-and-control, attack.t1059.003, attack.t1059.001, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_cmd_http_appdata.yml
// False Positives:
//   - High

DeviceProcessEvents
| where (ProcessCommandLine contains "http" and ProcessCommandLine contains "://" and ProcessCommandLine contains "%AppData%") and FolderPath endswith "\\cmd.exe"