// Title: User Added To Highly Privileged Group
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-02-23
// Level: high
// Description: Detects addition of users to highly privileged groups via "Net" or "Add-LocalGroupMember".
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1098
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_add_user_privileged_group.yml
// False Positives:
//   - Administrative activity that must be investigated

DeviceProcessEvents
| where (ProcessCommandLine contains "Group Policy Creator Owners" or ProcessCommandLine contains "Schema Admins") and ((ProcessCommandLine contains "localgroup " and ProcessCommandLine contains " /add") or (ProcessCommandLine contains "Add-LocalGroupMember " and ProcessCommandLine contains " -Group "))