// Title: Uncommon Extension Shim Database Installation Via Sdbinst.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-01
// Level: medium
// Description: Detects installation of a potentially suspicious new shim with an uncommon extension using sdbinst.exe.
// Adversaries may establish persistence and/or elevate privileges by executing malicious content triggered by application shims
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.t1546.011
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sdbinst_susp_extension.yml

DeviceProcessEvents
| where (FolderPath endswith "\\sdbinst.exe" or ProcessVersionInfoOriginalFileName =~ "sdbinst.exe") and (not((ProcessCommandLine =~ "" or ProcessCommandLine contains ".sdb" or ((ProcessCommandLine endswith " -c" or ProcessCommandLine endswith " -f" or ProcessCommandLine endswith " -mm" or ProcessCommandLine endswith " -t") or ProcessCommandLine contains " -m -bg") or isnull(ProcessCommandLine))))