// Title: HackTool - TruffleSnout Execution
// Author: frack113
// Date: 2022-08-20
// Level: high
// Description: Detects the use of TruffleSnout.exe an iterative AD discovery toolkit for offensive operators, situational awareness and targeted low noise enumeration.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1482
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_trufflesnout.yml

DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "TruffleSnout.exe" or FolderPath endswith "\\TruffleSnout.exe"