// Title: Potential Lateral Movement via Windows Remote Shell
// Author: Liran Ravich
// Date: 2025-10-22
// Level: medium
// Description: Detects a child process spawned by 'winrshost.exe', which suggests remote command execution through Windows Remote Shell (WinRs) and may indicate potential lateral movement activity.
// MITRE Tactic: Lateral Movement
// Tags: attack.lateral-movement, attack.t1021.006
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_winrshost_command_execution.yml
// False Positives:
//   - Legitimate use of WinRM within the organization

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\winrshost.exe" and (not(FolderPath =~ "C:\\Windows\\System32\\conhost.exe"))