// Title: Use Of The SFTP.EXE Binary As A LOLBIN
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-11-10
// Level: medium
// Description: Detects the usage of the "sftp.exe" binary as a LOLBIN by abusing the "-D" flag
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_sftp.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " -D .." or ProcessCommandLine contains " -D C:\\") and FolderPath endswith "\\sftp.exe"