// Title: Invoke-Obfuscation VAR+ Launcher
// Author: Jonathan Cheong, oscd.community
// Date: 2020-10-15
// Level: high
// Description: Detects Obfuscated use of Environment Variables to execute PowerShell
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_invoke_obfuscation_var.yml

DeviceProcessEvents
| where ProcessCommandLine matches regex "cmd.{0,5}(?:/c|/r)(?:\\s|)\\"set\\s[a-zA-Z]{3,6}.*(?:\\{\\d\\}){1,}\\\\\\"\\s+?\\-f(?:.*\\)){1,}.*\\""