// Title: Use of Scriptrunner.exe
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-01
// Level: medium
// Description: The "ScriptRunner.exe" binary can be abused to proxy execution through it and bypass possible whitelisting
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_scriptrunner.yml
// False Positives:
//   - Legitimate use when App-v is deployed

DeviceProcessEvents
| where ProcessCommandLine contains " -appvscript " and (FolderPath endswith "\\ScriptRunner.exe" or ProcessVersionInfoOriginalFileName =~ "ScriptRunner.exe")