// Title: Potential Rundll32 Execution With DLL Stored In ADS
// Author: Harjot Singh, '@cyb3rjy0t'
// Date: 2023-01-21
// Level: high
// Description: Detects execution of rundll32 where the DLL being called is stored in an Alternate Data Stream (ADS).
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1564.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_rundll32_ads_stored_dll_execution.yml

DeviceProcessEvents
| where ProcessCommandLine matches regex "[Rr][Uu][Nn][Dd][Ll][Ll]32(\\.[Ee][Xx][Ee])? \\S+?\\w:\\S+?:" and (FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE")