// Title: Suspicious Extrac32 Alternate Data Stream Execution
// Author: frack113
// Date: 2021-11-26
// Level: medium
// Description: Extract data from cab file and hide it in an alternate data stream
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1564.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_extrac32_ads.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "extrac32.exe" and ProcessCommandLine contains ".cab") and ProcessCommandLine matches regex ":[^\\\\]"