// Title: Renamed Vmnat.exe Execution
// Author: elhoim
// Date: 2022-09-09
// Level: high
// Description: Detects renamed vmnat.exe or portable version that can be used for DLL side-loading
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.defense-evasion, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_renamed_vmnat.yml

DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "vmnat.exe" and (not(FolderPath endswith "vmnat.exe"))