// Title: Potential Excel.EXE DCOM Lateral Movement Via ActivateMicrosoftApp
// Author: Aaron Stratton
// Date: 2023-11-13
// Level: high
// Description: Detects suspicious child processes of Excel which could be an indicator of lateral movement leveraging the "ActivateMicrosoftApp" Excel DCOM object.
// MITRE Tactic: Lateral Movement
// Tags: attack.t1021.003, attack.lateral-movement
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_office_excel_dcom_lateral_movement.yml

DeviceProcessEvents
| where ((ProcessVersionInfoOriginalFileName in~ ("foxprow.exe", "schdplus.exe", "winproj.exe")) or (FolderPath endswith "\\foxprow.exe" or FolderPath endswith "\\schdplus.exe" or FolderPath endswith "\\winproj.exe")) and InitiatingProcessFolderPath endswith "\\excel.exe"