// Title: Remote Access Tool - AnyDesk Piped Password Via CLI
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-28
// Level: medium
// Description: Detects piping the password to an anydesk instance via CMD and the '--set-password' flag.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1219.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_remote_access_tools_anydesk_piped_password_via_cli.yml
// False Positives:
//   - Legitimate piping of the password to anydesk
//   - Some FP could occur with similar tools that uses the same command line '--set-password'

DeviceProcessEvents
| where ProcessCommandLine contains "/c " and ProcessCommandLine contains "echo " and ProcessCommandLine contains ".exe --set-password"