// Title: DllUnregisterServer Function Call Via Msiexec.EXE
// Author: frack113
// Date: 2022-04-24
// Level: medium
// Description: Detects MsiExec loading a DLL and calling its DllUnregisterServer function
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.007
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_msiexec_dll.yml

DeviceProcessEvents
| where ProcessCommandLine contains ".dll" and (ProcessCommandLine contains " -z " or ProcessCommandLine contains " /z " or ProcessCommandLine contains " –z " or ProcessCommandLine contains " —z " or ProcessCommandLine contains " ―z ") and (FolderPath endswith "\\msiexec.exe" or ProcessVersionInfoOriginalFileName =~ "\\msiexec.exe")