// Title: Uncommon Child Process Of Appvlp.EXE
// Author: Sreeman
// Date: 2020-03-13
// Level: medium
// Description: Detects uncommon child processes of Appvlp.EXE
// Appvlp or the Application Virtualization Utility is included with Microsoft Office. Attackers are able to abuse "AppVLP" to execute shell commands.
// Normally, this binary is used for Application Virtualization, but it can also be abused to circumvent the ASR file path rule folder
// or to mark a file as a system file.
// MITRE Tactic: Defense Evasion
// Tags: attack.t1218, attack.defense-evasion, attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_appvlp_uncommon_child_process.yml

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\appvlp.exe" and (not((FolderPath endswith ":\\Windows\\SysWOW64\\rundll32.exe" or FolderPath endswith ":\\Windows\\System32\\rundll32.exe"))) and (not(((FolderPath contains ":\\Program Files\\Microsoft Office" and FolderPath endswith "\\msoasb.exe") or (FolderPath contains ":\\Program Files\\Microsoft Office" and FolderPath endswith "\\MSOUC.EXE") or ((FolderPath contains ":\\Program Files\\Microsoft Office" and FolderPath contains "\\SkypeSrv\\") and FolderPath endswith "\\SKYPESERVER.EXE"))))