// Title: Renamed Microsoft Teams Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-07-12
// Level: medium
// Description: Detects the execution of a renamed Microsoft Teams binary.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_renamed_msteams.yml

DeviceProcessEvents
| where (ProcessVersionInfoOriginalFileName in~ ("msteams.exe", "teams.exe")) and (not((FolderPath endswith "\\msteams.exe" or FolderPath endswith "\\teams.exe")))