// Title: Finger.EXE Execution
// Author: Florian Roth (Nextron Systems), omkar72, oscd.community
// Date: 2021-02-24
// Level: high
// Description: Detects execution of the "finger.exe" utility.
// Finger.EXE or "TCPIP Finger Command" is an old utility that is still present on modern Windows installation. It Displays information about users on a specified remote computer (typically a UNIX computer) that is running the finger service or daemon.
// Due to the old nature of this utility and the rareness of machines having the finger service. Any execution of "finger.exe" can be considered "suspicious" and worth investigating.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_finger_execution.yml
// False Positives:
//   - Admin activity (unclear what they do nowadays with finger.exe)

DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "finger.exe" or FolderPath endswith "\\finger.exe"