// Title: Suspicious ArcSOC.exe Child Process
// Author: Micah Babinski
// Date: 2025-11-25
// Level: high
// Description: Detects script interpreters, command-line tools, and similar suspicious child processes of ArcSOC.exe.
// ArcSOC.exe is the process name which hosts ArcGIS Server REST services. If an attacker compromises an ArcGIS
// Server system and uploads a malicious Server Object Extension (SOE), they can send crafted requests to the corresponding
// service endpoint and remotely execute code from the ArcSOC.exe process.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059, attack.t1203
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_arcsoc_susp_child_process.yml

DeviceProcessEvents
| where ((FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\cscript.exe" or FolderPath endswith "\\mshta.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\regsvr32.exe" or FolderPath endswith "\\rundll32.exe" or FolderPath endswith "\\wmic.exe" or FolderPath endswith "\\wscript.exe") and InitiatingProcessFolderPath endswith "\\ArcSOC.exe") and (not((ProcessCommandLine =~ "cmd.exe /c \"ver\"" and FolderPath endswith "\\cmd.exe")))