// Title: Suspicious Key Manager Access
// Author: Florian Roth (Nextron Systems)
// Date: 2022-04-21
// Level: high
// Description: Detects the invocation of the Stored User Names and Passwords dialogue (Key Manager)
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1555.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_rundll32_keymgr.yml
// False Positives:
//   - Administrative activity

DeviceProcessEvents
| where (ProcessCommandLine contains "keymgr" and ProcessCommandLine contains "KRShowKeyMgr") and (FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE")