// Title: PsExec Service Execution
// Author: Thomas Patzke, Romaissa Adjailia, Florian Roth (Nextron Systems)
// Date: 2017-06-12
// Level: medium
// Description: Detects launch of the PSEXESVC service, which means that this system was the target of a psexec remote execution
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sysinternals_psexesvc.yml
// False Positives:
//   - Legitimate administrative tasks

DeviceProcessEvents
| where FolderPath =~ "C:\\Windows\\PSEXESVC.exe" or ProcessVersionInfoOriginalFileName =~ "psexesvc.exe"