// Title: Potential Credential Dumping Attempt Using New NetworkProvider - CLI
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-23
// Level: high
// Description: Detects when an attacker tries to add a new network provider in order to dump clear text credentials, similar to how the NPPSpy tool does it
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_registry_new_network_provider.yml
// False Positives:
//   - Other legitimate network providers used and not filtred in this rule

DeviceProcessEvents
| where ProcessCommandLine contains "\\System\\CurrentControlSet\\Services\\" and ProcessCommandLine contains "\\NetworkProvider"