// Title: Chromium Browser Instance Executed With Custom Extension
// Author: Aedan Russell, frack113, X__Junior (Nextron Systems)
// Date: 2022-06-19
// Level: medium
// Description: Detects a Chromium based browser process with the 'load-extension' flag to start a instance with a custom extension
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1176.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_browsers_chromium_load_extension.yml
// False Positives:
//   - Usage of Chrome Extensions in testing tools such as BurpSuite will trigger this alert

DeviceProcessEvents
| where ProcessCommandLine contains "--load-extension=" and (FolderPath endswith "\\brave.exe" or FolderPath endswith "\\chrome.exe" or FolderPath endswith "\\msedge.exe" or FolderPath endswith "\\opera.exe" or FolderPath endswith "\\vivaldi.exe")