// Title: Potential Persistence Via Microsoft Compatibility Appraiser
// Author: Sreeman
// Date: 2020-09-29
// Level: medium
// Description: Detects manual execution of the "Microsoft Compatibility Appraiser" task via schtasks.
// In order to trigger persistence stored in the "\AppCompatFlags\TelemetryController" registry key.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.execution, attack.persistence, attack.t1053.005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_schtasks_persistence_windows_telemetry.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "run " and ProcessCommandLine contains "\\Application Experience\\Microsoft Compatibility Appraiser") and (FolderPath endswith "\\schtasks.exe" or ProcessVersionInfoOriginalFileName =~ "schtasks.exe")