// Title: SyncAppvPublishingServer Execute Arbitrary PowerShell Code
// Author: frack113
// Date: 2021-07-12
// Level: medium
// Description: Executes arbitrary PowerShell code using SyncAppvPublishingServer.exe.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_syncappvpublishingserver_execute_psh.yml
// False Positives:
//   - App-V clients

DeviceProcessEvents
| where ProcessCommandLine contains "\"n; " and (FolderPath endswith "\\SyncAppvPublishingServer.exe" or ProcessVersionInfoOriginalFileName =~ "syncappvpublishingserver.exe")