// Title: Indirect Inline Command Execution Via Bash.EXE
// Author: frack113
// Date: 2021-11-24
// Level: medium
// Description: Detects execution of Microsoft bash launcher with the "-c" flag.
// This can be used to potentially bypass defenses and execute Linux or Windows-based binaries directly via bash.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1202
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_bash_command_execution.yml

DeviceProcessEvents
| where ProcessCommandLine contains " -c " and ((FolderPath endswith ":\\Windows\\System32\\bash.exe" or FolderPath endswith ":\\Windows\\SysWOW64\\bash.exe") or ProcessVersionInfoOriginalFileName =~ "Bash.exe")