// Title: HackTool - Impersonate Execution
// Author: Sai Prashanth Pulisetti @pulisettis
// Date: 2022-12-21
// Level: medium
// Description: Detects execution of the Impersonate tool. Which can be used to manipulate tokens on a Windows computers remotely (PsExec/WmiExec) or interactively
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.defense-evasion, attack.t1134.001, attack.t1134.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_impersonate.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "impersonate.exe" and (ProcessCommandLine contains " list " or ProcessCommandLine contains " exec " or ProcessCommandLine contains " adduser ")) or (MD5 startswith "9520714AB576B0ED01D1513691377D01" or SHA256 startswith "E81CC96E2118DC4FBFE5BAD1604E0AC7681960143E2101E1A024D52264BB0A8A")