// Title: Rundll32 UNC Path Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-10
// Level: high
// Description: Detects rundll32 execution where the DLL is located on a remote location (share)
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.lateral-movement, attack.t1021.002, attack.t1218.011
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_rundll32_unc_path.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains " \\\\" and (FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE" or ProcessCommandLine contains "rundll32")