// Title: Stop Windows Service Via PowerShell Stop-Service
// Author: Jakob Weinzettl, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-03-05
// Level: low
// Description: Detects the stopping of a Windows service via the PowerShell Cmdlet "Stop-Service"
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1489
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_stop_service.yml
// False Positives:
//   - There are many legitimate reasons to stop a service. This rule isn't looking for any suspicious behaviour in particular. Filter legitimate activity accordingly

DeviceProcessEvents
| where ProcessCommandLine contains "Stop-Service " and ((ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")) or (FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe"))