// Title: PrintBrm ZIP Creation of Extraction
// Author: frack113
// Date: 2022-05-02
// Level: high
// Description: Detects the execution of the LOLBIN PrintBrm.exe, which can be used to create or extract ZIP files. PrintBrm.exe should not be run on a normal workstation.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1105, attack.defense-evasion, attack.t1564.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_printbrm.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " -f" and ProcessCommandLine contains ".zip") and FolderPath endswith "\\PrintBrm.exe"