// Title: System Disk And Volume Reconnaissance Via Wmic.EXE
// Author: Stephen Lincoln '@slincoln-aiq' (AttackIQ)
// Date: 2024-02-02
// Level: medium
// Description: An adversary might use WMI to discover information about the system, such as the volume name, size,
// free space, and other disk information. This can be done using the 'wmic' command-line utility and has been
// observed being used by threat actors such as Volt Typhoon.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.discovery, attack.t1047, attack.t1082
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wmic_recon_volume.yml

DeviceProcessEvents
| where ((ProcessCommandLine contains " volumename" or ProcessCommandLine contains " logicaldisk") or (ProcessCommandLine contains "path" and ProcessCommandLine contains "win32_logicaldisk") or (ProcessCommandLine contains " volume" and ProcessCommandLine contains " list ")) and (FolderPath endswith "\\WMIC.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")