// Title: Suspicious X509Enrollment - Process Creation
// Author: frack113
// Date: 2022-12-23
// Level: medium
// Description: Detect use of X509Enrollment
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1553.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_x509enrollment.yml
// False Positives:
//   - Legitimate administrative script

DeviceProcessEvents
| where ProcessCommandLine contains "X509Enrollment.CBinaryConverter" or ProcessCommandLine contains "884e2002-217d-11da-b2a4-000e7bbb2b09"