// Title: Remote Access Tool - Team Viewer Session Started On Windows Host
// Author: Josh Nickels, Qi Nan
// Date: 2024-03-11
// Level: low
// Description: Detects the command line executed when TeamViewer starts a session started by a remote host.
// Once a connection has been started, an investigator can verify the connection details by viewing the "incoming_connections.txt" log file in the TeamViewer folder.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.initial-access, attack.t1133
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_remote_access_tools_teamviewer_incoming_connection.yml
// False Positives:
//   - Legitimate usage of TeamViewer

DeviceProcessEvents
| where ProcessCommandLine endswith "TeamViewer_Desktop.exe --IPCport 5939 --Module 1" and FolderPath =~ "TeamViewer_Desktop.exe" and InitiatingProcessFolderPath =~ "TeamViewer_Service.exe"