// Title: Potential RDP Session Hijacking Activity
// Author: @juju4
// Date: 2022-12-27
// Level: medium
// Description: Detects potential RDP Session Hijacking activity on Windows systems
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_tscon_rdp_session_hijacking.yml
// False Positives:
//   - Administrative activity

DeviceProcessEvents
| where (FolderPath endswith "\\tscon.exe" or ProcessVersionInfoOriginalFileName =~ "tscon.exe") and (ProcessIntegrityLevel in~ ("System", "S-1-16-16384"))