// Title: Renamed CreateDump Utility Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-09-20
// Level: high
// Description: Detects uses of a renamed legitimate createdump.exe LOLOBIN utility to dump process memory
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036, attack.t1003.001, attack.credential-access
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_renamed_createdump.yml
// False Positives:
//   - Command lines that use the same flags

DeviceProcessEvents
| where (((ProcessCommandLine contains " -u " and ProcessCommandLine contains " -f " and ProcessCommandLine contains ".dmp") or (ProcessCommandLine contains " --full " and ProcessCommandLine contains " --name " and ProcessCommandLine contains ".dmp")) or ProcessVersionInfoOriginalFileName =~ "FX_VER_INTERNALNAME_STR") and (not(FolderPath endswith "\\createdump.exe"))