// Title: Potential Recon Activity Via Nltest.EXE
// Author: Craig Young, oscd.community, Georg Lauenstein
// Date: 2021-07-24
// Level: medium
// Description: Detects nltest commands that can be used for information discovery
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1016, attack.t1482
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_nltest_recon.yml
// False Positives:
//   - Legitimate administration use but user and host must be investigated

DeviceProcessEvents
| where (FolderPath endswith "\\nltest.exe" or ProcessVersionInfoOriginalFileName =~ "nltestrk.exe") and ((ProcessCommandLine contains "server" and ProcessCommandLine contains "query") or (ProcessCommandLine contains "/user" or ProcessCommandLine contains "all_trusts" or ProcessCommandLine contains "dclist:" or ProcessCommandLine contains "dnsgetdc:" or ProcessCommandLine contains "domain_trusts" or ProcessCommandLine contains "dsgetdc:" or ProcessCommandLine contains "parentdomain" or ProcessCommandLine contains "trusted_domains"))