// Title: Arbitrary File Download Via MSEDGE_PROXY.EXE
// Author: Swachchhanda Shrawan Poudel
// Date: 2023-11-09
// Level: medium
// Description: Detects usage of "msedge_proxy.exe" to download arbitrary files
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_msedge_proxy_download.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://") and (FolderPath endswith "\\msedge_proxy.exe" or ProcessVersionInfoOriginalFileName =~ "msedge_proxy.exe")