// Title: PowerShell Web Access Feature Enabled Via DISM
// Author: Michael Haag
// Date: 2024-09-03
// Level: high
// Description: Detects the use of DISM to enable the PowerShell Web Access feature, which could be used for remote access and potential abuse
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.defense-evasion, attack.persistence, attack.t1548.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_dism_enable_powershell_web_access_feature.yml
// False Positives:
//   - Legitimate PowerShell Web Access installations by administrators

DeviceProcessEvents
| where (ProcessCommandLine contains "WindowsPowerShellWebAccess" and ProcessCommandLine contains "/online" and ProcessCommandLine contains "/enable-feature") and (FolderPath endswith "\\dism.exe" or ProcessVersionInfoOriginalFileName =~ "DISM.EXE")