// Title: UAC Bypass Using Disk Cleanup
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-30
// Level: high
// Description: Detects the pattern of UAC Bypass using scheduled tasks and variable expansion of cleanmgr.exe (UACMe 34)
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1548.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_uac_bypass_cleanmgr.yml

DeviceProcessEvents
| where ProcessCommandLine endswith "\"\\system32\\cleanmgr.exe /autoclean /d C:" and (ProcessIntegrityLevel in~ ("High", "System", "S-1-16-16384", "S-1-16-12288")) and InitiatingProcessCommandLine =~ "C:\\Windows\\system32\\svchost.exe -k netsvcs -p -s Schedule"