// Title: Potential Download/Upload Activity Using Type Command
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-14
// Level: medium
// Description: Detects usage of the "type" command to download/upload data from WebDAV server
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_cmd_type_arbitrary_file_download.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "type \\\\" and ProcessCommandLine contains " > ") or (ProcessCommandLine contains "type " and ProcessCommandLine contains " > \\\\")