// Title: Potentially Suspicious Execution Of Regasm/Regsvcs With Uncommon Extension
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-13
// Level: medium
// Description: Detects potentially suspicious execution of the Regasm/Regsvcs utilities with an uncommon extension.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.009
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_regasm_regsvcs_uncommon_extension_execution.yml

DeviceProcessEvents
| where (ProcessCommandLine contains ".dat" or ProcessCommandLine contains ".gif" or ProcessCommandLine contains ".jpeg" or ProcessCommandLine contains ".jpg" or ProcessCommandLine contains ".png" or ProcessCommandLine contains ".txt") and ((FolderPath endswith "\\Regsvcs.exe" or FolderPath endswith "\\Regasm.exe") or (ProcessVersionInfoOriginalFileName in~ ("RegSvcs.exe", "RegAsm.exe")))