// Title: Invoke-Obfuscation Via Use MSHTA
// Author: Nikita Nazarov, oscd.community
// Date: 2020-10-08
// Level: high
// Description: Detects Obfuscated Powershell via use MSHTA in Scripts
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027, attack.execution, attack.t1059.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_invoke_obfuscation_via_use_mhsta.yml

DeviceProcessEvents
| where ProcessCommandLine contains "set" and ProcessCommandLine contains "&&" and ProcessCommandLine contains "mshta" and ProcessCommandLine contains "vbscript:createobject" and ProcessCommandLine contains ".run" and ProcessCommandLine contains "(window.close)"