// Title: Persistence Via Sticky Key Backdoor
// Author: Sreeman
// Date: 2020-02-18
// Level: critical
// Description: By replacing the sticky keys executable with the local admins CMD executable, an attacker is able to access a privileged windows console session without authenticating to the system.
// When the sticky keys are "activated" the privilleged shell is launched.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1546.008, attack.privilege-escalation
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_cmd_sticky_keys_replace.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains "copy " and ProcessCommandLine contains "/y " and ProcessCommandLine contains "C:\\windows\\system32\\cmd.exe C:\\windows\\system32\\sethc.exe"