// Title: LSA PPL Protection Disabled Via Reg.EXE
// Author: Florian Roth (Nextron Systems)
// Date: 2022-03-22
// Level: high
// Description: Detects the usage of the "reg.exe" utility to disable PPL protection on the LSA process
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.010
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_reg_lsa_ppl_protection_disabled.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (ProcessCommandLine contains "SYSTEM\\CurrentControlSet\\Control\\Lsa" and (ProcessCommandLine contains " add " and ProcessCommandLine contains " /d 0" and ProcessCommandLine contains " /v RunAsPPL ")) and (FolderPath endswith "\\reg.exe" or ProcessVersionInfoOriginalFileName =~ "reg.exe")