// Title: Powershell Executed From Headless ConHost Process
// Author: Matt Anderson (Huntress)
// Date: 2024-07-23
// Level: medium
// Description: Detects the use of powershell commands from headless ConHost window.
// The "--headless" flag hides the windows from the user upon execution.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1059.001, attack.t1059.003, attack.t1564.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_conhost_headless_powershell.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "--headless" and ProcessCommandLine contains "powershell") and (FolderPath endswith "\\conhost.exe" or ProcessVersionInfoOriginalFileName =~ "CONHOST.EXE")