// Title: UAC Bypass Using IDiagnostic Profile
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-03
// Level: high
// Description: Detects the "IDiagnosticProfileUAC" UAC bypass technique
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, attack.privilege-escalation, attack.t1548.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_uac_bypass_idiagnostic_profile.yml

DeviceProcessEvents
| where (ProcessIntegrityLevel in~ ("High", "System", "S-1-16-16384", "S-1-16-12288")) and InitiatingProcessCommandLine contains " /Processid:{12C21EA7-2EB8-4B55-9249-AC243DA8C666}" and InitiatingProcessFolderPath endswith "\\DllHost.exe"