// Title: RDP Connection Allowed Via Netsh.EXE
// Author: Sander Wiebing
// Date: 2020-05-23
// Level: high
// Description: Detects usage of the netsh command to open and allow connections to port 3389 (RDP). As seen used by Sarwent Malware
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_netsh_fw_allow_rdp.yml
// False Positives:
//   - Legitimate administration activity

DeviceProcessEvents
| where ((ProcessCommandLine contains "portopening" or ProcessCommandLine contains "allow") and (ProcessCommandLine contains "firewall " and ProcessCommandLine contains "add " and ProcessCommandLine contains "tcp " and ProcessCommandLine contains "3389")) and (FolderPath endswith "\\netsh.exe" or ProcessVersionInfoOriginalFileName =~ "netsh.exe")