// Title: Suspicious Diantz Alternate Data Stream Execution
// Author: frack113
// Date: 2021-11-26
// Level: medium
// Description: Compress target file into a cab file stored in the Alternate Data Stream (ADS) of the target file.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1564.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_diantz_ads.yml
// False Positives:
//   - Very Possible

DeviceProcessEvents
| where (ProcessCommandLine contains "diantz.exe" and ProcessCommandLine contains ".cab") and ProcessCommandLine matches regex ":[^\\\\]"