// Title: Suspicious GUP Usage
// Author: Florian Roth (Nextron Systems)
// Date: 2019-02-06
// Level: high
// Description: Detects execution of the Notepad++ updater in a suspicious directory, which is often used in DLL side-loading attacks
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.defense-evasion, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_gup_suspicious_execution.yml
// False Positives:
//   - Execution of tools named GUP.exe and located in folders different than Notepad++\updater

DeviceProcessEvents
| where FolderPath endswith "\\GUP.exe" and (not(((FolderPath endswith "\\Program Files\\Notepad++\\updater\\GUP.exe" or FolderPath endswith "\\Program Files (x86)\\Notepad++\\updater\\GUP.exe") or (FolderPath contains "\\Users\\" and (FolderPath endswith "\\AppData\\Local\\Notepad++\\updater\\GUP.exe" or FolderPath endswith "\\AppData\\Roaming\\Notepad++\\updater\\GUP.exe")))))