// Title: LOLBAS Data Exfiltration by DataSvcUtil.exe
// Author: Ialle Teixeira @teixeira0xfffff, Austin Songer @austinsonger
// Date: 2021-09-30
// Level: medium
// Description: Detects when a user performs data exfiltration by using DataSvcUtil.exe
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.t1567
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_data_exfiltration_by_using_datasvcutil.yml
// False Positives:
//   - DataSvcUtil.exe being used may be performed by a system administrator.
//   - Verify whether the user identity, user agent, and/or hostname should be making changes in your environment.
//   - DataSvcUtil.exe being executed from unfamiliar users should be investigated. If known behavior is causing false positives, it can be exempted from the rule.

DeviceProcessEvents
| where (ProcessCommandLine contains "/in:" or ProcessCommandLine contains "/out:" or ProcessCommandLine contains "/uri:") and (FolderPath endswith "\\DataSvcUtil.exe" or ProcessVersionInfoOriginalFileName =~ "DataSvcUtil.exe")