// Title: BitLockerTogo.EXE Execution
// Author: Josh Nickels, mttaggart
// Date: 2024-07-11
// Level: low
// Description: Detects the execution of "BitLockerToGo.EXE".
// BitLocker To Go is BitLocker Drive Encryption on removable data drives. This feature includes the encryption of, USB flash drives, SD cards, External hard disk drives, Other drives that are formatted by using the NTFS, FAT16, FAT32, or exFAT file system.
// This is a rarely used application and usage of it at all is worth investigating.
// Malware such as Lumma stealer has been seen using this process as a target for process hollowing.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_bitlockertogo_execution.yml
// False Positives:
//   - Legitimate usage of BitLockerToGo.exe to encrypt portable devices.

DeviceProcessEvents
| where FolderPath endswith "\\BitLockerToGo.exe"