// Title: Unusual Child Process of dns.exe
// Author: Tim Rauch, Elastic (idea)
// Date: 2022-09-27
// Level: high
// Description: Detects an unexpected process spawning from dns.exe which may indicate activity related to remote code execution or other forms of exploitation as seen in CVE-2020-1350 (SigRed)
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.initial-access, attack.t1133
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_dns_susp_child_process.yml

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\dns.exe" and (not(FolderPath endswith "\\conhost.exe"))