// Title: Potential Remote Desktop Tunneling
// Author: Tim Rauch, Elastic (idea)
// Date: 2022-09-27
// Level: medium
// Description: Detects potential use of an SSH utility to establish RDP over a reverse SSH Tunnel. This can be used by attackers to enable routing of network packets that would otherwise not reach their intended destination.
// MITRE Tactic: Lateral Movement
// Tags: attack.lateral-movement, attack.t1021
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_remote_desktop_tunneling.yml

DeviceProcessEvents
| where ProcessCommandLine contains ":3389" and (ProcessCommandLine contains " -L " or ProcessCommandLine contains " -P " or ProcessCommandLine contains " -R " or ProcessCommandLine contains " -pw " or ProcessCommandLine contains " -ssh ")