// Title: Password Set to Never Expire via WMI
// Author: Daniel Koifman (KoifSec)
// Date: 2025-07-30
// Level: medium
// Description: Detects the use of wmic.exe to modify user account settings and explicitly disable password expiration.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.execution, attack.persistence, attack.t1047, attack.t1098
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wmi_password_never_expire.yml
// False Positives:
//   - Legitimate administrative activity

DeviceProcessEvents
| where (ProcessCommandLine contains "useraccount" and ProcessCommandLine contains " set " and ProcessCommandLine contains "passwordexpires" and ProcessCommandLine contains "false") and (FolderPath endswith "\\wmic.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")