// Title: Potential PsExec Remote Execution
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-28
// Level: high
// Description: Detects potential psexec command that initiate execution on a remote systems via common commandline flags used by the utility
// MITRE Tactic: Resource Development
// Tags: attack.resource-development, attack.t1587.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sysinternals_psexec_remote_execution.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "accepteula" and ProcessCommandLine contains " -u " and ProcessCommandLine contains " -p " and ProcessCommandLine contains " \\\\") and (not((ProcessCommandLine contains "\\\\localhost" or ProcessCommandLine contains "\\\\127.")))