// Title: TrustedPath UAC Bypass Pattern
// Author: Florian Roth (Nextron Systems)
// Date: 2021-08-27
// Level: critical
// Description: Detects indicators of a UAC bypass method by mocking directories
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.defense-evasion, attack.t1548.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_uac_bypass_trustedpath.yml

DeviceProcessEvents
| where FolderPath contains "C:\\Windows \\System32\\" or FolderPath contains "C:\\Windows \\SysWOW64\\"