// Title: Outlook EnableUnsafeClientMailRules Setting Enabled
// Author: Markus Neis, Nasreddine Bencherchali (Nextron Systems)
// Date: 2018-12-27
// Level: high
// Description: Detects an attacker trying to enable the outlook security setting "EnableUnsafeClientMailRules" which allows outlook to run applications or execute macros
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, attack.t1059, attack.t1202
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_office_outlook_enable_unsafe_client_mail_rules.yml

DeviceProcessEvents
| where ProcessCommandLine contains "\\Outlook\\Security\\EnableUnsafeClientMailRules"