// Title: Potential Password Spraying Attempt Using Dsacls.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-20
// Level: medium
// Description: Detects possible password spraying attempts using Dsacls
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_dsacls_password_spray.yml
// False Positives:
//   - Legitimate use of dsacls to bind to an LDAP session

DeviceProcessEvents
| where (ProcessCommandLine contains "/user:" and ProcessCommandLine contains "/passwd:") and (FolderPath endswith "\\dsacls.exe" or ProcessVersionInfoOriginalFileName =~ "DSACLS.EXE")