// Title: Potential Data Stealing Via Chromium Headless Debugging
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-23
// Level: high
// Description: Detects chromium based browsers starting in headless and debugging mode and pointing to a user profile. This could be a sign of data stealing or remote control
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.credential-access, attack.collection, attack.t1185, attack.t1564.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_browsers_chromium_headless_debugging.yml

DeviceProcessEvents
| where ProcessCommandLine contains "--remote-debugging-" and ProcessCommandLine contains "--user-data-dir" and ProcessCommandLine contains "--headless"