// Title: Potential RDP Tunneling Via Plink
// Author: Florian Roth (Nextron Systems)
// Date: 2022-08-04
// Level: high
// Description: Execution of plink to perform data exfiltration and tunneling
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1572
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_plink_susp_tunneling.yml

DeviceProcessEvents
| where (ProcessCommandLine contains ":127.0.0.1:3389" and FolderPath endswith "\\plink.exe") or ((ProcessCommandLine contains ":3389" and FolderPath endswith "\\plink.exe") and (ProcessCommandLine contains " -P 443" or ProcessCommandLine contains " -P 22"))