// Title: Suspicious DumpMinitool Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-04-06
// Level: high
// Description: Detects suspicious ways to use the "DumpMinitool.exe" binary
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.credential-access, attack.t1036, attack.t1003.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_dumpminitool_susp_execution.yml

DeviceProcessEvents
| where ((FolderPath endswith "\\DumpMinitool.exe" or FolderPath endswith "\\DumpMinitool.x86.exe" or FolderPath endswith "\\DumpMinitool.arm64.exe") or (ProcessVersionInfoOriginalFileName in~ ("DumpMinitool.exe", "DumpMinitool.x86.exe", "DumpMinitool.arm64.exe"))) and ((not((FolderPath contains "\\Microsoft Visual Studio\\" or FolderPath contains "\\Extensions\\"))) or ProcessCommandLine contains ".txt" or ((ProcessCommandLine contains " Full" or ProcessCommandLine contains " Mini" or ProcessCommandLine contains " WithHeap") and (not(ProcessCommandLine contains "--dumpType"))))