// Title: Run PowerShell Script from Redirected Input Stream
// Author: Moriarty Meng (idea), Anton Kutepov (rule), oscd.community
// Date: 2020-10-17
// Level: high
// Description: Detects PowerShell script execution via input stream redirect
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1059
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_run_script_from_input_stream.yml

DeviceProcessEvents
| where ProcessCommandLine matches regex "\\s-\\s*<" and (FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")