// Title: Suspicious VBoxDrvInst.exe Parameters
// Author: Konstantin Grishchenko, oscd.community
// Date: 2020-10-06
// Level: medium
// Description: Detect VBoxDrvInst.exe run with parameters allowing processing INF file.
// This allows to create values in the registry and install drivers.
// For example one could use this technique to obtain persistence via modifying one of Run or RunOnce registry keys
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_virtualbox_vboxdrvinst_execution.yml
// False Positives:
//   - Legitimate use of VBoxDrvInst.exe utility by VirtualBox Guest Additions installation process

DeviceProcessEvents
| where (ProcessCommandLine contains "driver" and ProcessCommandLine contains "executeinf") and FolderPath endswith "\\VBoxDrvInst.exe"