// Title: Potential Obfuscated Ordinal Call Via Rundll32
// Author: Nasreddine Bencherchali (Nextron Systems), Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2023-05-17
// Level: medium
// Description: Detects execution of "rundll32" with potential obfuscated ordinal calls
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027.010
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_rundll32_obfuscated_ordinal_call.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "#+" or ProcessCommandLine contains "#-" or ProcessCommandLine contains "#0" or ProcessCommandLine contains "#655" or ProcessCommandLine contains "#656") and (FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE" or ProcessCommandLine contains "rundll32")