// Title: Add Windows Capability Via PowerShell Cmdlet
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-22
// Level: medium
// Description: Detects usage of the "Add-WindowsCapability" cmdlet to add Windows capabilities. Notable capabilities could be "OpenSSH" and others.
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_add_windows_capability.yml
// False Positives:
//   - Legitimate usage of the capabilities by administrators or users. Add additional filters accordingly.

DeviceProcessEvents
| where ProcessCommandLine contains "OpenSSH." and ProcessCommandLine contains "Add-WindowsCapability" and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")))