// Title: Potential Mftrace.EXE Abuse
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-09
// Level: medium
// Description: Detects child processes of the "Trace log generation tool for Media Foundation Tools" (Mftrace.exe) which can abused to execute arbitrary binaries.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1127
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_mftrace_child_process.yml
// False Positives:
//   - Legitimate use for tracing purposes

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\mftrace.exe"