// Title: Abusing Print Executable
// Author: Furkan CALISKAN, @caliskanfurkan_, @oscd_initiative
// Date: 2020-10-05
// Level: medium
// Description: Attackers can use print.exe for remote file copy
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_print_remote_file_copy.yml

DeviceProcessEvents
| where ((ProcessCommandLine contains "/D" and ProcessCommandLine contains ".exe") and ProcessCommandLine startswith "print" and FolderPath endswith "\\print.exe") and (not(ProcessCommandLine contains "print.exe"))