// Title: Replace.exe Usage
// Author: frack113
// Date: 2022-03-06
// Level: medium
// Description: Detects the use of Replace.exe which can be used to replace file with another file
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_replace.yml

DeviceProcessEvents
| where FolderPath endswith "\\replace.exe" and (ProcessCommandLine contains "-a" or ProcessCommandLine contains "/a" or ProcessCommandLine contains "–a" or ProcessCommandLine contains "—a" or ProcessCommandLine contains "―a")