// Title: Suspicious Plink Port Forwarding
// Author: Florian Roth (Nextron Systems)
// Date: 2021-01-19
// Level: high
// Description: Detects suspicious Plink tunnel port forwarding to a local port
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1572, attack.lateral-movement, attack.t1021.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_plink_port_forwarding.yml
// False Positives:
//   - Administrative activity using a remote port forwarding to a local port

DeviceProcessEvents
| where ProcessCommandLine contains " -R " and ProcessVersionInfoFileDescription =~ "Command-line SSH, Telnet, and Rlogin client"