// Title: PowerShell Script Change Permission Via Set-Acl
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-18
// Level: high
// Description: Detects PowerShell execution to set the ACL of a file or a folder
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_set_acl.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "Set-Acl " and ProcessCommandLine contains "-AclObject " and ProcessCommandLine contains "-Path ") and ((ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")) or (FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe"))