// Title: Potentially Suspicious GoogleUpdate Child Process
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-15
// Level: high
// Description: Detects potentially suspicious child processes of "GoogleUpdate.exe"
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_googleupdate_susp_child_process.yml

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\GoogleUpdate.exe" and (not((isnull(FolderPath) or (FolderPath contains "\\Google" or (FolderPath endswith "\\setup.exe" or FolderPath endswith "chrome_updater.exe" or FolderPath endswith "chrome_installer.exe")))))