// Title: Execute Files with Msdeploy.exe
// Author: Beyu Denis, oscd.community
// Date: 2020-10-18
// Level: medium
// Description: Detects file execution using the msdeploy.exe lolbin
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_msdeploy.yml
// False Positives:
//   - System administrator Usage

DeviceProcessEvents
| where (ProcessCommandLine contains "verb:sync" and ProcessCommandLine contains "-source:RunCommand" and ProcessCommandLine contains "-dest:runCommand") and FolderPath endswith "\\msdeploy.exe"