// Title: Windows Defender Context Menu Removed
// Author: Matt Anderson (Huntress)
// Date: 2025-07-09
// Level: high
// Description: Detects the use of reg.exe or PowerShell to delete the Windows Defender context menu handler registry keys.
// This action removes the "Scan with Microsoft Defender" option from the right-click menu for files, directories, and drives.
// Attackers may use this technique to hinder manual, on-demand scans and reduce the visibility of the security product.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_defender_remove_context_menu.yml
// False Positives:
//   - May be part of a system customization or "debloating" script, but this is highly unusual in a managed corporate environment.

DeviceProcessEvents
| where (ProcessCommandLine contains "del" or ProcessCommandLine contains "Remove-Item" or ProcessCommandLine contains "ri ") and ((FolderPath endswith "\\powershell_ise.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\reg.exe") or (ProcessVersionInfoOriginalFileName in~ ("powershell_ise.EXE", "PowerShell.EXE", "pwsh.dll", "reg.exe"))) and ProcessCommandLine contains "\\shellex\\ContextMenuHandlers\\EPP"