// Title: WmiPrvSE Spawned A Process
// Author: Roberto Rodriguez @Cyb3rWard0g
// Date: 2019-08-15
// Level: medium
// Description: Detects WmiPrvSE spawning a process
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1047
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wmiprvse_spawning_process.yml
// False Positives:
//   - False positives are expected (e.g. in environments where WinRM is used legitimately)

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\WmiPrvSe.exe" and (not(((LogonId in~ ("0x3e7", "null")) or isnull(LogonId) or (AccountName contains "AUTHORI" or AccountName contains "AUTORI") or FolderPath endswith "\\WerFault.exe" or FolderPath endswith "\\WmiPrvSE.exe")))