// Title: Hardware Model Reconnaissance Via Wmic.EXE
// Author: Florian Roth (Nextron Systems)
// Date: 2023-02-14
// Level: medium
// Description: Detects the execution of WMIC with the "csproduct" which is used to obtain information such as hardware models and vendor information
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1047, car.2016-03-002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wmic_recon_csproduct.yml

DeviceProcessEvents
| where ProcessCommandLine contains "csproduct" and (FolderPath endswith "\\wmic.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")