// Title: PUA - Chisel Tunneling Tool Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-09-13
// Level: high
// Description: Detects usage of the Chisel tunneling tool via the commandline arguments
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1090.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_chisel.yml
// False Positives:
//   - Some false positives may occur with other tools with similar commandlines

DeviceProcessEvents
| where FolderPath endswith "\\chisel.exe" or ((ProcessCommandLine contains "exe client " or ProcessCommandLine contains "exe server ") and (ProcessCommandLine contains "-socks5" or ProcessCommandLine contains "-reverse" or ProcessCommandLine contains " r:" or ProcessCommandLine contains ":127.0.0.1:" or ProcessCommandLine contains "-tls-skip-verify " or ProcessCommandLine contains ":socks"))