// Title: Suspicious PowerShell Mailbox Export to Share
// Author: Florian Roth (Nextron Systems)
// Date: 2021-08-07
// Level: critical
// Description: Detects usage of the powerShell New-MailboxExportRequest Cmdlet to exports a mailbox to a remote or local share, as used in ProxyShell exploitations
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_mailboxexport_share.yml

DeviceProcessEvents
| where ProcessCommandLine contains "New-MailboxExportRequest" and ProcessCommandLine contains " -Mailbox " and ProcessCommandLine contains " -FilePath \\\\"