// Title: Gzip Archive Decode Via PowerShell
// Author: Hieu Tran
// Date: 2023-03-13
// Level: medium
// Description: Detects attempts of decoding encoded Gzip archives via PowerShell.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1132.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_decode_gzip.yml
// False Positives:
//   - Legitimate administrative scripts may use this functionality. Use "ParentImage" in combination with the script names and allowed users and applications to filter legitimate executions

DeviceProcessEvents
| where ProcessCommandLine contains "GZipStream" and ProcessCommandLine contains "::Decompress"