// Title: Virtualbox Driver Installation or Starting of VMs
// Author: Janantha Marasinghe
// Date: 2020-09-26
// Level: low
// Description: Adversaries can carry out malicious operations using a virtual instance to avoid detection. This rule is built to detect the registration of the Virtualbox driver or start of a Virtualbox VM.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1564.006, attack.t1564
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_virtualbox_execution.yml
// False Positives:
//   - This may have false positives on hosts where Virtualbox is legitimately being used for operations

DeviceProcessEvents
| where (ProcessCommandLine contains "VBoxRT.dll,RTR3Init" or ProcessCommandLine contains "VBoxC.dll" or ProcessCommandLine contains "VBoxDrv.sys") or (ProcessCommandLine contains "startvm" or ProcessCommandLine contains "controlvm")