// Title: Suspicious Usage Of Active Directory Diagnostic Tool (ntdsutil.exe)
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-14
// Level: medium
// Description: Detects execution of ntdsutil.exe to perform different actions such as restoring snapshots...etc.
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_ntdsutil_susp_usage.yml
// False Positives:
//   - Legitimate usage to restore snapshots
//   - Legitimate admin activity

DeviceProcessEvents
| where ((ProcessCommandLine contains "snapshot" and ProcessCommandLine contains "mount ") or (ProcessCommandLine contains "ac" and ProcessCommandLine contains " i" and ProcessCommandLine contains " ntds")) and (FolderPath endswith "\\ntdsutil.exe" or ProcessVersionInfoOriginalFileName =~ "ntdsutil.exe")