// Title: Execution via stordiag.exe
// Author: Austin Songer (@austinsonger)
// Date: 2021-10-21
// Level: high
// Description: Detects the use of stordiag.exe to execute schtasks.exe systeminfo.exe and fltmc.exe
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_stordiag_susp_child_process.yml
// False Positives:
//   - Legitimate usage of stordiag.exe.

DeviceProcessEvents
| where ((FolderPath endswith "\\schtasks.exe" or FolderPath endswith "\\systeminfo.exe" or FolderPath endswith "\\fltmc.exe") and InitiatingProcessFolderPath endswith "\\stordiag.exe") and (not((InitiatingProcessFolderPath startswith "c:\\windows\\system32\\" or InitiatingProcessFolderPath startswith "c:\\windows\\syswow64\\")))