// Title: DriverQuery.EXE Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-01-19
// Level: medium
// Description: Detect usage of the "driverquery" utility. Which can be used to perform reconnaissance on installed drivers
// MITRE Tactic: Discovery
// Tags: attack.discovery
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_driverquery_usage.yml
// False Positives:
//   - Legitimate use by third party tools in order to investigate installed drivers

DeviceProcessEvents
| where (FolderPath endswith "driverquery.exe" or ProcessVersionInfoOriginalFileName =~ "drvqry.exe") and (not(((InitiatingProcessFolderPath endswith "\\cscript.exe" or InitiatingProcessFolderPath endswith "\\mshta.exe" or InitiatingProcessFolderPath endswith "\\regsvr32.exe" or InitiatingProcessFolderPath endswith "\\rundll32.exe" or InitiatingProcessFolderPath endswith "\\wscript.exe") or (InitiatingProcessFolderPath contains "\\AppData\\Local\\" or InitiatingProcessFolderPath contains "\\Users\\Public\\" or InitiatingProcessFolderPath contains "\\Windows\\Temp\\"))))