// Title: Audit Policy Tampering Via Auditpol
// Author: Janantha Marasinghe (https://github.com/blueteam0ps)
// Date: 2021-02-02
// Level: high
// Description: Threat actors can use auditpol binary to change audit policy configuration to impair detection capability.
// This can be carried out by selectively disabling/removing certain audit policies as well as restoring a custom policy owned by the threat actor.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_auditpol_susp_execution.yml
// False Positives:
//   - Administrator or administrator scripts might leverage the flags mentioned in the detection section. Either way, it should always be monitored

DeviceProcessEvents
| where (ProcessCommandLine contains "disable" or ProcessCommandLine contains "clear" or ProcessCommandLine contains "remove" or ProcessCommandLine contains "restore") and (FolderPath endswith "\\auditpol.exe" or ProcessVersionInfoOriginalFileName =~ "AUDITPOL.EXE")