// Title: Tap Installer Execution
// Author: Daniil Yugoslavskiy, Ian Davis, oscd.community
// Date: 2019-10-24
// Level: medium
// Description: Well-known TAP software installation. Possible preparation for data exfiltration using tunneling techniques
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.t1048
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_tapinstall_execution.yml
// False Positives:
//   - Legitimate OpenVPN TAP installation

DeviceProcessEvents
| where FolderPath endswith "\\tapinstall.exe" and (not(((FolderPath contains ":\\Program Files\\Avast Software\\SecureLine VPN\\" or FolderPath contains ":\\Program Files (x86)\\Avast Software\\SecureLine VPN\\") or FolderPath contains ":\\Program Files\\OpenVPN Connect\\drivers\\tap\\" or FolderPath contains ":\\Program Files (x86)\\Proton Technologies\\ProtonVPNTap\\installer\\")))