// Title: UAC Bypass Using DismHost
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-30
// Level: high
// Description: Detects the pattern of UAC Bypass using DismHost DLL hijacking (UACMe 63)
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1548.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_uac_bypass_dismhost.yml

DeviceProcessEvents
| where (ProcessIntegrityLevel in~ ("High", "System", "S-1-16-16384", "S-1-16-12288")) and (InitiatingProcessFolderPath contains "C:\\Users\\" and InitiatingProcessFolderPath contains "\\AppData\\Local\\Temp\\" and InitiatingProcessFolderPath contains "\\DismHost.exe")