// Title: Lolbin Runexehelper Use As Proxy
// Author: frack113
// Date: 2022-12-29
// Level: medium
// Description: Detect usage of the "runexehelper.exe" binary as a proxy to launch other programs
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_runexehelper.yml

DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\runexehelper.exe"