// Title: Remote Code Execute via Winrm.vbs
// Author: Julia Fomina, oscd.community
// Date: 2020-10-07
// Level: medium
// Description: Detects an attempt to execute code or create service on remote host via winrm.vbs.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1216
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_winrm_execution_via_scripting_api_winrm_vbs.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "winrm" and ProcessCommandLine contains "invoke Create wmicimv2/Win32_" and ProcessCommandLine contains "-r:http") and (FolderPath endswith "\\cscript.exe" or ProcessVersionInfoOriginalFileName =~ "cscript.exe")