// Title: HackTool - F-Secure C3 Load by Rundll32
// Author: Alfie Champion (ajpc500)
// Date: 2021-06-02
// Level: critical
// Description: F-Secure C3 produces DLLs with a default exported StartNodeRelay function.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.011
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_c3_rundll32_pattern.yml

DeviceProcessEvents
| where ProcessCommandLine contains "rundll32.exe" and ProcessCommandLine contains ".dll" and ProcessCommandLine contains "StartNodeRelay"