// Title: OpenEDR Spawning Command Shell
// Author: @kostastsale
// Date: 2026-02-19
// Level: medium
// Description: Detects the OpenEDR ssh-shellhost.exe spawning a command shell (cmd.exe) or PowerShell with PTY (pseudo-terminal) capabilities.
// This may indicate remote command execution through OpenEDR's remote management features, which could be legitimate administrative activity or potential abuse of the remote access tool.
// Threat actors may leverage OpenEDR's remote shell capabilities to execute commands on compromised systems, facilitating lateral movement or other command-and-control operations.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.003, attack.lateral-movement, attack.t1021.004, attack.command-and-control, attack.t1219
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_comodo_ssh_shellhost_cmd_spawn.yml
// False Positives:
//   - Legitimate use of OpenEDR for remote command execution

DeviceProcessEvents
| where (ProcessCommandLine contains "bash" or ProcessCommandLine contains "cmd" or ProcessCommandLine contains "powershell" or ProcessCommandLine contains "pwsh") and (ProcessCommandLine contains "--pty" and FolderPath endswith "\\ssh-shellhost.exe" and InitiatingProcessFolderPath endswith "\\ITSMService.exe")