// Title: Suspicious Rundll32 Activity Invoking Sys File
// Author: Florian Roth (Nextron Systems)
// Date: 2021-03-05
// Level: high
// Description: Detects suspicious process related to rundll32 based on command line that includes a *.sys file as seen being used by UNC2452
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.011
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_rundll32_sys.yml

DeviceProcessEvents
| where ProcessCommandLine contains "rundll32.exe" and (ProcessCommandLine contains ".sys," or ProcessCommandLine contains ".sys ")