// Title: Suspicious Schtasks Schedule Type With High Privileges
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-31
// Level: medium
// Description: Detects scheduled task creations or modification to be run with high privileges on a suspicious schedule type
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.execution, attack.t1053.005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_schtasks_schedule_type_system.yml
// False Positives:
//   - Some installers were seen using this method of creation unfortunately. Filter them in your environment

DeviceProcessEvents
| where (FolderPath endswith "\\schtasks.exe" or ProcessVersionInfoOriginalFileName =~ "schtasks.exe") and (ProcessCommandLine contains "NT AUT" or ProcessCommandLine contains " SYSTEM" or ProcessCommandLine contains "HIGHEST") and (ProcessCommandLine contains " ONLOGON " or ProcessCommandLine contains " ONSTART " or ProcessCommandLine contains " ONCE " or ProcessCommandLine contains " ONIDLE ")