// Title: Remote XSL Execution Via Msxsl.EXE
// Author: Swachchhanda Shrawan Poudel
// Date: 2023-11-09
// Level: high
// Description: Detects the execution of the "msxsl" binary with an "http" keyword in the command line. This might indicate a potential remote execution of XSL files.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1220
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_msxsl_remote_execution.yml
// False Positives:
//   - Msxsl is not installed by default and is deprecated, so unlikely on most systems.

DeviceProcessEvents
| where ProcessCommandLine contains "http" and FolderPath endswith "\\msxsl.exe"