// Title: Audio Capture via SoundRecorder
// Author: E.M. Anhaus (originally from Atomic Blue Detections, Endgame), oscd.community
// Date: 2019-10-24
// Level: medium
// Description: Detect attacker collecting audio via SoundRecorder application.
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1123
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_soundrecorder_audio_capture.yml
// False Positives:
//   - Legitimate audio capture by legitimate user.

DeviceProcessEvents
| where ProcessCommandLine contains "/FILE" and FolderPath endswith "\\SoundRecorder.exe"