// Title: Sysinternals PsService Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-16
// Level: medium
// Description: Detects usage of Sysinternals PsService which can be abused for service reconnaissance and tampering
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.discovery, attack.persistence, attack.t1543.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sysinternals_psservice.yml
// False Positives:
//   - Legitimate use of PsService by an administrator

DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "psservice.exe" or (FolderPath endswith "\\PsService.exe" or FolderPath endswith "\\PsService64.exe")