// Title: Use of Pcalua For Execution
// Author: Nasreddine Bencherchali (Nextron Systems), E.M. Anhaus (originally from Atomic Blue Detections, Endgame), oscd.community
// Date: 2022-06-14
// Level: medium
// Description: Detects execition of commands and binaries from the context of The program compatibility assistant (Pcalua.exe). This can be used as a LOLBIN in order to bypass application whitelisting.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_pcalua.yml
// False Positives:
//   - Legitimate use by a via a batch script or by an administrator.

DeviceProcessEvents
| where ProcessCommandLine contains " -a" and FolderPath endswith "\\pcalua.exe"