// Title: Suspicious UltraVNC Execution
// Author: Bhabesh Raj
// Date: 2022-03-04
// Level: high
// Description: Detects suspicious UltraVNC command line flag combination that indicate a auto reconnect upon execution, e.g. startup (as seen being used by Gamaredon threat group)
// MITRE Tactic: Lateral Movement
// Tags: attack.lateral-movement, attack.g0047, attack.t1021.005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_ultravnc_susp_execution.yml

DeviceProcessEvents
| where ProcessCommandLine contains "-autoreconnect " and ProcessCommandLine contains "-connect " and ProcessCommandLine contains "-id:"