// Title: Xwizard.EXE Execution From Non-Default Location
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-09-20
// Level: high
// Description: Detects the execution of Xwizard tool from a non-default directory.
// When executed from a non-default directory, this utility can be abused in order to side load a custom version of "xwizards.dll".
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.defense-evasion, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_xwizard_execution_non_default_location.yml
// False Positives:
//   - Windows installed on non-C drive

DeviceProcessEvents
| where (FolderPath endswith "\\xwizard.exe" or ProcessVersionInfoOriginalFileName =~ "xwizard.exe") and (not((FolderPath startswith "C:\\Windows\\System32\\" or FolderPath startswith "C:\\Windows\\SysWOW64\\" or FolderPath startswith "C:\\Windows\\WinSxS\\")))