// Title: WhoAmI as Parameter
// Author: Florian Roth (Nextron Systems)
// Date: 2021-11-29
// Level: high
// Description: Detects a suspicious process command line that uses whoami as first parameter (as e.g. used by EfsPotato)
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1033, car.2016-03-001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_whoami_as_param.yml

DeviceProcessEvents
| where ProcessCommandLine contains ".exe whoami"