// Title: HackTool - Jlaive In-Memory Assembly Execution
// Author: Jose Luis Sanchez Martinez (@Joseliyo_Jstnk)
// Date: 2022-05-24
// Level: medium
// Description: Detects the use of Jlaive to execute assemblies in a copied PowerShell
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_hktl_jlaive_batch_execution.yml

DeviceProcessEvents
| where (InitiatingProcessCommandLine endswith ".bat" and InitiatingProcessFolderPath endswith "\\cmd.exe") and (((ProcessCommandLine contains "powershell.exe" and ProcessCommandLine contains ".bat.exe") and FolderPath endswith "\\xcopy.exe") or ((ProcessCommandLine contains "pwsh.exe" and ProcessCommandLine contains ".bat.exe") and FolderPath endswith "\\xcopy.exe") or ((ProcessCommandLine contains "+s" and ProcessCommandLine contains "+h" and ProcessCommandLine contains ".bat.exe") and FolderPath endswith "\\attrib.exe"))