// Title: Query Usage To Exfil Data
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-01
// Level: medium
// Description: Detects usage of "query.exe" a system binary to exfil information such as "sessions" and "processes" for later use
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_query_session_exfil.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "session >" or ProcessCommandLine contains "process >") and FolderPath endswith ":\\Windows\\System32\\query.exe"