// Title: UEFI Persistence Via Wpbbin - ProcessCreation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-18
// Level: high
// Description: Detects execution of the binary "wpbbin" which is used as part of the UEFI based persistence method described in the reference section
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1542.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wpbbin_potential_persistence.yml
// False Positives:
//   - Legitimate usage of the file by hardware manufacturer such as lenovo (Thanks @0gtweet for the tip)

DeviceProcessEvents
| where FolderPath =~ "C:\\Windows\\System32\\wpbbin.exe"