// Title: Suspicious Use of CSharp Interactive Console
// Author: Michael R. (@nahamike01)
// Date: 2020-03-08
// Level: high
// Description: Detects the execution of CSharp interactive console by PowerShell
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, attack.t1127
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_csi_use_of_csharp_console.yml
// False Positives:
//   - Possible depending on environment. Pair with other factors such as net connections, command-line args, etc.

DeviceProcessEvents
| where FolderPath endswith "\\csi.exe" and ProcessVersionInfoOriginalFileName =~ "csi.exe" and (InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe" or InitiatingProcessFolderPath endswith "\\powershell_ise.exe")