// Title: PUA - Nimgrab Execution
// Author: frack113
// Date: 2022-08-28
// Level: high
// Description: Detects the usage of nimgrab, a tool bundled with the Nim programming framework and used for downloading files.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_nimgrab.yml
// False Positives:
//   - Legitimate use of Nim on a developer systems

DeviceProcessEvents
| where (MD5 startswith "2DD44C3C29D667F5C0EF5F9D7C7FFB8B" or SHA256 startswith "F266609E91985F0FE3E31C5E8FAEEEC4FFA5E0322D8B6F15FE69F4C5165B9559") or FolderPath endswith "\\nimgrab.exe"