// Title: Setup16.EXE Execution With Custom .Lst File
// Author: frack113
// Date: 2024-12-01
// Level: medium
// Description: Detects the execution of "Setup16.EXE" and old installation utility with a custom ".lst" file.
// These ".lst" file can contain references to external program that "Setup16.EXE" will execute.
// Attackers and adversaries might leverage this as a living of the land utility.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.defense-evasion, attack.t1574.005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_setup16_custom_lst_execution.yml
// False Positives:
//   - On modern Windows system, the "Setup16" utility is practically never used, hence false positive should be very rare.

DeviceProcessEvents
| where (InitiatingProcessCommandLine contains " -m " and InitiatingProcessFolderPath =~ "C:\\Windows\\SysWOW64\\setup16.exe") and (not(FolderPath startswith "C:\\~MSSETUP.T\\"))