// Title: Potential CommandLine Path Traversal Via Cmd.EXE
// Author: xknow @xknow_infosec, Tim Shelton
// Date: 2020-06-11
// Level: high
// Description: Detects potential path traversal attempt via cmd.exe. Could indicate possible command/argument confusion/hijacking
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_cmd_path_traversal.yml
// False Positives:
//   - Java tools are known to produce false-positive when loading libraries

DeviceProcessEvents
| where (((InitiatingProcessCommandLine contains "/c" or InitiatingProcessCommandLine contains "/k" or InitiatingProcessCommandLine contains "/r") or (ProcessCommandLine contains "/c" or ProcessCommandLine contains "/k" or ProcessCommandLine contains "/r")) and (InitiatingProcessFolderPath endswith "\\cmd.exe" or FolderPath endswith "\\cmd.exe" or ProcessVersionInfoOriginalFileName =~ "cmd.exe") and (InitiatingProcessCommandLine =~ "/../../" or ProcessCommandLine contains "/../../")) and (not(ProcessCommandLine contains "\\Tasktop\\keycloak\\bin\\/../../jre\\bin\\java"))