// Title: CreateDump Process Dump
// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-01-04
// Level: high
// Description: Detects uses of the createdump.exe LOLOBIN utility to dump process memory
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036, attack.t1003.001, attack.credential-access
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_createdump_lolbin_execution.yml
// False Positives:
//   - Command lines that use the same flags

DeviceProcessEvents
| where (ProcessCommandLine contains " -u " or ProcessCommandLine contains " --full " or ProcessCommandLine contains " -f " or ProcessCommandLine contains " --name " or ProcessCommandLine contains ".dmp ") and (FolderPath endswith "\\createdump.exe" or ProcessVersionInfoOriginalFileName =~ "FX_VER_INTERNALNAME_STR")