// Title: Suspicious Process Start Locations
// Author: juju4, Jonhnathan Ribeiro, oscd.community
// Date: 2019-01-16
// Level: medium
// Description: Detects suspicious process run from unusual locations
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036, car.2013-05-002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_rundll32_run_locations.yml
// False Positives:
//   - False positives depend on scripts and administrative tools used in the monitored environment

DeviceProcessEvents
| where (FolderPath contains ":\\RECYCLER\\" or FolderPath contains ":\\SystemVolumeInformation\\") or (FolderPath startswith "C:\\Windows\\Tasks\\" or FolderPath startswith "C:\\Windows\\debug\\" or FolderPath startswith "C:\\Windows\\fonts\\" or FolderPath startswith "C:\\Windows\\help\\" or FolderPath startswith "C:\\Windows\\drivers\\" or FolderPath startswith "C:\\Windows\\addins\\" or FolderPath startswith "C:\\Windows\\cursors\\" or FolderPath startswith "C:\\Windows\\system32\\tasks\\")