// Title: Potential Provisioning Registry Key Abuse For Binary Proxy Execution
// Author: Nasreddine Bencherchali (Nextron Systems), Swachchhanda Shrawan Poudel
// Date: 2023-08-08
// Level: high
// Description: Detects potential abuse of the provisioning registry key for indirect command execution through "Provlaunch.exe".
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_registry_provlaunch_provisioning_command.yml

DeviceProcessEvents
| where ProcessCommandLine contains "SOFTWARE\\Microsoft\\Provisioning\\Commands\\"