// Title: Potential Persistence Via Logon Scripts - CommandLine
// Author: Tom Ueltschi (@c_APT_ure)
// Date: 2019-01-12
// Level: high
// Description: Detects the addition of a new LogonScript to the registry value "UserInitMprLogonScript" for potential persistence
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1037.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_registry_logon_script.yml
// False Positives:
//   - Legitimate addition of Logon Scripts via the command line by administrators or third party tools

DeviceProcessEvents
| where ProcessCommandLine contains "UserInitMprLogonScript"