// Title: Active Directory Structure Export Via Ldifde.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-03-14
// Level: medium
// Description: Detects the execution of "ldifde.exe" in order to export organizational Active Directory structure.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_ldifde_export.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "-f" and (FolderPath endswith "\\ldifde.exe" or ProcessVersionInfoOriginalFileName =~ "ldifde.exe")) and (not(ProcessCommandLine contains " -i"))