// Title: Dropping Of Password Filter DLL
// Author: Sreeman
// Date: 2020-10-29
// Level: medium
// Description: Detects dropping of dll files in system32 that may be used to retrieve user credentials from LSASS
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.credential-access, attack.t1556.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_reg_credential_access_via_password_filter.yml

DeviceProcessEvents
| where ProcessCommandLine contains "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa" and ProcessCommandLine contains "scecli\\0" and ProcessCommandLine contains "reg add"