// Title: Suspicious Download Via Certutil.EXE
// Author: Florian Roth (Nextron Systems), Jonhnathan Ribeiro, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-15
// Level: medium
// Description: Detects the execution of certutil with certain flags that allow the utility to download files.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027, attack.command-and-control, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_certutil_download.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "urlcache " or ProcessCommandLine contains "verifyctl " or ProcessCommandLine contains "URL ") and ProcessCommandLine contains "http" and (FolderPath endswith "\\certutil.exe" or ProcessVersionInfoOriginalFileName =~ "CertUtil.exe")