// Title: Visual Studio Code Tunnel Execution
// Author: Nasreddine Bencherchali (Nextron Systems), citron_ninja
// Date: 2023-10-25
// Level: medium
// Description: Detects Visual Studio Code tunnel execution. Attackers can abuse this functionality to establish a C2 channel
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1071.001, attack.t1219
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_vscode_tunnel_execution.yml
// False Positives:
//   - Legitimate use of Visual Studio Code tunnel

DeviceProcessEvents
| where (ProcessCommandLine endswith ".exe tunnel" and isnull(ProcessVersionInfoOriginalFileName)) or ((ProcessCommandLine contains "/d /c " and ProcessCommandLine contains "\\servers\\Stable-" and ProcessCommandLine contains "code-server.cmd") and FolderPath endswith "\\cmd.exe" and InitiatingProcessCommandLine endswith " tunnel") or (ProcessCommandLine contains ".exe tunnel" and ProcessCommandLine contains "--accept-server-license-terms")