// Title: Suspicious JavaScript Execution Via Mshta.EXE
// Author: E.M. Anhaus (originally from Atomic Blue Detections, Endgame), oscd.community
// Date: 2019-10-24
// Level: high
// Description: Detects execution of javascript code using "mshta.exe".
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_mshta_javascript.yml

DeviceProcessEvents
| where ProcessCommandLine contains "javascript" and (FolderPath endswith "\\mshta.exe" or ProcessVersionInfoOriginalFileName =~ "MSHTA.EXE")