// Title: Firewall Rule Update Via Netsh.EXE
// Author: X__Junior (Nextron Systems)
// Date: 2023-07-18
// Level: medium
// Description: Detects execution of netsh with the "advfirewall" and the "set" option in order to set new values for properties of a existing rule
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_netsh_fw_set_rule.yml
// False Positives:
//   - Legitimate administration activity
//   - Software installations and removal

DeviceProcessEvents
| where (ProcessCommandLine contains " firewall " and ProcessCommandLine contains " set ") and (FolderPath endswith "\\netsh.exe" or ProcessVersionInfoOriginalFileName =~ "netsh.exe")