// Title: PUA - Crassus Execution
// Author: pH-T (Nextron Systems)
// Date: 2023-04-17
// Level: high
// Description: Detects Crassus, a Windows privilege escalation discovery tool, based on PE metadata characteristics.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.reconnaissance, attack.t1590.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_pua_crassus.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where FolderPath endswith "\\Crassus.exe" or ProcessVersionInfoOriginalFileName =~ "Crassus.exe" or ProcessVersionInfoFileDescription contains "Crassus"