// Title: Potential LethalHTA Technique Execution
// Author: Markus Neis
// Date: 2018-06-07
// Level: high
// Description: Detects potential LethalHTA technique where the "mshta.exe" is spawned by an "svchost.exe" process
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_mshta_lethalhta_technique.yml

DeviceProcessEvents
| where FolderPath endswith "\\mshta.exe" and InitiatingProcessFolderPath endswith "\\svchost.exe"