// Title: Wscript Shell Run In CommandLine
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-31
// Level: medium
// Description: Detects the presence of the keywords "Wscript", "Shell" and "Run" in the command, which could indicate a suspicious activity
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_mshta_inline_vbscript.yml
// False Positives:
//   - Inline scripting can be used by some rare third party applications or administrators. Investigate and apply additional filters accordingly

DeviceProcessEvents
| where ProcessCommandLine contains "Wscript." and ProcessCommandLine contains ".Shell" and ProcessCommandLine contains ".Run"