// Title: Domain Trust Discovery Via Dsquery
// Author: E.M. Anhaus, Tony Lambert, oscd.community, omkar72
// Date: 2019-10-24
// Level: medium
// Description: Detects execution of "dsquery.exe" for domain trust discovery
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1482
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_dsquery_domain_trust_discovery.yml
// False Positives:
//   - Legitimate use of the utilities by legitimate user for legitimate reason

DeviceProcessEvents
| where ProcessCommandLine contains "trustedDomain" and (FolderPath endswith "\\dsquery.exe" or ProcessVersionInfoOriginalFileName =~ "dsquery.exe")