// Title: Pubprn.vbs Proxy Execution
// Author: frack113
// Date: 2022-05-28
// Level: medium
// Description: Detects the use of the 'Pubprn.vbs' Microsoft signed script to execute commands.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1216.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_pubprn.yml

DeviceProcessEvents
| where ProcessCommandLine contains "\\pubprn.vbs" and ProcessCommandLine contains "script:"