// Title: Registry Manipulation via WMI Stdregprov
// Author: Daniel Koifman (KoifSec)
// Date: 2025-07-30
// Level: medium
// Description: Detects the usage of wmic.exe to manipulate Windows registry via the WMI StdRegProv class.
// This behaviour could be potentially suspicious because it uses an alternative method to modify registry keys instead of legitimate registry tools like reg.exe or regedit.exe.
// Attackers specifically choose this technique to evade detection and bypass security monitoring focused on traditional registry modification commands.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.execution, attack.defense-evasion, attack.discovery, attack.t1047, attack.t1112, attack.t1012
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wmic_stdregprov_reg_modification.yml
// False Positives:
//   - Legitimate administrative activity

DeviceProcessEvents
| where (ProcessCommandLine contains "call" and ProcessCommandLine contains "stdregprov") and (FolderPath endswith "\\wmic.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")