// Title: Application Terminated Via Wmic.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-09-11
// Level: medium
// Description: Detects calls to the "terminate" function via wmic in order to kill an application
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1047
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wmic_terminate_application.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "call" and ProcessCommandLine contains "terminate") and (FolderPath endswith "\\WMIC.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")