// Title: Uninstall Sysinternals Sysmon
// Author: frack113
// Date: 2022-01-12
// Level: high
// Description: Detects the removal of Sysmon, which could be a potential attempt at defense evasion
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_sysinternals_sysmon_uninstall.yml
// False Positives:
//   - Legitimate administrators might use this command to remove Sysmon for debugging purposes

DeviceProcessEvents
| where (ProcessCommandLine contains "-u" or ProcessCommandLine contains "/u" or ProcessCommandLine contains "–u" or ProcessCommandLine contains "—u" or ProcessCommandLine contains "―u") and ((FolderPath endswith "\\Sysmon64.exe" or FolderPath endswith "\\Sysmon.exe") or ProcessVersionInfoFileDescription =~ "System activity monitor")