// Title: Whoami.EXE Execution From Privileged Process
// Author: Florian Roth (Nextron Systems), Teymur Kheirkhabarov
// Date: 2022-01-28
// Level: high
// Description: Detects the execution of "whoami.exe" by privileged accounts that are often abused by threat actors
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.discovery, attack.t1033
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_whoami_execution_from_high_priv_process.yml

DeviceProcessEvents
| where (ProcessVersionInfoOriginalFileName =~ "whoami.exe" or FolderPath endswith "\\whoami.exe") and (AccountName contains "AUTHORI" or AccountName contains "AUTORI" or AccountName contains "TrustedInstaller")