// Title: UtilityFunctions.ps1 Proxy Dll
// Author: frack113
// Date: 2022-05-28
// Level: medium
// Description: Detects the use of a Microsoft signed script executing a managed DLL with PowerShell.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1216
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_utilityfunctions.yml

DeviceProcessEvents
| where ProcessCommandLine contains "UtilityFunctions.ps1" or ProcessCommandLine contains "RegSnapin "