// Title: Potentially Suspicious Inline JavaScript Execution via NodeJS Binary
// Author: Microsoft (idea), Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-04-21
// Level: medium
// Description: Detects potentially suspicious inline JavaScript execution using Node.js with specific keywords in the command line.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.007
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_inline_node_js_execution.yml
// False Positives:
//   - Legitimate scripts using Node.js with these modules

DeviceProcessEvents
| where (ProcessCommandLine contains "http" and ProcessCommandLine contains "execSync" and ProcessCommandLine contains "spawn" and ProcessCommandLine contains "fs" and ProcessCommandLine contains "path" and ProcessCommandLine contains "zlib") and (FolderPath endswith "\\node.exe" or ProcessVersionInfoOriginalFileName =~ "node.exe" or ProcessVersionInfoProductName =~ "Node.js")