// Title: Insecure Transfer Via Curl.EXE
// Author: X__Junior (Nextron Systems)
// Date: 2023-06-30
// Level: medium
// Description: Detects execution of "curl.exe" with the "--insecure" flag.
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_curl_insecure_connection.yml
// False Positives:
//   - Access to badly maintained internal or development systems

DeviceProcessEvents
| where (ProcessCommandLine matches regex "\\s-k\\s" or ProcessCommandLine contains "--insecure") and (FolderPath endswith "\\curl.exe" or ProcessVersionInfoOriginalFileName =~ "curl.exe")