// Title: Potential Reconnaissance For Cached Credentials Via Cmdkey.EXE
// Author: jmallette, Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2019-01-16
// Level: high
// Description: Detects usage of cmdkey to look for cached credentials on the system
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_cmdkey_recon.yml
// False Positives:
//   - Legitimate administrative tasks

DeviceProcessEvents
| where (ProcessCommandLine contains " -l" or ProcessCommandLine contains " /l" or ProcessCommandLine contains " –l" or ProcessCommandLine contains " —l" or ProcessCommandLine contains " ―l") and (FolderPath endswith "\\cmdkey.exe" or ProcessVersionInfoOriginalFileName =~ "cmdkey.exe")