// Title: Mstsc.EXE Execution With Local RDP File
// Author: Nasreddine Bencherchali (Nextron Systems), Christopher Peacock @securepeacock
// Date: 2023-04-18
// Level: low
// Description: Detects potential RDP connection via Mstsc using a local ".rdp" file
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1219.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_mstsc_run_local_rdp_file.yml
// False Positives:
//   - Likely with legitimate usage of ".rdp" files

DeviceProcessEvents
| where ((ProcessCommandLine endswith ".rdp" or ProcessCommandLine endswith ".rdp\"") and (FolderPath endswith "\\mstsc.exe" or ProcessVersionInfoOriginalFileName =~ "mstsc.exe")) and (not((ProcessCommandLine contains "C:\\ProgramData\\Microsoft\\WSL\\wslg.rdp" and InitiatingProcessFolderPath =~ "C:\\Windows\\System32\\lxss\\wslhost.exe")))