// Title: Suspicious Splwow64 Without Params
// Author: Florian Roth (Nextron Systems)
// Date: 2021-08-23
// Level: high
// Description: Detects suspicious Splwow64.exe process without any command line parameters
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1202
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_splwow64_cli_anomaly.yml

DeviceProcessEvents
| where ProcessCommandLine endswith "splwow64.exe" and FolderPath endswith "\\splwow64.exe"