// Title: Disabled Volume Snapshots
// Author: Florian Roth (Nextron Systems)
// Date: 2021-01-28
// Level: high
// Description: Detects commands that temporarily turn off Volume Snapshots
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_reg_volsnap_disable.yml
// False Positives:
//   - Legitimate administration

DeviceProcessEvents
| where ProcessCommandLine contains "\\Services\\VSS\\Diag" and ProcessCommandLine contains "/d Disabled"