// Title: Suspicious Calculator Usage
// Author: Florian Roth (Nextron Systems)
// Date: 2019-02-09
// Level: high
// Description: Detects suspicious use of 'calc.exe' with command line parameters or in a suspicious directory, which is likely caused by some PoC or detection evasion.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_calc_uncommon_exec.yml

DeviceProcessEvents
| where ProcessCommandLine contains "\\calc.exe " or (FolderPath endswith "\\calc.exe" and (not((FolderPath contains ":\\Windows\\System32\\" or FolderPath contains ":\\Windows\\SysWOW64\\" or FolderPath contains ":\\Windows\\WinSxS\\"))))