// Title: Whoami.EXE Execution Anomaly
// Author: Florian Roth (Nextron Systems)
// Date: 2021-08-12
// Level: medium
// Description: Detects the execution of whoami.exe with suspicious parent processes.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1033, car.2016-03-001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_whoami_parent_anomaly.yml
// False Positives:
//   - Admin activity
//   - Scripts and administrative tools used in the monitored environment
//   - Monitoring activity

DeviceProcessEvents
| where (FolderPath endswith "\\whoami.exe" or ProcessVersionInfoOriginalFileName =~ "whoami.exe") and (not(((InitiatingProcessFolderPath endswith "\\cmd.exe" or InitiatingProcessFolderPath endswith "\\powershell_ise.exe" or InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe") or (InitiatingProcessFolderPath in~ ("", "-")) or isnull(InitiatingProcessFolderPath)))) and (not(InitiatingProcessFolderPath endswith ":\\Program Files\\Microsoft Monitoring Agent\\Agent\\MonitoringHost.exe"))