// Title: Suspicious GrpConv Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-05-19
// Level: high
// Description: Detects the suspicious execution of a utility to convert Windows 3.x .grp files or for persistence purposes by malicious software or actors
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_susp_grpconv.yml

DeviceProcessEvents
| where ProcessCommandLine contains "grpconv.exe -o" or ProcessCommandLine contains "grpconv -o"