// Title: Logged-On User Password Change Via Ksetup.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-04-06
// Level: medium
// Description: Detects password change for the logged-on user's via "ksetup.exe"
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_ksetup_password_change_user.yml

DeviceProcessEvents
| where ProcessCommandLine contains " /ChangePassword " and (FolderPath endswith "\\ksetup.exe" or ProcessVersionInfoOriginalFileName =~ "ksetup.exe")