// Title: Potential File Download Via MS-AppInstaller Protocol Handler
// Author: Nasreddine Bencherchali (Nextron Systems), Swachchhanda Shrawan Poudel
// Date: 2023-11-09
// Level: medium
// Description: Detects usage of the "ms-appinstaller" protocol handler via command line to potentially download arbitrary files via AppInstaller.EXE
// The downloaded files are temporarly stored in ":\Users\%username%\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\AC\INetCache\<RANDOM-8-CHAR-DIRECTORY>"
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_ms_appinstaller_download.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "ms-appinstaller://" and ProcessCommandLine contains "source=") and ProcessCommandLine contains "http"