// Title: Potential PowerShell Obfuscation Via WCHAR/CHAR
// Author: Florian Roth (Nextron Systems)
// Date: 2020-07-09
// Level: high
// Description: Detects suspicious encoded character syntax often used for defense evasion
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.001, attack.defense-evasion, attack.t1027
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_obfuscation_via_utf8.yml

DeviceProcessEvents
| where ProcessCommandLine contains "[char]0x" or ProcessCommandLine contains "(WCHAR)0x"