// Title: Potential Product Reconnaissance Via Wmic.EXE
// Author: Nasreddine Bencherchali
// Date: 2023-02-14
// Level: medium
// Description: Detects the execution of WMIC in order to get a list of firewall and antivirus products
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1047
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wmic_recon_product.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "Product" and (FolderPath endswith "\\wmic.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")) and (not((ProcessCommandLine contains " uninstall" or ProcessCommandLine contains " install")))