// Title: Run PowerShell Script from ADS
// Author: Sergey Soldatov, Kaspersky Lab, oscd.community
// Date: 2019-10-30
// Level: high
// Description: Detects PowerShell script execution from Alternate Data Stream (ADS)
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1564.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_powershell_run_script_from_ads.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "Get-Content" and ProcessCommandLine contains "-Stream") and (FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") and (InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe")