// Title: Use Icacls to Hide File to Everyone
// Author: frack113
// Date: 2022-07-18
// Level: medium
// Description: Detect use of icacls to deny access for everyone in Users folder sometimes used to hide malicious files
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1564.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_icacls_deny.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "/deny" and ProcessCommandLine contains "S-1-1-0:") and (ProcessVersionInfoOriginalFileName =~ "iCACLS.EXE" or FolderPath endswith "\\icacls.exe")