// Title: Vulnerable Driver Blocklist Registry Tampering Via CommandLine
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2026-01-26
// Level: high
// Description: Detects tampering of the Vulnerable Driver Blocklist registry via command line tools such as PowerShell or REG.EXE.
// The Vulnerable Driver Blocklist is a security feature that helps prevent the loading of known vulnerable drivers.
// Disabling this feature may indicate an attempt to bypass security controls, often targeted by threat actors
// to facilitate the installation of malicious or vulnerable drivers, particularly in scenarios involving Endpoint Detection and Response
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// False Positives:
//   - It is very unlikely for legitimate activities to disable the Vulnerable Driver Blocklist via command line tools; thus it is recommended to investigate promptly.

DeviceProcessEvents
| where (ProcessCommandLine contains "add " or ProcessCommandLine contains "New-ItemProperty " or ProcessCommandLine contains "Set-ItemProperty " or ProcessCommandLine contains "si ") and (ProcessCommandLine contains "\\Control\\CI\\Config" and ProcessCommandLine contains "VulnerableDriverBlocklistEnable") and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\reg.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll", "reg.exe")))