// Title: Windows Credential Guard Registry Tampering Via CommandLine
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-12-26
// Level: high
// Description: Detects attempts to add, modify, or delete Windows Credential Guard related registry keys or values via command line tools such as Reg.exe or PowerShell.
// Credential Guard uses virtualization-based security to isolate secrets so that only privileged system software can access them.
// Adversaries may disable Credential Guard to gain access to sensitive credentials stored in the system, such as NTLM hashes and Kerberos tickets, which can be used for lateral movement and privilege escalation.
// The rule matches suspicious command lines that target DeviceGuard or LSA registry paths and manipulate keys like EnableVirtualizationBasedSecurity, RequirePlatformSecurityFeatures, or LsaCfgFlags.
// Such activity may indicate an attempt to disable or tamper with Credential Guard, potentially exposing sensitive credentials for misuse.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (ProcessCommandLine contains "add " or ProcessCommandLine contains "New-ItemProperty " or ProcessCommandLine contains "Set-ItemProperty " or ProcessCommandLine contains "si " or ProcessCommandLine contains "delete " or ProcessCommandLine contains "del " or ProcessCommandLine contains "Remove-ItemProperty " or ProcessCommandLine contains "rp ") and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\reg.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll", "reg.exe"))) and (ProcessCommandLine contains "\\Control\\DeviceGuard" or ProcessCommandLine contains "\\Control\\LSA" or ProcessCommandLine contains "Software\\Policies\\Microsoft\\Windows\\DeviceGuard") and (ProcessCommandLine contains "EnableVirtualizationBasedSecurity" or ProcessCommandLine contains "RequirePlatformSecurityFeatures" or ProcessCommandLine contains "LsaCfgFlags")