// Title: Windows AMSI Related Registry Tampering Via CommandLine
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-12-25
// Level: high
// Description: Detects tampering of AMSI (Anti-Malware Scan Interface) related registry values via command line tools such as reg.exe or PowerShell.
// AMSI provides a generic interface for applications and services to integrate with antimalware products.
// Adversaries may disable AMSI to evade detection of malicious scripts and code execution.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001, attack.t1562.006

DeviceProcessEvents
| where (ProcessCommandLine contains "\\Software\\Microsoft\\Windows Script\\Settings" and ProcessCommandLine contains "AmsiEnable") and (((ProcessCommandLine contains "Set-ItemProperty" or ProcessCommandLine contains "New-ItemProperty" or ProcessCommandLine contains "sp ") and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")))) or (ProcessCommandLine contains "add" and (FolderPath endswith "\\reg.exe" or ProcessVersionInfoOriginalFileName =~ "reg.exe")))