// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/10/17
// Level: medium
// Description: Detects file access requests to the Windows Credential History File by an uncommon application.
This can be a sign of credential stealing. Example case would be usage of mimikatz "dpapi::credhist" function

// Tags: attack.credential_access, attack.t1555.004
DeviceFileEvents
| where FileName endswith "\\Microsoft\\Protect\\CREDHIST" and (not((InitiatingProcessFolderPath endswith ":\\Windows\\explorer.exe" or (InitiatingProcessFolderPath contains ":\\Program Files\\" or InitiatingProcessFolderPath contains ":\\Program Files (x86)\\" or InitiatingProcessFolderPath contains ":\\Windows\\system32\\" or InitiatingProcessFolderPath contains ":\\Windows\\SysWOW64\\"))))