// Author: pH-T (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/07/27
// Level: medium
// Description: Detects browsers starting with the remote debugging flags. Which is a technique often used to perform browser injection attacks
// Tags: attack.credential_access, attack.t1185
DeviceProcessEvents
| where ProcessCommandLine contains " --remote-debugging-" or (ProcessCommandLine contains " -start-debugger-server" and FolderPath endswith "\\firefox.exe")