// Author: Julia Fomina, oscd.community
// Date: 2020/10/09
// Level: medium
// Description: Detects using Rpcping.exe to send a RPC test connection to the target server (-s) and force the NTLM hash to be sent in the process.
// Tags: attack.credential_access, attack.t1003
DeviceProcessEvents
| where FolderPath endswith "\\rpcping.exe" and (ProcessCommandLine contains "-s" or ProcessCommandLine contains "/s") and (((ProcessCommandLine contains "-u" or ProcessCommandLine contains "/u") and (ProcessCommandLine contains "NTLM")) or ((ProcessCommandLine contains "-t" or ProcessCommandLine contains "/t") and (ProcessCommandLine contains "ncacn_np")))