// Author: Sreeman
// Date: 2020/10/29
// Level: medium
// Description: Detects dropping of dll files in system32 that may be used to retrieve user credentials from LSASS
// Tags: attack.credential_access, attack.t1556.002
DeviceProcessEvents
| where ProcessCommandLine contains "HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa" and ProcessCommandLine contains "scecli\\0" and ProcessCommandLine contains "reg add"