// Author: sam0x90
// Date: 2021/08/06
// Level: medium
// Description: Conti recommendation to its affiliates to use esentutl to access NTDS dumped file. Trickbot also uses this utilities to get MSEdge info via its module pwgrab.
// Tags: attack.credential_access, attack.t1003, attack.t1003.003
DeviceProcessEvents
| where ProcessCommandLine contains "esentutl" and ProcessCommandLine contains " /p"