// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/10/20
// Level: critical
// Description: Detects the execution of the hacktool SafetyKatz via PE information and default Image name
// Tags: attack.credential_access, attack.t1003.001
DeviceProcessEvents
| where FolderPath endswith "\\SafetyKatz.exe" or ProcessVersionInfoOriginalFileName =~ "SafetyKatz.exe" or ProcessVersionInfoFileDescription =~ "SafetyKatz"