// Author: Vasiliy Burov
// Date: 2020/10/05
// Level: high
// Description: Detects command line parameters used by Hydra password guessing hack tool
// Tags: attack.credential_access, attack.t1110, attack.t1110.001
DeviceProcessEvents
| where (ProcessCommandLine contains "^USER^" or ProcessCommandLine contains "^PASS^") and (ProcessCommandLine contains "-u " and ProcessCommandLine contains "-p ")