// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/02/03
// Level: medium
// Description: Detects usage of "cmdkey.exe" to add generic credentials.
As an example, this can be used before connecting to an RDP session via command line interface.

// Tags: attack.credential_access, attack.t1003.005
DeviceProcessEvents
| where (ProcessCommandLine contains " -g" or ProcessCommandLine contains " /g") and (ProcessCommandLine contains " -p" or ProcessCommandLine contains " /p") and (ProcessCommandLine contains " -u" or ProcessCommandLine contains " /u") and (FolderPath endswith "\\cmdkey.exe" or ProcessVersionInfoOriginalFileName =~ "cmdkey.exe")