// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/23
// Level: high
// Description: Detects when an attacker tries to add a new network provider in order to dump clear text credentials, similar to how the NPPSpy tool does it
// Tags: attack.credential_access, attack.t1003
DeviceProcessEvents
| where ProcessCommandLine contains "\\System\\CurrentControlSet\\Services\\" and ProcessCommandLine contains "\\NetworkProvider"