// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/12/23
// Level: high
// Description: Detects chromium based browsers starting in headless and debugging mode and pointing to a user profile. This could be a sign of data stealing or remote control
// Tags: attack.credential_access, attack.t1185
DeviceProcessEvents
| where ProcessCommandLine contains "--remote-debugging-" and ProcessCommandLine contains "--user-data-dir" and ProcessCommandLine contains "--headless"