// Author: jmallette, Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2019/01/16
// Level: high
// Description: Detects usage of cmdkey to look for cached credentials on the system
// Tags: attack.credential_access, attack.t1003.005
DeviceProcessEvents
| where (ProcessCommandLine contains " /l" or ProcessCommandLine contains " -l") and (FolderPath endswith "\\cmdkey.exe" or ProcessVersionInfoOriginalFileName =~ "cmdkey.exe")