// Author: frack113
// Date: 2022/12/11
// Level: high
// Description: Detects potential tampering with Windows Defender settings such as adding exclusion using wmic
// Tags: attack.credential_access, attack.t1546.008
DeviceProcessEvents
| where ProcessCommandLine contains "/Namespace:\\\\root\\Microsoft\\Windows\\Defender" and (ProcessVersionInfoOriginalFileName =~ "wmic.exe" or FolderPath endswith "\\WMIC.exe")