// Author: Florian Roth (Nextron Systems)
// Date: 2021/04/23
// Level: high
// Description: Detects a "Get-Process" cmdlet and it's aliases on lsass process, which is in almost all cases a sign of malicious activity
// Tags: attack.credential_access, attack.t1552.004
DeviceProcessEvents
| where ProcessCommandLine contains "Get-Process lsas" or ProcessCommandLine contains "ps lsas" or ProcessCommandLine contains "gps lsas"