// Author: Florian Roth (Nextron Systems)
// Date: 2022/04/21
// Level: high
// Description: Detects the invocation of the Stored User Names and Passwords dialogue (Key Manager)
// Tags: attack.credential_access, attack.t1555.004
DeviceProcessEvents
| where (ProcessCommandLine contains "keymgr" and ProcessCommandLine contains "KRShowKeyMgr") and (FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE")