// Author: Elastic (idea), Tobias Michalski (Nextron Systems)
// Date: 2022/05/04
// Level: high
// Description: Detects a privilege elevation attempt by coercing NTLM authentication on the Printer Spooler service
// Tags: attack.privilege_escalation, attack.credential_access, attack.t1212
DeviceProcessEvents
| where ((ProcessCommandLine contains "spoolss" or ProcessCommandLine contains "srvsvc" or ProcessCommandLine contains "/print/pipe/") and (ProcessCommandLine contains "C:\\windows\\system32\\davclnt.dll,DavSetCookie" and ProcessCommandLine contains "http")) and (FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE")