// Author: frack113
// Date: 2021/12/19
// Level: medium
// Description: Attempts to access unattend.xml, where credentials are commonly stored, within the Panther directory where installation logs are stored.
If these files exist, their contents will be displayed. They are used to store credentials/answers during the unattended windows install process

// Tags: attack.credential_access, attack.t1552.001
DeviceFileEvents
| where FolderPath endswith "\\unattend.xml"