// Title: JAMF MDM Potential Suspicious Child Process
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-22
// Level: medium
// Description: Detects potential suspicious child processes of "jamf". Could be a sign of potential abuse of Jamf as a C2 server as seen by Typhon MythicAgent.
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_jamf_susp_child.yml
// False Positives:
//   - Legitimate execution of custom scripts or commands by Jamf administrators. Apply additional filters accordingly

DeviceProcessEvents
| where (FolderPath endswith "/bash" or FolderPath endswith "/sh") and InitiatingProcessFolderPath endswith "/jamf"