// Title: Payload Decoded and Decrypted via Built-in Utilities
// Author: Tim Rauch (rule), Elastic (idea)
// Date: 2022-10-17
// Level: medium
// Description: Detects when a built-in utility is used to decode and decrypt a payload after a macOS disk image (DMG) is executed. Malware authors may attempt to evade detection and trick users into executing malicious code by encoding and encrypting their payload and placing it in a disk image file. This behavior is consistent with adware or malware families such as Bundlore and Shlayer.
// MITRE Tactic: Execution
// Tags: attack.t1059, attack.t1204, attack.execution, attack.t1140, attack.defense-evasion, attack.s0482, attack.s0402
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_payload_decoded_and_decrypted.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "/Volumes/" and ProcessCommandLine contains "enc" and ProcessCommandLine contains "-base64" and ProcessCommandLine contains " -d ") and FolderPath endswith "/openssl"