// Title: System Shutdown/Reboot - MacOs
// Author: Igor Fits, Mikhail Larin, oscd.community
// Date: 2020-10-19
// Level: informational
// Description: Adversaries may shutdown/reboot systems to interrupt access to, or aid in the destruction of, those systems.
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1529
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_system_shutdown_reboot.yml
// False Positives:
//   - Legitimate administrative activity

DeviceProcessEvents
| where FolderPath endswith "/shutdown" or FolderPath endswith "/reboot" or FolderPath endswith "/halt"