// Title: Clipboard Data Collection Via OSAScript
// Author: Sohan G (D4rkCiph3r)
// Date: 2023-01-31
// Level: high
// Description: Detects possible collection of data from the clipboard via execution of the osascript binary
// MITRE Tactic: Collection
// Tags: attack.collection, attack.execution, attack.t1115, attack.t1059.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_clipboard_data_via_osascript.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains "osascript" and ProcessCommandLine contains " -e " and ProcessCommandLine contains "clipboard"