// Title: Binary Padding - MacOS
// Author: Igor Fits, Mikhail Larin, oscd.community
// Date: 2020-10-19
// Level: high
// Description: Adversaries may use binary padding to add junk data and change the on-disk representation of malware. This rule detect using dd and truncate to add a junk data to file.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_binary_padding.yml
// False Positives:
//   - Legitimate script work

DeviceProcessEvents
| where ((ProcessCommandLine contains "if=/dev/zero" or ProcessCommandLine contains "if=/dev/random" or ProcessCommandLine contains "if=/dev/urandom") and FolderPath endswith "/dd") or (ProcessCommandLine contains "-s +" and FolderPath endswith "/truncate")