// Title: New File Exclusion Added To Time Machine Via Tmutil - MacOS
// Author: Pratinav Chandra
// Date: 2024-05-29
// Level: medium
// Description: Detects the addition of a new file or path exclusion to MacOS Time Machine via the "tmutil" utility.
// An adversary could exclude a path from Time Machine backups to prevent certain files from being backed up.
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1490
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_tmutil_exclude_file_from_backup.yml
// False Positives:
//   - Legitimate administrator activity

DeviceProcessEvents
| where ProcessCommandLine contains "addexclusion" and (FolderPath endswith "/tmutil" or ProcessCommandLine contains "tmutil")