// Title: Launch Agent/Daemon Execution Via Launchctl
// Author: Pratinav Chandra
// Date: 2024-05-13
// Level: medium
// Description: Detects the execution of programs as Launch Agents or Launch Daemons using launchctl on macOS.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.execution, attack.persistence, attack.t1569.001, attack.t1543.001, attack.t1543.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_launchctl_execution.yml
// False Positives:
//   - Legitimate administration activities is expected to trigger false positives. Investigate the command line being passed to determine if the service or launch agent are suspicious.

DeviceProcessEvents
| where (ProcessCommandLine contains "submit" or ProcessCommandLine contains "load" or ProcessCommandLine contains "start") and FolderPath endswith "/launchctl"