// Title: Potential Discovery Activity Using Find - MacOS
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-28
// Level: medium
// Description: Detects usage of "find" binary in a suspicious manner to perform discovery
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1083
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_susp_find_execution.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "-perm -4000" or ProcessCommandLine contains "-perm -2000" or ProcessCommandLine contains "-perm 0777" or ProcessCommandLine contains "-perm -222" or ProcessCommandLine contains "-perm -o w" or ProcessCommandLine contains "-perm -o x" or ProcessCommandLine contains "-perm -u=s" or ProcessCommandLine contains "-perm -g=s") and FolderPath endswith "/find"