// Title: Local Groups Discovery - MacOs
// Author: Ömer Günal, Alejandro Ortuno, oscd.community
// Date: 2020-10-11
// Level: informational
// Description: Detects enumeration of local system groups
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1069.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_local_groups.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where ((ProcessCommandLine contains "-q" and ProcessCommandLine contains "group") and FolderPath endswith "/dscacheutil") or (ProcessCommandLine contains "/etc/group" and FolderPath endswith "/cat") or ((ProcessCommandLine contains "-list" and ProcessCommandLine contains "/groups") and FolderPath endswith "/dscl")