// Title: Time Machine Backup Deletion Attempt Via Tmutil - MacOS
// Author: Pratinav Chandra
// Date: 2024-05-29
// Level: medium
// Description: Detects deletion attempts of MacOS Time Machine backups via the native backup utility "tmutil".
// An adversary may perform this action before launching a ransonware attack to prevent the victim from restoring their files.
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1490
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_tmutil_delete_backup.yml
// False Positives:
//   - Legitimate activities

DeviceProcessEvents
| where ProcessCommandLine contains "delete" and (FolderPath endswith "/tmutil" or ProcessCommandLine contains "tmutil")