// Title: Disk Image Mounting Via Hdiutil - MacOS
// Author: Omar Khaled (@beacon_exe)
// Date: 2024-08-10
// Level: medium
// Description: Detects the execution of the hdiutil utility in order to mount disk images.
// MITRE Tactic: Initial Access
// Tags: attack.initial-access, attack.collection, attack.t1566.001, attack.t1560.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_hdiutil_mount.yml
// False Positives:
//   - Legitimate usage of hdiutil by administrators and users.

DeviceProcessEvents
| where (ProcessCommandLine contains "attach " or ProcessCommandLine contains "mount ") and FolderPath endswith "/hdiutil"