// Title: System Integrity Protection (SIP) Disabled
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2024-01-02
// Level: medium
// Description: Detects the use of csrutil to disable the Configure System Integrity Protection (SIP). This technique is used in post-exploit scenarios.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1518.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_csrutil_disable.yml

DeviceProcessEvents
| where ProcessCommandLine contains "disable" and FolderPath endswith "/csrutil"