// Title: Indicator Removal on Host - Clear Mac System Logs
// Author: remotephone, oscd.community
// Date: 2020-10-11
// Level: medium
// Description: Detects deletion of local audit logs
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1070.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_clear_system_logs.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where (FolderPath endswith "/rm" or FolderPath endswith "/unlink" or FolderPath endswith "/shred") and (ProcessCommandLine contains "/var/log" or (ProcessCommandLine contains "/Users/" and ProcessCommandLine contains "/Library/Logs/"))