// Title: System Information Discovery Using System_Profiler
// Author: Stephen Lincoln `@slincoln_aiq` (AttackIQ)
// Date: 2024-01-02
// Level: medium
// Description: Detects the execution of "system_profiler" with specific "Data Types" that have been seen being used by threat actors and malware. It provides system hardware and software configuration information.
// This process is primarily used for system information discovery. However, "system_profiler" can also be used to determine if virtualization software is being run for defense evasion purposes.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.defense-evasion, attack.t1082, attack.t1497.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_system_profiler_discovery.yml
// False Positives:
//   - Legitimate administrative activities

DeviceProcessEvents
| where (ProcessCommandLine contains "SPApplicationsDataType" or ProcessCommandLine contains "SPHardwareDataType" or ProcessCommandLine contains "SPNetworkDataType" or ProcessCommandLine contains "SPUSBDataType") and (FolderPath endswith "/system_profiler" or ProcessCommandLine contains "system_profiler")