// Title: User Added To Admin Group Via Sysadminctl
// Author: Sohan G (D4rkCiph3r)
// Date: 2023-03-19
// Level: medium
// Description: Detects attempts to create and add an account to the admin group via "sysadminctl"
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.initial-access, attack.privilege-escalation, attack.t1078.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_sysadminctl_add_user_to_admin_group.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where (ProcessCommandLine contains " -addUser " and ProcessCommandLine contains " -admin ") and FolderPath endswith "/sysadminctl"