// Title: Guest Account Enabled Via Sysadminctl
// Author: Sohan G (D4rkCiph3r)
// Date: 2023-02-18
// Level: low
// Description: Detects attempts to enable the guest account using the sysadminctl utility
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.defense-evasion, attack.initial-access, attack.t1078, attack.t1078.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_sysadminctl_enable_guest_account.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " -guestAccount" and ProcessCommandLine contains " on") and FolderPath endswith "/sysadminctl"