// Title: Time Machine Backup Disabled Via Tmutil - MacOS
// Author: Pratinav Chandra
// Date: 2024-05-29
// Level: medium
// Description: Detects disabling of Time Machine (Apple's automated backup utility software) via the native macOS backup utility "tmutil".
// An attacker can use this to prevent backups from occurring.
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1490
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_tmutil_disable_backup.yml
// False Positives:
//   - Legitimate administrator activity

DeviceProcessEvents
| where ProcessCommandLine contains "disable" and (FolderPath endswith "/tmutil" or ProcessCommandLine contains "tmutil")