// Title: JXA In-memory Execution Via OSAScript
// Author: Sohan G (D4rkCiph3r)
// Date: 2023-01-31
// Level: high
// Description: Detects possible malicious execution of JXA in-memory via OSAScript
// MITRE Tactic: Execution
// Tags: attack.t1059.002, attack.t1059.007, attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_jxa_in_memory_execution.yml

DeviceProcessEvents
| where ((ProcessCommandLine contains " -l " and ProcessCommandLine contains "JavaScript") or ProcessCommandLine contains ".js") and (ProcessCommandLine contains "osascript" and ProcessCommandLine contains " -e " and ProcessCommandLine contains "eval" and ProcessCommandLine contains "NSData.dataWithContentsOfURL")