// Title: System Information Discovery Via Sysctl - MacOS
// Author: Pratinav Chandra
// Date: 2024-05-27
// Level: medium
// Description: Detects the execution of "sysctl" with specific arguments that have been used by threat actors and malware. It provides system hardware information.
// This process is primarily used to detect and avoid virtualization and analysis environments.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1497.001, attack.discovery, attack.t1082
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_sysctl_discovery.yml
// False Positives:
//   - Legitimate administrative activities

DeviceProcessEvents
| where (ProcessCommandLine contains "hw." or ProcessCommandLine contains "kern." or ProcessCommandLine contains "machdep.") and (FolderPath endswith "/sysctl" or ProcessCommandLine contains "sysctl")