// Title: System Integrity Protection (SIP) Enumeration
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2024-01-02
// Level: low
// Description: Detects the use of csrutil to view the Configure System Integrity Protection (SIP) status. This technique is used in post-exploit scenarios.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1518.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_csrutil_status.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where ProcessCommandLine contains "status" and FolderPath endswith "/csrutil"