// Title: User Added To Admin Group Via DseditGroup
// Author: Sohan G (D4rkCiph3r)
// Date: 2023-08-22
// Level: medium
// Description: Detects attempts to create and/or add an account to the admin group, thus granting admin privileges.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.initial-access, attack.privilege-escalation, attack.t1078.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_dseditgroup_add_to_admin_group.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where (ProcessCommandLine contains " -o edit " and ProcessCommandLine contains " -a " and ProcessCommandLine contains " -t user" and ProcessCommandLine contains "admin") and FolderPath endswith "/dseditgroup"