// Title: Credentials from Password Stores - Keychain
// Author: Tim Ismilyaev, oscd.community, Florian Roth (Nextron Systems)
// Date: 2020-10-19
// Level: medium
// Description: Detects passwords dumps from Keychain
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1555.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_creds_from_keychain.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where ((ProcessCommandLine contains "find-certificate" or ProcessCommandLine contains " export ") and FolderPath =~ "/usr/bin/security") or (ProcessCommandLine contains " dump-keychain " or ProcessCommandLine contains " login-keychain ")