// Title: Hidden Flag Set On File/Directory Via Chflags - MacOS
// Author: Omar Khaled (@beacon_exe)
// Date: 2024-08-21
// Level: medium
// Description: Detects the execution of the "chflags" utility with the "hidden" flag, in order to hide files on MacOS.
// When a file or directory has this hidden flag set, it becomes invisible to the default file listing commands and in graphical file browsers.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.credential-access, attack.command-and-control, attack.t1218, attack.t1564.004, attack.t1552.001, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_chflags_hidden_flag.yml
// False Positives:
//   - Legitimate usage of chflags by administrators and users.

DeviceProcessEvents
| where ProcessCommandLine contains "hidden " and FolderPath endswith "/chflags"