// Title: MacOS Scripting Interpreter AppleScript
// Author: Alejandro Ortuno, oscd.community
// Date: 2020-10-21
// Level: medium
// Description: Detects execution of AppleScript of the macOS scripting language AppleScript.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_applescript.yml
// False Positives:
//   - Application installers might contain scripts as part of the installation process.

DeviceProcessEvents
| where (ProcessCommandLine contains " -e " or ProcessCommandLine contains ".scpt" or ProcessCommandLine contains ".js") and FolderPath endswith "/osascript"