// Title: Security Software Discovery - MacOs
// Author: Daniil Yugoslavskiy, oscd.community
// Date: 2020-10-19
// Level: medium
// Description: Detects usage of system utilities (only grep for now) to discover security software discovery
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1518.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_security_software_discovery.yml
// False Positives:
//   - Legitimate activities

DeviceProcessEvents
| where FolderPath =~ "/usr/bin/grep" and ((ProcessCommandLine contains "nessusd" or ProcessCommandLine contains "santad" or ProcessCommandLine contains "CbDefense" or ProcessCommandLine contains "falcond" or ProcessCommandLine contains "td-agent" or ProcessCommandLine contains "packetbeat" or ProcessCommandLine contains "filebeat" or ProcessCommandLine contains "auditbeat" or ProcessCommandLine contains "osqueryd" or ProcessCommandLine contains "BlockBlock" or ProcessCommandLine contains "LuLu") or (ProcessCommandLine contains "Little" and ProcessCommandLine contains "Snitch"))