// Title: Creation Of A Local User Account
// Author: Alejandro Ortuno, oscd.community
// Date: 2020-10-06
// Level: low
// Description: Detects the creation of a new user account. Such accounts may be used for persistence that do not require persistent remote access tools to be deployed on the system.
// MITRE Tactic: Persistence
// Tags: attack.t1136.001, attack.persistence
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_create_account.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where (ProcessCommandLine contains "create" and FolderPath endswith "/dscl") or (ProcessCommandLine contains "addUser" and FolderPath endswith "/sysadminctl")