// Title: Network Sniffing - MacOs
// Author: Alejandro Ortuno, oscd.community
// Date: 2020-10-14
// Level: informational
// Description: Detects the usage of tooling to sniff network traffic.
// An adversary may place a network interface into promiscuous mode to passively access data in transit over the network, or use span ports to capture a larger amount of data.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.credential-access, attack.t1040
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_network_sniffing.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where FolderPath endswith "/tcpdump" or FolderPath endswith "/tshark"