// Title: File Download Via Nscurl - MacOS
// Author: Daniel Cortez
// Date: 2024-06-04
// Level: medium
// Description: Detects the execution of the nscurl utility in order to download files.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.command-and-control, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_nscurl_usage.yml
// False Positives:
//   - Legitimate usage of nscurl by administrators and users.

DeviceProcessEvents
| where (ProcessCommandLine contains "--download " or ProcessCommandLine contains "--download-directory " or ProcessCommandLine contains "--output " or ProcessCommandLine contains "-dir " or ProcessCommandLine contains "-dl " or ProcessCommandLine contains "-ld" or ProcessCommandLine contains "-o ") and FolderPath endswith "/nscurl"