// Title: Osacompile Execution By Potentially Suspicious Applet/Osascript
// Author: Sohan G (D4rkCiph3r), Red Canary (Idea)
// Date: 2023-04-03
// Level: medium
// Description: Detects potential suspicious applet or osascript executing "osacompile".
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_suspicious_applet_behaviour.yml

DeviceProcessEvents
| where ProcessCommandLine contains "osacompile" and (InitiatingProcessFolderPath endswith "/applet" or InitiatingProcessFolderPath endswith "/osascript")