// Title: Screen Capture - macOS
// Author: remotephone, oscd.community
// Date: 2020-10-13
// Level: low
// Description: Detects attempts to use screencapture to collect macOS screenshots
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1113
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_screencapture.yml
// False Positives:
//   - Legitimate user activity taking screenshots

DeviceProcessEvents
| where FolderPath =~ "/usr/sbin/screencapture"