// Title: MacOS Network Service Scanning
// Author: Alejandro Ortuno, oscd.community
// Date: 2020-10-21
// Level: low
// Description: Detects enumeration of local or remote network services.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1046
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_network_service_scanning.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where ((FolderPath endswith "/nc" or FolderPath endswith "/netcat") and (not(ProcessCommandLine contains "l"))) or (FolderPath endswith "/nmap" or FolderPath endswith "/telnet")