// Title: Credentials In Files
// Author: Igor Fits, Mikhail Larin, oscd.community
// Date: 2020-10-19
// Level: high
// Description: Detecting attempts to extract passwords with grep and laZagne
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1552.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_find_cred_in_files.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "password" and FolderPath endswith "/grep") or ProcessCommandLine contains "laZagne"