// Title: Disk Image Creation Via Hdiutil - MacOS
// Author: Omar Khaled (@beacon_exe)
// Date: 2024-08-10
// Level: medium
// Description: Detects the execution of the hdiutil utility in order to create a disk image.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_hdiutil_create.yml
// False Positives:
//   - Legitimate usage of hdiutil by administrators and users.

DeviceProcessEvents
| where ProcessCommandLine contains "create" and FolderPath endswith "/hdiutil"