// Title: JAMF MDM Execution
// Author: Jay Pandit
// Date: 2023-08-22
// Level: low
// Description: Detects execution of the "jamf" binary to create user accounts and run commands. For example, the binary can be abused by attackers on the system in order to bypass security controls or remove application control polices.
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_jamf_usage.yml
// False Positives:
//   - Legitimate use of the JAMF CLI tool by IT support and administrators

DeviceProcessEvents
| where (ProcessCommandLine contains "createAccount" or ProcessCommandLine contains "manage" or ProcessCommandLine contains "removeFramework" or ProcessCommandLine contains "removeMdmProfile" or ProcessCommandLine contains "resetPassword" or ProcessCommandLine contains "setComputerName") and FolderPath endswith "/jamf"