// Title: System Network Connections Discovery - MacOs
// Author: Daniil Yugoslavskiy, oscd.community
// Date: 2020-10-19
// Level: informational
// Description: Detects usage of system utilities to discover system network connections
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1049
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/macos/process_creation/proc_creation_macos_system_network_connections_discovery.yml
// False Positives:
//   - Legitimate activities

DeviceProcessEvents
| where FolderPath endswith "/who" or FolderPath endswith "/w" or FolderPath endswith "/last" or FolderPath endswith "/lsof" or FolderPath endswith "/netstat"