// Title: Clipboard Data Collection Via Pbpaste
// Author: Daniel Cortez
// Date: 2024-07-30
// Level: medium
// Description: Detects execution of the "pbpaste" utility, which retrieves the contents of the clipboard (a.k.a. pasteboard) and writes them to the standard output (stdout).
// The utility is often used for creating new files with the clipboard content or for piping clipboard contents to other commands.
// It can also be used in shell scripts that may require clipboard content as input.
// Attackers can abuse this utility in order to collect data from the user clipboard, which may contain passwords or sensitive information.
// Use this rule to hunt for potential abuse of the utility by looking at the parent process and any potentially suspicious command line content.
// MITRE Tactic: Collection
// Tags: attack.collection, attack.credential-access, attack.t1115, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/macos/process_creation/proc_creation_macos_pbpaste_execution.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where FolderPath endswith "/pbpaste"