// Title: Terminate Linux Process Via Kill
// Author: Tuan Le (NCSGroup)
// Date: 2023-03-16
// Level: medium
// Description: Detects usage of command line tools such as "kill", "pkill" or "killall" to terminate or signal a running process.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/linux/process_creation/proc_creation_lnx_susp_process_termination_via_kill.yml

DeviceProcessEvents
| where FolderPath endswith "/kill" or FolderPath endswith "/killall" or FolderPath endswith "/pkill" or FolderPath endswith "/xkill"