// Title: Process Discovery
// Author: Ömer Günal, oscd.community, CheraaghiMilad
// Date: 2020-10-06
// Level: low
// Description: Detects process discovery commands. Adversaries may attempt to get information about running processes on a system.
// Information obtained could be used to gain an understanding of common software/applications running on systems within the network
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1057, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/linux/process_creation/proc_creation_lnx_susp_running_process_discovery.yml
// False Positives:
//   - Legitimate administration activities

DeviceProcessEvents
| where FolderPath endswith "/atop" or FolderPath endswith "/htop" or FolderPath endswith "/pgrep" or FolderPath endswith "/ps" or FolderPath endswith "/pstree" or FolderPath endswith "/top"