// Title: Linux Crypto Mining Pool Connections
// Author: Florian Roth (Nextron Systems)
// Date: 2021-10-26
// Level: high
// Description: Detects process connections to a Monero crypto mining pool
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1496
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/network_connection/net_connection_lnx_crypto_mining_indicators.yml
// False Positives:
//   - Legitimate use of crypto miners

DeviceNetworkEvents
| where RemoteUrl in~ ("pool.minexmr.com", "fr.minexmr.com", "de.minexmr.com", "sg.minexmr.com", "ca.minexmr.com", "us-west.minexmr.com", "pool.supportxmr.com", "mine.c3pool.com", "xmr-eu1.nanopool.org", "xmr-eu2.nanopool.org", "xmr-us-east1.nanopool.org", "xmr-us-west1.nanopool.org", "xmr-asia1.nanopool.org", "xmr-jp1.nanopool.org", "xmr-au1.nanopool.org", "xmr.2miners.com", "xmr.hashcity.org", "xmr.f2pool.com", "xmrpool.eu", "pool.hashvault.pro", "moneroocean.stream", "monerocean.stream")