// Title: WDAC Policy File Creation In CodeIntegrity Folder
// Author: Andreas Braathen (mnemonic.io)
// Date: 2025-01-30
// Level: medium
// Description: Attackers can craft a custom Windows Defender Application Control (WDAC) policy that blocks Endpoint Detection and Response (EDR) components while allowing their own malicious code. The policy is placed in the privileged Windows Code Integrity folder (C:\Windows\System32\CodeIntegrity\). Upon reboot, the policy prevents EDR drivers from loading, effectively bypassing security measures and may further enable undetected lateral movement within an Active Directory environment.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/file/file_event/file_event_win_wdac_policy_creation_in_codeintegrity_folder.yml
// False Positives:
//   - May occur legitimately as part of admin activity, but rarely with interactive elevation.

DeviceFileEvents
| where InitiatingProcessIntegrityLevel =~ "High" and FolderPath contains ":\\Windows\\System32\\CodeIntegrity\\" and (FolderPath endswith ".cip" or FolderPath endswith ".p7b")