// Title: WebDAV Temporary Local File Creation
// Author: Micah Babinski
// Date: 2023-08-21
// Level: medium
// Description: Detects the creation of WebDAV temporary files with potentially suspicious extensions
// MITRE Tactic: Initial Access
// Tags: attack.initial-access, attack.resource-development, attack.t1584, attack.t1566, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/file/file_event/file_event_win_webdav_tmpfile_creation.yml
// False Positives:
//   - Legitimate use of WebDAV in an environment

DeviceFileEvents
| where FolderPath contains "\\AppData\\Local\\Temp\\TfsStore\\Tfs_DAV\\" and (FolderPath endswith ".7z" or FolderPath endswith ".bat" or FolderPath endswith ".dat" or FolderPath endswith ".ico" or FolderPath endswith ".js" or FolderPath endswith ".lnk" or FolderPath endswith ".ps1" or FolderPath endswith ".rar" or FolderPath endswith ".vbe" or FolderPath endswith ".vbs" or FolderPath endswith ".zip")