// Author: Tim Shelton (HAWK.IO)
// Date: 2021/12/09
// Level: medium
// Description: Detects a when net.exe is called with a password in the command line
// Tags: attack.defense_evasion, attack.initial_access, attack.persistence, attack.privilege_escalation, attack.lateral_movement, attack.t1021.002, attack.t1078
DeviceProcessEvents
| where ((ProcessCommandLine contains " use " and (ProcessCommandLine contains ":" and ProcessCommandLine contains "\\") and (ProcessCommandLine contains "/USER:" and ProcessCommandLine contains " ")) and ((FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe") or (ProcessVersionInfoOriginalFileName in~ ("net.exe", "net1.exe")))) and (not(ProcessCommandLine endswith " "))