// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/01/21
// Level: high
// Description: Detects creation of the PSEXEC key file. Which is created anytime a PsExec command is executed. It gets written to the file system and will be recorded in the USN Journal on the target system
// Tags: attack.lateral_movement, attack.privilege_escalation, attack.execution, attack.persistence, attack.t1136.002, attack.t1543.003, attack.t1570, attack.s0029
DeviceFileEvents
| where FolderPath endswith ".key" and FolderPath startswith "C:\\Windows\\PSEXEC-"