// Title: Lace Tempest Malware Loader Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-11-09
// Level: high
// Description: Detects execution of a specific binary based on filename and hash used by Lace Tempest to load additional malware as reported by SysAid Team
// MITRE Tactic: Execution
// Tags: attack.execution, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2023/TA/Lace-Tempest/proc_creation_win_apt_lace_tempest_loader_execution.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where SHA256 startswith "B5ACF14CDAC40BE590318DEE95425D0746E85B1B7B1CBD14DA66F21F2522BF4D" or FolderPath endswith ":\\Program Files\\SysAidServer\\tomcat\\webapps\\usersfiles\\user.exe"