// Title: Lace Tempest Cobalt Strike Download
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-11-09
// Level: high
// Description: Detects specific command line execution used by Lace Tempest to download Cobalt Strike as reported by SysAid Team
// MITRE Tactic: Execution
// Tags: attack.execution, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2023/TA/Lace-Tempest/proc_creation_win_apt_lace_tempest_cobalt_strike_download.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains "-nop -w hidden -c IEX ((new-object net.webclient).downloadstring(" and ProcessCommandLine contains "/a')"