// Title: System Drawing DLL Load
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2020-05-02
// Level: low
// Description: Detects processes loading "System.Drawing.ni.dll". This could be an indicator of potential Screen Capture.
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1113, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/image_load/image_load_dll_system_drawing_load.yml
// False Positives:
//   - False positives are very common from system and third party applications, activity needs to be investigated. This rule is best correlated with other events to increase the level of suspiciousness

DeviceImageLoadEvents
| where FolderPath endswith "\\System.Drawing.ni.dll"