// Title: Microsoft Word Add-In Loaded
// Author: Steffen Rogge (dr0pd34d)
// Date: 2024-07-10
// Level: low
// Description: Detects Microsoft Word loading an Add-In (.wll) file which can be used by threat actors for initial access or persistence.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1204.002, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/image_load/image_load_office_word_wll_load.yml
// False Positives:
//   - The rules is only looking for ".wll" loads. So some false positives are expected with legitimate and allowed WLLs.

DeviceImageLoadEvents
| where FolderPath endswith ".wll" and InitiatingProcessFolderPath endswith "\\winword.exe"