// Title: Task Scheduler DLL Loaded By Application Located In Potentially Suspicious Location
// Author: Swachchhanda Shrawan Poudel
// Date: 2024-09-02
// Level: low
// Description: Detects the loading of the "taskschd.dll" module from a process that located in a potentially suspicious or uncommon directory.
// The loading of this DLL might indicate that the application have the capability to create a scheduled task via the "Schedule.Service" COM object.
// Investigation of the loading application and its behavior is required to determining if its malicious.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.execution, attack.privilege-escalation, attack.t1053.005, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/image_load/image_load_dll_taskschd_by_process_in_potentially_suspicious_location.yml
// False Positives:
//   - Some installers might generate false positives, apply additional filters accordingly.

DeviceImageLoadEvents
| where (FolderPath endswith "\\taskschd.dll" or InitiatingProcessVersionInfoOriginalFileName =~ "taskschd.dll") and (InitiatingProcessFolderPath contains ":\\Temp\\" or InitiatingProcessFolderPath contains ":\\Users\\Public\\" or InitiatingProcessFolderPath contains ":\\Windows\\Temp\\" or InitiatingProcessFolderPath contains "\\AppData\\Local\\Temp\\" or InitiatingProcessFolderPath contains "\\Desktop\\" or InitiatingProcessFolderPath contains "\\Downloads\\")