// Title: ADS Zone.Identifier Deleted
// Author: frack113
// Date: 2023-09-04
// Level: low
// Description: Detects the deletion of the "Zone.Identifier" ADS. Attackers can leverage this in order to bypass security restrictions that make use of the ADS such as Microsoft Office apps.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1070.004, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/file/file_delete/file_delete_win_zone_identifier_ads.yml
// False Positives:
//   - Likely

DeviceFileEvents
| where FolderPath endswith ":Zone.Identifier"