// Title: Access To Windows Credential History File By Uncommon Applications
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-17
// Level: medium
// Description: Detects file access requests to the Windows Credential History File by an uncommon application.
// This can be a sign of credential stealing. Example case would be usage of mimikatz "dpapi::credhist" function
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1555.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_access/file_access_win_susp_credhist.yml

DeviceFileEvents
| where FileName endswith "\\Microsoft\\Protect\\CREDHIST" and (not((InitiatingProcessFolderPath =~ "C:\\Windows\\explorer.exe" or (InitiatingProcessFolderPath startswith "C:\\Program Files\\" or InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\system32\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\SysWOW64\\"))))