// Title: Access To Windows DPAPI Master Keys By Uncommon Applications
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-17
// Level: medium
// Description: Detects file access requests to the the Windows Data Protection API Master keys by an uncommon application.
// This can be a sign of credential stealing. Example case would be usage of mimikatz "dpapi::masterkey" function
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1555.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_access/file_access_win_susp_dpapi_master_key_access.yml

DeviceFileEvents
| where (FileName contains "\\Microsoft\\Protect\\S-1-5-18\\" or FileName contains "\\Microsoft\\Protect\\S-1-5-21-") and (not((InitiatingProcessFolderPath startswith "C:\\Program Files\\" or InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\system32\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\SysWOW64\\")))