// Title: Credential Manager Access By Uncommon Applications
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-11
// Level: medium
// Description: Detects suspicious processes based on name and location that access the windows credential manager and vault.
// Which can be a sign of credential stealing. Example case would be usage of mimikatz "dpapi::cred" function
// MITRE Tactic: Credential Access
// Tags: attack.t1003, attack.credential-access
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_access/file_access_win_susp_credential_manager_access.yml
// False Positives:
//   - Legitimate software installed by the users for example in the "AppData" directory may access these files (for any reason).

DeviceFileEvents
| where (FileName contains "\\AppData\\Local\\Microsoft\\Credentials\\" or FileName contains "\\AppData\\Roaming\\Microsoft\\Credentials\\" or FileName contains "\\AppData\\Local\\Microsoft\\Vault\\" or FileName contains "\\ProgramData\\Microsoft\\Vault\\") and (not((InitiatingProcessFolderPath startswith "C:\\Program Files\\" or InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\system32\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\SysWOW64\\")))