// Title: Microsoft Teams Sensitive File Access By Uncommon Applications
// Author: @SerkinValery
// Date: 2024-07-22
// Level: medium
// Description: Detects file access attempts to sensitive Microsoft teams files (leveldb, cookies) by an uncommon process.
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1528
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_access/file_access_win_teams_sensitive_files.yml

DeviceFileEvents
| where (FileName contains "\\Microsoft\\Teams\\Cookies" or FileName contains "\\Microsoft\\Teams\\Local Storage\\leveldb") and (not(InitiatingProcessFolderPath endswith "\\Microsoft\\Teams\\current\\Teams.exe"))