// Title: Potential Hidden Directory Creation Via NTFS INDEX_ALLOCATION Stream
// Author: Scoubi (@ScoubiMtl)
// Date: 2023-10-09
// Level: medium
// Description: Detects the creation of hidden file/folder with the "::$index_allocation" stream. Which can be used as a technique to prevent access to folder and files from tooling such as "explorer.exe" and "powershell.exe"
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1564.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_susp_hidden_dir_index_allocation.yml
// False Positives:
//   - Unlikely

DeviceFileEvents
| where FolderPath contains "::$index_allocation"