// Title: TeamViewer Remote Session
// Author: Florian Roth (Nextron Systems)
// Date: 2022-01-30
// Level: medium
// Description: Detects the creation of log files during a TeamViewer remote session
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1219.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_susp_teamviewer_remote_session.yml
// False Positives:
//   - Legitimate uses of TeamViewer in an organisation

DeviceFileEvents
| where (FolderPath endswith "\\TeamViewer\\RemotePrinting\\tvprint.db" or FolderPath endswith "\\TeamViewer\\TVNetwork.log") or (FolderPath contains "\\TeamViewer" and FolderPath contains "_Logfile.log")