// Title: Suspicious PROCEXP152.sys File Created In TMP
// Author: xknow (@xknow_infosec), xorxes (@xor_xes)
// Date: 2019-04-08
// Level: medium
// Description: Detects the creation of the PROCEXP152.sys file in the application-data local temporary folder.
// This driver is used by Sysinternals Process Explorer but also by KDU (https://github.com/hfiref0x/KDU) or Ghost-In-The-Logs (https://github.com/bats3c/Ghost-In-The-Logs), which uses KDU.
// MITRE Tactic: Defense Evasion
// Tags: attack.t1562.001, attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_susp_procexplorer_driver_created_in_tmp_folder.yml
// False Positives:
//   - Other legimate tools using this driver and filename (like Sysinternals). Note - Clever attackers may easily bypass this detection by just renaming the driver filename. Therefore just Medium-level and don't rely on it.

DeviceFileEvents
| where (FolderPath contains "\\AppData\\Local\\Temp\\" and FolderPath endswith "PROCEXP152.sys") and (not((InitiatingProcessFolderPath contains "\\procexp64.exe" or InitiatingProcessFolderPath contains "\\procexp.exe" or InitiatingProcessFolderPath contains "\\procmon64.exe" or InitiatingProcessFolderPath contains "\\procmon.exe")))