// Title: HackTool - NPPSpy Hacktool Usage
// Author: Florian Roth (Nextron Systems)
// Date: 2021-11-29
// Level: high
// Description: Detects the use of NPPSpy hacktool that stores cleartext passwords of users that logged in to a local file
// MITRE Tactic: Credential Access
// Tags: attack.credential-access
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_hktl_nppspy.yml

DeviceFileEvents
| where FolderPath endswith "\\NPPSpy.txt" or FolderPath endswith "\\NPPSpy.dll"