// Title: WMI Persistence - Script Event Consumer File Write
// Author: Thomas Patzke
// Date: 2018-03-07
// Level: high
// Description: Detects file writes of WMI script event consumer
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.t1546.003, attack.persistence
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_wmi_persistence_script_event_consumer_write.yml
// False Positives:
//   - Dell Power Manager (C:\Program Files\Dell\PowerManager\DpmPowerPlanSetup.exe)

DeviceFileEvents
| where InitiatingProcessFolderPath =~ "C:\\WINDOWS\\system32\\wbem\\scrcons.exe"