// Title: UAC Bypass Using Consent and Comctl32 - File
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-23
// Level: high
// Description: Detects the pattern of UAC Bypass using consent.exe and comctl32.dll (UACMe 22)
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1548.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_uac_bypass_consent_comctl32.yml

DeviceFileEvents
| where FolderPath endswith "\\comctl32.dll" and FolderPath startswith "C:\\Windows\\System32\\consent.exe.@"