// Title: NTDS Exfiltration Filename Patterns
// Author: Florian Roth (Nextron Systems)
// Date: 2022-03-11
// Level: high
// Description: Detects creation of files with specific name patterns seen used in various tools that export the NTDS.DIT for exfiltration.
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_ntds_exfil_tools.yml

DeviceFileEvents
| where FolderPath endswith "\\All.cab" or FolderPath endswith ".ntds.cleartext"