// Title: Advanced IP Scanner - File Event
// Author: @ROxPinTeddy
// Date: 2020-05-12
// Level: medium
// Description: Detects the use of Advanced IP Scanner. Seems to be a popular tool for ransomware groups.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1046
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_advanced_ip_scanner.yml
// False Positives:
//   - Legitimate administrative use

DeviceFileEvents
| where FolderPath contains "\\AppData\\Local\\Temp\\Advanced IP Scanner 2"