// Title: CSExec Service File Creation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-04
// Level: medium
// Description: Detects default CSExec service filename which indicates CSExec service installation and execution
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1569.002, attack.s0029
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_csexec_service.yml

DeviceFileEvents
| where FolderPath endswith "\\csexecsvc.exe"