// Title: Rclone Config File Creation
// Author: Aaron Greetham (@beardofbinary) - NCC Group
// Date: 2021-05-26
// Level: medium
// Description: Detects Rclone config files being created
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.t1567.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_rclone_config_files.yml
// False Positives:
//   - Legitimate Rclone usage

DeviceFileEvents
| where FolderPath contains ":\\Users\\" and FolderPath contains "\\.config\\rclone\\"