// Title: ISO File Created Within Temp Folders
// Author: @sam0x90
// Date: 2022-07-30
// Level: high
// Description: Detects the creation of a ISO file in the Outlook temp folder or in the Appdata temp folder. Typical of Qakbot TTP from end-July 2022.
// MITRE Tactic: Initial Access
// Tags: attack.initial-access, attack.t1566.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_iso_file_mount.yml
// False Positives:
//   - Potential FP by sysadmin opening a zip file containing a legitimate ISO file

DeviceFileEvents
| where ((FolderPath contains "\\AppData\\Local\\Temp\\" and FolderPath contains ".zip\\") and FolderPath endswith ".iso") or (FolderPath contains "\\AppData\\Local\\Microsoft\\Windows\\INetCache\\Content.Outlook\\" and FolderPath endswith ".iso")