// Title: Adwind RAT / JRAT File Artifact
// Author: Florian Roth (Nextron Systems), Tom Ueltschi, Jonhnathan Ribeiro, oscd.community
// Date: 2017-11-10
// Level: high
// Description: Detects javaw.exe in AppData folder as used by Adwind / JRAT
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.005, attack.t1059.007
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_mal_adwind.yml

DeviceFileEvents
| where (FolderPath contains "\\AppData\\Roaming\\Oracle\\bin\\java" and FolderPath contains ".exe") or (FolderPath contains "\\Retrive" and FolderPath contains ".vbs")