// Title: Office Macro File Creation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-01-23
// Level: low
// Description: Detects the creation of a new office macro files on the systems
// MITRE Tactic: Initial Access
// Tags: attack.initial-access, attack.t1566.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_office_macro_files_created.yml
// False Positives:
//   - Very common in environments that rely heavily on macro documents

DeviceFileEvents
| where FolderPath endswith ".docm" or FolderPath endswith ".dotm" or FolderPath endswith ".xlsm" or FolderPath endswith ".xltm" or FolderPath endswith ".potm" or FolderPath endswith ".pptm"