// Title: UAC Bypass Using MSConfig Token Modification - File
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-30
// Level: high
// Description: Detects the pattern of UAC Bypass using a msconfig GUI hack (UACMe 55)
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1548.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_uac_bypass_msconfig_gui.yml

DeviceFileEvents
| where FolderPath endswith "\\AppData\\Local\\Temp\\pkgmgr.exe" and FolderPath startswith "C:\\Users\\"