// Title: Suspicious ASPX File Drop by Exchange
// Author: Florian Roth (Nextron Systems), MSTI (query, idea)
// Date: 2022-10-01
// Level: high
// Description: Detects suspicious file type dropped by an Exchange component in IIS into a suspicious folder
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1505.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_exchange_webshell_drop.yml

DeviceFileEvents
| where (InitiatingProcessCommandLine contains "MSExchange" and InitiatingProcessFolderPath endswith "\\w3wp.exe" and (FolderPath contains "FrontEnd\\HttpProxy\\" or FolderPath contains "\\inetpub\\wwwroot\\aspnet_client\\")) and (FolderPath endswith ".aspx" or FolderPath endswith ".asp" or FolderPath endswith ".ashx")