// Title: LiveKD Kernel Memory Dump File Created
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-16
// Level: high
// Description: Detects the creation of a file that has the same name as the default LiveKD kernel memory dump.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_sysinternals_livekd_default_dump_name.yml
// False Positives:
//   - In rare occasions administrators might leverage LiveKD to perform live kernel debugging. This should not be allowed on production systems. Investigate and apply additional filters where necessary.

DeviceFileEvents
| where FolderPath =~ "C:\\Windows\\livekd.dmp"