// Title: LiveKD Driver Creation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-16
// Level: medium
// Description: Detects the creation of the LiveKD driver, which is used for live kernel debugging
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_sysinternals_livekd_driver.yml
// False Positives:
//   - Legitimate usage of LiveKD for debugging purposes will also trigger this

DeviceFileEvents
| where (InitiatingProcessFolderPath endswith "\\livekd.exe" or InitiatingProcessFolderPath endswith "\\livek64.exe") and FolderPath =~ "C:\\Windows\\System32\\drivers\\LiveKdD.SYS"