// Title: EVTX Created In Uncommon Location
// Author: D3F7A5105
// Date: 2023-01-02
// Level: medium
// Description: Detects the creation of new files with the ".evtx" extension in non-common or non-standard location.
// This could indicate tampering with default EVTX locations in order to evade security controls or simply exfiltration of event log to search for sensitive information within.
// Note that backup software and legitimate administrator might perform similar actions during troubleshooting.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_create_evtx_non_common_locations.yml
// False Positives:
//   - Administrator or backup activity
//   - An unknown bug seems to trigger the Windows "svchost" process to drop EVTX files in the "C:\Windows\Temp" directory in the form "<log_name">_<uuid>.evtx". See https://superuser.com/questions/1371229/low-disk-space-after-filling-up-c-windows-temp-with-evtx-and-txt-files

DeviceFileEvents
| where FolderPath endswith ".evtx" and (not(((FolderPath endswith "\\Windows\\System32\\winevt\\Logs\\" and FolderPath startswith "C:\\ProgramData\\Microsoft\\Windows\\Containers\\BaseImages\\") or FolderPath startswith "C:\\Windows\\System32\\winevt\\Logs\\")))