// Title: Suspicious Executable File Creation
// Author: frack113
// Date: 2022-09-05
// Level: high
// Description: Detect creation of suspicious executable file names.
// Some strings look for suspicious file extensions, others look for filenames that exploit unquoted service paths.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1564
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_susp_executable_creation.yml

DeviceFileEvents
| where FolderPath endswith ":\\$Recycle.Bin.exe" or FolderPath endswith ":\\Documents and Settings.exe" or FolderPath endswith ":\\MSOCache.exe" or FolderPath endswith ":\\PerfLogs.exe" or FolderPath endswith ":\\Recovery.exe" or FolderPath endswith ".bat.exe" or FolderPath endswith ".sys.exe"