// Title: VsCode Powershell Profile Modification
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-24
// Level: medium
// Description: Detects the creation or modification of a vscode related powershell profile which could indicate suspicious activity as the profile can be used as a mean of persistence
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.t1546.013
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_susp_vscode_powershell_profile.yml
// False Positives:
//   - Legitimate use of the profile by developers or administrators

DeviceFileEvents
| where FolderPath endswith "\\Microsoft.VSCode_profile.ps1"