// Title: NTDS.DIT Creation By Uncommon Parent Process
// Author: Florian Roth (Nextron Systems)
// Date: 2022-03-11
// Level: high
// Description: Detects creation of a file named "ntds.dit" (Active Directory Database) by an uncommon parent process or directory
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_ntds_dit_uncommon_parent_process.yml

DeviceFileEvents
| where FolderPath endswith "\\ntds.dit" and ((InitiatingProcessParentFileName in~ ("cscript.exe", "httpd.exe", "nginx.exe", "php-cgi.exe", "powershell.exe", "pwsh.exe", "w3wp.exe", "wscript.exe")) or (InitiatingProcessParentFileName startswith "apache" or InitiatingProcessParentFileName startswith "tomcat" or InitiatingProcessParentFileName startswith "" or InitiatingProcessParentFileName startswith "" or InitiatingProcessParentFileName startswith "" or InitiatingProcessParentFileName startswith ""))