// Title: LSASS Process Memory Dump Creation Via Taskmgr.EXE
// Author: Swachchhanda Shrawan Poudel
// Date: 2023-10-19
// Level: high
// Description: Detects the creation of an "lsass.dmp" file by the taskmgr process. This indicates a manual dumping of the LSASS.exe process memory using Windows Task Manager.
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_taskmgr_lsass_dump.yml
// False Positives:
//   - Rare case of troubleshooting by an administrator or support that has to be investigated regardless

DeviceFileEvents
| where (InitiatingProcessFolderPath endswith ":\\Windows\\system32\\taskmgr.exe" or InitiatingProcessFolderPath endswith ":\\Windows\\SysWOW64\\taskmgr.exe") and (FolderPath contains "\\AppData\\Local\\Temp\\" and FolderPath contains "\\lsass" and FolderPath contains ".DMP")