// Title: GatherNetworkInfo.VBS Reconnaissance Script Output
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-08
// Level: medium
// Description: Detects creation of files which are the results of executing the built-in reconnaissance script "C:\Windows\System32\gatherNetworkInfo.vbs".
// MITRE Tactic: Discovery
// Tags: attack.discovery
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_lolbin_gather_network_info_script_output.yml

DeviceFileEvents
| where (FolderPath endswith "\\Hotfixinfo.txt" or FolderPath endswith "\\netiostate.txt" or FolderPath endswith "\\sysportslog.txt" or FolderPath endswith "\\VmSwitchLog.evtx") and FolderPath startswith "C:\\Windows\\System32\\config"