// Title: Suspicious Get-Variable.exe Creation
// Author: frack113
// Date: 2022-04-23
// Level: high
// Description: Get-Variable is a valid PowerShell cmdlet
// WindowsApps is by default in the path where PowerShell is executed.
// So when the Get-Variable command is issued on PowerShell execution, the system first looks for the Get-Variable executable in the path and executes the malicious binary instead of looking for the PowerShell cmdlet.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1546, attack.defense-evasion, attack.t1027
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_susp_get_variable.yml

DeviceFileEvents
| where FolderPath endswith "Local\\Microsoft\\WindowsApps\\Get-Variable.exe"