// Title: Creation Exe for Service with Unquoted Path
// Author: frack113
// Date: 2021-12-30
// Level: high
// Description: Adversaries may execute their own malicious payloads by hijacking vulnerable file path references.
// Adversaries can take advantage of paths that lack surrounding quotations by placing an executable in a higher level directory within the path, so that Windows will choose the adversary's executable to launch.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547.009
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_creation_unquoted_service_path.yml

DeviceFileEvents
| where FolderPath =~ "C:\\program.exe"