// Title: Potential Suspicious PowerShell Module File Created
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-09
// Level: medium
// Description: Detects the creation of a new PowerShell module in the first folder of the module directory structure "\WindowsPowerShell\Modules\malware\malware.psm1". This is somewhat an uncommon practice as legitimate modules often includes a version folder.
// MITRE Tactic: Persistence
// Tags: attack.persistence
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_powershell_module_susp_creation.yml
// False Positives:
//   - False positive rate will vary depending on the environments. Additional filters might be required to make this logic usable in production.

DeviceFileEvents
| where (FolderPath contains "\\WindowsPowerShell\\Modules\\" and FolderPath contains "\\.ps") or (FolderPath contains "\\WindowsPowerShell\\Modules\\" and FolderPath contains "\\.dll")