// Title: Renamed VsCode Code Tunnel Execution - File Indicator
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-10-25
// Level: high
// Description: Detects the creation of a file with the name "code_tunnel.json" which indicate execution and usage of VsCode tunneling utility by an "Image" or "Process" other than VsCode.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_vscode_tunnel_renamed_execution.yml

DeviceFileEvents
| where FolderPath endswith "\\code_tunnel.json" and (not((InitiatingProcessFolderPath endswith "\\code-tunnel.exe" or InitiatingProcessFolderPath endswith "\\code.exe")))