// Title: Suspicious File Created in Outlook Temporary Directory
// Author: Florian Roth (Nextron Systems), Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-07-22
// Level: high
// Description: Detects the creation of files with suspicious file extensions in the temporary directory that Outlook uses when opening attachments.
// This can be used to detect spear-phishing campaigns that use suspicious files as attachments, which may contain malicious code.
// MITRE Tactic: Initial Access
// Tags: attack.initial-access, attack.t1566.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_office_outlook_susp_file_creation_in_temp_dir.yml
// False Positives:
//   - Opening of headers or footers in email signatures that include SVG images or legitimate SVG attachments

DeviceFileEvents
| where (FolderPath endswith ".cpl" or FolderPath endswith ".hta" or FolderPath endswith ".iso" or FolderPath endswith ".rdp" or FolderPath endswith ".svg" or FolderPath endswith ".vba" or FolderPath endswith ".vbe" or FolderPath endswith ".vbs") and ((FolderPath contains "\\AppData\\Local\\Packages\\Microsoft.Outlook_" or FolderPath contains "\\AppData\\Local\\Microsoft\\Olk\\Attachments\\") or (FolderPath contains "\\AppData\\Local\\Microsoft\\Windows\\" and FolderPath contains "\\Content.Outlook\\"))