// Title: UAC Bypass Using IDiagnostic Profile - File
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-03
// Level: high
// Description: Detects the creation of a file by "dllhost.exe" in System32 directory part of "IDiagnosticProfileUAC" UAC bypass technique
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, attack.privilege-escalation, attack.t1548.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_uac_bypass_idiagnostic_profile.yml

DeviceFileEvents
| where InitiatingProcessFolderPath endswith "\\DllHost.exe" and FolderPath endswith ".dll" and FolderPath startswith "C:\\Windows\\System32\\"