// Title: Suspicious Outlook Macro Created
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-08
// Level: high
// Description: Detects the creation of a macro file for Outlook.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.command-and-control, attack.t1137, attack.t1008, attack.t1546
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_office_outlook_susp_macro_creation.yml
// False Positives:
//   - Unlikely

DeviceFileEvents
| where FolderPath endswith "\\Microsoft\\Outlook\\VbaProject.OTM" and (not(InitiatingProcessFolderPath endswith "\\outlook.exe"))