// Title: UAC Bypass Abusing Winsat Path Parsing - File
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-30
// Level: high
// Description: Detects the pattern of UAC Bypass using a path parsing issue in winsat.exe (UACMe 52)
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1548.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_uac_bypass_winsat.yml

DeviceFileEvents
| where (FolderPath endswith "\\AppData\\Local\\Temp\\system32\\winsat.exe" or FolderPath endswith "\\AppData\\Local\\Temp\\system32\\winmm.dll") and FolderPath startswith "C:\\Users\\"