// Title: UAC Bypass Using IEInstal - File
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-08-30
// Level: high
// Description: Detects the pattern of UAC Bypass using IEInstal.exe (UACMe 64)
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1548.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_uac_bypass_ieinstal.yml

DeviceFileEvents
| where InitiatingProcessFolderPath =~ "C:\\Program Files\\Internet Explorer\\IEInstal.exe" and FolderPath contains "\\AppData\\Local\\Temp\\" and FolderPath endswith "consent.exe" and FolderPath startswith "C:\\Users\\"