// Title: DPAPI Backup Keys And Certificate Export Activity IOC
// Author: Nounou Mbeiri, Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-06-26
// Level: high
// Description: Detects file names with specific patterns seen generated and used by tools such as Mimikatz and DSInternals related to exported or stolen DPAPI backup keys and certificates.
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1555, attack.t1552.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_susp_dpapi_backup_and_cert_export_ioc.yml
// False Positives:
//   - Unlikely

DeviceFileEvents
| where (FolderPath contains "ntds_capi_" or FolderPath contains "ntds_legacy_" or FolderPath contains "ntds_unknown_") and (FolderPath endswith ".cer" or FolderPath endswith ".key" or FolderPath endswith ".pfx" or FolderPath endswith ".pvk")