// Title: Suspicious Scheduled Task Write to System32 Tasks
// Author: Florian Roth (Nextron Systems)
// Date: 2021-11-16
// Level: high
// Description: Detects the creation of tasks from processes executed from suspicious locations
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.execution, attack.t1053
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_susp_task_write.yml

DeviceFileEvents
| where (InitiatingProcessFolderPath contains "\\AppData\\" or InitiatingProcessFolderPath contains "C:\\PerfLogs" or InitiatingProcessFolderPath contains "\\Windows\\System32\\config\\systemprofile") and FolderPath contains "\\Windows\\System32\\Tasks"