// Title: HackTool - QuarksPwDump Dump File
// Author: Florian Roth (Nextron Systems)
// Date: 2018-02-10
// Level: critical
// Description: Detects a dump file written by QuarksPwDump password dumper
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_hktl_quarkspw_filedump.yml

DeviceFileEvents
| where FolderPath contains "\\AppData\\Local\\Temp\\SAM-" and FolderPath contains ".dmp"