// Title: Suspicious File Write to Webapps Root Directory
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-10-20
// Level: medium
// Description: Detects suspicious file writes to the root directory of web applications, particularly Apache web servers or Tomcat servers.
// This may indicate an attempt to deploy malicious files such as web shells or other unauthorized scripts.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1505.003, attack.initial-access, attack.t1190
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_susp_file_write_in_webapps_root.yml

DeviceFileEvents
| where FolderPath contains "\\webapps\\ROOT\\" and (FolderPath contains "\\apache" or FolderPath contains "\\tomcat") and FolderPath endswith ".jsp" and (InitiatingProcessFolderPath endswith "\\dotnet.exe" or InitiatingProcessFolderPath endswith "\\w3wp.exe" or InitiatingProcessFolderPath endswith "\\java.exe")