// Title: Potential Persistence Via Outlook Form
// Author: Tobias Michalski (Nextron Systems)
// Date: 2021-06-10
// Level: high
// Description: Detects the creation of a new Outlook form which can contain malicious code
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1137.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_office_outlook_newform.yml
// False Positives:
//   - Legitimate use of outlook forms

DeviceFileEvents
| where InitiatingProcessFolderPath endswith "\\outlook.exe" and (FolderPath contains "\\AppData\\Local\\Microsoft\\FORMS\\IPM" or FolderPath contains "\\Local Settings\\Application Data\\Microsoft\\Forms")