// Title: Publisher Attachment File Dropped In Suspicious Location
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-08
// Level: medium
// Description: Detects creation of files with the ".pub" extension in suspicious or uncommon locations. This could be a sign of attackers abusing Publisher documents
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_office_publisher_files_in_susp_locations.yml
// False Positives:
//   - Legitimate usage of ".pub" files from those locations

DeviceFileEvents
| where (FolderPath contains "\\AppData\\Local\\Temp\\" or FolderPath contains "\\Users\\Public\\" or FolderPath contains "\\Windows\\Temp\\" or FolderPath contains "C:\\Temp\\") and FolderPath endswith ".pub"