// Title: Process Explorer Driver Creation By Non-Sysinternals Binary
// Author: Florian Roth (Nextron Systems)
// Date: 2023-05-05
// Level: high
// Description: Detects creation of the Process Explorer drivers by processes other than Process Explorer (procexp) itself.
// Hack tools or malware may use the Process Explorer driver to elevate privileges, drops it to disk for a few moments, runs a service using that driver and removes it afterwards.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.t1068
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_sysinternals_procexp_driver_susp_creation.yml
// False Positives:
//   - Some false positives may occur with legitimate renamed process explorer binaries

DeviceFileEvents
| where (FolderPath contains "\\PROCEXP" and FolderPath endswith ".sys") and (not((InitiatingProcessFolderPath endswith "\\procexp.exe" or InitiatingProcessFolderPath endswith "\\procexp64.exe")))