// Title: Assembly DLL Creation Via AspNetCompiler
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-14
// Level: medium
// Description: Detects the creation of new DLL assembly files by "aspnet_compiler.exe", which could be a sign of "aspnet_compiler" abuse to proxy execution through a build provider.
// MITRE Tactic: Execution
// Tags: attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_aspnet_temp_files.yml
// False Positives:
//   - Legitimate assembly compilation using a build provider

DeviceFileEvents
| where InitiatingProcessFolderPath endswith "\\aspnet_compiler.exe" and (FolderPath contains "\\Temporary ASP.NET Files\\" and FolderPath contains "\\assembly\\tmp\\" and FolderPath contains ".dll")