// Title: Dynamic CSharp Compile Artefact
// Author: frack113
// Date: 2022-01-09
// Level: low
// Description: When C# is compiled dynamically, a .cmdline file will be created as a part of the process.
// Certain processes are not typically observed compiling C# code, but can do so without touching disk.
// This can be used to unpack a payload for execution
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_csharp_compile_artefact.yml

DeviceFileEvents
| where FolderPath endswith ".cmdline"