// Title: UEFI Persistence Via Wpbbin - FileCreation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-18
// Level: high
// Description: Detects creation of a file named "wpbbin" in the "%systemroot%\system32\" directory. Which could be indicative of UEFI based persistence method
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1542.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_wpbbin_persistence.yml
// False Positives:
//   - Legitimate usage of the file by hardware manufacturer such as lenovo (Thanks @0gtweet for the tip)

DeviceFileEvents
| where FolderPath =~ "C:\\Windows\\System32\\wpbbin.exe"