// Title: HackTool - Powerup Write Hijack DLL
// Author: Subhash Popuri (@pbssubhash)
// Date: 2021-08-21
// Level: high
// Description: Powerup tool's Write Hijack DLL exploits DLL hijacking for privilege escalation.
// In it's default mode, it builds a self deleting .bat file which executes malicious command.
// The detection rule relies on creation of the malicious bat file (debug.bat by default).
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.defense-evasion, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_hktl_powerup_dllhijacking.yml
// False Positives:
//   - Any powershell script that creates bat files

DeviceFileEvents
| where (InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe") and FolderPath endswith ".bat"