// Title: Malicious DLL File Dropped in the Teams or OneDrive Folder
// Author: frack113
// Date: 2022-08-12
// Level: high
// Description: Detects creation of a malicious DLL file in the location where the OneDrive or Team applications
// Upon execution of the Teams or OneDrive application, the dropped malicious DLL file ("iphlpapi.dll") is sideloaded
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.defense-evasion, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_iphlpapi_dll_sideloading.yml

DeviceFileEvents
| where FolderPath contains "iphlpapi.dll" and FolderPath contains "\\AppData\\Local\\Microsoft"