// Title: Suspicious Interactive PowerShell as SYSTEM
// Author: Florian Roth (Nextron Systems)
// Date: 2021-12-07
// Level: high
// Description: Detects the creation of files that indicator an interactive use of PowerShell in the SYSTEM user context
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_susp_system_interactive_powershell.yml
// False Positives:
//   - Administrative activity
//   - PowerShell scripts running as SYSTEM user

DeviceFileEvents
| where FolderPath in~ ("C:\\Windows\\System32\\config\\systemprofile\\AppData\\Roaming\\Microsoft\\Windows\\PowerShell\\PSReadLine\\ConsoleHost_history.txt", "C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\Microsoft\\Windows\\PowerShell\\StartupProfileData-Interactive")