// Title: Anydesk Temporary Artefact
// Author: frack113
// Date: 2022-02-11
// Level: medium
// Description: An adversary may use legitimate desktop support and remote access software, such as Team Viewer, Go2Assist, LogMein, AmmyyAdmin, etc, to establish an interactive command and control channel to target systems within networks.
// These services are commonly used as legitimate technical support software, and may be allowed by application control within a target environment.
// Remote access tools like VNC, Ammyy, and Teamviewer are used frequently when compared with other legitimate software commonly used by adversaries. (Citation: Symantec Living off the Land)
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1219.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_anydesk_artefact.yml
// False Positives:
//   - Legitimate use

DeviceFileEvents
| where FolderPath contains "\\AppData\\Roaming\\AnyDesk\\user.conf" or FolderPath contains "\\AppData\\Roaming\\AnyDesk\\system.conf"