// Title: Self Extraction Directive File Created In Potentially Suspicious Location
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2024-02-05
// Level: medium
// Description: Detects the creation of Self Extraction Directive files (.sed) in a potentially suspicious location.
// These files are used by the "iexpress.exe" utility in order to create self extracting packages.
// Attackers were seen abusing this utility and creating PE files with embedded ".sed" entries.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_sed_file_creation.yml

DeviceFileEvents
| where (FolderPath contains ":\\ProgramData\\" or FolderPath contains ":\\Temp\\" or FolderPath contains ":\\Windows\\System32\\Tasks\\" or FolderPath contains ":\\Windows\\Tasks\\" or FolderPath contains ":\\Windows\\Temp\\" or FolderPath contains "\\AppData\\Local\\Temp\\") and FolderPath endswith ".sed"