// Title: Process Monitor Driver Creation By Non-Sysinternals Binary
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-05
// Level: medium
// Description: Detects creation of the Process Monitor driver by processes other than Process Monitor (procmon) itself.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.t1068
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_sysinternals_procmon_driver_susp_creation.yml
// False Positives:
//   - Some false positives may occur with legitimate renamed process monitor binaries

DeviceFileEvents
| where (FolderPath contains "\\procmon" and FolderPath endswith ".sys") and (not((InitiatingProcessFolderPath endswith "\\procmon.exe" or InitiatingProcessFolderPath endswith "\\procmon64.exe")))