// Title: Writing Local Admin Share
// Author: frack113
// Date: 2022-01-01
// Level: medium
// Description: Aversaries may use to interact with a remote network share using Server Message Block (SMB).
// This technique is used by post-exploitation frameworks.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.lateral-movement, attack.t1546.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_writing_local_admin_share.yml

DeviceFileEvents
| where FolderPath contains "\\\\127.0.0" and FolderPath contains "\\ADMIN$\\"