// Title: DLL Search Order Hijackig Via Additional Space in Path
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-30
// Level: high
// Description: Detects when an attacker create a similar folder structure to windows system folders such as (Windows, Program Files...)
// but with a space in order to trick DLL load search order and perform a "DLL Search Order Hijacking" attack
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.defense-evasion, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_dll_sideloading_space_path.yml

DeviceFileEvents
| where FolderPath endswith ".dll" and (FolderPath startswith "C:\\Windows \\" or FolderPath startswith "C:\\Program Files \\" or FolderPath startswith "C:\\Program Files (x86) \\")