// Title: Suspicious File Drop by Exchange
// Author: Florian Roth (Nextron Systems)
// Date: 2022-10-04
// Level: medium
// Description: Detects suspicious file type dropped by an Exchange component in IIS
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1190, attack.initial-access, attack.t1505.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_exchange_webshell_drop_suspicious.yml

DeviceFileEvents
| where (InitiatingProcessCommandLine contains "MSExchange" and InitiatingProcessFolderPath endswith "\\w3wp.exe") and (FolderPath endswith ".aspx" or FolderPath endswith ".asp" or FolderPath endswith ".ashx" or FolderPath endswith ".ps1" or FolderPath endswith ".bat" or FolderPath endswith ".exe" or FolderPath endswith ".dll" or FolderPath endswith ".vbs")