// Title: ADExplorer Writing Complete AD Snapshot Into .dat File
// Author: Arnim Rupp (Nextron Systems), Thomas Patzke
// Date: 2025-07-09
// Level: medium
// Description: Detects the dual use tool ADExplorer writing a complete AD snapshot into a .dat file. This can be used by attackers to extract data for Bloodhound, usernames for password spraying or use the meta data for social engineering. The snapshot doesn't contain password hashes but there have been cases, where administrators put passwords in the comment field.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1087.002, attack.t1069.002, attack.t1482
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_sysinternals_adexplorer_dump_written.yml
// False Positives:
//   - Legitimate use of ADExplorer by administrators creating .dat snapshots

DeviceFileEvents
| where (InitiatingProcessFolderPath endswith "\\ADExp.exe" or InitiatingProcessFolderPath endswith "\\ADExplorer.exe" or InitiatingProcessFolderPath endswith "\\ADExplorer64.exe" or InitiatingProcessFolderPath endswith "\\ADExplorer64a.exe") and FolderPath endswith ".dat"