// Title: Potential Persistence Via Microsoft Office Startup Folder
// Author: Max Altgelt (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-06-02
// Level: high
// Description: Detects creation of Microsoft Office files inside of one of the default startup folders in order to achieve persistence.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1137
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_office_startup_persistence.yml
// False Positives:
//   - Loading a user environment from a backup or a domain controller
//   - Synchronization of templates

DeviceFileEvents
| where (((FolderPath endswith ".doc" or FolderPath endswith ".docm" or FolderPath endswith ".docx" or FolderPath endswith ".dot" or FolderPath endswith ".dotm" or FolderPath endswith ".rtf") and (FolderPath contains "\\Microsoft\\Word\\STARTUP" or (FolderPath contains "\\Office" and FolderPath contains "\\Program Files" and FolderPath contains "\\STARTUP"))) or ((FolderPath endswith ".xls" or FolderPath endswith ".xlsm" or FolderPath endswith ".xlsx" or FolderPath endswith ".xlt" or FolderPath endswith ".xltm") and (FolderPath contains "\\Microsoft\\Excel\\XLSTART" or (FolderPath contains "\\Office" and FolderPath contains "\\Program Files" and FolderPath contains "\\XLSTART")))) and (not((InitiatingProcessFolderPath endswith "\\WINWORD.exe" or InitiatingProcessFolderPath endswith "\\EXCEL.exe")))