// Title: HackTool - Typical HiveNightmare SAM File Export
// Author: Florian Roth (Nextron Systems)
// Date: 2021-07-23
// Level: high
// Description: Detects files written by the different tools that exploit HiveNightmare
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1552.001, cve.2021-36934
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_hktl_hivenightmare_file_exports.yml
// False Positives:
//   - Files that accidentally contain these strings

DeviceFileEvents
| where (FolderPath contains "\\hive_sam_" or FolderPath contains "\\SAM-2021-" or FolderPath contains "\\SAM-2022-" or FolderPath contains "\\SAM-2023-" or FolderPath contains "\\SAM-haxx" or FolderPath contains "\\Sam.save") or FolderPath =~ "C:\\windows\\temp\\sam"