// Title: Potential Persistence Attempt Via ErrorHandler.Cmd
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-09
// Level: medium
// Description: Detects creation of a file named "ErrorHandler.cmd" in the "C:\WINDOWS\Setup\Scripts\" directory which could be used as a method of persistence
// The content of C:\WINDOWS\Setup\Scripts\ErrorHandler.cmd is read whenever some tools under C:\WINDOWS\System32\oobe\ (e.g. Setup.exe) fail to run for any reason.
// MITRE Tactic: Persistence
// Tags: attack.persistence
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_errorhandler_persistence.yml

DeviceFileEvents
| where FolderPath endswith "\\WINDOWS\\Setup\\Scripts\\ErrorHandler.cmd"