// Title: Potential Startup Shortcut Persistence Via PowerShell.EXE
// Author: Christopher Peacock '@securepeacock', SCYTHE
// Date: 2021-10-24
// Level: high
// Description: Detects PowerShell writing startup shortcuts.
// This procedure was highlighted in Red Canary Intel Insights Oct. 2021, "We frequently observe adversaries using PowerShell to write malicious .lnk files into the startup directory to establish persistence.
// Accordingly, this detection opportunity is likely to identify persistence mechanisms in multiple threats.
// In the context of Yellow Cockatoo, this persistence mechanism eventually launches the command-line script that leads to the installation of a malicious DLL"
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_powershell_startup_shortcuts.yml
// False Positives:
//   - Depending on your environment accepted applications may leverage this at times. It is recommended to search for anomalies inidicative of malware.

DeviceFileEvents
| where (InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe") and FolderPath contains "\\start menu\\programs\\startup\\" and FolderPath endswith ".lnk"