// Title: ISO or Image Mount Indicator in Recent Files
// Author: Florian Roth (Nextron Systems)
// Date: 2022-02-11
// Level: medium
// Description: Detects the creation of recent element file that points to an .ISO, .IMG, .VHD or .VHDX file as often used in phishing attacks.
// This can be a false positive on server systems but on workstations users should rarely mount .iso or .img files.
// MITRE Tactic: Initial Access
// Tags: attack.initial-access, attack.t1566.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_iso_file_recent.yml
// False Positives:
//   - Cases in which a user mounts an image file for legitimate reasons

DeviceFileEvents
| where FolderPath contains "\\Microsoft\\Windows\\Recent\\" and (FolderPath endswith ".iso.lnk" or FolderPath endswith ".img.lnk" or FolderPath endswith ".vhd.lnk" or FolderPath endswith ".vhdx.lnk")