// Title: Suspicious Creation with Colorcpl
// Author: frack113
// Date: 2022-01-21
// Level: high
// Description: Once executed, colorcpl.exe will copy the arbitrary file to c:\windows\system32\spool\drivers\color\
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1564
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_susp_colorcpl.yml

DeviceFileEvents
| where InitiatingProcessFolderPath endswith "\\colorcpl.exe" and (not((FolderPath endswith ".icm" or FolderPath endswith ".gmmp" or FolderPath endswith ".cdmp" or FolderPath endswith ".camp")))