// Title: Suspicious Binary Writes Via AnyDesk
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-28
// Level: high
// Description: Detects AnyDesk writing binary files to disk other than "gcapi.dll".
// According to RedCanary research it is highly abnormal for AnyDesk to write executable files to disk besides gcapi.dll,
// which is a legitimate DLL that is part of the Google Chrome web browser used to interact with the Google Cloud API. (See reference section for more details)
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1219.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_anydesk_writing_susp_binaries.yml

DeviceFileEvents
| where ((InitiatingProcessFolderPath endswith "\\AnyDesk.exe" or InitiatingProcessFolderPath endswith "\\AnyDeskMSI.exe") and (FolderPath endswith ".dll" or FolderPath endswith ".exe")) and (not(FolderPath endswith "\\gcapi.dll"))