// Title: Windows Terminal Profile Settings Modification By Uncommon Process
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-07-22
// Level: medium
// Description: Detects the creation or modification of the Windows Terminal Profile settings file "settings.json" by an uncommon process.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547.015
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_susp_windows_terminal_profile.yml
// False Positives:
//   - Some false positives may occur with admin scripts that set WT settings.

DeviceFileEvents
| where (InitiatingProcessFolderPath endswith "\\cmd.exe" or InitiatingProcessFolderPath endswith "\\cscript.exe" or InitiatingProcessFolderPath endswith "\\mshta.exe" or InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe" or InitiatingProcessFolderPath endswith "\\wscript.exe") and FolderPath endswith "\\AppData\\Local\\Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\settings.json"