// Title: PDF File Created By RegEdit.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-07-08
// Level: high
// Description: Detects the creation of a file with the ".pdf" extension by the "RegEdit.exe" process.
// This indicates that a user is trying to print/save a registry key as a PDF in order to potentially extract sensitive information and bypass defenses.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_regedit_print_as_pdf.yml
// False Positives:
//   - Unlikely

DeviceFileEvents
| where InitiatingProcessFolderPath endswith "\\regedit.exe" and FolderPath endswith ".pdf"