// Title: WerFault LSASS Process Memory Dump
// Author: Florian Roth (Nextron Systems)
// Date: 2022-06-27
// Level: high
// Description: Detects WerFault creating a dump file with a name that indicates that the dump file could be an LSASS process memory, which contains user credentials
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_lsass_werfault_dump.yml

DeviceFileEvents
| where InitiatingProcessFolderPath =~ "C:\\WINDOWS\\system32\\WerFault.exe" and (FolderPath contains "\\lsass" or FolderPath contains "lsass.exe")