// Title: Potential Privilege Escalation Attempt Via .Exe.Local Technique
// Author: Nasreddine Bencherchali (Nextron Systems), Subhash P (@pbssubhash)
// Date: 2022-12-16
// Level: high
// Description: Detects potential privilege escalation attempt via the creation of the "*.Exe.Local" folder inside the "System32" directory in order to sideload "comctl32.dll"
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.persistence, attack.privilege-escalation
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_system32_local_folder_privilege_escalation.yml

DeviceFileEvents
| where FolderPath endswith "\\comctl32.dll" and (FolderPath startswith "C:\\Windows\\System32\\logonUI.exe.local" or FolderPath startswith "C:\\Windows\\System32\\werFault.exe.local" or FolderPath startswith "C:\\Windows\\System32\\consent.exe.local" or FolderPath startswith "C:\\Windows\\System32\\narrator.exe.local" or FolderPath startswith "C:\\Windows\\System32\\wermgr.exe.local")