// Title: Remote Access Tool - ScreenConnect Temporary File
// Author: Ali Alwashali
// Date: 2023-10-10
// Level: low
// Description: Detects the creation of files in a specific location by ScreenConnect RMM.
// ScreenConnect has feature to remotely execute binaries on a target machine. These binaries will be dropped to ":\Users\<username>\Documents\ConnectWiseControl\Temp\" before execution.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_remote_access_tools_screenconnect_remote_file.yml
// False Positives:
//   - Legitimate use of ScreenConnect

DeviceFileEvents
| where InitiatingProcessFolderPath endswith "\\ScreenConnect.WindowsClient.exe" and FolderPath contains "\\Documents\\ConnectWiseControl\\Temp\\"