// Title: WScript or CScript Dropper - File
// Author: Tim Shelton
// Date: 2022-01-10
// Level: high
// Description: Detects a file ending in jse, vbe, js, vba, vbs written by cscript.exe or wscript.exe
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.005, attack.t1059.007
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_cscript_wscript_dropper.yml

DeviceFileEvents
| where (InitiatingProcessFolderPath endswith "\\wscript.exe" or InitiatingProcessFolderPath endswith "\\cscript.exe") and (FolderPath endswith ".jse" or FolderPath endswith ".vbe" or FolderPath endswith ".js" or FolderPath endswith ".vba" or FolderPath endswith ".vbs") and (FolderPath startswith "C:\\Users\\" or FolderPath startswith "C:\\ProgramData")