// Title: Suspicious Deno File Written from Remote Source
// Author: Josh Nickels, Michael Taggart
// Date: 2025-05-22
// Level: low
// Description: Detects Deno writing a file from a direct HTTP(s) call and writing to the appdata folder or bringing it's own malicious DLL.
// This behavior may indicate an attempt to execute remotely hosted, potentially malicious files through deno.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1204, attack.t1059.007, attack.command-and-control, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_creation_deno.yml
// False Positives:
//   - Legitimate usage of deno to request a file or bring a DLL to a host

DeviceFileEvents
| where (FolderPath contains "\\deno\\gen\\" or FolderPath contains "\\deno\\remote\\https\\") and (FolderPath contains ":\\Users\\" and FolderPath contains "\\AppData\\")