// Title: Suspicious Creation TXT File in User Desktop
// Author: frack113
// Date: 2021-12-26
// Level: high
// Description: Ransomware create txt file in the user Desktop
// MITRE Tactic: Impact
// Tags: attack.impact, attack.t1486
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_susp_desktop_txt.yml

DeviceFileEvents
| where InitiatingProcessFolderPath endswith "\\cmd.exe" and (FolderPath contains "\\Users\\" and FolderPath contains "\\Desktop\\") and FolderPath endswith ".txt"