// Title: Suspicious Desktopimgdownldr Target File
// Author: Florian Roth (Nextron Systems)
// Date: 2020-07-03
// Level: high
// Description: Detects a suspicious Microsoft desktopimgdownldr file creation that stores a file to a suspicious location or contains a file with a suspicious extension
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1105
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_susp_desktopimgdownldr_file.yml
// False Positives:
//   - False positives depend on scripts and administrative tools used in the monitored environment

DeviceFileEvents
| where (InitiatingProcessFolderPath endswith "\\svchost.exe" and FolderPath contains "\\Personalization\\LockScreenImage\\") and (not(FolderPath contains "C:\\Windows\\")) and (not((FolderPath contains ".jpg" or FolderPath contains ".jpeg" or FolderPath contains ".png")))