// Title: Potential Winnti Dropper Activity
// Author: Alexander Rausch
// Date: 2020-06-24
// Level: high
// Description: Detects files dropped by Winnti as described in RedMimicry Winnti playbook
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_redmimicry_winnti_filedrop.yml

DeviceFileEvents
| where FolderPath endswith "\\gthread-3.6.dll" or FolderPath endswith "\\sigcmm-2.4.dll" or FolderPath endswith "\\Windows\\Temp\\tmp.bat"