// Title: Files With System DLL Name In Unsuspected Locations
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-06-24
// Level: medium
// Description: Detects the creation of a file with the ".dll" extension that has the name of a System DLL in uncommon or unsuspected locations. (Outisde of "System32", "SysWOW64", etc.).
// It is highly recommended to perform an initial baseline before using this rule in production.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036.005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_creation_system_dll_files.yml
// False Positives:
//   - Third party software might bundle specific versions of system DLLs.

DeviceFileEvents
| where (FolderPath endswith "\\secur32.dll" or FolderPath endswith "\\tdh.dll") and (not((FolderPath contains "C:\\$WINDOWS.~BT\\" or FolderPath contains "C:\\$WinREAgent\\" or FolderPath contains "C:\\Windows\\SoftwareDistribution\\" or FolderPath contains "C:\\Windows\\System32\\" or FolderPath contains "C:\\Windows\\SysWOW64\\" or FolderPath contains "C:\\Windows\\WinSxS\\" or FolderPath contains "C:\\Windows\\uus\\")))