// Title: NTDS.DIT Created
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-05
// Level: low
// Description: Detects creation of a file named "ntds.dit" (Active Directory Database)
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_ntds_dit_creation.yml

DeviceFileEvents
| where FolderPath endswith "ntds.dit"