// Title: Python Path Configuration File Creation - MacOS
// Author: Andreas Braathen (mnemonic.io)
// Date: 2024-04-25
// Level: medium
// Description: Detects creation of a Python path configuration file (.pth) in Python library folders, which can be maliciously abused for code execution and persistence.
// Modules referenced by these files are run at every Python startup (v3.5+), regardless of whether the module is imported by the calling script.
// Default paths are '\lib\site-packages\*.pth' (Windows) and '/lib/pythonX.Y/site-packages/*.pth' (Unix and macOS).
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1059.006, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/macos/file/file_event/file_event_macos_python_path_configuration_files.yml
// False Positives:
//   - Although .pth files are discouraged due to potential security implications, these are legitimate files by specification.

DeviceFileEvents
| where FolderPath endswith ".pth" and FolderPath matches regex "(?i)/lib/python3\\.([5-9]|[0-9]{2})/site-packages/"