// Title: TAIDOOR RAT DLL Load
// Author: Florian Roth (Nextron Systems)
// Date: 2020-07-30
// Level: high
// Description: Detects specific process characteristics of Chinese TAIDOOR RAT malware load
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.defense-evasion, attack.execution, attack.t1055.001, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2020/TA/TAIDOOR-RAT/proc_creation_win_apt_taidoor.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "dll,MyStart" or ProcessCommandLine contains "dll MyStart") or (ProcessCommandLine endswith " MyStart" and ProcessCommandLine contains "rundll32.exe")