// Title: Potential ACTINIUM Persistence Activity
// Author: Andreas Hunkeler (@Karneades)
// Date: 2022-02-07
// Level: high
// Description: Detects specific process parameters as used by ACTINIUM scheduled task persistence creation.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.execution, attack.persistence, attack.t1053, attack.t1053.005, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2022/TA/ACTINIUM/proc_creation_win_apt_actinium_persistence.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains "schtasks" and ProcessCommandLine contains "create" and ProcessCommandLine contains "wscript" and ProcessCommandLine contains " /e:vbscript"