// Title: Diamond Sleet APT DLL Sideloading Indicators
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-10-24
// Level: high
// Description: Detects DLL sideloading activity seen used by Diamond Sleet APT
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.persistence, attack.privilege-escalation, attack.t1574.001, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2023/TA/Diamond-Sleet/image_load_apt_diamond_sleet_side_load.yml
// False Positives:
//   - Unlikely

DeviceImageLoadEvents
| where (FolderPath endswith ":\\ProgramData\\Version.dll" and InitiatingProcessFolderPath endswith ":\\ProgramData\\clip.exe") or (FolderPath endswith ":\\ProgramData\\DSROLE.dll" and InitiatingProcessFolderPath endswith ":\\ProgramData\\wsmprovhost.exe")