// Title: Diamond Sleet APT Process Activity Indicators
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-10-24
// Level: high
// Description: Detects process creation activity indicators related to Diamond Sleet APT
// MITRE Tactic: Execution
// Tags: attack.execution, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2023/TA/Diamond-Sleet/proc_creation_win_apt_diamond_sleet_indicators.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains " uTYNkfKxHiZrx3KJ"