// Title: Diamond Sleet APT Scheduled Task Creation - Registry
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-10-24
// Level: high
// Description: Detects registry event related to the creation of a scheduled task used by Diamond Sleet APT during exploitation of Team City CVE-2023-42793 vulnerability
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2023/TA/Diamond-Sleet/registry_event_apt_diamond_sleet_scheduled_task.yml

DeviceRegistryEvents
| where RegistryKey endswith "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tree*" and RegistryKey contains "Windows TeamCity Settings User Interface"