// Title: Shell Context Menu Command Tampering
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-03-06
// Level: low
// Description: Detects changes to shell context menu commands. Use this rule to hunt for potential anomalies and suspicious shell commands.
// MITRE Tactic: Persistence
// Tags: attack.persistence, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/registry/registry_set/registry_set_shell_context_menu_tampering.yml
// False Positives:
//   - Likely from new software installation suggesting to add context menu items. Such as "PowerShell", "Everything", "Git", etc.

DeviceRegistryEvents
| where RegistryKey endswith "\\Software\\Classes*" and RegistryKey endswith "\\shell*" and RegistryKey endswith "\\command*"