// Title: Command Executed Via Run Dialog Box - Registry
// Author: Ahmed Farouk, Nasreddine Bencherchali
// Date: 2024-11-01
// Level: low
// Description: Detects execution of commands via the run dialog box on Windows by checking values of the "RunMRU" registry key.
// This technique was seen being abused by threat actors to deceive users into pasting and executing malicious commands, often disguised as CAPTCHA verification steps.
// MITRE Tactic: Execution
// Tags: detection.threat-hunting, attack.execution
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/registry/registry_set/registry_set_runmru_command_execution.yml
// False Positives:
//   - Likely

DeviceRegistryEvents
| where RegistryKey contains "\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RunMRU" and (not(RegistryKey endswith "\\MRUList")) and (not(((RegistryValueData in~ ("%appdata%\\1", "%localappdata%\\1", "%public%\\1", "%temp%\\1", "calc\\1", "dxdiag\\1", "explorer\\1", "gpedit.msc\\1", "mmc\\1", "notepad\\1", "regedit\\1", "services.msc\\1", "winver\\1")) or RegistryValueData contains "ping")))