// Title: Registry Set With Crypto-Classes From The "Cryptography" PowerShell Namespace
// Author: Andreas Braathen (mnemonic.io)
// Date: 2023-12-01
// Level: medium
// Description: Detects the setting of a registry inside the "\Shell\Open\Command" value with PowerShell classes from the "System.Security.Cryptography" namespace.
// The PowerShell namespace "System.Security.Cryptography" provides classes for on-the-fly encryption and decryption.
// These can be used for example in decrypting malicious payload for defense evasion.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.persistence, attack.privilege-escalation, attack.t1059.001, attack.t1027.010, attack.t1547.001, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/registry/registry_set/registry_set_powershell_crypto_namespace.yml
// False Positives:
//   - Classes are legitimately used, but less so when e.g. parents with low prevalence or decryption of content in temporary folders.

DeviceRegistryEvents
| where RegistryKey contains "\\Shell\\Open\\Command" and (RegistryValueData contains ".AesCryptoServiceProvider" or RegistryValueData contains ".DESCryptoServiceProvider" or RegistryValueData contains ".DSACryptoServiceProvider" or RegistryValueData contains ".RC2CryptoServiceProvider" or RegistryValueData contains ".Rijndael" or RegistryValueData contains ".RSACryptoServiceProvider" or RegistryValueData contains ".TripleDESCryptoServiceProvider") and (RegistryValueData contains "powershell" or RegistryValueData contains "pwsh") and RegistryValueData contains "System.Security.Cryptography."