// Title: Successful Account Login Via WMI
// Author: Thomas Patzke
// Date: 2019-12-04
// Level: low
// Description: Detects successful logon attempts performed with WMI
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1047
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/security/account_management/win_security_susp_wmi_login.yml
// False Positives:
//   - Monitoring tools
//   - Legitimate system administration

DeviceLogonEvents
| where InitiatingProcessFolderPath endswith "\\WmiPrvSE.exe"