// Title: Defrag Deactivation
// Author: Florian Roth (Nextron Systems), Bartlomiej Czyz (@bczyz1)
// Date: 2019-03-04
// Level: medium
// Description: Detects the deactivation and disabling of the Scheduled defragmentation task as seen by Slingshot APT group
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.execution, attack.persistence, attack.t1053.005, attack.s0111, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2018/TA/Slingshot/proc_creation_win_apt_slingshot.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "/delete" or ProcessCommandLine contains "/change") and (ProcessCommandLine contains "/TN" and ProcessCommandLine contains "\\Microsoft\\Windows\\Defrag\\ScheduledDefrag") and FolderPath endswith "\\schtasks.exe"