// Title: Pandemic Registry Key
// Author: Florian Roth (Nextron Systems)
// Date: 2017-06-01
// Level: critical
// Description: Detects Pandemic Windows Implant
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1105, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2017/TA/Pandemic/registry_event_apt_pandemic.yml

DeviceRegistryEvents
| where RegistryKey contains "\\SYSTEM\\CurrentControlSet\\services\\null\\Instance"