// Author: Timur Zinniatullin, E.M. Anhaus, oscd.community
// Date: 2019/10/21
// Level: low
// Description: Detects usage of "rar" to add files to an archive for potential compression. An adversary may compress data (e.g. sensitive documents) that is collected prior to exfiltration in order to make it portable and minimize the amount of data sent over the network.
// Tags: attack.collection, attack.t1560.001
DeviceProcessEvents
| where ProcessCommandLine contains " a " and FolderPath endswith "\\rar.exe"