// Author: @ROxPinTeddy
// Date: 2020/05/12
// Level: high
// Description: Detects the use of rar.exe, on the command line, to create an archive with password protection or with a specific compression level. This is pretty indicative of malicious actions.
// Tags: attack.collection, attack.t1560.001
DeviceProcessEvents
| where ProcessCommandLine contains " -hp" and (ProcessCommandLine contains " -m" or ProcessCommandLine contains " a ")