// Author: TropChaud
// Date: 2022/12/19
// Level: high
// Description: Detect usage of the "sqlite" binary to query databases in Chromium-based browsers for potential data stealing.
// Tags: attack.credential_access, attack.t1539, attack.t1555.003, attack.collection, attack.t1005
DeviceProcessEvents
| where (ProcessCommandLine contains "\\User Data\\" or ProcessCommandLine contains "\\Opera Software\\" or ProcessCommandLine contains "\\ChromiumViewer\\") and (ProcessCommandLine contains "Login Data" or ProcessCommandLine contains "Cookies" or ProcessCommandLine contains "Web Data" or ProcessCommandLine contains "History" or ProcessCommandLine contains "Bookmarks") and (ProcessVersionInfoProductName =~ "SQLite" or (FolderPath endswith "\\sqlite.exe" or FolderPath endswith "\\sqlite3.exe"))