// Author: Florian Roth (Nextron Systems), Tigzy
// Date: 2021/11/17
// Level: medium
// Description: Detects a suspicious winrar execution in a folder which is not the default installation folder
// Tags: attack.collection, attack.t1560.001
DeviceProcessEvents
| where ((FolderPath endswith "\\rar.exe" or FolderPath endswith "\\winrar.exe") or ProcessVersionInfoFileDescription =~ "Command line RAR") and (not(((FolderPath contains ":\\Program Files (x86)\\WinRAR\\" or FolderPath contains ":\\Program Files\\WinRAR\\") or FolderPath endswith "\\UnRAR.exe"))) and (not(FolderPath contains ":\\Windows\\Temp\\"))