// Author: frack113
// Date: 2021/07/20
// Level: medium
// Description: Use living off the land tools to zip a file and stage it in the Windows temporary folder for later exfiltration
// Tags: attack.collection, attack.t1074.001
DeviceProcessEvents
| where ProcessCommandLine contains "Compress-Archive " and ProcessCommandLine contains " -Path " and ProcessCommandLine contains " -DestinationPath " and ProcessCommandLine contains "$env:TEMP\\"