// Title: Headless Process Launched Via Conhost.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-07-23
// Level: medium
// Description: Detects the launch of a child process via "conhost.exe" with the "--headless" flag.
// The "--headless" flag hides the windows from the user upon execution.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1059.001, attack.t1059.003, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_conhost_headless_execution.yml

DeviceProcessEvents
| where InitiatingProcessCommandLine contains "--headless" and InitiatingProcessFolderPath endswith "\\conhost.exe"