// Title: Suspicious New Instance Of An Office COM Object
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-13
// Level: medium
// Description: Detects an svchost process spawning an instance of an office application. This happens when the initial word application creates an instance of one of the Office COM objects such as 'Word.Application', 'Excel.Application', etc.
// This can be used by malicious actors to create malicious Office documents with macros on the fly. (See vba2clr project in the references)
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_office_svchost_parent.yml
// False Positives:
//   - Legitimate usage of office automation via scripting

DeviceProcessEvents
| where (FolderPath endswith "\\eqnedt32.exe" or FolderPath endswith "\\excel.exe" or FolderPath endswith "\\msaccess.exe" or FolderPath endswith "\\mspub.exe" or FolderPath endswith "\\powerpnt.exe" or FolderPath endswith "\\visio.exe" or FolderPath endswith "\\winword.exe") and InitiatingProcessFolderPath endswith "\\svchost.exe"