// Title: CMD Shell Output Redirect
// Author: frack113
// Date: 2022-01-22
// Level: low
// Description: Detects the use of the redirection character ">" to redirect information on the command line.
// This technique is sometimes used by malicious actors in order to redirect the output of reconnaissance commands such as "hostname" and "dir" to files for future exfiltration.
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1082, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_cmd_redirect.yml
// False Positives:
//   - Internet Download Manager extensions use named pipes and redirection via CLI. Filter it out if you use it in your environment

DeviceProcessEvents
| where (ProcessCommandLine contains ">" and (ProcessVersionInfoOriginalFileName =~ "Cmd.Exe" or FolderPath endswith "\\cmd.exe")) and (not((ProcessCommandLine contains "C:\\Program Files (x86)\\Internet Download Manager\\IDMMsgHost.exe" or ProcessCommandLine contains "chrome-extension://" or ProcessCommandLine contains "\\.\\pipe\\chrome.nativeMessaging")))