// Title: Import New Module Via PowerShell CommandLine
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-09
// Level: low
// Description: Detects usage of the "Import-Module" cmdlet in order to add new Cmdlets to the current PowerShell session
// MITRE Tactic: Execution
// Tags: attack.execution, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_powershell_import_module.yml
// False Positives:
//   - Depending on the environement, many legitimate scripts will import modules inline. This rule is targeted for hunting purposes.

DeviceProcessEvents
| where ((ProcessCommandLine contains "Import-Module " or ProcessCommandLine contains "ipmo ") and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")))) and (not(((ProcessCommandLine contains ":\\Program Files\\Microsoft Visual Studio\\" and ProcessCommandLine contains "Tools\\Microsoft.VisualStudio.DevShell.dll") and (InitiatingProcessFolderPath contains ":\\Program Files\\WindowsApps\\Microsoft.WindowsTerminal_" or InitiatingProcessFolderPath contains ":\\Windows\\System32\\cmd.exe"))))