// Title: Potential Password Reconnaissance Via Findstr.EXE
// Author: Josh Nickels
// Date: 2023-05-18
// Level: medium
// Description: Detects command line usage of "findstr" to search for the "passwords" keyword in a variety of different languages
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1552.001, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_findstr_password_recon.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "contraseña" or ProcessCommandLine contains "hasło" or ProcessCommandLine contains "heslo" or ProcessCommandLine contains "parola" or ProcessCommandLine contains "passe" or ProcessCommandLine contains "passw" or ProcessCommandLine contains "senha" or ProcessCommandLine contains "senord" or ProcessCommandLine contains "密碼") and (FolderPath endswith "\\findstr.exe" or ProcessVersionInfoOriginalFileName =~ "FINDSTR.EXE")