// Title: Diskshadow Script Mode Execution
// Author: Ivan Dyachkov, oscd.community
// Date: 2020-10-07
// Level: medium
// Description: Detects execution of "Diskshadow.exe" in script mode using the "/s" flag. Attackers often abuse "diskshadow" to execute scripts that deleted the shadow copies on the systems. Investigate the content of the scripts and its location.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218, attack.execution, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_diskshadow_script_mode.yml
// False Positives:
//   - Likely from legitimate backup scripts

DeviceProcessEvents
| where (ProcessCommandLine contains "-s " or ProcessCommandLine contains "/s " or ProcessCommandLine contains "–s " or ProcessCommandLine contains "—s " or ProcessCommandLine contains "―s ") and (ProcessVersionInfoOriginalFileName =~ "diskshadow.exe" or FolderPath endswith "\\diskshadow.exe")