// Title: New Self Extracting Package Created Via IExpress.EXE
// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2024-02-05
// Level: medium
// Description: Detects the "iexpress.exe" utility creating self-extracting packages.
// Attackers where seen leveraging "iexpress" to compile packages on the fly via ".sed" files.
// Investigate the command line options provided to "iexpress" and in case of a ".sed" file, check the contents and legitimacy of it.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_iexpress_execution.yml
// False Positives:
//   - Administrators building packages using iexpress.exe

DeviceProcessEvents
| where ((FolderPath endswith "\\makecab.exe" or ProcessVersionInfoOriginalFileName =~ "makecab.exe") and InitiatingProcessFolderPath endswith "\\iexpress.exe") or (ProcessCommandLine contains " /n " and (FolderPath endswith "\\iexpress.exe" or ProcessVersionInfoOriginalFileName =~ "IEXPRESS.exe"))