// Title: File Download Via Curl.EXE
// Author: Florian Roth (Nextron Systems)
// Date: 2022-07-05
// Level: medium
// Description: Detects file download using curl.exe
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1105, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_curl_download.yml
// False Positives:
//   - Scripts created by developers and admins
//   - Administrative activity
//   - The "\Git\usr\bin\sh.exe" process uses the "--output" flag to download a specific file in the temp directory with the pattern "gfw-httpget-xxxxxxxx.txt "

DeviceProcessEvents
| where (FolderPath endswith "\\curl.exe" or ProcessVersionInfoProductName =~ "The curl executable") and (ProcessCommandLine contains " -O" or ProcessCommandLine contains "--remote-name" or ProcessCommandLine contains "--output")