// Title: Potential File Override/Append Via SET Command
// Author: Nasreddine Bencherchali (Nextron Systems), MahirAli Khan (in/mahiralikhan)
// Date: 2024-08-22
// Level: low
// Description: Detects the use of the "SET" internal command of Cmd.EXE with the /p flag followed directly by an "=" sign.
// Attackers used this technique along with an append redirection operator ">>" in order to update the content of a file indirectly.
// Ex: cmd /c >> example.txt set /p="test data". This will append "test data" to contents of "example.txt".
// The typical use case of the "set /p=" command is to prompt the user for input.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_cmd_set_prompt_abuse.yml
// False Positives:
//   - Legitimate use of the SET with the "/p" flag for user prompting. command in administrative scripts or user-generated scripts.

DeviceProcessEvents
| where (ProcessCommandLine contains "/c set /p=" or ProcessCommandLine contains "\"set /p=" or (ProcessCommandLine contains ">>" and ProcessCommandLine contains "set /p=")) and (FolderPath endswith "\\cmd.exe" or ProcessVersionInfoOriginalFileName =~ "Cmd.Exe")