// Title: Potential Proxy Execution Via Explorer.EXE From Shell Process
// Author: Furkan CALISKAN, @caliskanfurkan_, @oscd_initiative
// Date: 2020-10-05
// Level: low
// Description: Detects the creation of a child "explorer.exe" process from a shell like process such as "cmd.exe" or "powershell.exe".
// Attackers can use "explorer.exe" for evading defense mechanisms by proxying the execution through the latter.
// While this is often a legitimate action, this rule can be use to hunt for anomalies.
// Muddy Waters threat actor was seeing using this technique.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_explorer_child_of_shell_process.yml
// False Positives:
//   - Legitimate explorer.exe run from a shell host like "cmd.exe" or "powershell.exe"

DeviceProcessEvents
| where ProcessCommandLine contains "explorer.exe" and FolderPath endswith "\\explorer.exe" and (InitiatingProcessFolderPath endswith "\\cmd.exe" or InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe")