// Title: Scheduled Task Creation From Potential Suspicious Parent Location
// Author: Florian Roth (Nextron Systems)
// Date: 2022-02-23
// Level: medium
// Description: Detects the execution of "schtasks.exe" from a parent that is located in a potentially suspicious location.
// Multiple malware strains were seen exhibiting a similar behavior in order to achieve persistence.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.persistence, attack.privilege-escalation, attack.t1053.005, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_schtasks_creation_from_susp_parent.yml
// False Positives:
//   - Software installers that run from temporary folders and also install scheduled tasks

DeviceProcessEvents
| where (ProcessCommandLine contains "/Create " and FolderPath endswith "\\schtasks.exe" and (InitiatingProcessFolderPath contains ":\\Temp\\" or InitiatingProcessFolderPath contains "\\AppData\\Local\\" or InitiatingProcessFolderPath contains "\\AppData\\Roaming\\" or InitiatingProcessFolderPath contains "\\Temporary Internet" or InitiatingProcessFolderPath contains "\\Users\\Public\\" or InitiatingProcessFolderPath contains "\\Windows\\Temp\\")) and (not((ProcessCommandLine contains "update_task.xml" or ProcessCommandLine contains "unattended.ini")))