// Title: Microsoft Workflow Compiler Execution
// Author: Nik Seetharaman, frack113
// Date: 2019-01-16
// Level: medium
// Description: Detects the execution of Microsoft Workflow Compiler, which may permit the execution of arbitrary unsigned code.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.execution, attack.t1127, attack.t1218, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_microsoft_workflow_compiler_execution.yml
// False Positives:
//   - Legitimate MWC use (unlikely in modern enterprise environments)

DeviceProcessEvents
| where FolderPath endswith "\\Microsoft.Workflow.Compiler.exe" or ProcessVersionInfoOriginalFileName =~ "Microsoft.Workflow.Compiler.exe"