// Title: Suspicious Tasklist Discovery Command
// Author: frack113
// Date: 2021-12-11
// Level: informational
// Description: Adversaries may attempt to get information about running processes on a system. Information obtained could be used to gain an understanding of common software/applications running on systems within the network
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1057, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_tasklist_basic_execution.yml
// False Positives:
//   - Likely from users, administrator and different internal and third party applications.

DeviceProcessEvents
| where ProcessCommandLine contains "tasklist" or FolderPath endswith "\\tasklist.exe" or ProcessVersionInfoOriginalFileName =~ "tasklist.exe"