// Title: SC.EXE Query Execution
// Author: frack113
// Date: 2021-12-06
// Level: low
// Description: Detects execution of "sc.exe" to query information about registered services on the system
// MITRE Tactic: Discovery
// Tags: attack.discovery, attack.t1007, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_sc_query.yml
// False Positives:
//   - Legitimate query of a service by an administrator to get more information such as the state or PID
//   - Keybase process "kbfsdokan.exe" query the dokan1 service with the following commandline "sc query dokan1"

DeviceProcessEvents
| where (ProcessCommandLine contains " query" and (FolderPath endswith "\\sc.exe" and ProcessVersionInfoOriginalFileName =~ "sc.exe")) and (not(ProcessCommandLine =~ "sc query dokan1"))