// Title: Execution From Webserver Root Folder
// Author: Florian Roth (Nextron Systems)
// Date: 2019-01-16
// Level: medium
// Description: Detects a program executing from a web server root folder. Use this rule to hunt for potential interesting activity such as webshell or backdoors
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1505.003, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_susp_execution_path_webserver.yml
// False Positives:
//   - Various applications
//   - Tools that include ping or nslookup command invocations

DeviceProcessEvents
| where (FolderPath contains "\\wwwroot\\" or FolderPath contains "\\wmpub\\" or FolderPath contains "\\htdocs\\") and (not(((FolderPath contains "bin\\" or FolderPath contains "\\Tools\\" or FolderPath contains "\\SMSComponent\\") and InitiatingProcessFolderPath endswith "\\services.exe")))