// Title: Password Protected Compressed File Extraction Via 7Zip
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-03-10
// Level: low
// Description: Detects usage of 7zip utilities (7z.exe, 7za.exe and 7zr.exe) to extract password protected zip files.
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1560.001, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_7zip_password_extraction.yml
// False Positives:
//   - Legitimate activity is expected since extracting files with a password can be common in some environment.

DeviceProcessEvents
| where (ProcessVersionInfoFileDescription contains "7-Zip" or (FolderPath endswith "\\7z.exe" or FolderPath endswith "\\7zr.exe" or FolderPath endswith "\\7za.exe") or (ProcessVersionInfoOriginalFileName in~ ("7z.exe", "7za.exe"))) and (ProcessCommandLine contains " -p" and ProcessCommandLine contains " x " and ProcessCommandLine contains " -o")