// Title: Tunneling Tool Execution
// Author: Daniil Yugoslavskiy, oscd.community
// Date: 2019-10-24
// Level: medium
// Description: Detects the execution of well known tools that can be abused for data exfiltration and tunneling.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.command-and-control, attack.t1041, attack.t1572, attack.t1071.001, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_susp_exfil_and_tunneling_tool_execution.yml
// False Positives:
//   - Legitimate administrators using one of these tools

DeviceProcessEvents
| where FolderPath endswith "\\httptunnel.exe" or FolderPath endswith "\\plink.exe" or FolderPath endswith "\\socat.exe" or FolderPath endswith "\\stunnel.exe"