// Title: EventLog Query Requests By Builtin Utilities
// Author: Ali Alwashali, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-11-20
// Level: medium
// Description: Detect attempts to query the contents of the event log using command line utilities. Attackers use this technique in order to look for sensitive information in the logs such as passwords, usernames, IPs, etc.
// MITRE Tactic: Credential Access
// Tags: attack.t1552, attack.credential-access, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_susp_event_log_query.yml
// False Positives:
//   - Legitimate log access by administrators or troubleshooting tools

DeviceProcessEvents
| where (ProcessCommandLine contains "Select" and ProcessCommandLine contains "Win32_NTLogEvent") or ((ProcessCommandLine contains " qe " or ProcessCommandLine contains " query-events ") and (FolderPath endswith "\\wevtutil.exe" or ProcessVersionInfoOriginalFileName =~ "wevtutil.exe")) or (ProcessCommandLine contains " ntevent" and (FolderPath endswith "\\wmic.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")) or (ProcessCommandLine contains "Get-WinEvent " or ProcessCommandLine contains "get-eventlog ")