// Title: New Windows Firewall Rule Added Via New-NetFirewallRule Cmdlet
// Author: frack113
// Date: 2024-05-03
// Level: low
// Description: Detects calls to the "New-NetFirewallRule" cmdlet from PowerShell in order to add a new firewall rule with an "Allow" action.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.004, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_powershell_new_netfirewallrule_allow.yml
// False Positives:
//   - Administrator script

DeviceProcessEvents
| where (ProcessCommandLine contains "New-NetFirewallRule " and ProcessCommandLine contains " -Action " and ProcessCommandLine contains "allow") and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\powershell_ise.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")))