// Title: Process Execution From WebDAV Share
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-06-13
// Level: low
// Description: Detects execution of processes with image paths starting with WebDAV shares (\\), which might indicate malicious file execution from remote web shares.
// Execution of processes from WebDAV shares can be a sign of lateral movement or exploitation attempts, especially if the process is not a known legitimate application.
// Exploitation Attempt of vulnerabilities like CVE-2025-33053 also involves executing processes from WebDAV paths.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.command-and-control, attack.lateral-movement, attack.t1105, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_webdav_process_execution.yml
// False Positives:
//   - Legitimate use of WebDAV shares for process execution
//   - Known applications executing from WebDAV paths

DeviceProcessEvents
| where FolderPath contains "\\DavWWWRoot\\" and FolderPath startswith "\\\\"