// Title: CodePage Modification Via MODE.COM
// Author: Nasreddine Bencherchali (Nextron Systems), Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2024-01-19
// Level: low
// Description: Detects a CodePage modification using the "mode.com" utility.
// This behavior has been used by threat actors behind Dharma ransomware.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_mode_codepage_change.yml

DeviceProcessEvents
| where (ProcessCommandLine contains " con " and ProcessCommandLine contains " cp " and ProcessCommandLine contains " select=") and (FolderPath endswith "\\mode.com" or ProcessVersionInfoOriginalFileName =~ "MODE.COM")