// Title: Curl.EXE Execution With Custom UserAgent
// Author: frack113
// Date: 2022-01-23
// Level: medium
// Description: Detects execution of curl.exe with custom useragent options
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1071.001, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_curl_useragent.yml
// False Positives:
//   - Scripts created by developers and admins
//   - Administrative activity

DeviceProcessEvents
| where (FolderPath endswith "\\curl.exe" or ProcessVersionInfoProductName =~ "The curl executable") and (ProcessCommandLine contains " -A " or ProcessCommandLine contains " --user-agent ")