// Title: Potential CommandLine Obfuscation Using Unicode Characters
// Author: frack113, Florian Roth (Nextron Systems)
// Date: 2022-01-15
// Level: medium
// Description: Detects potential CommandLine obfuscation using unicode characters.
// Adversaries may attempt to make an executable or file difficult to discover or analyze by encrypting, encoding, or otherwise obfuscating its contents on the system or in transit.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_susp_cli_obfuscation_unicode.yml

DeviceProcessEvents
| where ProcessCommandLine contains "ˣ" or ProcessCommandLine contains "˪" or ProcessCommandLine contains "ˢ" or ProcessCommandLine contains "∕" or ProcessCommandLine contains "⁄" or ProcessCommandLine contains "―" or ProcessCommandLine contains "—" or ProcessCommandLine contains " " or ProcessCommandLine contains "¯" or ProcessCommandLine contains "®" or ProcessCommandLine contains "¶"