// Title: Potential Suspicious Execution From GUID Like Folder Names
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-01
// Level: low
// Description: Detects potential suspicious execution of a GUID like folder name located in a suspicious location such as %TEMP% as seen being used in IcedID attacks.
// Use this rule to hunt for potentially suspicious activity stemming from uncommon folders.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_susp_execution_from_guid_folder_names.yml
// False Positives:
//   - Installers are sometimes known for creating temporary folders with GUID like names. Add appropriate filters accordingly

DeviceProcessEvents
| where ((ProcessCommandLine contains "\\AppData\\Roaming\\" or ProcessCommandLine contains "\\AppData\\Local\\Temp\\") and (ProcessCommandLine contains "\\{" and ProcessCommandLine contains "}\\")) and (not((FolderPath =~ "C:\\Windows\\System32\\drvinst.exe" or (FolderPath contains "\\{" and FolderPath contains "}\\") or (FolderPath in~ ("C:\\Windows\\System32\\msiexec.exe", "C:\\Windows\\SysWOW64\\msiexec.exe")) or isnull(FolderPath))))