// Title: HTML File Opened From Download Folder
// Author: Joseph Kamau
// Date: 2025-12-05
// Level: low
// Description: Detects web browser process opening an HTML file from a user's Downloads folder.
// This behavior is could be associated with phishing attacks where threat actors send HTML attachments to users.
// When a user opens such an attachment, it can lead to the execution of malicious scripts or the download of malware.
// During investigation, analyze the HTML file for embedded scripts or links, check for any subsequent downloads or process executions, and investigate the source of the email or message containing the attachment.
// MITRE Tactic: Initial Access
// Tags: attack.t1598.002, attack.t1566.001, attack.initial-access, attack.reconnaissance, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_susp_open_html_file_from_download_folder.yml
// False Positives:
//   - Opening any HTML file located in users directories via a browser process will trigger this.

DeviceProcessEvents
| where (ProcessCommandLine contains ":\\users\\" and ProcessCommandLine contains "\\Downloads\\" and ProcessCommandLine contains ".htm") and (FolderPath endswith "\\brave.exe" or FolderPath endswith "\\chrome.exe" or FolderPath endswith "\\firefox.exe" or FolderPath endswith "\\msedge.exe" or FolderPath endswith "\\opera.exe" or FolderPath endswith "\\vivaldi.exe")