// Title: Remote Access Tool - Action1 Arbitrary Code Execution and Remote Sessions
// Author: @kostastsale
// Date: 2023-04-13
// Level: medium
// Description: Detects the execution of Action1 in order to execute arbitrary code or establish a remote session.
// Action1 is a powerful Remote Monitoring and Management tool that enables users to execute commands, scripts, and binaries.
// Through the web interface of action1, the administrator must create a new policy or an app to establish remote execution and then points that the agent is installed.
// Hunting Opportunity 1- Weed Out The Noise
// When threat actors execute a script, a command, or a binary through these new policies and apps, the names of these become visible in the command line during the execution process. Below is an example of the command line that contains the deployment of a binary through  a policy with name "test_app_1":
// ParentCommandLine: "C:\WINDOWS\Action1\action1_agent.exe schedule:Deploy_App__test_app_1_1681327673425 runaction:0"
// After establishing a baseline, we can split the command to extract the policy name and group all the policy names and inspect the results with a list of frequency occurrences.
// Hunting Opportunity 2 - Remote Sessions On Out Of Office Hours
// If you have admins within your environment using remote sessions to administer endpoints, you can create a threat-hunting query and modify the time of the initiated sessions looking for abnormal activity.
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1219.002, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_remote_access_tools_action1_code_exec_and_remote_sessions.yml
// False Positives:
//   - If Action1 is among the approved software in your environment, you might find that this is a noisy query. See description for ideas on how to alter this query and start looking for suspicious activities.

DeviceProcessEvents
| where (FolderPath contains "\\Windows\\Action1\\package_downloads\\" and InitiatingProcessFolderPath endswith "\\action1_agent.exe") or ((InitiatingProcessCommandLine contains "\\Action1\\scripts\\Run_Command_" or InitiatingProcessCommandLine contains "\\Action1\\scripts\\Run_PowerShell_") and (InitiatingProcessFolderPath endswith "\\cmd.exe" or InitiatingProcessFolderPath endswith "\\powershell.exe")) or FolderPath endswith "\\agent1_remote.exe"