// Title: Dynamic .NET Compilation Via Csc.EXE - Hunting
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-02
// Level: medium
// Description: Detects execution of "csc.exe" to compile .NET code. Attackers often leverage this to compile code on the fly and use it in other stages.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027.004, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_csc_compilation.yml
// False Positives:
//   - Many legitimate applications make use of dynamic compilation. Use this rule to hunt for anomalies

DeviceProcessEvents
| where ProcessCommandLine contains "/noconfig /fullpaths @" and FolderPath endswith "\\csc.exe"