// Title: Potential DLL Sideloading Activity Via ExtExport.EXE
// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2021-11-26
// Level: medium
// Description: Detects the execution of "Extexport.exe".A utility that is part of the Internet Explorer browser and is used to export and import various settings and data, particularly when switching between Internet Explorer and other web browsers like Firefox. It allows users to transfer bookmarks, browsing history, and other preferences from Internet Explorer to Firefox or vice versa.
// It can be abused as a tool to side load any DLL. If a folder is provided in the command line it'll load any DLL with one of the following names "mozcrt19.dll", "mozsqlite3.dll", or "sqlite.dll".
// Arbitrary DLLs can also be loaded if a specific number of flags was provided.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_extexport_execution.yml

DeviceProcessEvents
| where FolderPath endswith "\\Extexport.exe" or ProcessVersionInfoOriginalFileName =~ "extexport.exe"