// Title: DLL Call by Ordinal Via Rundll32.EXE
// Author: Florian Roth (Nextron Systems)
// Date: 2019-10-22
// Level: medium
// Description: Detects calls of DLLs exports by ordinal numbers via rundll32.dll.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.011, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_rundll32_by_ordinal.yml
// False Positives:
//   - False positives depend on scripts and administrative tools used in the monitored environment.
//   - Windows control panel elements have been identified as source (mmc).

DeviceProcessEvents
| where ((ProcessCommandLine contains ",#" or ProcessCommandLine contains ", #" or ProcessCommandLine contains ".dll #" or ProcessCommandLine contains ".ocx #") and (FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE")) and (not(((ProcessCommandLine contains "EDGEHTML.dll" and ProcessCommandLine contains "#141") or ((ProcessCommandLine contains "\\FileTracker32.dll,#1" or ProcessCommandLine contains "\\FileTracker32.dll\",#1" or ProcessCommandLine contains "\\FileTracker64.dll,#1" or ProcessCommandLine contains "\\FileTracker64.dll\",#1") and (InitiatingProcessFolderPath contains "\\Msbuild\\Current\\Bin\\" or InitiatingProcessFolderPath contains "\\VC\\Tools\\MSVC\\" or InitiatingProcessFolderPath contains "\\Tracker.exe")))))