// Title: SMB over QUIC Via Net.EXE
// Author: frack113
// Date: 2023-07-21
// Level: medium
// Description: Detects the mounting of Windows SMB shares over QUIC, which can be an unexpected event in some enterprise environments.
// MITRE Tactic: Lateral Movement
// Tags: attack.lateral-movement, attack.t1570, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_net_quic.yml
// False Positives:
//   - Administrative activity

DeviceProcessEvents
| where ProcessCommandLine contains "/TRANSPORT:QUIC" and ((FolderPath endswith "\\net.exe" or FolderPath endswith "\\net1.exe") or (ProcessVersionInfoOriginalFileName in~ ("net.exe", "net1.exe")))