// Title: Curl.EXE Execution
// Author: Florian Roth (Nextron Systems)
// Date: 2022-07-05
// Level: low
// Description: Detects a curl process start on Windows, which could indicates a file download from a remote location or a simple web request to a remote server
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1105, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_curl_execution.yml
// False Positives:
//   - Scripts created by developers and admins
//   - Administrative activity

DeviceProcessEvents
| where FolderPath endswith "\\curl.exe" or ProcessVersionInfoProductName =~ "The curl executable"