// Title: Winscp Execution From Non Standard Folder
// Author: frack113
// Date: 2025-10-12
// Level: medium
// Description: Detects the execution of Winscp from an a non standard folder. This could indicate the execution of Winscp portable.
// MITRE Tactic: Exfiltration
// Tags: attack.exfiltration, attack.t1048, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_winscp_portable_execution.yml

DeviceProcessEvents
| where (FolderPath endswith "\\WinSCP.exe" or ProcessVersionInfoOriginalFileName =~ "winscp.exe") and (not(FolderPath startswith "C:\\Program Files (x86)\\WinSCP\\"))