// Title: ClickOnce Deployment Execution - Dfsvc.EXE Child Process
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-12
// Level: medium
// Description: Detects child processes of "dfsvc" which indicates a ClickOnce deployment execution.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/process_creation/proc_creation_win_dfsvc_child_processes.yml
// False Positives:
//   - False positives are expected in environement leveraging ClickOnce deployments. An initial baselining is required before using this rule in production.

DeviceProcessEvents
| where FolderPath endswith "\\AppData\\Local\\Apps\\2.0\\" and InitiatingProcessFolderPath endswith "\\dfsvc.exe"