// Title: AMSI Disabled via Registry Modification
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-12-25
// Level: high
// Description: Detects attempts to disable AMSI (Anti-Malware Scan Interface) by modifying the AmsiEnable registry value.
// Anti-Malware Scan Interface (AMSI) is a security feature in Windows that allows applications and services to integrate with anti-malware products for enhanced protection against malicious content.
// Adversaries may attempt to disable AMSI to evade detection by security software, allowing them to execute malicious scripts or code without being scanned.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001, attack.t1562.006
// False Positives:
//   - Unlikely

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey endswith "\\Software\\Microsoft\\Windows Script\\Settings\\AmsiEnable"