// Title: Disabled Windows Defender Eventlog
// Author: Florian Roth (Nextron Systems)
// Date: 2022-07-04
// Level: high
// Description: Detects the disabling of the Windows Defender eventlog as seen in relation to Lockbit 3.0 infections
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_disabled_microsoft_defender_eventlog.yml
// False Positives:
//   - Other Antivirus software installations could cause Windows to disable that eventlog (unknown)

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey contains "\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\Microsoft-Windows-Windows Defender/Operational\\Enabled"