// Title: Winlogon AllowMultipleTSSessions Enable
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-09-09
// Level: medium
// Description: Detects when the 'AllowMultipleTSSessions' value is enabled.
// Which allows for multiple Remote Desktop connection sessions to be opened at once.
// This is often used by attacker as a way to connect to an RDP session without disconnecting the other users
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_winlogon_allow_multiple_tssessions.yml
// False Positives:
//   - Legitimate use of the multi session functionality

DeviceRegistryEvents
| where RegistryValueData endswith "DWORD (0x00000001)" and RegistryKey endswith "\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\AllowMultipleTSSessions"