// Title: Scripted Diagnostics Turn Off Check Enabled - Registry
// Author: Christopher Peacock @securepeacock, SCYTHE @scythe_io
// Date: 2022-06-15
// Level: medium
// Description: Detects enabling TurnOffCheck which can be used to bypass defense of MSDT Follina vulnerability
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_enabling_turnoffcheck.yml
// False Positives:
//   - Administrator actions

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000001)" and RegistryKey endswith "\\Policies\\Microsoft\\Windows\\ScriptedDiagnostics\\TurnOffCheck"