// Title: Potential Persistence Via Scrobj.dll COM Hijacking
// Author: frack113
// Date: 2022-08-20
// Level: medium
// Description: Detect use of scrobj.dll as this DLL looks for the ScriptletURL key to get the location of the script to execute
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1546.015
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_persistence_scrobj_dll.yml
// False Positives:
//   - Legitimate use of the dll.

DeviceRegistryEvents
| where RegistryValueData =~ "C:\\WINDOWS\\system32\\scrobj.dll" and RegistryKey endswith "InprocServer32\\(Default)"