// Title: Outlook Security Settings Updated - Registry
// Author: frack113
// Date: 2021-12-28
// Level: medium
// Description: Detects changes to the registry values related to outlook security settings
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1137
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_office_outlook_security_settings.yml
// False Positives:
//   - Administrative activity

DeviceRegistryEvents
| where RegistryKey endswith "\\SOFTWARE\\Microsoft\\Office*" and RegistryKey endswith "\\Outlook\\Security*"