// Title: Potential Persistence Via Shim Database In Uncommon Location
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-01
// Level: high
// Description: Detects the installation of a new shim database where the file is located in a non-default location
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1546.011
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_persistence_shim_database_uncommon_location.yml

DeviceRegistryEvents
| where (RegistryKey endswith "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\AppCompatFlags\\InstalledSDB*" and RegistryKey contains "\\DatabasePath") and (not(RegistryValueData contains ":\\Windows\\AppPatch\\Custom"))