// Title: Periodic Backup For System Registry Hives Enabled
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-07-01
// Level: medium
// Description: Detects the enabling of the "EnablePeriodicBackup" registry value. Once enabled, The OS will backup System registry hives on restarts to the "C:\Windows\System32\config\RegBack" folder. Windows creates a "RegIdleBackup" task to manage subsequent backups.
// Registry backup was a default behavior on Windows and was disabled as of "Windows 10, version 1803".
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1113
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_enable_periodic_backup.yml
// False Positives:
//   - Legitimate need for RegBack feature by administrators.

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000001)" and RegistryKey endswith "\\Control\\Session Manager\\Configuration Manager\\EnablePeriodicBackup"