// Title: Potential Persistence Via CHM Helper DLL
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-21
// Level: high
// Description: Detects when an attacker modifies the registry key "HtmlHelp Author" to achieve persistence
// MITRE Tactic: Persistence
// Tags: attack.persistence
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_persistence_chm.yml

DeviceRegistryEvents
| where RegistryKey contains "\\Software\\Microsoft\\HtmlHelp Author\\Location" or RegistryKey contains "\\Software\\WOW6432Node\\Microsoft\\HtmlHelp Author\\Location"