// Title: Registry Modification to Hidden File Extension
// Author: frack113
// Date: 2022-01-22
// Level: medium
// Description: Hides the file extension through modification of the registry
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1137
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_hidden_extention.yml
// False Positives:
//   - Administrative scripts

DeviceRegistryEvents
| where (RegistryValueData =~ "DWORD (0x00000002)" and RegistryKey endswith "\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\\Hidden") or (RegistryValueData =~ "DWORD (0x00000001)" and RegistryKey endswith "\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\\HideFileExt")