// Title: Office Macros Warning Disabled
// Author: Trent Liffick (@tliffick), Nasreddine Bencherchali (Nextron Systems)
// Date: 2020-05-22
// Level: high
// Description: Detects registry changes to Microsoft Office "VBAWarning" to a value of "1" which enables the execution of all macros, whether signed or unsigned.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_office_vba_warnings_tamper.yml
// False Positives:
//   - Unlikely

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000001)" and RegistryKey endswith "\\Security\\VBAWarnings"