// Title: Suspicious Space Characters in TypedPaths Registry Path - FileFix
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-11-04
// Level: high
// Description: Detects the occurrence of numerous space characters in TypedPaths registry paths, which may indicate execution via phishing lures using file-fix techniques to hide malicious commands.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1204.004, attack.defense-evasion, attack.t1027.010
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_susp_typedpaths_space_characters.yml
// False Positives:
//   - Unlikely

DeviceRegistryEvents
| where (RegistryValueData contains "#" and RegistryKey endswith "\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\TypedPaths\\url1") and (RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            ")