// Title: Potential Persistence Via Mpnotify
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-21
// Level: high
// Description: Detects when an attacker register a new SIP provider for persistence and defense evasion
// MITRE Tactic: Persistence
// Tags: attack.persistence
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_persistence_mpnotify.yml
// False Positives:
//   - Might trigger if a legitimate new SIP provider is registered. But this is not a common occurrence in an environment and should be investigated either way

DeviceRegistryEvents
| where RegistryKey contains "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\mpnotify"