// Title: Potential Persistence Via MyComputer Registry Keys
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-09
// Level: high
// Description: Detects modification to the "Default" value of the "MyComputer" key and subkeys to point to a custom binary that will be launched whenever the associated action is executed (see reference section for example)
// MITRE Tactic: Persistence
// Tags: attack.persistence
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_persistence_mycomputer.yml
// False Positives:
//   - Unlikely but if you experience FPs add specific processes and locations you would like to monitor for

DeviceRegistryEvents
| where RegistryKey contains "\\Microsoft\\Windows\\CurrentVersion\\Explorer\\MyComputer" and RegistryKey endswith "(Default)"