// Title: ETW Logging Disabled In .NET Processes - Sysmon Registry
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2020-06-05
// Level: high
// Description: Potential adversaries stopping ETW providers recording loaded .NET assemblies.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112, attack.t1562
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_dot_net_etw_tamper.yml

DeviceRegistryEvents
| where ((RegistryValueData in~ ("0", "DWORD (0x00000000)")) and (RegistryKey endswith "\\COMPlus_ETWEnabled" or RegistryKey endswith "\\COMPlus_ETWFlags")) or (RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey endswith "SOFTWARE\\Microsoft\\.NETFramework\\ETWEnabled")