// Title: Potential Persistence Via Excel Add-in - Registry
// Author: frack113
// Date: 2023-01-15
// Level: high
// Description: Detect potential persistence via the creation of an excel add-in (XLL) file to make it run automatically when Excel is started.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1137.006
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_persistence_xll.yml

DeviceRegistryEvents
| where RegistryValueData endswith ".xll" and RegistryValueData startswith "/R " and RegistryKey endswith "Software\\Microsoft\\Office*" and RegistryKey endswith "\\Excel\\Options"