// Title: Persistence Via Hhctrl.ocx
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-21
// Level: high
// Description: Detects when an attacker modifies the registry value of the "hhctrl" to point to a custom binary
// MITRE Tactic: Persistence
// Tags: attack.persistence
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_hhctrl_persistence.yml
// False Positives:
//   - Unlikely

DeviceRegistryEvents
| where RegistryKey contains "\\CLSID\\{52A2AAAE-085D-4187-97EA-8C30DB990436}\\InprocServer32\\(Default)" and (not(RegistryValueData =~ "C:\\Windows\\System32\\hhctrl.ocx"))