// Title: Security Event Logging Disabled via MiniNt Registry Key - Registry Set
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-04-09
// Level: high
// Description: Detects the addition of the 'MiniNt' key to the registry. Upon a reboot, Windows Event Log service will stop writing events.
// Windows Event Log is a service that collects and stores event logs from the operating system and applications. It is an important component of Windows security and auditing.
// Adversary may want to disable this service to disable logging of security events which could be used to detect their activities.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1562.002, attack.t1112, car.2022-03-001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_create_minint_key.yml
// False Positives:
//   - Highly Unlikely

DeviceRegistryEvents
| where RegistryKey =~ "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet001\\Control\\MiniNt\\(Default)"