// Title: Outlook Macro Execution Without Warning Setting Enabled
// Author: @ScoubiMtl
// Date: 2021-04-05
// Level: high
// Description: Detects the modification of Outlook security setting to allow unprompted execution of macros.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.command-and-control, attack.t1137, attack.t1008, attack.t1546
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_office_outlook_enable_macro_execution.yml
// False Positives:
//   - Unlikely

DeviceRegistryEvents
| where RegistryValueData contains "0x00000001" and RegistryKey endswith "\\Outlook\\Security\\Level"