// Title: Hide Schedule Task Via Index Value Tamper
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-26
// Level: high
// Description: Detects when the "index" value of a scheduled task is modified from the registry
// Which effectively hides it from any tooling such as "schtasks /query" (Read the referenced link for more information about the effects of this technique)
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_hide_scheduled_task_via_index_tamper.yml
// False Positives:
//   - Unlikely

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and (RegistryKey endswith "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tree*" and RegistryKey contains "Index")