// Title: CrashControl CrashDump Disabled
// Author: Tobias Michalski (Nextron Systems)
// Date: 2022-02-24
// Level: medium
// Description: Detects disabling the CrashDump per registry (as used by HermeticWiper)
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1564, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_crashdump_disabled.yml
// False Positives:
//   - Legitimate disabling of crashdumps

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey contains "SYSTEM\\CurrentControlSet\\Control\\CrashControl"