// Title: Potential PendingFileRenameOperations Tampering
// Author: frack113
// Date: 2023-01-27
// Level: medium
// Description: Detect changes to the "PendingFileRenameOperations" registry key from uncommon or suspicious images locations to stage currently used files for rename or deletion after reboot.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_susp_pendingfilerenameoperations.yml
// False Positives:
//   - Installers and updaters may set currently in use files for rename or deletion after a reboot.

DeviceRegistryEvents
| where RegistryKey contains "\\CurrentControlSet\\Control\\Session Manager\\PendingFileRenameOperations" and ((InitiatingProcessFolderPath endswith "\\reg.exe" or InitiatingProcessFolderPath endswith "\\regedit.exe") or InitiatingProcessFolderPath contains "\\Users\\Public\\")