// Title: Disable Macro Runtime Scan Scope
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-10-25
// Level: high
// Description: Detects tampering with the MacroRuntimeScanScope registry key to disable runtime scanning of enabled macros
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_disable_macroruntimescanscope.yml

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and (RegistryKey endswith "\\SOFTWARE*" and RegistryKey endswith "\\Microsoft\\Office*" and RegistryKey contains "\\Common\\Security") and RegistryKey endswith "\\MacroRuntimeScanScope"