// Title: Disable Windows Security Center Notifications
// Author: frack113
// Date: 2022-08-19
// Level: medium
// Description: Detect set UseActionCenterExperience to 0 to disable the Windows security center notification
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_disable_security_center_notifications.yml

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey endswith "Windows\\CurrentVersion\\ImmersiveShell\\UseActionCenterExperience"