// Title: Potential Persistence Via Custom Protocol Handler
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-05-30
// Level: medium
// Description: Detects potential persistence activity via the registering of a new custom protocole handlers. While legitimate applications register protocole handlers often times during installation. And attacker can abuse this by setting a custom handler to be used as a persistence mechanism.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_persistence_custom_protocol_handler.yml
// False Positives:
//   - Many legitimate applications can register a new custom protocol handler. Additional filters needs to applied according to your environment.

DeviceRegistryEvents
| where (RegistryValueData startswith "URL:" and RegistryKey =~ "HKEY_LOCAL_MACHINE\\CLASSES*") and (not(((InitiatingProcessFolderPath startswith "C:\\Program Files (x86)" or InitiatingProcessFolderPath startswith "C:\\Program Files\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\System32\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\SysWOW64\\") or RegistryValueData startswith "URL:ms-")))