// Title: Suspicious Printer Driver Empty Manufacturer
// Author: Florian Roth (Nextron Systems)
// Date: 2020-07-01
// Level: high
// Description: Detects a suspicious printer driver installation with an empty Manufacturer value
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.privilege-escalation, attack.t1574, cve.2021-1675
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_susp_printer_driver.yml
// False Positives:
//   - Alerts on legitimate printer drivers that do not set any more details in the Manufacturer value

DeviceRegistryEvents
| where (RegistryValueData =~ "(Empty)" and (RegistryKey contains "\\Control\\Print\\Environments\\Windows x64\\Drivers" and RegistryKey contains "\\Manufacturer")) and (not((RegistryKey endswith "\\CutePDF Writer v4.0*" or RegistryKey endswith "\\Version-3\\PDF24*" or (RegistryKey endswith "\\VNC Printer (PS)*" or RegistryKey endswith "\\VNC Printer (UD)*"))))