// Title: Enable LM Hash Storage
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-12-15
// Level: high
// Description: Detects changes to the "NoLMHash" registry value in order to allow Windows to store LM Hashes.
// By setting this registry value to "0" (DWORD), Windows will be allowed to store a LAN manager hash of your password in Active Directory and local SAM databases.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_system_lsa_nolmhash.yml

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey endswith "System\\CurrentControlSet\\Control\\Lsa\\NoLMHash"