// Title: Windows Recall Feature Enabled - Registry
// Author: Sajid Nawaz Khan
// Date: 2024-06-02
// Level: medium
// Description: Detects the enabling of the Windows Recall feature via registry manipulation. Windows Recall can be enabled by setting the value of "DisableAIDataAnalysis" to "0".
// Adversaries may enable Windows Recall as part of post-exploitation discovery and collection activities.
// This rule assumes that Recall is already explicitly disabled on the host, and subsequently enabled by the adversary.
// MITRE Tactic: Collection
// Tags: attack.collection, attack.t1113
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_enable_windows_recall.yml
// False Positives:
//   - Legitimate use/activation of Windows Recall

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey endswith "\\Software\\Policies\\Microsoft\\Windows\\WindowsAI\\DisableAIDataAnalysis"