// Title: PowerShell as a Service in Registry
// Author: oscd.community, Natalia Shornikova
// Date: 2020-10-06
// Level: high
// Description: Detects that a powershell code is written to the registry as a service.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1569.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_powershell_as_service.yml

DeviceRegistryEvents
| where (RegistryValueData contains "powershell" or RegistryValueData contains "pwsh") and RegistryKey endswith "\\Services*" and RegistryKey endswith "\\ImagePath"