// Title: Potential Persistence Via Outlook Home Page
// Author: Tobias Michalski (Nextron Systems), David Bertho (@dbertho) & Eirik Sveen (@0xSV1), Storebrand
// Date: 2021-06-09
// Level: high
// Description: Detects potential persistence activity via outlook home page.
// An attacker can set a home page to achieve code execution and persistence by editing the WebView registry keys.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.persistence, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_persistence_outlook_homepage.yml

DeviceRegistryEvents
| where (RegistryKey endswith "\\Software\\Microsoft\\Office*" and RegistryKey endswith "\\Outlook\\WebView*") and RegistryKey endswith "\\URL"