// Title: Bypass UAC Using SilentCleanup Task
// Author: frack113, Nextron Systems
// Date: 2022-01-06
// Level: high
// Description: Detects the setting of the environement variable "windir" to a non default value.
// Attackers often abuse this variable in order to trigger a UAC bypass via the "SilentCleanup" task.
// The SilentCleanup task located in %windir%\system32\cleanmgr.exe is an auto-elevated task that can be abused to elevate any file with administrator privileges without prompting UAC.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.defense-evasion, attack.t1548.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_bypass_uac_using_silentcleanup_task.yml

DeviceRegistryEvents
| where RegistryKey endswith "\\Environment\\windir" and (not(RegistryValueData =~ "%SystemRoot%"))