// Title: PUA - Sysinternals Tools Execution - Registry
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-24
// Level: medium
// Description: Detects the execution of some potentially unwanted tools such as PsExec, Procdump, etc. (part of the Sysinternals suite) via the creation of the "accepteula" registry key.
// MITRE Tactic: Resource Development
// Tags: attack.resource-development, attack.t1588.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_pua_sysinternals_susp_execution_via_eula.yml
// False Positives:
//   - Legitimate use of SysInternals tools. Filter the legitimate paths used in your environment

DeviceRegistryEvents
| where (RegistryKey contains "\\Active Directory Explorer" or RegistryKey contains "\\Handle" or RegistryKey contains "\\LiveKd" or RegistryKey contains "\\Process Explorer" or RegistryKey contains "\\ProcDump" or RegistryKey contains "\\PsExec" or RegistryKey contains "\\PsLoglist" or RegistryKey contains "\\PsPasswd" or RegistryKey contains "\\SDelete" or RegistryKey contains "\\Sysinternals") and RegistryKey endswith "\\EulaAccepted"