// Title: ETW Logging Disabled For rpcrt4.dll
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-09
// Level: low
// Description: Detects changes to the "ExtErrorInformation" key in order to disable ETW logging for rpcrt4.dll
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112, attack.t1562
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_rpcrt4_etw_tamper.yml

DeviceRegistryEvents
| where (RegistryValueData in~ ("DWORD (0x00000000)", "DWORD (0x00000002)")) and RegistryKey endswith "\\Microsoft\\Windows NT\\Rpc\\ExtErrorInformation"