// Title: Sysmon Driver Altitude Change
// Author: B.Talebi
// Date: 2022-07-28
// Level: high
// Description: Detects changes in Sysmon driver altitude value.
// If the Sysmon driver is configured to load at an altitude of another registered service, it will fail to load at boot.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_change_sysmon_driver_altitude.yml
// False Positives:
//   - Legitimate driver altitude change to hide sysmon

DeviceRegistryEvents
| where RegistryKey endswith "\\Services*" and RegistryKey endswith "\\Instances\\Sysmon Instance\\Altitude"