// Title: Macro Enabled In A Potentially Suspicious Document
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-06-21
// Level: high
// Description: Detects registry changes to Office trust records where the path is located in a potentially suspicious location
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_office_trust_record_susp_location.yml
// False Positives:
//   - Unlikely

DeviceRegistryEvents
| where (RegistryKey contains "/AppData/Local/Microsoft/Windows/INetCache/" or RegistryKey contains "/AppData/Local/Temp/" or RegistryKey contains "/PerfLogs/" or RegistryKey contains "C:/Users/Public/" or RegistryKey contains "file:///D:/" or RegistryKey contains "file:///E:/") and RegistryKey contains "\\Security\\Trusted Documents\\TrustRecords"