// Title: Suspicious Space Characters in RunMRU Registry Path - ClickFix
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-11-04
// Level: high
// Description: Detects the occurrence of numerous space characters in RunMRU registry paths, which may indicate execution via phishing lures using clickfix techniques to hide malicious commands in the Windows Run dialog box from naked eyes.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1204.004, attack.defense-evasion, attack.t1027.010
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_susp_runmru_space_character.yml
// False Positives:
//   - Unlikely

DeviceRegistryEvents
| where (RegistryValueData contains "#" and RegistryKey endswith "\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RunMRU*") and (RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            " or RegistryValueData contains "            ")