// Title: RDP Sensitive Settings Changed to Zero
// Author: Samir Bousseaden, David ANDRE, Roberto Rodriguez @Cyb3rWard0g, Nasreddine Bencherchali
// Date: 2022-09-29
// Level: medium
// Description: Detects tampering of RDP Terminal Service/Server sensitive settings.
// Such as allowing unauthorized users access to a system via the 'fAllowUnsolicited' or enabling RDP via 'fDenyTSConnections', etc.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.persistence, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_terminal_server_suspicious.yml
// False Positives:
//   - Some of the keys mentioned here could be modified by an administrator while setting group policy (it should be investigated either way)

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and (RegistryKey endswith "\\fDenyTSConnections" or RegistryKey endswith "\\fSingleSessionPerUser" or RegistryKey endswith "\\UserAuthentication")