// Title: IE Change Domain Zone
// Author: frack113
// Date: 2022-01-22
// Level: medium
// Description: Hides the file extension through modification of the registry
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.t1137
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_change_security_zones.yml
// False Positives:
//   - Administrative scripts

DeviceRegistryEvents
| where RegistryKey endswith "\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ZoneMap\\Domains*" and (not((RegistryValueData in~ ("DWORD (0x00000000)", "DWORD (0x00000001)", "(Empty)"))))