// Title: New BgInfo.EXE Custom VBScript Registry Configuration
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-16
// Level: medium
// Description: Detects setting of a new registry value related to BgInfo configuration, which can be abused to execute custom VBScript via "BgInfo.exe"
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_bginfo_custom_vbscript.yml
// False Positives:
//   - Legitimate VBScript

DeviceRegistryEvents
| where RegistryValueData startswith "4" and RegistryKey endswith "\\Software\\Winternals\\BGInfo\\UserFields*"