// Title: Potential EventLog File Location Tampering
// Author: D3F7A5105
// Date: 2023-01-02
// Level: high
// Description: Detects tampering with EventLog service "file" key. In order to change the default location of an Evtx file. This technique is used to tamper with log collection and alerting
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_evtx_file_key_tamper.yml

DeviceRegistryEvents
| where (RegistryKey endswith "\\SYSTEM\\CurrentControlSet\\Services\\EventLog*" and RegistryKey endswith "\\File") and (not(RegistryValueData contains "\\System32\\Winevt\\Logs\\"))