// Title: Potential WerFault ReflectDebugger Registry Value Abuse
// Author: X__Junior
// Date: 2023-05-18
// Level: high
// Description: Detects potential WerFault "ReflectDebugger" registry value abuse for persistence.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1036.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_persistence_reflectdebugger.yml

DeviceRegistryEvents
| where RegistryKey endswith "\\Microsoft\\Windows\\Windows Error Reporting\\Hangs\\ReflectDebugger"