// Title: Potential Persistence Via AutodialDLL
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-10
// Level: high
// Description: Detects change the the "AutodialDLL" key which could be used as a persistence method to load custom DLL via the "ws2_32" library
// MITRE Tactic: Persistence
// Tags: attack.persistence
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_persistence_autodial_dll.yml
// False Positives:
//   - Unlikely

DeviceRegistryEvents
| where RegistryKey contains "\\Services\\WinSock2\\Parameters\\AutodialDLL"