// Title: ScreenSaver Registry Key Set
// Author: Jose Luis Sanchez Martinez (@Joseliyo_Jstnk)
// Date: 2022-05-04
// Level: medium
// Description: Detects registry key established after masqueraded .scr file execution using Rundll32 through desk.cpl
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.011
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_scr_file_executed_by_rundll32.yml
// False Positives:
//   - Legitimate use of screen saver

DeviceRegistryEvents
| where InitiatingProcessFolderPath endswith "\\rundll32.exe" and (RegistryValueData endswith ".scr" and RegistryKey contains "\\Control Panel\\Desktop\\SCRNSAVE.EXE") and (not((RegistryValueData contains "C:\\Windows\\System32\\" or RegistryValueData contains "C:\\Windows\\SysWOW64\\")))