// Title: Change Winevt Channel Access Permission Via Registry
// Author: frack113
// Date: 2022-09-17
// Level: high
// Description: Detects tampering with the "ChannelAccess" registry key in order to change access to Windows event channel.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_change_winevt_channelaccess.yml

DeviceRegistryEvents
| where ((RegistryValueData contains "(A;;0x1;;;LA)" or RegistryValueData contains "(A;;0x1;;;SY)" or RegistryValueData contains "(A;;0x5;;;BA)") and RegistryKey endswith "\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels*" and RegistryKey endswith "\\ChannelAccess") and (not(((InitiatingProcessFolderPath endswith "\\TiWorker.exe" and InitiatingProcessFolderPath startswith "C:\\Windows\\WinSxS\\") or InitiatingProcessFolderPath =~ "C:\\Windows\\servicing\\TrustedInstaller.exe")))