// Title: Potential Persistence Via LSA Extensions
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-21
// Level: high
// Description: Detects when an attacker modifies the "REG_MULTI_SZ" value named "Extensions" to include a custom DLL to achieve persistence via lsass.
// The "Extensions" list contains filenames of DLLs being automatically loaded by lsass.exe. Each DLL has its InitializeLsaExtension() method called after loading.
// MITRE Tactic: Persistence
// Tags: attack.persistence
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_persistence_lsa_extension.yml
// False Positives:
//   - Unlikely

DeviceRegistryEvents
| where RegistryKey contains "\\SYSTEM\\CurrentControlSet\\Control\\LsaExtensionConfig\\LsaSrv\\Extensions"