// Title: Disable Privacy Settings Experience in Registry
// Author: frack113
// Date: 2022-10-02
// Level: medium
// Description: Detects registry modifications that disable Privacy Settings Experience
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_disable_privacy_settings_experience.yml
// False Positives:
//   - Legitimate admin script

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey endswith "\\SOFTWARE\\Policies\\Microsoft\\Windows\\OOBE\\DisablePrivacyExperience"