// Title: Activate Suppression of Windows Security Center Notifications
// Author: frack113
// Date: 2022-08-19
// Level: medium
// Description: Detect set Notification_Suppress to 1 to disable the Windows security center notification
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_suppress_defender_notifications.yml

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000001)" and RegistryKey endswith "SOFTWARE\\Policies\\Microsoft\\Windows Defender\\UX Configuration\\Notification_Suppress"