// Title: Directory Service Restore Mode(DSRM) Registry Value Tampering
// Author: Nischal Khadgi
// Date: 2024-07-11
// Level: high
// Description: Detects changes to "DsrmAdminLogonBehavior" registry value.
// During a Domain Controller (DC) promotion, administrators create a Directory Services Restore Mode (DSRM) local administrator account with a password that rarely changes. The DSRM account is an “Administrator” account that logs in with the DSRM mode when the server is booting up to restore AD backups or recover the server from a failure.
// Attackers could abuse DSRM account to maintain their persistence and access to the organization's Active Directory.
// If the "DsrmAdminLogonBehavior" value is set to "0", the administrator account can only be used if the DC starts in DSRM.
// If the "DsrmAdminLogonBehavior" value is set to "1", the administrator account can only be used if the local AD DS service is stopped.
// If the "DsrmAdminLogonBehavior" value is set to "2", the administrator account can always be used.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.credential-access, attack.persistence, attack.t1556
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_dsrm_tampering.yml

DeviceRegistryEvents
| where RegistryKey endswith "\\Control\\Lsa\\DsrmAdminLogonBehavior" and (not(RegistryValueData =~ "DWORD (0x00000000)"))