// Title: New DNS ServerLevelPluginDll Installed
// Author: Florian Roth (Nextron Systems)
// Date: 2017-05-08
// Level: high
// Description: Detects the installation of a DNS plugin DLL via ServerLevelPluginDll parameter in registry, which can be used to execute code in context of the DNS server (restart required)
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.defense-evasion, attack.t1574.001, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_dns_server_level_plugin_dll.yml

DeviceRegistryEvents
| where RegistryKey endswith "\\services\\DNS\\Parameters\\ServerLevelPluginDll"