// Title: Disable Windows Firewall by Registry
// Author: frack113
// Date: 2022-08-19
// Level: medium
// Description: Detect set EnableFirewall to 0 to disable the Windows firewall
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.004
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_disable_windows_firewall.yml

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and (RegistryKey endswith "\\SOFTWARE\\Policies\\Microsoft\\WindowsFirewall\\StandardProfile\\EnableFirewall" or RegistryKey endswith "\\SOFTWARE\\Policies\\Microsoft\\WindowsFirewall\\DomainProfile\\EnableFirewall")