// Title: NET NGenAssemblyUsageLog Registry Key Tamper
// Author: frack113
// Date: 2022-11-18
// Level: high
// Description: Detects changes to the NGenAssemblyUsageLog registry key.
// .NET Usage Log output location can be controlled by setting the NGenAssemblyUsageLog CLR configuration knob in the Registry or by configuring an environment variable (as described in the next section).
// By simplify specifying an arbitrary value (e.g. fake output location or junk data) for the expected value, a Usage Log file for the .NET execution context will not be created.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_net_cli_ngenassemblyusagelog.yml

DeviceRegistryEvents
| where RegistryKey endswith "SOFTWARE\\Microsoft\\.NETFramework\\NGenAssemblyUsageLog"