// Title: Antivirus Filter Driver Disallowed On Dev Drive - Registry
// Author: @kostastsale, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-11-05
// Level: high
// Description: Detects activity that indicates a user disabling the ability for Antivirus mini filter to inspect a "Dev Drive".
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_devdrv_disallow_antivirus_filter.yml
// False Positives:
//   - Unlikely

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey endswith "\\FilterManager\\FltmgrDevDriveAllowAntivirusFilter"