// Title: PUA - Sysinternal Tool Execution - Registry
// Author: Markus Neis
// Date: 2017-08-28
// Level: low
// Description: Detects the execution of a Sysinternals Tool via the creation of the "accepteula" registry key
// MITRE Tactic: Resource Development
// Tags: attack.resource-development, attack.t1588.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_pua_sysinternals_execution_via_eula.yml
// False Positives:
//   - Legitimate use of SysInternals tools
//   - Programs that use the same Registry Key

DeviceRegistryEvents
| where RegistryKey endswith "\\EulaAccepted"