// Title: New File Association Using Exefile
// Author: Andreas Hunkeler (@Karneades)
// Date: 2021-11-19
// Level: high
// Description: Detects the abuse of the exefile handler in new file association. Used for bypass of security products.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_file_association_exefile.yml

DeviceRegistryEvents
| where RegistryValueData =~ "exefile" and RegistryKey contains "Classes\\."