// Title: Persistence Via New SIP Provider
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-21
// Level: medium
// Description: Detects when an attacker register a new SIP provider for persistence and defense evasion
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1553.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_sip_persistence.yml
// False Positives:
//   - Legitimate SIP being registered by the OS or different software.

DeviceRegistryEvents
| where ((RegistryKey contains "\\Dll" or RegistryKey contains "\\$DLL") and (RegistryKey endswith "\\SOFTWARE\\Microsoft\\Cryptography\\Providers*" or RegistryKey contains "\\SOFTWARE\\Microsoft\\Cryptography\\OID\\EncodingType" or RegistryKey endswith "\\SOFTWARE\\WOW6432Node\\Microsoft\\Cryptography\\Providers*" or RegistryKey contains "\\SOFTWARE\\WOW6432Node\\Microsoft\\Cryptography\\OID\\EncodingType")) and (not(((RegistryValueData in~ ("WINTRUST.DLL", "mso.dll")) or (RegistryValueData =~ "C:\\Windows\\System32\\PsfSip.dll" and InitiatingProcessFolderPath =~ "C:\\Windows\\System32\\poqexec.exe" and RegistryKey contains "\\CryptSIPDll"))))