// Title: ETW Logging Disabled For SCM
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-09
// Level: low
// Description: Detects changes to the "TracingDisabled" key in order to disable ETW logging for services.exe (SCM)
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112, attack.t1562
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_services_etw_tamper.yml

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000001)" and RegistryKey endswith "Software\\Microsoft\\Windows NT\\CurrentVersion\\Tracing\\SCM\\Regular\\TracingDisabled"