// Title: Allow RDP Remote Assistance Feature
// Author: frack113
// Date: 2022-08-19
// Level: medium
// Description: Detect enable rdp feature to allow specific user to rdp connect on the targeted machine
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_allow_rdp_remote_assistance_feature.yml
// False Positives:
//   - Legitimate use of the feature (alerts should be investigated either way)

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000001)" and RegistryKey endswith "System\\CurrentControlSet\\Control\\Terminal Server\\fAllowToGetHelp"