// Title: New BgInfo.EXE Custom DB Path Registry Configuration
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-08-16
// Level: medium
// Description: Detects setting of a new registry database value related to BgInfo configuration. Attackers can for example set this value to save the results of the commands executed by BgInfo in order to exfiltrate information.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_bginfo_custom_db.yml
// False Positives:
//   - Legitimate use of external DB to save the results

DeviceRegistryEvents
| where RegistryKey endswith "\\Software\\Winternals\\BGInfo\\Database"