// Title: Python Function Execution Security Warning Disabled In Excel - Registry
// Author: Nasreddine Bencherchali (Nextron Systems), @Kostastsale
// Date: 2024-08-23
// Level: high
// Description: Detects changes to the registry value "PythonFunctionWarnings" that would prevent any warnings or alerts from showing when Python functions are about to be executed.
// Threat actors could run malicious code through the new Microsoft Excel feature that allows Python to run within the spreadsheet.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_office_disable_python_security_warnings.yml

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000001)" and RegistryKey endswith "\\Microsoft\\Office*" and RegistryKey endswith "\\Excel\\Security\\PythonFunctionWarnings"