// Title: Windows Defender Service Disabled - Registry
// Author: Ján Trenčanský, frack113, AlertIQ, Nasreddine Bencherchali
// Date: 2022-08-01
// Level: high
// Description: Detects when an attacker or tool disables the  Windows Defender service (WinDefend) via the registry
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_disable_windows_defender_service.yml
// False Positives:
//   - Administrator actions

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000004)" and RegistryKey endswith "\\Services\\WinDefend\\Start"