// Title: Suspicious Keyboard Layout Load
// Author: Florian Roth (Nextron Systems)
// Date: 2019-10-12
// Level: medium
// Description: Detects the keyboard preload installation with a suspicious keyboard layout, e.g. Chinese, Iranian or Vietnamese layout load in user session on systems maintained by US staff only
// MITRE Tactic: Resource Development
// Tags: attack.resource-development, attack.t1588.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_susp_keyboard_layout_load.yml
// False Positives:
//   - Administrators or users that actually use the selected keyboard layouts (heavily depends on the organisation's user base)

DeviceRegistryEvents
| where (RegistryValueData contains "00000429" or RegistryValueData contains "00050429" or RegistryValueData contains "0000042a") and (RegistryKey endswith "\\Keyboard Layout\\Preload*" or RegistryKey endswith "\\Keyboard Layout\\Substitutes*")