// Title: Custom File Open Handler Executes PowerShell
// Author: CD_R0M_
// Date: 2022-06-11
// Level: high
// Description: Detects the abuse of custom file open handler, executing powershell
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1202
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_custom_file_open_handler_powershell_execution.yml

DeviceRegistryEvents
| where (RegistryValueData contains "powershell" and RegistryValueData contains "-command") and RegistryKey endswith "shell\\open\\command*"