// Title: Hiding User Account Via SpecialAccounts Registry Key
// Author: Nasreddine Bencherchali (Nextron Systems), frack113
// Date: 2022-07-12
// Level: high
// Description: Detects modifications to the registry key "HKLM\Software\Microsoft\Windows NT\CurrentVersion\Winlogon\SpecialAccounts\Userlist" where the value is set to "0" in order to hide user account from being listed on the logon screen.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1564.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_special_accounts.yml

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey contains "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\SpecialAccounts\\UserList"