// Title: Windows Defender Exclusions Added - Registry
// Author: Christian Burkard (Nextron Systems)
// Date: 2021-07-06
// Level: medium
// Description: Detects the Setting of Windows Defender Exclusions
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_defender_exclusions.yml
// False Positives:
//   - Administrator actions

DeviceRegistryEvents
| where RegistryKey contains "\\Microsoft\\Windows Defender\\Exclusions"