// Title: Add Debugger Entry To AeDebug For Persistence
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-21
// Level: medium
// Description: Detects when an attacker adds a new "Debugger" value to the "AeDebug" key in order to achieve persistence which will get invoked when an application crashes
// MITRE Tactic: Persistence
// Tags: attack.persistence
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_aedebug_persistence.yml
// False Positives:
//   - Legitimate use of the key to setup a debugger. Which is often the case on developers machines

DeviceRegistryEvents
| where (RegistryValueData endswith ".dll" and RegistryKey contains "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\AeDebug\\Debugger") and (not(RegistryValueData =~ "\"C:\\WINDOWS\\system32\\vsjitdebugger.exe\" -p %ld -e %ld -j 0x%p"))