// Title: Potential Provisioning Registry Key Abuse For Binary Proxy Execution - REG
// Author: Swachchhanda Shrawan Poudel
// Date: 2023-08-02
// Level: high
// Description: Detects potential abuse of the provisioning registry key for indirect command execution through "Provlaunch.exe".
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_provisioning_command_abuse.yml

DeviceRegistryEvents
| where RegistryKey endswith "\\SOFTWARE\\Microsoft\\Provisioning\\Commands*"