// Title: Windows Vulnerable Driver Blocklist Disabled
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2026-01-26
// Level: high
// Description: Detects when the Windows Vulnerable Driver Blocklist is set to disabled. This setting is crucial for preventing the loading of known vulnerable drivers,
// and its modification may indicate an attempt to bypass security controls. It is often targeted by threat actors to facilitate the installation of malicious or vulnerable drivers,
// particularly in scenarios involving Endpoint Detection and Response (EDR) bypass techniques.
// This rule applies to systems that support the Vulnerable Driver Blocklist feature, including Windows 10 version 1903 and later, and Windows Server 2022 and later.
// Note that this change will require a reboot to take effect, and this rule only detects the registry modification action.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// False Positives:
//   - Unlikely and should be investigated immediately.

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey endswith "\\Control\\CI\\Config\\VulnerableDriverBlocklistEnable"