// Title: Leviathan Registry Key Activity
// Author: Aidan Bracher
// Date: 2020-07-07
// Level: critical
// Description: Detects registry key used by Leviathan APT in Malaysian focused campaign
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547.001, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2020/TA/Leviathan/registry_event_apt_leviathan.yml

DeviceRegistryEvents
| where RegistryKey contains "\\Software\\Microsoft\\Windows\\CurrentVersion\\Run\\ntkd"