// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/12/04
// Level: medium
// Description: Detects the execution of "whoami.exe" with the "/all" flag
// Tags: attack.discovery, attack.t1033, car.2016-03-001
DeviceProcessEvents
| where (ProcessCommandLine contains " -all" or ProcessCommandLine contains " /all") and (FolderPath endswith "\\whoami.exe" or ProcessVersionInfoOriginalFileName =~ "whoami.exe")