// Author: Andreas Hunkeler (@Karneades), oscd.community
// Date: 2020/04/20
// Level: medium
// Description: Detect the harvesting of wifi credentials using netsh.exe
// Tags: attack.discovery, attack.credential_access, attack.t1040
DeviceProcessEvents
| where (ProcessCommandLine contains "wlan" and ProcessCommandLine contains " s" and ProcessCommandLine contains " p" and ProcessCommandLine contains " k" and ProcessCommandLine contains "=clear") and (FolderPath endswith "\\netsh.exe" or ProcessVersionInfoOriginalFileName =~ "netsh.exe")