// Author: Florian Roth (Nextron Systems)
// Date: 2022/08/03
// Level: medium
// Description: Detects use of an encoded/obfuscated version of an IP address (hex, octal...) in an URL combined with a download command
// Tags: attack.discovery
DeviceProcessEvents
| where (ProcessCommandLine contains "Invoke-WebRequest" or ProcessCommandLine contains "iwr " or ProcessCommandLine contains "wget " or ProcessCommandLine contains "curl " or ProcessCommandLine contains "DownloadFile" or ProcessCommandLine contains "DownloadString") and ((ProcessCommandLine contains "//0x" or ProcessCommandLine contains ".0x" or ProcessCommandLine contains ".00x") or (ProcessCommandLine contains "http://%" and ProcessCommandLine contains "%2e"))