// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2021/12/18
// Level: medium
// Description: Detects the use of Advanced Port Scanner.
// Tags: attack.discovery, attack.t1046, attack.t1135
DeviceProcessEvents
| where (ProcessCommandLine contains "/portable" and ProcessCommandLine contains "/lng") or (FolderPath contains "\\advanced_port_scanner" or ProcessVersionInfoOriginalFileName contains "advanced_port_scanner" or ProcessVersionInfoFileDescription contains "Advanced Port Scanner")