// Author: @d4ns4n_ (Wuerth-Phoenix)
// Date: 2024/04/25
// Level: medium
// Description: Detects usage of SoftPerfect's "netscan.exe". An application for scanning networks.
It is actively used in-the-wild by threat actors to inspect and understand the network architecture of a victim.

// Tags: attack.discovery, attack.t1046
DeviceProcessEvents
| where FolderPath endswith "\\netscan.exe" or ProcessVersionInfoProductName =~ "Network Scanner" or ProcessVersionInfoFileDescription =~ "Application for scanning networks"