// Author: Nasreddine Bencherchali (Nextron Systems), @ROxPinTeddy
// Date: 2020/05/12
// Level: medium
// Description: Detects the use of Advanced IP Scanner. Seems to be a popular tool for ransomware groups.
// Tags: attack.discovery, attack.t1046, attack.t1135
DeviceProcessEvents
| where (ProcessCommandLine contains "/portable" and ProcessCommandLine contains "/lng") or (FolderPath contains "\\advanced_ip_scanner" or ProcessVersionInfoOriginalFileName contains "advanced_ip_scanner" or ProcessVersionInfoFileDescription contains "Advanced IP Scanner")