// Author: frack113, Christopher Peacock '@securepeacock', SCYTHE '@scythe_io'
// Date: 2021/12/07
// Level: low
// Description: Adversaries may look for details about the network configuration and settings of systems they access or through information discovery of remote systems
// Tags: attack.discovery, attack.t1016
DeviceProcessEvents
| where ProcessCommandLine contains "ipconfig /all" or ProcessCommandLine contains "netsh interface show interface" or ProcessCommandLine contains "arp -a" or ProcessCommandLine contains "nbtstat -n" or ProcessCommandLine contains "net config" or ProcessCommandLine contains "route print"