// Author: Florian Roth (Nextron Systems), Teymur Kheirkhabarov
// Date: 2022/01/28
// Level: high
// Description: Detects the execution of "whoami.exe" by privileged accounts that are often abused by threat actors
// Tags: attack.privilege_escalation, attack.discovery, attack.t1033
DeviceProcessEvents
| where (ProcessVersionInfoOriginalFileName =~ "whoami.exe" or FolderPath endswith "\\whoami.exe") and (AccountName contains "AUTHORI" or AccountName contains "AUTORI" or AccountName contains "TrustedInstaller")