// Author: Florian Roth (Nextron Systems)
// Date: 2021/08/12
// Level: medium
// Description: Detects the execution of whoami.exe with suspicious parent processes.
// Tags: attack.discovery, attack.t1033, car.2016-03-001
DeviceProcessEvents
| where (FolderPath endswith "\\whoami.exe" or ProcessVersionInfoOriginalFileName =~ "whoami.exe") and (not(((InitiatingProcessFolderPath endswith "\\cmd.exe" or InitiatingProcessFolderPath endswith "\\powershell_ise.exe" or InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe") or InitiatingProcessFolderPath =~ "" or isnull(InitiatingProcessFolderPath)))) and (not(InitiatingProcessFolderPath endswith ":\\Program Files\\Microsoft Monitoring Agent\\Agent\\MonitoringHost.exe"))