// Author: Oddvar Moe, Sander Wiebing, oscd.community
// Date: 2020/10/07
// Level: low
// Description: Detects the export of the target Registry key to a file.
// Tags: attack.exfiltration, attack.t1012
DeviceProcessEvents
| where ((ProcessCommandLine contains " /E " or ProcessCommandLine contains " -E ") and (FolderPath endswith "\\regedit.exe" or ProcessVersionInfoOriginalFileName =~ "REGEDIT.EXE")) and (not(((ProcessCommandLine contains "hklm" or ProcessCommandLine contains "hkey_local_machine") and (ProcessCommandLine endswith "\\system" or ProcessCommandLine endswith "\\sam" or ProcessCommandLine endswith "\\security"))))