// Author: Kamran Saifullah, Nasreddine Bencherchali (Nextron Systems)
// Date: 2024/05/27
// Level: medium
// Description: Detects network connections to Cloudflared tunnels domains initiated by a process on the system.
Attackers can abuse that feature to establish a reverse shell or persistence on a machine.

// Tags: attack.exfiltration, attack.command_and_control, attack.t1567.001
DeviceNetworkEvents
| where RemoteUrl endswith ".v2.argotunnel.com" or RemoteUrl endswith "protocol-v2.argotunnel.com" or RemoteUrl endswith "trycloudflare.com" or RemoteUrl endswith "update.argotunnel.com"