// Author: Florian Roth (Nextron Systems)
// Date: 2022/01/16
// Level: high
// Description: Detects a suspicious output redirection to the local admins share, this technique is often found in malicious scripts or hacktool stagers
// Tags: attack.exfiltration, attack.t1048
DeviceProcessEvents
| where ProcessCommandLine contains ">" and (ProcessCommandLine contains "\\\\127.0.0.1\\admin$\\" or ProcessCommandLine contains "\\\\localhost\\admin$\\")