// Title: Potential DLL Sideloading Of MpSvc.DLL
// Author: Nasreddine Bencherchali (Nextron Systems), Wietze Beukema
// Date: 2024-07-11
// Level: medium
// Description: Detects potential DLL sideloading of "MpSvc.dll".
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.defense-evasion, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_side_load_mpsvc.yml
// False Positives:
//   - Legitimate applications loading their own versions of the DLL mentioned in this rule.

DeviceImageLoadEvents
| where FolderPath endswith "\\MpSvc.dll" and (not((FolderPath startswith "C:\\Program Files\\Windows Defender\\" or FolderPath startswith "C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\" or FolderPath startswith "C:\\Windows\\WinSxS\\")))