// Title: Wmiprvse Wbemcomn DLL Hijack
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2020-10-12
// Level: high
// Description: Detects a threat actor creating a file named `wbemcomn.dll` in the `C:\Windows\System32\wbem\` directory over the network and loading it for a WMI DLL Hijack scenario.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1047, attack.lateral-movement, attack.t1021.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_wmiprvse_wbemcomn_dll_hijack.yml

DeviceImageLoadEvents
| where FolderPath endswith "\\wbem\\wbemcomn.dll" and InitiatingProcessFolderPath endswith "\\wmiprvse.exe"