// Title: UAC Bypass With Fake DLL
// Author: oscd.community, Dmitry Uchakin
// Date: 2020-10-06
// Level: high
// Description: Attempts to load dismcore.dll after dropping it
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.privilege-escalation, attack.t1548.002, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_uac_bypass_via_dism.yml
// False Positives:
//   - Actions of a legitimate telnet client

DeviceImageLoadEvents
| where (FolderPath endswith "\\dismcore.dll" and InitiatingProcessFolderPath endswith "\\dism.exe") and (not(FolderPath =~ "C:\\Windows\\System32\\Dism\\dismcore.dll"))