// Title: Python Image Load By Non-Python Process
// Author: Patrick St. John, OTR (Open Threat Research)
// Date: 2020-05-03
// Level: low
// Description: Detects the image load of "Python Core" by a non-Python process. This might be indicative of a execution of executable that has been bundled from Python code.
// Various tools like Py2Exe, PyInstaller, and cx_Freeze are used to bundle Python code into standalone executables.
// Threat actors often use these tools to bundle malicious Python scripts into executables, sometimes to obfuscate the code or to bypass security measures.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1027.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_susp_python_image_load.yml
// False Positives:
//   - Legitimate Py2Exe Binaries
//   - Known false positive caused with Python Anaconda
//   - Various legitimate software is bundled from Python code into executables

DeviceImageLoadEvents
| where InitiatingProcessVersionInfoFileDescription =~ "Python Core" and (not((InitiatingProcessFolderPath contains "Python" or (InitiatingProcessFolderPath startswith "C:\\Program Files\\" or InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\" or InitiatingProcessFolderPath startswith "C:\\ProgramData\\Anaconda3\\")))) and (not(isnull(InitiatingProcessFolderPath)))