// Title: WMI Persistence - Command Line Event Consumer
// Author: Thomas Patzke
// Date: 2018-03-07
// Level: high
// Description: Detects WMI command line event consumers
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.t1546.003, attack.persistence
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_wmi_persistence_commandline_event_consumer.yml
// False Positives:
//   - Unknown (data set is too small; further testing needed)

DeviceImageLoadEvents
| where InitiatingProcessFolderPath =~ "C:\\Windows\\System32\\wbem\\WmiPrvSE.exe" and FolderPath endswith "\\wbemcons.dll"