// Title: DLL Sideloading Of ShellChromeAPI.DLL
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-12-01
// Level: high
// Description: Detects processes loading the non-existent DLL "ShellChromeAPI". One known example is the "DeviceEnroller" binary in combination with the "PhoneDeepLink" flag tries to load this DLL.
// Adversaries can drop their own renamed DLL and execute it via DeviceEnroller.exe using this parameter
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.persistence, attack.privilege-escalation, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_side_load_shell_chrome_api.yml

DeviceImageLoadEvents
| where FolderPath endswith "\\ShellChromeAPI.dll"