// Title: Potential EACore.DLL Sideloading
// Author: X__Junior (Nextron Systems)
// Date: 2023-08-03
// Level: high
// Description: Detects potential DLL sideloading of "EACore.dll"
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.privilege-escalation, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_side_load_eacore.yml
// False Positives:
//   - Unlikely

DeviceImageLoadEvents
| where FolderPath endswith "\\EACore.dll" and (not((FolderPath startswith "C:\\Program Files\\Electronic Arts\\EA Desktop\\" and (InitiatingProcessFolderPath contains "C:\\Program Files\\Electronic Arts\\EA Desktop\\" and InitiatingProcessFolderPath contains "\\EACoreServer.exe"))))