// Title: Potential DLL Sideloading Of Libcurl.DLL Via GUP.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-05
// Level: medium
// Description: Detects potential DLL sideloading of "libcurl.dll" by the "gup.exe" process from an uncommon location
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.persistence, attack.privilege-escalation, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_side_load_gup_libcurl.yml

DeviceImageLoadEvents
| where (FolderPath endswith "\\libcurl.dll" and InitiatingProcessFolderPath endswith "\\gup.exe") and (not(InitiatingProcessFolderPath endswith "\\Notepad++\\updater\\GUP.exe"))