// Title: Potential Rcdll.DLL Sideloading
// Author: X__Junior (Nextron Systems)
// Date: 2023-03-13
// Level: high
// Description: Detects potential DLL sideloading of rcdll.dll
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.privilege-escalation, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_side_load_rcdll.yml

DeviceImageLoadEvents
| where FolderPath endswith "\\rcdll.dll" and (not((FolderPath startswith "C:\\Program Files (x86)\\Microsoft Visual Studio\\" or FolderPath startswith "C:\\Program Files (x86)\\Windows Kits\\")))