// Title: Potential SolidPDFCreator.DLL Sideloading
// Author: X__Junior (Nextron Systems)
// Date: 2023-05-07
// Level: medium
// Description: Detects potential DLL sideloading of "SolidPDFCreator.dll"
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.privilege-escalation, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_side_load_solidpdfcreator.yml

DeviceImageLoadEvents
| where FolderPath endswith "\\SolidPDFCreator.dll" and (not(((FolderPath startswith "C:\\Program Files (x86)\\SolidDocuments\\SolidPDFCreator\\" or FolderPath startswith "C:\\Program Files\\SolidDocuments\\SolidPDFCreator\\") and InitiatingProcessFolderPath endswith "\\SolidPDFCreator.exe")))