// Title: Potential Vivaldi_elf.DLL Sideloading
// Author: X__Junior (Nextron Systems)
// Date: 2023-08-03
// Level: medium
// Description: Detects potential DLL sideloading of "vivaldi_elf.dll"
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.privilege-escalation, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_side_load_vivaldi_elf.yml

DeviceImageLoadEvents
| where FolderPath endswith "\\vivaldi_elf.dll" and (not((FolderPath contains "\\Vivaldi\\Application\\" and InitiatingProcessFolderPath endswith "\\Vivaldi\\Application\\vivaldi.exe")))