// Title: Microsoft Office DLL Sideload
// Author: Nasreddine Bencherchali (Nextron Systems), Wietze Beukema (project and research)
// Date: 2022-08-17
// Level: high
// Description: Detects DLL sideloading of DLLs that are part of Microsoft Office from non standard location
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.persistence, attack.privilege-escalation, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_side_load_office_dlls.yml
// False Positives:
//   - Unlikely

DeviceImageLoadEvents
| where FolderPath endswith "\\outllib.dll" and (not((FolderPath startswith "C:\\Program Files\\Microsoft Office\\OFFICE" or FolderPath startswith "C:\\Program Files (x86)\\Microsoft Office\\OFFICE" or FolderPath startswith "C:\\Program Files\\Microsoft Office\\Root\\OFFICE" or FolderPath startswith "C:\\Program Files (x86)\\Microsoft Office\\Root\\OFFICE")))