// Title: WerFaultSecure Loading DbgCore or DbgHelp - EDR-Freeze
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-11-27
// Level: medium
// Description: Detects WerFaultSecure.exe loading dbgcore.dll or dbghelp.dll which contains the MiniDumpWriteDump function.
// The MiniDumpWriteDump function creates a minidump of a process by suspending all threads in the target process to ensure a consistent memory snapshot.
// The EDR-Freeze technique abuses WerFaultSecure.exe running as a Protected Process Light (PPL) with WinTCB protection level to suspend EDR/AV processes.
// By leveraging MiniDumpWriteDump's thread suspension behavior, edr-freeze allows malicious activity to execute undetected during the suspension period.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_win_werfaultsecure_dbgcore_dbghelp_load.yml

DeviceImageLoadEvents
| where (FolderPath endswith "\\dbgcore.dll" or FolderPath endswith "\\dbghelp.dll") and InitiatingProcessFolderPath endswith "\\WerFaultSecure.exe"