// Title: HackTool - SILENTTRINITY Stager DLL Load
// Author: Aleksey Potapov, oscd.community
// Date: 2019-10-22
// Level: high
// Description: Detects SILENTTRINITY stager dll loading activity
// MITRE Tactic: Command and Control
// Tags: attack.command-and-control, attack.t1071
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_hktl_silenttrinity_stager.yml
// False Positives:
//   - Unlikely

DeviceImageLoadEvents
| where InitiatingProcessVersionInfoFileDescription contains "st2stager"