// Title: Remote DLL Load Via Rundll32.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-09-18
// Level: medium
// Description: Detects a remote DLL load event via "rundll32.exe".
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1204.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_rundll32_remote_share_load.yml

DeviceImageLoadEvents
| where FolderPath startswith "\\\\" and InitiatingProcessFolderPath endswith "\\rundll32.exe"