// Title: WMI ActiveScriptEventConsumers Activity Via Scrcons.EXE DLL Load
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2020-09-02
// Level: medium
// Description: Detects signs of the WMI script host process "scrcons.exe" loading scripting DLLs which could indicates WMI ActiveScriptEventConsumers EventConsumers activity.
// MITRE Tactic: Lateral Movement
// Tags: attack.lateral-movement, attack.privilege-escalation, attack.persistence, attack.t1546.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_scrcons_wmi_scripteventconsumer.yml
// False Positives:
//   - Legitimate event consumers
//   - Dell computers on some versions register an event consumer that is known to cause false positives when brightness is changed by the corresponding keyboard button

DeviceImageLoadEvents
| where (FolderPath endswith "\\vbscript.dll" or FolderPath endswith "\\wbemdisp.dll" or FolderPath endswith "\\wshom.ocx" or FolderPath endswith "\\scrrun.dll") and InitiatingProcessFolderPath endswith "\\scrcons.exe"