// Title: Potential AVKkid.DLL Sideloading
// Author: X__Junior (Nextron Systems)
// Date: 2023-08-03
// Level: medium
// Description: Detects potential DLL sideloading of "AVKkid.dll"
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.privilege-escalation, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_side_load_avkkid.yml

DeviceImageLoadEvents
| where FolderPath endswith "\\AVKkid.dll" and (not(((FolderPath startswith "C:\\Program Files (x86)\\G DATA\\" or FolderPath startswith "C:\\Program Files\\G DATA\\") and (InitiatingProcessFolderPath contains "C:\\Program Files (x86)\\G DATA\\" or InitiatingProcessFolderPath contains "C:\\Program Files\\G DATA\\") and InitiatingProcessFolderPath endswith "\\AVKKid.exe")))