// Title: Potential Edputil.DLL Sideloading
// Author: X__Junior (Nextron Systems)
// Date: 2023-06-09
// Level: high
// Description: Detects potential DLL sideloading of "edputil.dll"
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.privilege-escalation, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_side_load_edputil.yml
// False Positives:
//   - Unlikely

DeviceImageLoadEvents
| where FolderPath endswith "\\edputil.dll" and (not((FolderPath startswith "C:\\Windows\\System32\\" or FolderPath startswith "C:\\Windows\\SysWOW64\\" or FolderPath startswith "C\\Windows\\WinSxS\\")))