// Title: DLL Load By System Process From Suspicious Locations
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-17
// Level: medium
// Description: Detects when a system process (i.e. located in system32, syswow64, etc.) loads a DLL from a suspicious location or a location with permissive permissions such as "C:\Users\Public"
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1070
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_susp_dll_load_system_process.yml

DeviceImageLoadEvents
| where (FolderPath startswith "C:\\Users\\Public\\" or FolderPath startswith "C:\\PerfLogs\\") and InitiatingProcessFolderPath startswith "C:\\Windows\\"