// Title: Potential Libvlc.DLL Sideloading
// Author: X__Junior
// Date: 2023-04-17
// Level: medium
// Description: Detects potential DLL sideloading of "libvlc.dll", a DLL that is legitimately used by "VLC.exe"
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.persistence, attack.privilege-escalation, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_side_load_libvlc.yml
// False Positives:
//   - False positives are expected if VLC is installed in non-default locations

DeviceImageLoadEvents
| where FolderPath endswith "\\libvlc.dll" and (not((FolderPath startswith "C:\\Program Files (x86)\\VideoLAN\\VLC\\" or FolderPath startswith "C:\\Program Files\\VideoLAN\\VLC\\")))