// Title: MMC Loading Script Engines DLLs
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-02-05
// Level: medium
// Description: Detects when the Microsoft Management Console (MMC) loads the DLL libraries like vbscript, jscript etc which might indicate an attempt
// to execute malicious scripts within a trusted system process for bypassing application whitelisting or defense evasion.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-evasion, attack.t1059.005, attack.t1218.014
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_win_mmc_loads_script_engine_dll.yml
// False Positives:
//   - Legitimate MMC operations or extensions loading these libraries

DeviceImageLoadEvents
| where (FolderPath endswith "\\vbscript.dll" or FolderPath endswith "\\jscript.dll" or FolderPath endswith "\\jscript9.dll") and InitiatingProcessFolderPath endswith "\\mmc.exe"