// Title: Microsoft VBA For Outlook Addin Loaded Via Outlook
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-02-08
// Level: medium
// Description: Detects outlvba (Microsoft VBA for Outlook Addin) DLL being loaded by the outlook process
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1204.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_office_outlook_outlvba_load.yml
// False Positives:
//   - Legitimate macro usage. Add the appropriate filter according to your environment

DeviceImageLoadEvents
| where FolderPath endswith "\\outlvba.dll" and InitiatingProcessFolderPath endswith "\\outlook.exe"