// Title: DLL Loaded From Suspicious Location Via Cmspt.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-30
// Level: high
// Description: Detects cmstp loading "dll" or "ocx" files from suspicious locations
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1218.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_cmstp_load_dll_from_susp_location.yml
// False Positives:
//   - Unikely

DeviceImageLoadEvents
| where (FolderPath contains "\\PerfLogs\\" or FolderPath contains "\\ProgramData\\" or FolderPath contains "\\Users\\" or FolderPath contains "\\Windows\\Temp\\" or FolderPath contains "C:\\Temp\\") and (FolderPath endswith ".dll" or FolderPath endswith ".ocx") and InitiatingProcessFolderPath endswith "\\cmstp.exe"