// Title: Potential WWlib.DLL Sideloading
// Author: X__Junior (Nextron Systems)
// Date: 2023-05-18
// Level: medium
// Description: Detects potential DLL sideloading of "wwlib.dll"
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.privilege-escalation, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_side_load_wwlib.yml

DeviceImageLoadEvents
| where FolderPath endswith "\\wwlib.dll" and (not(((FolderPath startswith "C:\\Program Files (x86)\\Microsoft Office\\" or FolderPath startswith "C:\\Program Files\\Microsoft Office\\") and InitiatingProcessFolderPath endswith "\\winword.exe" and (InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\Microsoft Office\\" or InitiatingProcessFolderPath startswith "C:\\Program Files\\Microsoft Office\\"))))