// Title: GAC DLL Loaded Via Office Applications
// Author: Antonlovesdnb
// Date: 2020-02-19
// Level: high
// Description: Detects any GAC DLL being loaded by an Office Product
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1204.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_office_dotnet_gac_dll_load.yml
// False Positives:
//   - Legitimate macro usage. Add the appropriate filter according to your environment

DeviceImageLoadEvents
| where FolderPath startswith "C:\\Windows\\Microsoft.NET\\assembly\\GAC_MSIL" and (InitiatingProcessFolderPath endswith "\\excel.exe" or InitiatingProcessFolderPath endswith "\\mspub.exe" or InitiatingProcessFolderPath endswith "\\onenote.exe" or InitiatingProcessFolderPath endswith "\\onenoteim.exe" or InitiatingProcessFolderPath endswith "\\outlook.exe" or InitiatingProcessFolderPath endswith "\\powerpnt.exe" or InitiatingProcessFolderPath endswith "\\winword.exe")