// Title: Potential ShellDispatch.DLL Sideloading
// Author: X__Junior (Nextron Systems)
// Date: 2023-06-20
// Level: medium
// Description: Detects potential DLL sideloading of "ShellDispatch.dll"
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.defense-evasion, attack.privilege-escalation, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_side_load_shelldispatch.yml
// False Positives:
//   - Some installers may trigger some false positives

DeviceImageLoadEvents
| where FolderPath endswith "\\ShellDispatch.dll" and (not(((FolderPath contains ":\\Users\\" and FolderPath contains "\\AppData\\Local\\Temp\\") or FolderPath contains ":\\Windows\\Temp\\")))