// Title: Microsoft Excel Add-In Loaded From Uncommon Location
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-05-12
// Level: medium
// Description: Detects Microsoft Excel loading an Add-In (.xll) file from an uncommon location
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1204.002
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_office_excel_xll_susp_load.yml
// False Positives:
//   - Some tuning might be required to allow or remove certain locations used by the rule if you consider them as safe locations

DeviceImageLoadEvents
| where (FolderPath contains "\\Desktop\\" or FolderPath contains "\\Downloads\\" or FolderPath contains "\\Perflogs\\" or FolderPath contains "\\Temp\\" or FolderPath contains "\\Users\\Public\\" or FolderPath contains "\\Windows\\Tasks\\") and FolderPath endswith ".xll" and InitiatingProcessFolderPath endswith "\\excel.exe"