// Title: Potential CCleanerDU.DLL Sideloading
// Author: X__Junior (Nextron Systems)
// Date: 2023-07-13
// Level: medium
// Description: Detects potential DLL sideloading of "CCleanerDU.dll"
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.persistence, attack.privilege-escalation, attack.t1574.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/image_load/image_load_side_load_ccleaner_du.yml
// False Positives:
//   - False positives could occur from other custom installation paths. Apply additional filters accordingly.

DeviceImageLoadEvents
| where FolderPath endswith "\\CCleanerDU.dll" and (not(((InitiatingProcessFolderPath endswith "\\CCleaner.exe" or InitiatingProcessFolderPath endswith "\\CCleaner64.exe") and (InitiatingProcessFolderPath startswith "C:\\Program Files\\CCleaner\\" or InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\CCleaner\\"))))