// Title: Equation Group DLL_U Export Function Load
// Author: Florian Roth (Nextron Systems)
// Date: 2019-03-04
// Level: critical
// Description: Detects a specific export function name used by one of EquationGroup tools
// MITRE Tactic: Defense Evasion
// Tags: attack.g0020, attack.defense-evasion, attack.t1218.011, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2019/TA/EquationGroup/proc_creation_win_apt_equationgroup_dll_u_load.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains "-export dll_u" or (ProcessCommandLine endswith ",dll_u" or ProcessCommandLine endswith " dll_u")