// Author: Furkan CALISKAN, @caliskanfurkan_, @oscd_initiative, Nasreddine Bencherchali
// Date: 2020/10/05
// Level: medium
// Description: Attackers can use findstr to hide their artifacts or search specific strings and evade defense mechanism
// Tags: attack.defense_evasion, attack.t1218, attack.t1564.004, attack.t1552.001, attack.t1105
DeviceProcessEvents
| where (ProcessCommandLine contains "findstr" or FolderPath endswith "findstr.exe" or ProcessVersionInfoOriginalFileName =~ "FINDSTR.EXE") and (((ProcessCommandLine contains " /v " or ProcessCommandLine contains " -v ") and (ProcessCommandLine contains " /l " or ProcessCommandLine contains " -l ")) or ((ProcessCommandLine contains " /s " or ProcessCommandLine contains " -s ") and (ProcessCommandLine contains " /i " or ProcessCommandLine contains " -i ")))