// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/04/17
// Level: medium
// Description: Detects usage of winget to add new additional download sources
// Tags: attack.defense_evasion, attack.execution, attack.t1059
DeviceProcessEvents
| where (ProcessCommandLine contains "source " and ProcessCommandLine contains "add ") and (FolderPath endswith "\\winget.exe" or ProcessVersionInfoOriginalFileName =~ "winget.exe")