// Author: Nasreddine Bencherchali (Nextron Systems), memory-shards
// Date: 2022/12/24
// Level: medium
// Description: Detects execution of the AgentExecutor.exe binary. Which can be abused as a LOLBIN to execute powershell scripts with the ExecutionPolicy "Bypass" or any binary named "powershell.exe" located in the path provided by 6th positional argument
// Tags: attack.defense_evasion, attack.t1218
DeviceProcessEvents
| where (ProcessCommandLine contains " -powershell" or ProcessCommandLine contains " -remediationScript") and (FolderPath =~ "\\AgentExecutor.exe" or ProcessVersionInfoOriginalFileName =~ "AgentExecutor.exe")