// Author: frack113
// Date: 2023/03/12
// Level: low
// Description: Detects loading of Amsi.dll by uncommon processes
// Tags: attack.defense_evasion, attack.impact, attack.t1490
DeviceImageLoadEvents
| where FolderPath endswith "\\amsi.dll" and (not(((InitiatingProcessFolderPath endswith "\\ngentask.exe" and (InitiatingProcessFolderPath startswith "C:\\Windows\\Microsoft.NET\\Framework\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\Microsoft.NET\\Framework64\\")) or InitiatingProcessFolderPath =~ "" or (InitiatingProcessFolderPath in~ ("C:\\Windows\\explorer.exe", "C:\\Windows\\Sysmon64.exe")) or (InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\" or InitiatingProcessFolderPath startswith "C:\\Program Files\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\System32\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\SysWOW64\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\WinSxS\\") or isnull(InitiatingProcessFolderPath) or (InitiatingProcessFolderPath endswith "\\MsMpEng.exe" and InitiatingProcessFolderPath startswith "C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\"))))