// Author: Beyu Denis, oscd.community
// Date: 2019/10/26
// Level: medium
// Description: Execute VBscript code that is referenced within the *.bgi file.
// Tags: attack.execution, attack.t1059.005, attack.defense_evasion, attack.t1218, attack.t1202
DeviceProcessEvents
| where (ProcessCommandLine contains "/popup" and ProcessCommandLine contains "/nolicprompt") and FolderPath endswith "\\bginfo.exe"