// Author: Swachchhanda Shrawan Poudel
// Date: 2023/11/09
// Level: medium
// Description: Detects usage of "msedge_proxy.exe" to download arbitrary files
// Tags: attack.defense_evasion, attack.execution, attack.t1218
DeviceProcessEvents
| where (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://") and (FolderPath endswith "\\msedge_proxy.exe" or ProcessVersionInfoOriginalFileName =~ "msedge_proxy.exe")