// Author: frack113
// Date: 2021/11/24
// Level: medium
// Description: Detects execution of "aspnet_compiler.exe" which can be abused to compile and execute C# code.
// Tags: attack.defense_evasion, attack.t1127
DeviceProcessEvents
| where (FolderPath contains "C:\\Windows\\Microsoft.NET\\Framework\\" or FolderPath contains "C:\\Windows\\Microsoft.NET\\Framework64\\") and FolderPath endswith "\\aspnet_compiler.exe"