// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/05/21
// Level: medium
// Description: Detects calls to "LoadAssemblyFromPath" or "LoadAssemblyFromNS" that are part of the "CL_LoadAssembly.ps1" script. This can be abused to load different assemblies and bypass App locker controls.
// Tags: attack.defense_evasion, attack.t1216
DeviceProcessEvents
| where ProcessCommandLine contains "LoadAssemblyFromPath " or ProcessCommandLine contains "LoadAssemblyFromNS "