// Author: frack113, Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/05/07
// Level: medium
// Description: Detects the use of "Ilasm.EXE" in order to compile C# intermediate (IL) code to EXE or DLL.
// Tags: attack.defense_evasion, attack.t1127
DeviceProcessEvents
| where (ProcessCommandLine contains " /dll" or ProcessCommandLine contains " /exe") and (FolderPath endswith "\\ilasm.exe" or ProcessVersionInfoOriginalFileName =~ "ilasm.exe")