// Author: frack113
// Date: 2022/09/17
// Level: high
// Description: Detects tampering with the "ChannelAccess" registry key in order to change access to Windows event channel
// Tags: attack.defense_evasion, attack.t1562.002
DeviceRegistryEvents
| where ((RegistryValueData contains "(A;;0x1;;;SY)" or RegistryValueData contains "(A;;0x5;;;BA)" or RegistryValueData contains "(A;;0x1;;;LA)") and ActionType =~ "RegistryValueSet" and RegistryKey endswith "\\ChannelAccess" and RegistryKey startswith "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels") and (not((InitiatingProcessFolderPath in~ ("C:\\Windows\\servicing\\TrustedInstaller.exe") or InitiatingProcessFolderPath endswith "\\TiWorker.exe")))