// Author: Joseliyo Sanchez, @Joseliyo_Jstnk
// Date: 2024/01/17
// Level: medium
// Description: Detects a CodePage modification using the "mode.com" utility to Russian language.
This behavior has been used by threat actors behind Dharma ransomware.

// Tags: attack.defense_evasion, attack.t1036
DeviceProcessEvents
| where ((ProcessCommandLine contains " con " and ProcessCommandLine contains " cp " and ProcessCommandLine contains " select=") and (ProcessCommandLine endswith "=1251" or ProcessCommandLine endswith "=866")) and (FolderPath endswith "\\mode.com" or ProcessVersionInfoOriginalFileName =~ "MODE.COM")