// Author: Florian Roth (Nextron Systems), Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/01/04
// Level: high
// Description: Detects uses of the createdump.exe LOLOBIN utility to dump process memory
// Tags: attack.defense_evasion, attack.t1036, attack.t1003.001
DeviceProcessEvents
| where (ProcessCommandLine contains " -u " or ProcessCommandLine contains " --full " or ProcessCommandLine contains " -f " or ProcessCommandLine contains " --name " or ProcessCommandLine contains ".dmp ") and (FolderPath endswith "\\createdump.exe" or ProcessVersionInfoOriginalFileName =~ "FX_VER_INTERNALNAME_STR")