// Author: Ensar Şamil, @sblmsrsn, @oscd_initiative
// Date: 2020/10/07
// Level: medium
// Description: Detects the execution of Xwizard tool with specific arguments which utilized to run custom class properties.
// Tags: attack.defense_evasion, attack.t1218
DeviceProcessEvents
| where ProcessCommandLine matches regex "\\{[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}\\}" and FolderPath endswith "\\xwizard.exe"