// Author: frack113
// Date: 2023/01/13
// Level: high
// Description: Detect activation of DisableRestrictedAdmin to desable RestrictedAdmin mode.
RestrictedAdmin mode prevents the transmission of reusable credentials to the remote system to which you connect using Remote Desktop.
This prevents your credentials from being harvested during the initial connection process if the remote server has been compromise

// Tags: attack.defense_evasion, attack.t1112
DeviceProcessEvents
| where ProcessCommandLine contains "\\System\\CurrentControlSet\\Control\\Lsa\\" and ProcessCommandLine contains "DisableRestrictedAdmin" and ProcessCommandLine contains " 1"