// Author: frack113
// Date: 2022/01/09
// Level: medium
// Description: Adversaries may disable or modify system firewalls in order to bypass controls limiting network usage
// Tags: attack.defense_evasion, attack.t1562.004
DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey contains "\\Services\\SharedAccess\\Parameters\\FirewallPolicy" and RegistryKey endswith "\\EnableFirewall"