// Author: B.Talebi
// Date: 2022/07/28
// Level: high
// Description: Detects changes in Sysmon driver altitude. If the Sysmon driver is configured to load at an altitude of another registered service, it will fail to load at boot.
// Tags: attack.defense_evasion, attack.t1562.001
DeviceRegistryEvents
| where ActionType =~ "RegistryValueSet" and RegistryKey endswith "\\Instances\\Sysmon Instance\\Altitude" and RegistryKey startswith "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet001"