// Author: Florian Roth (Nextron Systems)
// Date: 2022/07/04
// Level: high
// Description: Detects the disabling of the Windows Defender eventlog as seen in relation to Lockbit 3.0 infections
// Tags: attack.defense_evasion, attack.t1562.001
DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey contains "\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\Microsoft-Windows-Windows Defender/Operational\\Enabled"