// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/09/15
// Level: medium
// Description: Detects execution of "Diskshadow.exe" in script mode using the "/s" flag where the script is located in a potentially suspicious location.
// Tags: attack.defense_evasion, attack.t1218
DeviceProcessEvents
| where (ProcessCommandLine contains "-s " or ProcessCommandLine contains "/s ") and (ProcessVersionInfoOriginalFileName =~ "diskshadow.exe" or FolderPath endswith "\\diskshadow.exe") and (ProcessCommandLine contains ":\\Temp\\" or ProcessCommandLine contains ":\\Windows\\Temp\\" or ProcessCommandLine contains "\\AppData\\Local\\" or ProcessCommandLine contains "\\AppData\\Roaming\\" or ProcessCommandLine contains "\\ProgramData\\" or ProcessCommandLine contains "\\Users\\Public\\")