// Author: Austin Songer @austinsonger
// Date: 2021/10/23
// Level: medium
// Description: Detects when a user installs certificates by using CertOC.exe to loads the target DLL file.
// Tags: attack.defense_evasion, attack.t1218
DeviceProcessEvents
| where (ProcessCommandLine contains " -LoadDLL " or ProcessCommandLine contains " /LoadDLL ") and (FolderPath endswith "\\certoc.exe" or ProcessVersionInfoOriginalFileName =~ "CertOC.exe")