// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/07/17
// Level: medium
// Description: Detects when a system process (i.e. located in system32, syswow64, etc.) loads a DLL from a suspicious location or a location with permissive permissions such as "C:\Users\Public"
// Tags: attack.defense_evasion, attack.t1070
DeviceImageLoadEvents
| where (FolderPath startswith "C:\\Users\\Public\\" or FolderPath startswith "C:\\PerfLogs\\") and InitiatingProcessFolderPath startswith "C:\\Windows\\"