// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/06/27
// Level: high
// Description: Detects a "dllhost" process spawning with no commandline arguments which is very rare to happen and could indicate process injection activity or malware mimicking similar system processes.
// Tags: attack.defense_evasion, attack.t1055
DeviceProcessEvents
| where ((ProcessCommandLine in~ ("dllhost.exe", "dllhost")) and FolderPath endswith "\\dllhost.exe") and (not(isnull(ProcessCommandLine)))