// Author: frack113
// Date: 2022/04/24
// Level: medium
// Description: Detects MsiExec loading a DLL and calling its DllUnregisterServer function
// Tags: attack.defense_evasion, attack.t1218.007
DeviceProcessEvents
| where ProcessCommandLine contains ".dll" and (ProcessCommandLine contains " -z " or ProcessCommandLine contains " /z ") and (FolderPath endswith "\\msiexec.exe" or ProcessVersionInfoOriginalFileName =~ "\\msiexec.exe")