// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/12/15
// Level: high
// Description: Detects changes to the "NoLMHash" registry value in order to allow Windows to store LM Hashes.
By setting this registry value to "0" (DWORD), Windows will be allowed to store a LAN manager hash of your password in Active Directory and local SAM databases.

// Tags: attack.defense_evasion, attack.t1112
DeviceProcessEvents
| where ProcessCommandLine contains "\\System\\CurrentControlSet\\Control\\Lsa" and ProcessCommandLine contains "NoLMHash" and ProcessCommandLine contains " 0"