// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/12/09
// Level: low
// Description: Detects changes to the "TracingDisabled" key in order to disable ETW logging for services.exe (SCM)
// Tags: attack.defense_evasion, attack.t1112, attack.t1562
DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000001)" and RegistryKey endswith "Software\\Microsoft\\Windows NT\\CurrentVersion\\Tracing\\SCM\\Regular\\TracingDisabled"