// Author: D3F7A5105
// Date: 2023/01/02
// Level: medium
// Description: Detects the creation of new files with the ".evtx" extension in non-common locations. Which could indicate tampering with default evtx locations in order to evade security controls
// Tags: attack.defense_evasion, attack.t1562.002
DeviceFileEvents
| where FolderPath endswith ".evtx" and (not(((FolderPath endswith "\\Windows\\System32\\winevt\\Logs\\" and FolderPath startswith "C:\\ProgramData\\Microsoft\\Windows\\Containers\\BaseImages\\") or (InitiatingProcessFolderPath in~ ("C:\\Windows\\explorer.exe", "C:\\Windows\\system32\\dllhost.exe")) or FolderPath startswith "C:\\Windows\\System32\\winevt\\Logs\\")))