// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/06/13
// Level: high
// Description: Detects execution of "msdt.exe" using an answer file which is simulating the legitimate way of calling msdt via "pcwrun.exe" (For example from the compatibility tab)
// Tags: attack.defense_evasion, attack.t1218, attack.execution
DeviceProcessEvents
| where ((ProcessCommandLine contains " -af " or ProcessCommandLine contains " /af ") and (ProcessCommandLine contains "\\WINDOWS\\diagnostics\\index\\PCWDiagnostic.xml" and FolderPath endswith "\\msdt.exe")) and (not(InitiatingProcessFolderPath endswith "\\pcwrun.exe"))