// Author: Michael Haag, FPT.EagleEye
// Date: 2017/03/09
// Level: medium
// Description: Detects usage of bitsadmin downloading a file
// Tags: attack.defense_evasion, attack.persistence, attack.t1197, attack.s0190, attack.t1036.003
DeviceProcessEvents
| where (FolderPath endswith "\\bitsadmin.exe" or ProcessVersionInfoOriginalFileName =~ "bitsadmin.exe") and (ProcessCommandLine contains " /transfer " or ((ProcessCommandLine contains " /create " or ProcessCommandLine contains " /addfile ") and ProcessCommandLine contains "http"))