// Author: X__Junior (Nextron Systems)
// Date: 2023/07/18
// Level: medium
// Description: Detects execution of netsh with the "advfirewall" and the "set" option in order to set new values for properties of a existing rule
// Tags: attack.defense_evasion
DeviceProcessEvents
| where (ProcessCommandLine contains " firewall " and ProcessCommandLine contains " set ") and (FolderPath endswith "\\netsh.exe" or ProcessVersionInfoOriginalFileName =~ "netsh.exe")