// Author: Thomas Patzke
// Date: 2020/05/22
// Level: high
// Description: The CrachMapExec pentesting framework implements a PowerShell obfuscation with some static strings detected by this rule.
// Tags: attack.execution, attack.t1059.001, attack.defense_evasion, attack.t1027.005
DeviceProcessEvents
| where (match or ProcessCommandLine contains "( $ShellId[1]+$ShellId[13]+'x')" or match or ProcessCommandLine contains "( $env:Public[13]+$env:Public[5]+'x')" or match or ProcessCommandLine contains "[1,3]+'x'-Join'')") and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") or (ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")))