// Author: Sami Ruohonen
// Date: 2019/01/16
// Level: medium
// Description: Detects usage of attrib.exe to hide files from users.
// Tags: attack.defense_evasion, attack.t1564.001
DeviceProcessEvents
| where (ProcessCommandLine contains " +h " and (FolderPath endswith "\\attrib.exe" or ProcessVersionInfoOriginalFileName =~ "ATTRIB.EXE")) and (not(ProcessCommandLine contains "\\desktop.ini ")) and (not((ProcessCommandLine =~ "+R +H +S +A \\*.cui" and InitiatingProcessCommandLine =~ "C:\\WINDOWS\\system32\\*.bat" and InitiatingProcessFolderPath endswith "\\cmd.exe")))