// Author: Sreeman, Florian Roth (Nextron Systems), frack113
// Date: 2020/04/21
// Level: medium
// Description: Detects usage of winget to install applications via manifest file. Adversaries can abuse winget to download payloads remotely and execute them.
The manifest option enables you to install an application by passing in a YAML file directly to the client.
Winget can be used to download and install exe, msi or msix files later.

// Tags: attack.defense_evasion, attack.execution, attack.t1059
DeviceProcessEvents
| where (FolderPath endswith "\\winget.exe" or ProcessVersionInfoOriginalFileName =~ "winget.exe") and (ProcessCommandLine contains "install" or ProcessCommandLine contains " add ") and (ProcessCommandLine contains "-m " or ProcessCommandLine contains "--manifest")