// Author: Jonathan Cheong, oscd.community
// Date: 2020/10/15
// Level: high
// Description: Detects Obfuscated use of Environment Variables to execute PowerShell
// Tags: attack.defense_evasion, attack.t1027, attack.execution, attack.t1059.001
DeviceProcessEvents
| where (ProcessCommandLine contains "/c" or ProcessCommandLine contains "/r") and (ProcessCommandLine contains "cmd" and ProcessCommandLine contains "\"set" and ProcessCommandLine contains "-f")