// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/11/01
// Level: high
// Description: Detects the execution of a signed binary dropped by Kaspersky Lab Products Remover (kavremover) which can be abused as a LOLBIN to execute arbitrary commands and binaries.
// Tags: attack.defense_evasion, attack.t1127
DeviceProcessEvents
| where ProcessCommandLine contains " run run-cmd " and (not((InitiatingProcessFolderPath endswith "\\kavremover.exe" or InitiatingProcessFolderPath endswith "\\cleanapi.exe")))