// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024/03/19
// Level: low
// Description: Detects changes to the "MaxMpxCt" registry value.
MaxMpxCt specifies the maximum outstanding network requests for the server per client, which is used when negotiating a Server Message Block (SMB) connection with a client. Note if the value is set beyond 125 older Windows 9x clients will fail to negotiate.
Ransomware threat actors and operators (specifically BlackCat) were seen increasing this value in order to handle a higher volume of traffic.

// Tags: attack.defense_evasion, attack.t1070.005
DeviceRegistryEvents
| where RegistryKey endswith "\\Services\\LanmanServer\\Parameters\\MaxMpxCt"