// Author: frack113
// Date: 2022/01/22
// Level: low
// Description: Detects modification of the registry settings used for Internet Explorer and other Windows components that use these settings. An attacker can abuse this registry key to add a domain to the trusted sites Zone or insert javascript for persistence
// Tags: attack.defense_evasion, attack.t1112
DeviceRegistryEvents
| where (ActionType =~ "RegistryValueSet" and RegistryKey contains "\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings") and (not((RegistryKey contains "\\Accepted Documents" or RegistryValueData =~ "Binary Data" or RegistryValueData startswith "DWORD" or (RegistryValueData in~ ("Cookie:", "Visited:", "(Empty)")) or (RegistryKey contains "\\Cache" or RegistryKey contains "\\ZoneMap" or RegistryKey contains "\\WpadDecision"))))