// Author: Sreeman
// Date: 2020/10/29
// Level: medium
// Description: BITS will allow you to schedule a command to execute after a successful download to notify you that the job is finished. When the job runs on the system the command specified in the BITS job will be executed. This can be abused by actors to create a backdoor within the system and for persistence. It will be chained in a BITS job to schedule the download of malware/additional binaries and execute the program after being downloaded
// Tags: attack.defense_evasion, attack.t1197
DeviceProcessEvents
| where ((ProcessCommandLine contains "%COMSPEC%" or ProcessCommandLine contains "cmd.exe" or ProcessCommandLine contains "regsvr32.exe") and (ProcessCommandLine contains "bitsadmin" and ProcessCommandLine contains "/SetNotifyCmdLine")) or ((ProcessCommandLine contains "http:" or ProcessCommandLine contains "https:" or ProcessCommandLine contains "ftp:" or ProcessCommandLine contains "ftps:") and (ProcessCommandLine contains "bitsadmin" and ProcessCommandLine contains "/Addfile"))