// Author: frack113
// Date: 2022/01/16
// Level: medium
// Description: Adversaries may abuse msiexec.exe to proxy execution of malicious payloads.
Msiexec.exe is the command-line utility for the Windows Installer and is thus commonly associated with executing installation packages (.msi)

// Tags: attack.defense_evasion, attack.t1218.007
DeviceProcessEvents
| where ((ProcessCommandLine contains "/i" or ProcessCommandLine contains "-i" or ProcessCommandLine contains "/package" or ProcessCommandLine contains "-package" or ProcessCommandLine contains "/a" or ProcessCommandLine contains "-a" or ProcessCommandLine contains "/j" or ProcessCommandLine contains "-j") and (FolderPath endswith "\\msiexec.exe" or ProcessVersionInfoOriginalFileName =~ "msiexec.exe") and (ProcessCommandLine contains "/q" or ProcessCommandLine contains "-q")) and (not(((ProcessIntegrityLevel =~ "System" and InitiatingProcessFolderPath =~ "C:\\Windows\\CCM\\Ccm32BitLauncher.exe") or InitiatingProcessFolderPath startswith "C:\\Windows\\Temp\\" or (InitiatingProcessFolderPath contains "\\AppData\\Local\\Temp\\" and InitiatingProcessFolderPath startswith "C:\\Users\\"))))