// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/08/16
// Level: medium
// Description: Detects setting of a new registry value related to BgInfo configuration, which can be abused to execute custom VBScript via "BgInfo.exe"
// Tags: attack.defense_evasion, attack.t1112
DeviceRegistryEvents
| where RegistryValueData startswith "4" and ActionType =~ "RegistryValueSet" and RegistryKey contains "\\Software\\Winternals\\BGInfo\\UserFields"