// Author: Florian Roth (Nextron Systems)
// Date: 2018/03/13
// Level: low
// Description: Detects the creation of a process via the Windows task manager. This might be an attempt to bypass UAC
// Tags: attack.defense_evasion, attack.t1036
DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\taskmgr.exe" and (not((FolderPath endswith ":\\Windows\\System32\\mmc.exe" or FolderPath endswith ":\\Windows\\System32\\resmon.exe" or FolderPath endswith ":\\Windows\\System32\\Taskmgr.exe")))