// Author: Markus Neis, Sander Wiebing
// Date: 2019/01/29
// Level: medium
// Description: Detects the addition of a new rule to the Windows firewall via netsh
// Tags: attack.defense_evasion, attack.t1562.004
DeviceProcessEvents
| where ((ProcessCommandLine contains " firewall " and ProcessCommandLine contains " add ") and (FolderPath endswith "\\netsh.exe" or ProcessVersionInfoOriginalFileName =~ "netsh.exe")) and (not(((ProcessCommandLine contains "\\netsh.exe advfirewall firewall add rule name=Dropbox dir=in action=allow \"program=C:\\Program Files (x86)\\Dropbox\\Client\\Dropbox.exe\" enable=yes profile=Any" or ProcessCommandLine contains "\\netsh.exe advfirewall firewall add rule name=Dropbox dir=in action=allow \"program=C:\\Program Files\\Dropbox\\Client\\Dropbox.exe\" enable=yes profile=Any") or (ProcessCommandLine contains "advfirewall firewall show rule name=all" and InitiatingProcessFolderPath endswith "\\thor64.exe" and InitiatingProcessFolderPath startswith "C:\\Windows\\Temp\\asgard2-agent\\"))))