// Author: Florian Roth (Nextron Systems)
// Date: 2018/10/30
// Level: high
// Description: Detects suspicious uses of the SysInternals Procdump utility by using a special command line parameter in combination with the lsass.exe process.
This way we are also able to catch cases in which the attacker has renamed the procdump executable.

// Tags: attack.defense_evasion, attack.t1036, attack.credential_access, attack.t1003.001, car.2013-05-009
DeviceProcessEvents
| where (ProcessCommandLine contains " -ma " or ProcessCommandLine contains " /ma ") and ProcessCommandLine contains " ls"