// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/06/20
// Level: medium
// Description: Detects usage of Dsacls to grant over permissive permissions
// Tags: attack.defense_evasion, attack.t1218
DeviceProcessEvents
| where ProcessCommandLine contains " /G " and (FolderPath endswith "\\dsacls.exe" or ProcessVersionInfoOriginalFileName =~ "DSACLS.EXE") and (ProcessCommandLine contains "GR" or ProcessCommandLine contains "GE" or ProcessCommandLine contains "GW" or ProcessCommandLine contains "GA" or ProcessCommandLine contains "WP" or ProcessCommandLine contains "WD")