// Author: X__Junior (Nextron Systems)
// Date: 2023/03/21
// Level: high
// Description: Detects potential DLL sideloading of "iviewers.dll" (OLE/COM Object Interface Viewer)
// Tags: attack.defense_evasion, attack.privilege_escalation, attack.t1574.001, attack.t1574.002
DeviceImageLoadEvents
| where FolderPath endswith "\\iviewers.dll" and (not((FolderPath startswith "C:\\Program Files (x86)\\Windows Kits\\" or FolderPath startswith "C:\\Program Files\\Windows Kits\\")))