// Author: Victor Sergeev, oscd.community
// Date: 2020/10/09
// Level: medium
// Description: Detects execution of "ftp.exe" script with the "-s" or "/s" flag and any child processes ran by "ftp.exe".
// Tags: attack.execution, attack.t1059, attack.defense_evasion, attack.t1202
DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\ftp.exe" or ((ProcessCommandLine contains "-s:" or ProcessCommandLine contains "/s:") and (FolderPath endswith "\\ftp.exe" or ProcessVersionInfoOriginalFileName =~ "ftp.exe"))