// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/01
// Level: high
// Description: Detects tampering with autologger trace sessions which is a technique used by attackers to disable logging
// Tags: attack.defense_evasion
DeviceRegistryEvents
| where (RegistryKey contains "\\System\\CurrentControlSet\\Control\\WMI\\Autologger" and (RegistryValueData =~ "DWORD (0x00000000)" and (RegistryKey contains "\\EventLog-" or RegistryKey contains "\\Defender") and (RegistryKey endswith "\\Enable" or RegistryKey endswith "\\Start"))) and (not(InitiatingProcessFolderPath =~ "C:\\Windows\\system32\\wevtutil.exe"))