// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/05/15
// Level: high
// Description: Detects potentially suspicious child processes of "GoogleUpdate.exe"
// Tags: attack.defense_evasion
DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\GoogleUpdate.exe" and (not((isnull(FolderPath) or (FolderPath contains "\\Google" or (FolderPath endswith "\\setup.exe" or FolderPath endswith "chrome_updater.exe" or FolderPath endswith "chrome_installer.exe")))))