// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/06/20
// Level: medium
// Description: Detects possible password spraying attempts using Dsacls
// Tags: attack.defense_evasion, attack.t1218
DeviceProcessEvents
| where (ProcessCommandLine contains "/user:" and ProcessCommandLine contains "/passwd:") and (FolderPath endswith "\\dsacls.exe" or ProcessVersionInfoOriginalFileName =~ "DSACLS.EXE")