// Author: Nasreddine Bencherchali (Nextron Systems), oscd.community, Natalia Shornikova, frack113
// Date: 2022/05/21
// Level: medium
// Description: Detects the use of the Microsoft signed script "CL_mutexverifiers" to proxy the execution of additional PowerShell script commands
// Tags: attack.defense_evasion, attack.t1216
DeviceProcessEvents
| where (ProcessCommandLine contains " -nologo -windowstyle minimized -file " and FolderPath endswith "\\powershell.exe" and (InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe")) and (ProcessCommandLine contains "\\AppData\\Local\\Temp\\" or ProcessCommandLine contains "\\Windows\\Temp\\")