// Author: frack113, Nasreddine Bencherchali
// Date: 2022/08/01
// Level: medium
// Description: Detects the import of '.reg' files from suspicious paths using the 'reg.exe' utility
// Tags: attack.t1112, attack.defense_evasion
DeviceProcessEvents
| where ProcessCommandLine contains " import " and (FolderPath endswith "\\reg.exe" or ProcessVersionInfoOriginalFileName =~ "reg.exe") and (ProcessCommandLine contains "C:\\Users\\" or ProcessCommandLine contains "%temp%" or ProcessCommandLine contains "%tmp%" or ProcessCommandLine contains "%appdata%" or ProcessCommandLine contains "\\AppData\\Local\\Temp\\" or ProcessCommandLine contains "C:\\Windows\\Temp\\" or ProcessCommandLine contains "C:\\ProgramData\\")