// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/08/14
// Level: high
// Description: Detects execution of "aspnet_compiler.exe" with potentially suspicious paths for compilation.
// Tags: attack.defense_evasion, attack.t1127
DeviceProcessEvents
| where (ProcessCommandLine contains "\\Users\\Public\\" or ProcessCommandLine contains "\\AppData\\Local\\Temp\\" or ProcessCommandLine contains "\\AppData\\Local\\Roaming\\" or ProcessCommandLine contains ":\\Temp\\" or ProcessCommandLine contains ":\\Windows\\Temp\\" or ProcessCommandLine contains ":\\Windows\\System32\\Tasks\\" or ProcessCommandLine contains ":\\Windows\\Tasks\\") and (FolderPath contains "C:\\Windows\\Microsoft.NET\\Framework\\" or FolderPath contains "C:\\Windows\\Microsoft.NET\\Framework64\\") and FolderPath endswith "\\aspnet_compiler.exe"