// Author: Beyu Denis, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2019/10/26
// Level: medium
// Description: Detects usage of "cdb.exe" to launch arbitrary processes or commands from a debugger script file
// Tags: attack.execution, attack.t1106, attack.defense_evasion, attack.t1218, attack.t1127
DeviceProcessEvents
| where (ProcessCommandLine contains " -c " or ProcessCommandLine contains " -cf ") and (FolderPath endswith "\\cdb.exe" or ProcessVersionInfoOriginalFileName =~ "CDB.Exe")