// Author: frack113
// Date: 2022/12/14
// Level: medium
// Description: Detects potential DLL sideloading using JUSTSYSTEMS Japanese word processor
// Tags: attack.defense_evasion, attack.persistence, attack.privilege_escalation, attack.t1574.001, attack.t1574.002
DeviceImageLoadEvents
| where FolderPath endswith "\\JSESPR.dll" and (not(FolderPath startswith "C:\\Program Files\\Common Files\\Justsystem\\JsSchHlp\\"))