// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/09/01
// Level: high
// Description: Detects possible NTLM coercion via certutil using the 'syncwithWU' flag
// Tags: attack.defense_evasion, attack.t1218
DeviceProcessEvents
| where (ProcessCommandLine contains " -syncwithWU " and ProcessCommandLine contains " \\\\") and (FolderPath endswith "\\certutil.exe" or ProcessVersionInfoOriginalFileName =~ "CertUtil.exe")