// Author: Scoubi (@ScoubiMtl)
// Date: 2023/10/09
// Level: medium
// Description: Detects the creation of hidden file/folder with the "::$index_allocation" stream. Which can be used as a technique to prevent access to folder and files from tooling such as "explorer.exe" and "powershell.exe"

// Tags: attack.defense_evasion, attack.t1564.004
DeviceFileEvents
| where FolderPath contains "::$index_allocation"