// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/10/18
// Level: high
// Description: Detects PowerShell scripts to set the ACL to a file in the Windows folder
// Tags: attack.defense_evasion
DeviceProcessEvents
| where (ProcessCommandLine contains "Set-Acl " and ProcessCommandLine contains "-AclObject ") and ((ProcessVersionInfoOriginalFileName in~ ("PowerShell.EXE", "pwsh.dll")) or (FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe")) and (ProcessCommandLine contains "-Path \"C:\\Windows" or ProcessCommandLine contains "-Path 'C:\\Windows" or ProcessCommandLine contains "-Path %windir%" or ProcessCommandLine contains "-Path $env:windir") and (ProcessCommandLine contains "FullControl" or ProcessCommandLine contains "Allow")