// Author: Subhash Popuri (@pbssubhash)
// Date: 2021/08/21
// Level: high
// Description: Powerup tool's Write Hijack DLL exploits DLL hijacking for privilege escalation.
In it's default mode, it builds a self deleting .bat file which executes malicious command.
The detection rule relies on creation of the malicious bat file (debug.bat by default).

// Tags: attack.persistence, attack.privilege_escalation, attack.defense_evasion, attack.t1574.001
DeviceFileEvents
| where (InitiatingProcessFolderPath endswith "\\powershell.exe" or InitiatingProcessFolderPath endswith "\\pwsh.exe") and FolderPath endswith ".bat"