// Author: Cedric MAURUGEON
// Date: 2021/09/29
// Level: high
// Description: Detects the deletion of a prefetch file which may indicate an attempt to destroy forensic evidence
// Tags: attack.defense_evasion, attack.t1070.004
DeviceFileEvents
| where (FolderPath endswith ".pf" and FolderPath startswith "C:\\Windows\\Prefetch\\") and (not((InitiatingProcessFolderPath =~ "C:\\windows\\system32\\svchost.exe" and (RequestAccountName contains "AUTHORI" or RequestAccountName contains "AUTORI"))))