// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/03/14
// Level: medium
// Description: Detects the execution of "dotnet-dump" with the "collect" flag. The execution could indicate potential process dumping of critical processes such as LSASS
// Tags: attack.defense_evasion, attack.t1218
DeviceProcessEvents
| where ProcessCommandLine contains "collect" and (FolderPath endswith "\\dotnet-dump.exe" or ProcessVersionInfoOriginalFileName =~ "dotnet-dump.dll")