// Author: Eli Salem, Sander Wiebing, oscd.community
// Date: 2020/10/08
// Level: low
// Description: Detects the execution of regini.exe which can be used to modify registry keys, the changes are imported from one or more text files.
// Tags: attack.t1112, attack.defense_evasion
DeviceProcessEvents
| where (FolderPath endswith "\\regini.exe" or ProcessVersionInfoOriginalFileName =~ "REGINI.EXE") and (not(ProcessCommandLine matches regex ":[^ \\\\]"))