// Author: Furkan CALISKAN, @caliskanfurkan_, @oscd_initiative, Nasreddine Bencherchali (Nextron Systems)
// Date: 2020/10/05
// Level: medium
// Description: Detects execution of "findstr" with specific flags and a remote share path. This specific set of CLI flags would allow "findstr" to download the content of the file located on the remote share as described in the LOLBAS entry.

// Tags: attack.defense_evasion, attack.t1218, attack.t1564.004, attack.t1552.001, attack.t1105
DeviceProcessEvents
| where (ProcessCommandLine contains "findstr" or FolderPath endswith "findstr.exe" or ProcessVersionInfoOriginalFileName =~ "FINDSTR.EXE") and ((ProcessCommandLine contains " -v " or ProcessCommandLine contains " /v ") and (ProcessCommandLine contains " -l " or ProcessCommandLine contains " /l ") and ProcessCommandLine contains "\\\\")