// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/09/19
// Level: medium
// Description: Detects execution of renamed Remote Utilities (RURAT) via Product PE header field
// Tags: attack.defense_evasion, attack.collection, attack.command_and_control, attack.discovery, attack.s0592
DeviceProcessEvents
| where ProcessVersionInfoProductName =~ "Remote Utilities" and (not((FolderPath endswith "\\rutserv.exe" or FolderPath endswith "\\rfusclient.exe")))