// Author: Markus Neis, Swisscom
// Date: 2019/06/04
// Level: high
// Description: Detects the execution of a renamed "jusched.exe" as seen used by the cobalt group
// Tags: attack.execution, attack.defense_evasion, attack.t1036.003
DeviceProcessEvents
| where (ProcessVersionInfoFileDescription in~ ("Java Update Scheduler", "Java(TM) Update Scheduler")) and (not(FolderPath endswith "\\jusched.exe"))