// Author: Florian Roth (Nextron Systems)
// Date: 2022/09/20
// Level: high
// Description: Detects uses of a renamed legitimate createdump.exe LOLOBIN utility to dump process memory
// Tags: attack.defense_evasion, attack.t1036, attack.t1003.001
DeviceProcessEvents
| where (((ProcessCommandLine contains " -u " and ProcessCommandLine contains " -f " and ProcessCommandLine contains ".dmp") or (ProcessCommandLine contains " --full " and ProcessCommandLine contains " --name " and ProcessCommandLine contains ".dmp")) or ProcessVersionInfoOriginalFileName =~ "FX_VER_INTERNALNAME_STR") and (not(FolderPath endswith "\\createdump.exe"))