// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/06/06
// Level: high
// Description: Detects the execution of a renamed version of the Plink binary
// Tags: attack.defense_evasion, attack.t1036
DeviceProcessEvents
| where (ProcessVersionInfoOriginalFileName =~ "Plink" or (ProcessCommandLine contains " -l forward" and ProcessCommandLine contains " -P " and ProcessCommandLine contains " -R ")) and (not(FolderPath endswith "\\plink.exe"))