// Author: Kirill Kiryanov, Beyu Denis, Daniil Yugoslavskiy, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/05/22
// Level: medium
// Description: Detects execution of "odbcconf" with the "-f" flag in order to load a response file which might contain a malicious action.
// Tags: attack.defense_evasion, attack.t1218.008
DeviceProcessEvents
| where (ProcessCommandLine contains " -f " or ProcessCommandLine contains " /f ") and (FolderPath endswith "\\odbcconf.exe" or ProcessVersionInfoOriginalFileName =~ "odbcconf.exe") and ProcessCommandLine contains ".rsp"