// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/10
// Level: high
// Description: Detects rundll32 execution where the DLL is located on a remote location (share)
// Tags: attack.defense_evasion, attack.execution, attack.t1021.002, attack.t1218.011
DeviceProcessEvents
| where ProcessCommandLine contains " \\\\" and (FolderPath endswith "\\rundll32.exe" or ProcessVersionInfoOriginalFileName =~ "RUNDLL32.EXE" or ProcessCommandLine contains "rundll32")