// Author: Jose Luis Sanchez Martinez (@Joseliyo_Jstnk)
// Date: 2022/05/04
// Level: medium
// Description: Detects registry key established after masqueraded .scr file execution using Rundll32 through desk.cpl
// Tags: attack.defense_evasion, attack.t1218.011
DeviceRegistryEvents
| where InitiatingProcessFolderPath endswith "\\rundll32.exe" and (RegistryValueData endswith ".scr" and RegistryKey contains "\\Control Panel\\Desktop\\SCRNSAVE.EXE") and (not((RegistryValueData contains "C:\\Windows\\System32\\" or RegistryValueData contains "C:\\Windows\\SysWOW64\\")))