// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/03/04
// Level: medium
// Description: Detects the use of the PowerShell "Set-Service" cmdlet to change the startup type of a service to "disabled" or "manual"
// Tags: attack.execution, attack.defense_evasion, attack.t1562.001
DeviceProcessEvents
| where ((ProcessCommandLine contains "Disabled" or ProcessCommandLine contains "Manual") and (ProcessCommandLine contains "Set-Service" and ProcessCommandLine contains "-StartupType")) and (FolderPath endswith "\\powershell.exe" or ProcessVersionInfoOriginalFileName =~ "PowerShell.EXE")