// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/08/01
// Level: high
// Description: Detects execution of "reg.exe" commands with the "delete" flag on services registry key. Often used by attacker to remove AV software services
// Tags: attack.defense_evasion, attack.t1562.001
DeviceProcessEvents
| where ProcessCommandLine contains " delete " and (FolderPath endswith "reg.exe" or ProcessVersionInfoOriginalFileName =~ "reg.exe") and ProcessCommandLine contains "\\SYSTEM\\CurrentControlSet\\services\\"