// Author: Florian Roth (Nextron Systems), Jonhnathan Ribeiro, oscd.community, Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/02/15
// Level: medium
// Description: Detects the execution of certutil with certain flags that allow the utility to download files.
// Tags: attack.defense_evasion, attack.t1027
DeviceProcessEvents
| where (ProcessCommandLine contains "urlcache " or ProcessCommandLine contains "verifyctl ") and ProcessCommandLine contains "http" and (FolderPath endswith "\\certutil.exe" or ProcessVersionInfoOriginalFileName =~ "CertUtil.exe")