// Author: frack113
// Date: 2022/04/23
// Level: high
// Description: Get-Variable is a valid PowerShell cmdlet
WindowsApps is by default in the path where PowerShell is executed.
So when the Get-Variable command is issued on PowerShell execution, the system first looks for the Get-Variable executable in the path and executes the malicious binary instead of looking for the PowerShell cmdlet.

// Tags: attack.persistence, attack.t1546, attack.defense_evasion, attack.t1027
DeviceFileEvents
| where FolderPath endswith "Local\\Microsoft\\WindowsApps\\Get-Variable.exe"