// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/10/28
// Level: medium
// Description: Detects usage of Msiexec.exe to install packages hosted remotely quietly
// Tags: attack.defense_evasion, attack.t1218.007
DeviceProcessEvents
| where (ProcessCommandLine contains "-i" or ProcessCommandLine contains "/i" or ProcessCommandLine contains "-package" or ProcessCommandLine contains "/package" or ProcessCommandLine contains "-a" or ProcessCommandLine contains "/a" or ProcessCommandLine contains "-j" or ProcessCommandLine contains "/j") and (FolderPath endswith "\\msiexec.exe" or ProcessVersionInfoOriginalFileName =~ "msiexec.exe") and (ProcessCommandLine contains "-q" or ProcessCommandLine contains "/q") and (ProcessCommandLine contains "http" or ProcessCommandLine contains "\\\\")