// Author: Nasreddine Bencherchali (Nextron Systems), GossiTheDog, frack113
// Date: 2022/06/21
// Level: medium
// Description: Detects execution of msdt.exe using the "cab" flag which could indicates suspicious diagcab files with embedded answer files leveraging CVE-2022-30190
// Tags: attack.defense_evasion, attack.t1202
DeviceProcessEvents
| where (ProcessCommandLine contains " /cab " or ProcessCommandLine contains " -cab ") and (FolderPath endswith "\\msdt.exe" or ProcessVersionInfoOriginalFileName =~ "msdt.exe")