// Author: frack113
// Date: 2022/11/18
// Level: medium
// Description: Detects suspicious execution of 'Powercfg.exe' to change lock screen timeout
// Tags: attack.defense_evasion
DeviceProcessEvents
| where (FolderPath endswith "\\powercfg.exe" or ProcessVersionInfoOriginalFileName =~ "PowerCfg.exe") and ((ProcessCommandLine contains "/setacvalueindex " and ProcessCommandLine contains "SCHEME_CURRENT" and ProcessCommandLine contains "SUB_VIDEO" and ProcessCommandLine contains "VIDEOCONLOCK") or (ProcessCommandLine contains "-change " and ProcessCommandLine contains "-standby-timeout-"))