// Author: Konstantin Grishchenko, oscd.community
// Date: 2020/10/06
// Level: medium
// Description: Detect VBoxDrvInst.exe run with parameters allowing processing INF file.
This allows to create values in the registry and install drivers.
For example one could use this technique to obtain persistence via modifying one of Run or RunOnce registry keys

// Tags: attack.defense_evasion, attack.t1112
DeviceProcessEvents
| where (ProcessCommandLine contains "driver" and ProcessCommandLine contains "executeinf") and FolderPath endswith "\\VBoxDrvInst.exe"