// Author: Florian Roth (Nextron Systems)
// Date: 2021/05/27
// Level: high
// Description: Detects suspicious start of rundll32.exe without any parameters as found in CobaltStrike beacon activity
// Tags: attack.defense_evasion, attack.t1202
DeviceProcessEvents
| where ProcessCommandLine endswith "\\rundll32.exe" and (not((InitiatingProcessFolderPath endswith "\\svchost.exe" or (InitiatingProcessFolderPath contains "\\AppData\\Local\\" or InitiatingProcessFolderPath contains "\\Microsoft\\Edge\\"))))