// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/02/15
// Level: high
// Description: Detects the execution of certutil with certain flags that allow the utility to download files from direct IPs.
// Tags: attack.defense_evasion, attack.t1027
DeviceProcessEvents
| where ((ProcessCommandLine contains "urlcache " or ProcessCommandLine contains "verifyctl ") and (ProcessCommandLine contains "://1" or ProcessCommandLine contains "://2" or ProcessCommandLine contains "://3" or ProcessCommandLine contains "://4" or ProcessCommandLine contains "://5" or ProcessCommandLine contains "://6" or ProcessCommandLine contains "://7" or ProcessCommandLine contains "://8" or ProcessCommandLine contains "://9") and (FolderPath endswith "\\certutil.exe" or ProcessVersionInfoOriginalFileName =~ "CertUtil.exe")) and (not(ProcessCommandLine contains "://7-"))