// Author: SBousseaden
// Date: 2019/10/28
// Level: high
// Description: Detects DLL sideloading of DLLs that are loaded by the SCM for some services (IKE, IKEEXT, SessionEnv) which do not exists on a typical modern system
IKEEXT and SessionEnv service, as they call LoadLibrary on files that do not exist within C:\Windows\System32\ by default.
An attacker can place their malicious logic within the PROCESS_ATTACH block of their library and restart the aforementioned services "svchost.exe -k netsvcs" to gain code execution on a remote machine.

// Tags: attack.persistence, attack.defense_evasion, attack.t1574.002, attack.t1574.001
DeviceImageLoadEvents
| where ((FolderPath endswith "\\tsmsisrv.dll" or FolderPath endswith "\\tsvipsrv.dll" or FolderPath endswith "\\wlbsctrl.dll") and InitiatingProcessFolderPath endswith "\\svchost.exe") and (not(FolderPath startswith "C:\\Windows\\WinSxS\\"))