// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/03/23
// Level: high
// Description: Detects suspicious execution of Sysinternals PsSuspend, where the utility is used to suspend critical processes such as AV or EDR to bypass defenses
// Tags: attack.defense_evasion, attack.t1562.001
DeviceProcessEvents
| where ProcessCommandLine contains "msmpeng.exe" and (ProcessVersionInfoOriginalFileName =~ "pssuspend.exe" or (FolderPath endswith "\\pssuspend.exe" or FolderPath endswith "\\pssuspend64.exe"))