// Author: Sreeman
// Date: 2020/01/13
// Level: high
// Description: The Tasks folder in system32 and syswow64 are globally writable paths.
Adversaries can take advantage of this and load or influence any script hosts or ANY .NET Application 
in Tasks to load and execute a custom assembly into cscript, wscript, regsvr32, mshta, eventvwr

// Tags: attack.defense_evasion, attack.persistence, attack.execution, attack.t1574.002
DeviceProcessEvents
| where (ProcessCommandLine contains "echo " or ProcessCommandLine contains "copy " or ProcessCommandLine contains "type " or ProcessCommandLine contains "file createnew") and (ProcessCommandLine contains " C:\\Windows\\System32\\Tasks\\" or ProcessCommandLine contains " C:\\Windows\\SysWow64\\Tasks\\")