// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/07/03
// Level: high
// Description: Detects the "IDiagnosticProfileUAC" UAC bypass technique
// Tags: attack.execution, attack.defense_evasion, attack.privilege_escalation, attack.t1548.002
DeviceProcessEvents
| where (ProcessIntegrityLevel in~ ("High", "System")) and InitiatingProcessCommandLine contains " /Processid:{12C21EA7-2EB8-4B55-9249-AC243DA8C666}" and InitiatingProcessFolderPath endswith "\\DllHost.exe"