// Author: frack113
// Date: 2022/01/05
// Level: medium
// Description: Detects when an attacker tries to disable User Account Control (UAC) by setting the registry value "EnableLUA" to 0.

// Tags: attack.privilege_escalation, attack.defense_evasion, attack.t1548.002
DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey contains "\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\EnableLUA"