// Author: Christian Burkard (Nextron Systems)
// Date: 2021/08/23
// Level: high
// Description: Detects an UAC bypass that uses changepk.exe and slui.exe (UACMe 61)
// Tags: attack.defense_evasion, attack.privilege_escalation, attack.t1548.002
DeviceProcessEvents
| where FolderPath endswith "\\changepk.exe" and (ProcessIntegrityLevel in~ ("High", "System")) and InitiatingProcessFolderPath endswith "\\slui.exe"