// Author: oscd.community, Dmitry Uchakin
// Date: 2020/10/06
// Level: high
// Description: Attempts to load dismcore.dll after dropping it
// Tags: attack.persistence, attack.defense_evasion, attack.privilege_escalation, attack.t1548.002, attack.t1574.002
DeviceImageLoadEvents
| where (FolderPath endswith "\\dismcore.dll" and InitiatingProcessFolderPath endswith "\\dism.exe") and (not(FolderPath =~ "C:\\Windows\\System32\\Dism\\dismcore.dll"))