// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/11/22
// Level: high
// Description: Detects the pattern of UAC Bypass using Event Viewer RecentViews
// Tags: attack.defense_evasion, attack.privilege_escalation
DeviceProcessEvents
| where (ProcessCommandLine contains "\\Event Viewer\\RecentViews" or ProcessCommandLine contains "\\EventV~1\\RecentViews") and ProcessCommandLine contains ">"