// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/07/17
// Level: high
// Description: Detects the "iscsicpl.exe" UAC bypass technique that leverages a DLL Search Order hijacking technique to load a custom DLL's from temp or a any user controlled location in the users %PATH%
// Tags: attack.defense_evasion, attack.privilege_escalation, attack.t1548.002
DeviceImageLoadEvents
| where (InitiatingProcessFolderPath =~ "C:\\Windows\\SysWOW64\\iscsicpl.exe" and FolderPath endswith "\\iscsiexe.dll") and (not((FolderPath contains "C:\\Windows\\" and FolderPath contains "iscsiexe.dll")))