// Author: Nasreddine Bencherchali (Nextron Systems), Beyu Denis, oscd.community
// Date: 2019/10/26
// Level: medium
// Description: Detects uncommon child processes of "BgInfo.exe" which could be a sign of potential abuse of the binary to proxy execution via external VBScript
// Tags: attack.execution, attack.t1059.005, attack.defense_evasion, attack.t1218, attack.t1202
DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\bginfo.exe" or InitiatingProcessFolderPath endswith "\\bginfo64.exe"