// Author: frack113
// Date: 2021/07/12
// Level: high
// Description: Adversaries may disable security tools to avoid possible detection of their tools and activities by uninstalling Crowdstrike Falcon
// Tags: attack.defense_evasion, attack.t1562.001
DeviceProcessEvents
| where ProcessCommandLine contains "\\WindowsSensor.exe" and ProcessCommandLine contains " /uninstall" and ProcessCommandLine contains " /quiet"