// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/06/09
// Level: medium
// Description: The "VSIISExeLauncher.exe" binary part of the Visual Studio/VS Code can be used to execute arbitrary binaries
// Tags: attack.defense_evasion, attack.t1127
DeviceProcessEvents
| where (ProcessCommandLine contains " -p " or ProcessCommandLine contains " -a ") and (FolderPath endswith "\\VSIISExeLauncher.exe" or ProcessVersionInfoOriginalFileName =~ "VSIISExeLauncher.exe")