// Author: Sreeman
// Date: 2020/03/13
// Level: medium
// Description: Application Virtualization Utility is included with Microsoft Office. We are able to abuse "AppVLP" to execute shell commands.
Normally, this binary is used for Application Virtualization, but we can use it as an abuse binary to circumvent the ASR file path rule folder
or to mark a file as a system file.

// Tags: attack.t1218, attack.defense_evasion, attack.execution
DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\appvlp.exe" and (not((FolderPath endswith "\\msoasb.exe" or FolderPath endswith "\\rundll32.exe")))