// Author: frack113, manasmbellani
// Date: 2022/02/16
// Level: medium
// Description: Detects use of Wlrmdr.exe in which the -u parameter is passed to ShellExecute
// Tags: attack.defense_evasion, attack.t1218
DeviceProcessEvents
| where InitiatingProcessFolderPath endswith "\\wlrmdr.exe" or (((ProcessCommandLine contains "-s " and ProcessCommandLine contains "-f " and ProcessCommandLine contains "-t " and ProcessCommandLine contains "-m " and ProcessCommandLine contains "-a " and ProcessCommandLine contains "-u ") and (FolderPath endswith "\\wlrmdr.exe" or ProcessVersionInfoOriginalFileName =~ "WLRMNDR.EXE")) and (not((InitiatingProcessFolderPath in~ ("C:\\Windows\\System32\\winlogon.exe", "-")))))