// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/07/01
// Level: medium
// Description: Detects the execution of ".xbap" (Browser Applications) files via PresentationHost.EXE from an uncommon location. These files can be abused to run malicious ".xbap" files any bypass AWL

// Tags: attack.defense_evasion, attack.execution, attack.t1218
DeviceProcessEvents
| where (ProcessCommandLine contains ".xbap" and (FolderPath endswith "\\presentationhost.exe" or ProcessVersionInfoOriginalFileName =~ "PresentationHost.exe")) and (not((ProcessCommandLine contains " C:\\Windows\\" or ProcessCommandLine contains " C:\\Program Files")))