// Author: Christian Burkard (Nextron Systems)
// Date: 2021/09/20
// Level: high
// Description: Detects the execution of Xwizard tool from a non-default directory.
When executed from a non-default directory, this utility can be abused in order to side load a custom version of "xwizards.dll".

// Tags: attack.defense_evasion, attack.t1574.002
DeviceProcessEvents
| where (FolderPath endswith "\\xwizard.exe" or ProcessVersionInfoOriginalFileName =~ "xwizard.exe") and (not((FolderPath startswith "C:\\Windows\\System32\\" or FolderPath startswith "C:\\Windows\\SysWOW64\\")))