// Title: WCE wceaux.dll Access
// Author: Thomas Patzke
// Date: 2017-06-14
// Level: critical
// Description: Detects wceaux.dll access while WCE pass-the-hash remote command execution on source host
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003, attack.s0005
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/security/win_security_mal_wceaux_dll.yml

DeviceRegistryEvents
| where RegistryKey endswith "\\wceaux.dll"