// Title: Potential Secure Deletion with SDelete
// Author: Thomas Patzke
// Date: 2017-06-14
// Level: medium
// Description: Detects files that have extensions commonly seen while SDelete is used to wipe files.
// MITRE Tactic: Impact
// Tags: attack.impact, attack.defense-evasion, attack.t1070.004, attack.t1027.005, attack.t1485, attack.t1553.002, attack.s0195
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/security/win_security_sdelete_potential_secure_deletion.yml
// False Positives:
//   - Legitimate usage of SDelete
//   - Files that are interacted with that have these extensions legitimately

DeviceRegistryEvents
| where RegistryKey endswith ".AAA" or RegistryKey endswith ".ZZZ"