// Title: Suspicious Teams Application Related ObjectAcess Event
// Author: @SerkinValery
// Date: 2022-09-16
// Level: high
// Description: Detects an access to authentication tokens and accounts of Microsoft Teams desktop application.
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1528
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/security/win_security_teams_suspicious_objectaccess.yml

DeviceRegistryEvents
| where (RegistryKey contains "\\Microsoft\\Teams\\Cookies" or RegistryKey contains "\\Microsoft\\Teams\\Local Storage\\leveldb") and (not(InitiatingProcessFolderPath contains "\\Microsoft\\Teams\\current\\Teams.exe"))