// Title: File Access Of Signal Desktop Sensitive Data
// Author: Andreas Braathen (mnemonic.io)
// Date: 2025-10-19
// Level: medium
// Description: Detects access to Signal Desktop's sensitive data files: db.sqlite and config.json.
// The db.sqlite file in Signal Desktop stores all locally saved messages in an encrypted SQLite database, while the config.json contains the decryption key needed to access that data.
// Since the key is stored in plain text, a threat actor who gains access to both files can decrypt and read sensitive messages without needing the users credentials.
// Currently the rule only covers the default Signal installation path in AppData\Roaming. Signal Portable installations may use different paths based on user configuration. Additional paths can be added to the selection as needed.
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/security/win_security_signal_sensitive_config_access.yml
// False Positives:
//   - Unlikely, but possible from AV or backup software accessing the files.

DeviceRegistryEvents
| where (RegistryKey endswith "\\AppData\\Roaming\\Signal*" and (RegistryKey endswith "\\config.json" or RegistryKey endswith "\\db.sqlite")) and (not((InitiatingProcessFolderPath endswith "\\signal-portable.exe" or InitiatingProcessFolderPath endswith "\\signal.exe")))