// Title: WMI Persistence - Security
// Author: Florian Roth (Nextron Systems), Gleb Sukhodolskiy, Timur Zinniatullin oscd.community
// Date: 2017-08-22
// Level: medium
// Description: Detects suspicious WMI event filter and command line event consumer based on WMI and Security Logs.
// MITRE Tactic: Persistence
// Tags: attack.persistence, attack.privilege-escalation, attack.t1546.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/security/win_security_wmi_persistence.yml
// False Positives:
//   - Unknown (data set is too small; further testing needed)

DeviceRegistryEvents
| where RegistryKey contains "subscription"