// Title: Access To Chromium Browsers Sensitive Files By Uncommon Applications
// Author: X__Junior (Nextron Systems)
// Date: 2024-07-29
// Level: low
// Description: Detects file access requests to chromium based browser sensitive files by uncommon processes.
// Could indicate potential attempt of stealing sensitive information.
// MITRE Tactic: Credential Access
// Tags: attack.t1003, attack.credential-access, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/file/file_access/file_access_win_browsers_chromium_sensitive_files.yml
// False Positives:
//   - Antivirus, Anti-Spyware, Anti-Malware Software
//   - Backup software
//   - Legitimate software installed on partitions other than "C:\"
//   - Searching software such as "everything.exe"

DeviceFileEvents
| where (FileName contains "\\User Data\\Default\\Cookies" or FileName contains "\\User Data\\Default\\History" or FileName contains "\\User Data\\Default\\Network\\Cookies" or FileName contains "\\User Data\\Default\\Web Data") and (not(((InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\" or InitiatingProcessFolderPath startswith "C:\\Program Files\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\system32\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\SysWOW64\\") or InitiatingProcessFolderPath =~ "System"))) and (not(((InitiatingProcessFolderPath endswith "\\MpCopyAccelerator.exe" or InitiatingProcessFolderPath endswith "\\MsMpEng.exe") and InitiatingProcessFolderPath startswith "C:\\ProgramData\\Microsoft\\Windows Defender\\")))