// Title: Access To .Reg/.Hive Files By Uncommon Applications
// Author: frack113
// Date: 2023-09-15
// Level: low
// Description: Detects file access requests to files ending with either the ".hive"/".reg" extension, usually associated with Windows Registry backups.
// MITRE Tactic: Defense Evasion
// Tags: attack.t1112, attack.defense-evasion, attack.persistence, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/file/file_access/file_access_win_susp_reg_and_hive.yml
// False Positives:
//   - Third party software installed in the user context might generate a lot of FPs. Heavy baselining and tuning might be required.

DeviceFileEvents
| where (FileName endswith ".hive" or FileName endswith ".reg") and (not((InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\" or InitiatingProcessFolderPath startswith "C:\\Program Files\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\System32\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\SysWOW64\\")))