// Title: Access To Windows Outlook Mail Files By Uncommon Applications
// Author: frack113
// Date: 2024-05-10
// Level: low
// Description: Detects file access requests to Windows Outlook Mail by uncommon processes.
// Could indicate potential attempt of credential stealing.
// Requires heavy baselining before usage
// MITRE Tactic: Defense Evasion
// Tags: attack.t1070.008, attack.defense-evasion, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/file/file_access/file_access_win_office_outlook_mail_credential.yml
// False Positives:
//   - Antivirus, Anti-Spyware, Anti-Malware Software
//   - Backup software
//   - Legitimate software installed on partitions other than "C:\"
//   - Searching software such as "everything.exe"

DeviceFileEvents
| where (FileName contains "\\AppData\\Local\\Comms\\Unistore\\data" or FileName endswith "\\AppData\\Local\\Comms\\UnistoreDB\\store.vol") and (not(((InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\" or InitiatingProcessFolderPath startswith "C:\\Program Files\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\system32\\" or InitiatingProcessFolderPath startswith "C:\\Windows\\SysWOW64\\") or InitiatingProcessFolderPath =~ "System"))) and (not((((InitiatingProcessFolderPath endswith "\\MpCopyAccelerator.exe" or InitiatingProcessFolderPath endswith "\\MsMpEng.exe") and InitiatingProcessFolderPath startswith "C:\\ProgramData\\Microsoft\\Windows Defender\\") or (InitiatingProcessFolderPath endswith "\\thor64.exe" or InitiatingProcessFolderPath endswith "\\thor.exe"))))