// Title: Access To Sysvol Policies Share By Uncommon Process
// Author: frack113
// Date: 2023-12-21
// Level: medium
// Description: Detects file access requests to the Windows Sysvol Policies Share by uncommon processes
// MITRE Tactic: Credential Access
// Tags: attack.credential-access, attack.t1552.006, detection.threat-hunting
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/file/file_access/file_access_win_susp_gpo_access_uncommon_process.yml

DeviceFileEvents
| where ((FileName contains "\\sysvol\\" and FileName contains "\\Policies\\") and FileName startswith "\\") and (not((InitiatingProcessFolderPath contains ":\\Program Files (x86)\\" or InitiatingProcessFolderPath contains ":\\Program Files\\" or InitiatingProcessFolderPath contains ":\\Windows\\explorer.exe" or InitiatingProcessFolderPath contains ":\\Windows\\system32\\" or InitiatingProcessFolderPath contains ":\\Windows\\SysWOW64\\")))