// Title: Persistence Via Sudoers Files
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-05
// Level: medium
// Description: Detects creation of sudoers file or files in "sudoers.d" directory which can be used a potential method to persiste privileges for a specific user.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.execution, attack.persistence, attack.t1053.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/file_event/file_event_lnx_persistence_sudoers_files.yml
// False Positives:
//   - Creation of legitimate files in sudoers.d folder part of administrator work

DeviceFileEvents
| where FolderPath startswith "/etc/sudoers.d/"