// Title: Triple Cross eBPF Rootkit Default LockFile
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-07-05
// Level: high
// Description: Detects the creation of the file "rootlog" which is used by the TripleCross rootkit as a way to check if the backdoor is already running.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/file_event/file_event_lnx_triple_cross_rootkit_lock_file.yml
// False Positives:
//   - Unlikely

DeviceFileEvents
| where FolderPath =~ "/tmp/rootlog"