// Title: Linux Doas Conf File Creation
// Author: Sittikorn S, Teoderick Contreras
// Date: 2022-01-20
// Level: medium
// Description: Detects the creation of doas.conf file in linux host platform.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.privilege-escalation, attack.t1548
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/file_event/file_event_lnx_doas_conf_creation.yml
// False Positives:
//   - Unlikely

DeviceFileEvents
| where FolderPath endswith "/etc/doas.conf"