// Title: RunMRU Registry Key Deletion - Registry
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-09-25
// Level: high
// Description: Detects attempts to delete the RunMRU registry key, which stores the history of commands executed via the run dialog.
// In the clickfix techniques, the phishing lures instruct users to open a run dialog through (Win + R) and execute malicious commands.
// Adversaries may delete this key to cover their tracks after executing commands.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1070.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_delete/registry_delete_runmru.yml

DeviceRegistryEvents
| where RegistryKey endswith "\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RunMRU"