// Title: Removal Of Index Value to Hide Schedule Task - Registry
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-26
// Level: medium
// Description: Detects when the "index" value of a scheduled task is removed or deleted from the registry. Which effectively hides it from any tooling such as "schtasks /query"
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_delete/registry_delete_schtasks_hide_task_via_index_value_removal.yml

DeviceRegistryEvents
| where RegistryKey endswith "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tree*" and RegistryKey contains "Index"