// Title: Removal Of SD Value to Hide Schedule Task - Registry
// Author: Sittikorn S
// Date: 2022-04-15
// Level: medium
// Description: Remove SD (Security Descriptor) value in \Schedule\TaskCache\Tree registry hive to hide schedule task. This technique is used by Tarrask malware
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_delete/registry_delete_schtasks_hide_task_via_sd_value_removal.yml

DeviceRegistryEvents
| where RegistryKey endswith "\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tree*" and RegistryKey contains "SD"