// Author: frack113, Nextron Systems
// Date: 2022/01/06
// Level: high
// Description: Detects the setting of the environement variable "windir" to a non default value.
Attackers often abuse this variable in order to trigger a UAC bypass via the "SilentCleanup" task.
The SilentCleanup task located in %windir%\system32\cleanmgr.exe is an auto-elevated task that can be abused to elevate any file with administrator privileges without prompting UAC.

// Tags: attack.privilege_escalation, attack.defense_evasion, attack.t1548.002
DeviceRegistryEvents
| where RegistryKey endswith "\\Environment\\windir" and (not(RegistryValueData =~ "%SystemRoot%"))