// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/05/16
// Level: high
// Description: Detects the creation of the LiveKD driver by a process image other than "livekd.exe".
// Tags: attack.defense_evasion, attack.privilege_escalation
DeviceFileEvents
| where FolderPath =~ "C:\\Windows\\System32\\drivers\\LiveKdD.SYS" and (not((InitiatingProcessFolderPath endswith "\\livekd.exe" or InitiatingProcessFolderPath endswith "\\livek64.exe")))