// Author: frack113, Florian Roth
// Date: 2021/07/12
// Level: high
// Description: Detects process injection using the signed Windows tool "Mavinject" via the "INJECTRUNNING" flag
// Tags: attack.defense_evasion, attack.privilege_escalation, attack.t1055.001, attack.t1218.013
DeviceProcessEvents
| where ProcessCommandLine contains " /INJECTRUNNING " and (not(InitiatingProcessFolderPath =~ "C:\\Windows\\System32\\AppVClient.exe"))