// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/07/14
// Level: medium
// Description: Detects creation of a new service (kernel driver) with the type "kernel"
// Tags: attack.persistence, attack.privilege_escalation, attack.t1543.003
DeviceProcessEvents
| where (ProcessCommandLine contains "create" or ProcessCommandLine contains "config") and (ProcessCommandLine contains "binPath" and ProcessCommandLine contains "type" and ProcessCommandLine contains "kernel") and FolderPath endswith "\\sc.exe"