// Author: Florian Roth (Nextron Systems)
// Date: 2022/01/20
// Level: medium
// Description: Detects the execution of AdvancedRun utility
// Tags: attack.execution, attack.defense_evasion, attack.privilege_escalation, attack.t1564.003, attack.t1134.002, attack.t1059.003
DeviceProcessEvents
| where ProcessVersionInfoOriginalFileName =~ "AdvancedRun.exe" or (ProcessCommandLine contains " /EXEFilename " and ProcessCommandLine contains " /Run") or (ProcessCommandLine contains " /WindowState 0" and ProcessCommandLine contains " /RunAs " and ProcessCommandLine contains " /CommandLine ")