// Author: Andreas Hunkeler (@Karneades)
// Date: 2021/12/20
// Level: high
// Description: Detects usage of the "sc.exe" utility adding a new service with special permission seen used by threat actors which makes the service hidden and unremovable.
// Tags: attack.persistence, attack.defense_evasion, attack.privilege_escalation, attack.t1574.011
DeviceProcessEvents
| where (ProcessCommandLine contains "sdset" and ProcessCommandLine contains "DCLCWPDTSD") and (FolderPath endswith "\\sc.exe" or ProcessVersionInfoOriginalFileName =~ "sc.exe")