// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023/02/28
// Level: medium
// Description: Detection of sc.exe utility adding a new service with special permission which hides that service.
// Tags: attack.persistence, attack.defense_evasion, attack.privilege_escalation, attack.t1574.011
DeviceProcessEvents
| where ProcessCommandLine contains "sdset" and (FolderPath endswith "\\sc.exe" or ProcessVersionInfoOriginalFileName =~ "sc.exe")