// Author: Christian Burkard (Nextron Systems)
// Date: 2021/08/30
// Level: high
// Description: Detects the pattern of UAC Bypass using a path parsing issue in winsat.exe (UACMe 52)
// Tags: attack.defense_evasion, attack.privilege_escalation, attack.t1548.002
DeviceRegistryEvents
| where RegistryValueData endswith "\\appdata\\local\\temp\\system32\\winsat.exe" and RegistryValueData startswith "c:\\users\\" and RegistryKey contains "\\Root\\InventoryApplicationFile\\winsat.exe|" and RegistryKey endswith "\\LowerCaseLongPath"