// Author: Christian Burkard (Nextron Systems)
// Date: 2021/08/31
// Level: high
// Description: Detects tools such as UACMe used to bypass UAC with computerdefaults.exe (UACMe 59)
// Tags: attack.defense_evasion, attack.privilege_escalation, attack.t1548.002
DeviceProcessEvents
| where (FolderPath =~ "C:\\Windows\\System32\\ComputerDefaults.exe" and (ProcessIntegrityLevel in~ ("High", "System"))) and (not((InitiatingProcessFolderPath contains ":\\Windows\\System32" or InitiatingProcessFolderPath contains ":\\Program Files")))