// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022/01/23
// Level: low
// Description: Detects the creation of a new office macro files on the systems
// Tags: attack.initial_access, attack.t1566.001
DeviceFileEvents
| where FolderPath endswith ".docm" or FolderPath endswith ".dotm" or FolderPath endswith ".xlsm" or FolderPath endswith ".xltm" or FolderPath endswith ".potm" or FolderPath endswith ".pptm"