// Author: Andreas Hunkeler (@Karneades), Nasreddine Bencherchali
// Date: 2021/12/17
// Level: medium
// Description: Detects shell spawned from Java host process, which could be a sign of exploitation (e.g. log4j exploitation)
// Tags: attack.initial_access, attack.persistence, attack.privilege_escalation
DeviceProcessEvents
| where ((FolderPath endswith "\\cmd.exe" or FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe") and InitiatingProcessFolderPath endswith "\\java.exe") and (not((ProcessCommandLine contains "build" and InitiatingProcessFolderPath contains "build")))