// Author: Florian Roth (Nextron Systems)
// Date: 2022/02/25
// Level: high
// Description: Detects suspicious activity in which the MSExchangeMailboxReplication process writes .asp and .apsx files to disk, which could be a sign of ProxyShell exploitation
// Tags: attack.initial_access, attack.t1190, attack.persistence, attack.t1505.003
DeviceFileEvents
| where InitiatingProcessFolderPath endswith "\\MSExchangeMailboxReplication.exe" and (FolderPath endswith ".aspx" or FolderPath endswith ".asp")