// Author: Florian Roth (Nextron Systems)
// Date: 2022/10/04
// Level: medium
// Description: Detects suspicious file type dropped by an Exchange component in IIS
// Tags: attack.persistence, attack.t1190, attack.initial_access, attack.t1505.003
DeviceFileEvents
| where (InitiatingProcessCommandLine contains "MSExchange" and InitiatingProcessFolderPath endswith "\\w3wp.exe") and (FolderPath endswith ".aspx" or FolderPath endswith ".asp" or FolderPath endswith ".ashx" or FolderPath endswith ".ps1" or FolderPath endswith ".bat" or FolderPath endswith ".exe" or FolderPath endswith ".dll" or FolderPath endswith ".vbs")