// Title: Forest Blizzard APT - JavaScript Constrained File Creation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-04-23
// Level: medium
// Description: Detects the creation of JavaScript files inside of the DriverStore directory.
// Forest Blizzard used this to exploit the CVE-2022-38028 vulnerability in Windows Print Spooler service by modifying a JavaScript constraints file and executing it with SYSTEM-level permissions.
// MITRE Tactic: Defense Evasion
// Tags: attack.defense-evasion, attack.t1562.002, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2024/TA/Forest-Blizzard/file_event_win_apt_forest_blizzard_constrained_js.yml
// False Positives:
//   - Unlikely

DeviceFileEvents
| where FolderPath endswith "\\.js" and FolderPath startswith "C:\\Windows\\System32\\DriverStore\\FileRepository\\"