// Title: Forest Blizzard APT - Custom Protocol Handler DLL Registry Set
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-04-23
// Level: high
// Description: Detects the setting of the DLL that handles the custom protocol handler.
// Seen being created by Forest Blizzard APT as reported by MSFT.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.persistence, attack.t1547.001, detection.emerging-threats
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-emerging-threats/2024/TA/Forest-Blizzard/registry_set_apt_forest_blizzard_custom_protocol_handler_dll.yml
// False Positives:
//   - Unlikely

DeviceRegistryEvents
| where RegistryValueData endswith ".dll" and RegistryKey contains "\\CLSID\\{026CC6D7-34B2-33D5-B551-CA31EB6CE345}\\Server"